### ISSUE TITLE
PHP70 and XDebug

### ISSUE THREAD

**Issue by bsantore** [DataDog/dd-trace-php#1010]
I see there is a test for incompatibility with xdebug on PHP 7. If this is is actually triggered in a production environment, would this log somewhere, or is it just sent to stdout?

https://github.com/DataDog/dd-trace-php/blob/5f8f0b8e8f07867354a583f6856c6eb4bcfe14e3/tests/xdebug/2.7.2/request_init_hook_disable_php_7.0.phpt#L15

**Comment by SammyK** [comment]
These errors are logged to file specified in [the `error_log` INI setting](https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-log).

**Comment by bsantore** [comment]
Any thoughts on elevating this to a warning by default in the DataDog logs? Leveraging the PSR3 definition "exceptional occurrences that are not errors," this might be easier to spot if it's elevated from info, since the application is running, but in a degraded state.

**Comment by SammyK** [comment]
Thanks for the suggestion about log levels. Unfortunately we don't have log levels built into the tracer logging at the moment. But adding log levels is on our radar. 

For better troubleshooting this specific issue, the next release of ddtrace (`0.48.2`) will contain diagnostic information on the `phpinfo()` page (under the "ddtrace" section) when there are incompatible extensions detected.
