### ISSUE TITLE
[Feature] Allow recording query strings in resource name for WordPress

### ISSUE THREAD

**Issue by robolmos** [DataDog/dd-trace-php#1033]
A lot of WooCommerce and WordPress URLs are in the format of "POST /?wc-ajax=checkout", "POST /?wc-api=stripe_webhook", etc. 

I'm unable to see the query string in the APM trace list because the query string is stripped, so it only shows up as "POST /" for all those various calls.

It would be nice if there's some way to get the URL like "/?wc-ajax=checkout" to show up in the trace list/log for easier inspecting.

Maybe that just needs to be added to the WordPress integration code?

**Comment by labbati** [comment]
Hi @robolmos. You are making a very good point. We are thinking about an approach that would be generic enough, but we haven't made a final decision yet and I'd like to ask for you opinion on a possible direction.

1. Define a list of query string parameters that will be part of the resource name. This list by default is empty. Users can define custom query string parameters they want to be part of the resource name via `DD_TRACE_QUERY_STRING_RESOURCE_PARAMS=name1,name2`.
2. If we provide deep instrumentation for a specific framework (e.g. WordPress) and we know that a specific query string parameter is relevant (e.g. `wc-ajax`) then we automatically add that specific query string parameter(s) to this list without any work required by the user.
3. For relevant query string parameters from points 1. and 2., we add only that specific one (or more) query string parameters AND their value to the resource name. E.g. https://example.com/path/123/subpath?discard=123&keep1=456%keep2=789 would result in `GET /path/?/subpath ?keep1=456&keep2=789`

Would this approach work for you?

**Comment by mauriciogior** [comment]
Hi @labbati, I'd like to take part on this discussion.
Our API endpoint is always `/api/` and we map the methods using the `action` query parameter. Here are a few examples:
- `/api/?action=person.signIn`
- `/api/?action=person.get`
- `/api/?action=event.find`

We also have extra attributes, but the goal here is to map only the `action` attribute during the URL normalization, so the first option you gave would work like a charm to us.

**Comment by mauriciogior** [comment]
I created a pull request with this suggestion: https://github.com/DataDog/dd-trace-php/pull/1117

**Comment by shridharlohia** [comment]
is this same feature available for Java Agent ?
