### ISSUE TITLE
[BUG] Call to undefined function dd_trace_peek_span_id()

### ISSUE THREAD

**Issue by creativedevs** [DataDog/dd-trace-php#1045]
### Bug description
Getting Call to undefined function dd_trace_peek_span_id() in laravel

Using laravel 5.5

### PHP version
7.3

**Comment by labbati** [comment]
Hi @creativedevs, would you mind providing us with some more info? E.g. is it a web or cli app? `dd_trace_peek_span_id` is exported by our tracer, so this looks to me something related to caching? E.g. you enabled the tracer then removed the tracer without restarting or cleaning up cache?

**Comment by creativedevs** [comment]
@labbati 

Yes I am using application for API call and I was checking it in postman tool.

As well as, I have checked in laravel directory and dd_trace_peek_span_id() method is not exists, not even in this package.

Is there any specific command?

I have cleared cache and composer dump-autoload as well. It was not worked though.

**Comment by labbati** [comment]
I have a few questions:
- do you do any form of manual instrumentation?
- which steps did you use to install our extension?
- would it be possible for you to provide as with the output of `<?php phpinfo(); >?` so we can take a look? (please see [here](https://docs.datadoghq.com/tracing/troubleshooting/tracer_startup_logs/?tab=php#php-info) for instructions)

**Comment by creativedevs** [comment]
@labbati 

Steps followed

composer require datadog/dd-trace
composer dump-autoload
Added LogServiceProvider.php
<?php
 
namespace App\Services\Api\Providers;
 
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;
use Monolog\Formatter\JsonFormatter;
 
class LogServiceProvider extends ServiceProvider
{
   /**
    * Bootstrap the application services.
    *
    * @return void
    */
   public function boot()
   {
       // dd(get_class_methods(request()));
       // create a log channel
       $log = new Logger('channel_name');
 
       // create a Json formatter
       $formatter = new JsonFormatter();
 
       // create a handler
       $stream = new StreamHandler(storage_path().'\logs\application-json.log', Logger::DEBUG);
       $stream->setFormatter($formatter);
 
       // bind
       $log->pushHandler($stream);
 
       // an example
      
 
       /************* */
       $monolog = $log;
       if (!$monolog instanceof \Monolog\Logger) { dd('not instance of monolog');
           return;
       }
 
       // Optional: Use JSON formatting
       $useJson = false;
       foreach ($monolog->getHandlers() as $handler) {
           if (method_exists($handler, 'setFormatter')) {
               $handler->setFormatter(new \Monolog\Formatter\JsonFormatter());
               $useJson = true;
           }
       }
 
       // Inject the trace and span ID to connect the log entry with the APM trace
       $monolog->pushProcessor(function ($record) use ($useJson) {
           $span = \DDTrace\GlobalTracer::get()->getActiveSpan();
           if (null === $span) { dd('span is null');
               return $record;
           }
           if ($useJson === true) {
               $record['dd'] = [
                   'trace_id' => $span->getTraceId(),
                   'span_id'  => \dd_trace_peek_span_id(),
               ];
           } else {
               $record['message'] .= sprintf(
                   ' [dd.trace_id=%d dd.span_id=%d]',
                   $span->getTraceId(),
                   \dd_trace_peek_span_id()
               );
           }
           return $record;
       });
 
       $log->info('111111Adding a new user', array('username' => '1111Seldaek'));
   }
 
   /**
    * Register the application services.
    *
    * @return void
    */
   public function register()
   {
       //
   }
}
 
No PHP Custom Instrumentation
PHP Version: 7.2.4
Laravel version: 5.5

**Comment by creativedevs** [comment]
@labbati any update?

**Comment by labbati** [comment]
Is it possible that you [did not install our extension](https://docs.datadoghq.com/tracing/setup/php/#install-the-extension)? It is not mentioned in your steps and it would easily explain the issue.

The package in composer, it is only an helper for basic functionalities, but is you call functions like `\dd_trace_peek_span_id()` you need the extension installed following the instructions in the link above.

**Comment by creativedevs** [comment]
@labbati Extension is already setup as it was setup by devops team so I forgot to write in steps

**Comment by labbati** [comment]
Hi @creativedevs and sorry for the late reply. This issue is very strange as the function you mention is exposed from `0.31.0` a long time ago.

Can you please tell me the exact version of the tracer as seen by the file you pasted? You can do this by just adding at the beginning of the `boot()` function the following line: `error_log('Tracer version: ' . var_export(phpversion('ddtrace'), 1));`.

After sharing this information, we can decide next steps.

**Comment by labbati** [comment]
Hi @creativedevs, not sure if you had a chance to read my last message. Can you provide the requested info? I am also opened to chat on the [public slack channel](datadoghq.slack.com) if this helps, my handle is @luca.abbati there.

**Comment by creativedevs** [comment]
@labbati 

Here is the screenshot of phpinfo

![image](https://user-images.githubusercontent.com/5255532/97840755-96188580-1d0a-11eb-9117-e4385ebc977f.png)

is it okay? or anything missing to set?

**Comment by creativedevs** [comment]
This issue has been fixed. Thanks @labbati 

It was because it is important to restart php-fpm and once it is restarted, it started working.

**Comment by labbati** [comment]
Thanks for the heads up @creativedevs. Happy to see now things are working. I will make sure to make it more clear in our configuration and setup page that a restart of the php fpm process is required after installation.
