### ISSUE TITLE
[Feature] Allow splitting of Redis services integrations by hostname 

### ISSUE THREAD

**Issue by jamesmcminn96** [DataDog/dd-trace-php#1052]
**Is your feature request related to a problem? Please describe.**
When tracing PHP applications that connect to multiple Redis data stores, calls to different Redis servers are clumped into the same service (either `redis` for [Predis](https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Integrations/Predis/PredisIntegration.php#L45), and `phpredis` for [phpredis](https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Integrations/PHPRedis/PHPRedisIntegration.php#L255)) making it difficult to identify different Redis environments in the following circumstances:

1. Unable to distinguish between two different Redis servers used by two separate applications
2. Unable to distinguish between multiple different Redis servers used by the same application

**Describe the solution you'd like**
It'd be great if environment variables can be used to tell the integration code to set the service name to a meaningful value, similar to how https://github.com/DataDog/dd-trace-php/pull/459 was implemented for cURL & Guzzle. The URI host was used in that example; the Redis server hostname could be used to implement `DD_TRACE_REDIS_CLIENT_SPLIT_BY_HOST`.

The service could be prefixed with the integration type, then, remapped further to even more meaningful names using a regular service mapping.

**Describe alternatives you've considered**
For the first case mentioned, we can use `DD_SERVICE_MAPPING` in each application to name each Redis service and provide distinction between any number of servers. There is no work around that I can think of for the second case.

**Additional context**
- PHPRedis is [already fetching the host](https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Integrations/PHPRedis/PHPRedisIntegration.php#L32) and appending it to the trace, this value would be able to be used to implement `DD_TRACE_REDIS_CLIENT_SPLIT_BY_HOST`.

It does seem like this functionality would be useful across other integrations too (multiple Elasticsearch, PDO, etc). I wonder if integration service naming needs to be thought about more holistically for this extension.

If there are no objects from maintainers, I'd be happy to start implementing based off of the spec I've described. Largely following https://github.com/DataDog/dd-trace-php/pull/459.

Thanks for the awesome product!

**Comment by labbati** [comment]
Hi @jamesmcminn96, thank you for opening this issue and for the perfectly clear explanation.

I think that this is a very good idea and I'd love to see it landing in our tracer, but let me collect feedback from other maintainers as well, just to make sure there is not something I am not considering. We will get back very shortly.

**Comment by labbati** [comment]
Hi @jamesmcminn96 I just wanted to get back to you about this issue. We really like your proposal and if you are interested we would love to see your contribution.

**Specifications**

- We introduce a new setting named `DD_TRACE_REDIS_CLIENT_SPLIT_BY_HOST`. Default value is `false`. It can be set to `true`.
- If the value of the above setting is `true`, then the service name for redis client spans is changed to `redis-<host>`. Example: `host=127.0.01 --> service=redis-127.0.0.1`, `host=some.host --> service=redis-some.host`.
- We do not make a distinction between phpredis and predis while defining the service name.

**Notes and tips**

In case you decide to contribute please let us know, and:

- Do not feel obligated to work on both phpredis and predis. While both of them are welcomed, you can focus on the one that you actually use in your application and we can work later on the other library.
- You might have an extra level of complexity compared to guzzle and curl, as the `host` might be only available during `connect`. In this case you either might have access to the host from the `Redis` instance, or you might have to append it during `connect` using a strategy similar to what we do [here](https://github.com/DataDog/dd-trace-php/blob/7bebb190e0f5afeb24d7b21d320c49ec43a05d2e/src/DDTrace/Integrations/Mysqli/MysqliIntegration.php#L111) and then consume during other methods tracing. This has to be investigated across versions/libraries.
- Feel free to open a draft PR as soon as you have anything to share or questions to ask on the code and directly ping me so I can assist.

**Comment by labbati** [comment]
@jamesmcminn96, we are starting the work on this. Which one of phpredis and predis  you are actually using? We will probably  contribute the two of them sepatately.

**Comment by jamesmcminn96** [comment]
Hey @labbati, we actually use both. Thanks for getting to it!

**Comment by labbati** [comment]
Hi @jamesmcminn96 👋 . This feature is due for release early next week with 0.51.0. If you like to test a preview of it in your staging/testing envs you can download the appropriate artifact from this page: https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/4883/workflows/dd51c6db-5198-483b-b1c3-36d54b68bcbd/jobs/280174/artifacts

**Comment by cfong63** [comment]
Hello thread, I was wondering if theres any similar work going on for splitting by host for PDO?

**Comment by labbati** [comment]
> Hi @jamesmcminn96 👋 . This feature is due for release early next week with 0.51.0. If you like to test a preview of it in your staging/testing envs you can download the appropriate artifact from this page: https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/4883/workflows/dd51c6db-5198-483b-b1c3-36d54b68bcbd/jobs/280174/artifacts

It is technically possible but currently we haven't any work scheduled for it. Feel free to open a separate feature request, though.
