### ISSUE TITLE
[Feature] Enable setting errors in \DDTrace\trace_function DDTrace\trace_method

### ISSUE THREAD

**Issue by stanislau93** [DataDog/dd-trace-php#1098]
I would like to trace Symfony Messenger component. 
I trace vendor/symfony/messenger/Worker.php::dispatchEvent() method. This method's sole argument is the event object which is either WorkerMessageHandledEvent or WorkerMessageFailedEvent. 
The problem is - Symfony Messenger does not throw an error if a message handling fails. Instead - it dispatches a WorkerMessageFailedEvent. So even if there is an error, my span is not marked as Error

Inside of the trace_method() I would like to set an error to the span if the $arg[0] is an instance of WorkerMessageHandledEvent. But the SpanData class does not give me such possibility

I've considered an alternative of using Event Listener on WorkerMessageFailedEvent. I almost succeeded, but for some reason I am not able to set my service's name to the span and it takes the default one (which is 'cli')

here's what's on my mind, unless someone would have a better suggestion?

```
if (function_exists('\DDTrace\trace_method') && function_exists('\ddtrace_config_app_name')) {
    \DDTrace\trace_method(
        'Symfony\Component\Messenger\Worker',
        'dispatchEvent',
        function (\DDTrace\SpanData $span, $args) {
            $event = $args[0];

            if (
                ($event instanceof \Symfony\Component\Messenger\Event\WorkerMessageHandledEvent) === false &&
                ($event instanceof \Symfony\Component\Messenger\Event\WorkerMessageFailedEvent) === false
            ) {
                return;
            }

            /** @var \Symfony\Component\Messenger\Envelope $envelope */
            $envelope = $event->getEnvelope();
            $messageName = (new ReflectionClass($envelope->getMessage()))->getShortName();

            $span->name = 'symfony.messenger';
            $span->service = \ddtrace_config_app_name('symfony');
            $span->resource = "MessageHandler#{$messageName}";


            /** Impossible at the moment */
            if ($event instanceof \Symfony\Component\Messenger\Event\WorkerMessageFailedEvent) {
                $span->error = $event->getThrowable();
            }
        }
    );
}

`

**Comment by SammyK** [comment]
👋 @stanislau93. There are three error-related keys as part of `DDTrace\SpanData::$meta`:

- `error.msg`: The error message (if present, this will mark the span as an error in the UI)
- `error.type`: The error name/type (optional; usually the exception name)
- `error.stack`: The backtrace of the exception (optional)

So in your case you could do something like this:

```php
if ($event instanceof WorkerMessageFailedEvent) {
	$ex = $event->getThrowable();
	$span->meta['error.msg'] = $ex->getMessage();
	$span->meta['error.type'] = get_class($ex);
	$span->meta['error.stack'] = $ex->getTraceAsString();
}
```

**Comment by stanislau93** [comment]
Thank you very much! I knew there were the meta key, but didn't know how it is parsed =)
I'll test it out and close the request
