### ISSUE TITLE
[Feature] Service name as prefix

### ISSUE THREAD

**Issue by andrei-dascalu** [DataDog/dd-trace-php#1114]
**Is your feature request related to a problem? Please describe.**
In other DD tracers, when specifying DD_SERVICE it acts as a prefix for naming other automatically instrumented "service" (eg: redis, http, etc). For example, when using the nodejs tracer, an application where DD_SERVICE=myapp will also report myapp-redis when using redis module and so on.

However, for the PHP tracer, DD_SERVICE appears as standalone and other services obtained when automatically instrumenting things like phpredis, appear as standalone. Therefore, different PHP applications using phpredis will have their redis related traces combined under phpredis. 

**Describe the solution you'd like**
Have DD_SERVICE act the same was as for the node library, eg - use it as a prefix for other related services.

**Describe alternatives you've considered**
I have looked for ways to manually name the automatically instrumented services, but I have found no documentation. Perhaps some documentation on how to do this manually would also help

Thanks!

**Comment by AndreyMarchuk** [comment]
+1
that's how .NET CORE tracer works

Potential solution for now is to map it manually
`DD_SERVICE_MAPPING = "curl:service-curl,elasticsearch:service-elasticsearch,eloquent:service-eloquent,guzzle:service-guzzle,laravel:service-laravel,pdo:service-pdo"`

Check [integration-names](https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=containers#integration-names) for full list

**Comment by labbati** [comment]
Hi @andrei-dascalu. We are not going to add this feature to our tracer as we are going to change the way we approach service maps and service naming in the near future for all the tracers. The final version will not be based on the `<service>-*` approach.

As of today you have two options to improve the visibility of your application:
1. service mapping as @AndreyMarchuk suggested
2. split-by options: see [docs](https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=containers#environment-variable-configuration) `DD_TRACE_HTTP_CLIENT_SPLIT_BY_DOMAIN` and `DD_TRACE_REDIS_CLIENT_SPLIT_BY_HOST `

I am closing this issue as we cannot implement it. Let me know if you need any further info on how to use the above mitigations.

**Comment by radykal-com** [comment]
@labbati is there any way to split also PDO by databases or hosts?

**Comment by labbati** [comment]
Hi @radykal-com, not at the moment. Please feel free to file a feature request with our support channel so it can be prioritized. Thank you
