### ISSUE TITLE
[BUG] Composer package does not contain _generated.php file

### ISSUE THREAD

**Issue by bgaillard** [DataDog/dd-trace-php#1128]
Hi, i'm not sure this one is a bug or not but I struggle several hours before finding it.

I wanted to upgrade our version of `dd-trace-php` to the last version `0.53.0`.

We have a Docker build which previously globally installed the extension with composer.;

```bash
php -d memory_limit=-1 /usr/local/bin/composer global require --no-progress --no-scripts --prefer-dist --profile "datadog/dd-trace:0.53.0"
```

The we configured a `ddtrace.ini` file with the `.so` extension and the path to the `dd_wrap_autoloader.php` file.

```ini
extension=ddtrace
ddtrace.request_init_hook = /usr/local/composer/vendor/datadog/dd-trace/bridge/dd_wrap_autoloader.php
```

We previously had version `0.47.1` of the extension and it worked as expected. But now it is not working anymore because their is not `bridge/_generated.php` file in the package installed through `require datadog/dd-trace`.

As a consequence I encounter the same issue as reported in https://github.com/DataDog/dd-trace-php/issues/1090 and https://github.com/DataDog/dd-trace-php/issues/1115.

We install the extension through PECL, if in my `ddtrace.ini` I change the path to the `dd_wrap_autoloader.php` file to point to a file installed by PECL then I do not have any problem anymore (because now the `bridge/_generated.php` file is their).

```ini
extension=ddtrace
ddtrace.request_init_hook = /usr/local/lib/php/datadog_trace/bridge/dd_wrap_autoloader.php
```

Is it normal to not have the `bridge/_generated.php` file in the composer package now ? Or is it a recent regression ?

**Comment by morrisonlevi** [comment]
Since version 0.48, PECL installs do not require the composer package nor require users to set the `ddtrace.request_init_hook` configuration setting manually. Version 0.53.0 fixed a bug in the PECL package so definitely use the latest.

I will make sure an escalation engineer takes a look at this; I'm just passing by and thought I'd convey this information.

**Comment by labbati** [comment]
Hi @bgaillard.

> Is it normal to not have the bridge/_generated.php file in the composer package now ? Or is it a recent regression ?

It is expected. the extension should the `dd_wrap_autoloader.php` that comes with it (meaning the one coming from `_generated.php`).

If I am understanding your setup, here is the process that you should have:

1. install extension via `pecl`
2. create/edit the `ddtrace.ini` to point to the `dd_wrap_autoloader.php` installed by pecl (no composer involved so far)
3. if you are not doing manual instrumentation (aka using the `DDTrace\*` namespace in your code) then nothing else is required. You do not need our composer package and you can skip next steps.
4. if you are using classes from `DDTrace\` namespace in your codebase then add our composer package to application composer and use the classes provided by composer as you would with any other package. Note that only classes from `src/api` are provided by our psr4 autoloader and you should only use those. __This works even if the extension is not installed and it just results in a noop tracer__
5. in production (or in general when the extension is instealled) the extension will take case of replacing the classes and provide the correct "real" autoloader.

**Comment by bgaillard** [comment]
Hi @morrisonlevi @labbati, thanks for your detailed responses :+1: 

Ok, we now have the exact setup you described @labbati and it correctly works.

So I think we can close this issue as it was a configuration problem on our side.

**Comment by axot** [comment]
Hi @labbati, we are testing PHP 8 these days, I understand `composer -dtooling/generation generate` will not work under PHP 8. Is it necessary to have _generated.php with PHP 8 and latest dd-trace-php 0.59.0?
