### ISSUE TITLE
[FEATURE] Allow Setting/Reading of DD_* ENV vars from application runtime

### ISSUE THREAD

**Issue by mglinski** [DataDog/dd-trace-php#1133]
Currently I don't see a way to configure these ENV vars like `DD_VERSION` or `DD_APP` from inside the php runtime itself. I am using the Laravel Integration mostly, but if I run something like `putenv("DD_VERSION=1.2.3")` in my app boot process, it does not get used because the bridge functions to get this data from ENV get called before any of my app code gets run and are not called again.

It would be great to be able to set the values during runtime, and not have to worry about updating/maintaining a php-fpm pool configuration file during our deploy process.

**Comment by morrisonlevi** [comment]
Thanks for the feature request. If we allowed you to configure using INI variables, would that be any easier for you in this case?

**Comment by mglinski** [comment]
In our use-case, no. Our runtime environments are shared currently and the usability difference between having to manage a custom INI file vs a custom fpm pool config is splitting hairs for us.

**Comment by labbati** [comment]
Hi @mglinski, at the moment we are re-thinking the way we let configure our tracer. Your feature request definitely makes sense. I added a note to our ticket to support this use case. It reads like "Support overwriting settings at runtime from PHP userland code". While we target end of Q1 for implementation, I cannot commit at the moment to a specific ETA as we are keeping focus on stability right now.

**Comment by lwohlhart** [comment]
Maintaining legacy code here;
would also really appreciate the ability to set the `DD_*`  environment variables within the userland code.

Looking forward to hearing about a solution.

**Comment by bwoebi** [comment]
Hey,

we've moved to additional ini-supported configuration about half a year ago.

So, the `DD_*` env variables are still supported, but their values can also be set via inis and these inis can be altered at runtime.

Every `DD_*` env variable has an equivalent ini setting. Every env var starting with `DD_TRACE_*` has an equivalent `datadog.trace.*` setting, example `DD_TRACE_GENERATE_ROOT_SPAN` => `datadog.trace.generate_root_span`. Other env vars starting with `DD_*` only have an equivalent `datadog.*` setting, for example: `DD_PRIORITY_SAMPLING` => `datadog.priority_sampling`.

Not all of these inis can be changed a runtime, but most can. Note however that changes to the inis are generally not retro-actively applied (datadog.trace.generate_root_span can be set at runtime though), so if a span has been started with a pre-set DD_VERSION, and `ini_set("datadog.version", "4")` is only executed afterwards, that span will still have the pre-set value.

**Comment by bwoebi** [comment]
I'm also closing the issue as the feature request has been implemented that way.

**Comment by georaldc** [comment]
> Hey,
> 
> we've moved to additional ini-supported configuration about half a year ago.
> 
> So, the `DD_*` env variables are still supported, but their values can also be set via inis and these inis can be altered at runtime.
> 
> Every `DD_*` env variable has an equivalent ini setting. Every env var starting with `DD_TRACE_*` has an equivalent `datadog.trace.*` setting, example `DD_TRACE_GENERATE_ROOT_SPAN` => `datadog.trace.generate_root_span`. Other env vars starting with `DD_*` only have an equivalent `datadog.*` setting, for example: `DD_PRIORITY_SAMPLING` => `datadog.priority_sampling`.
> 
> Not all of these inis can be changed a runtime, but most can. Note however that changes to the inis are generally not retro-actively applied (datadog.trace.generate_root_span can be set at runtime though), so if a span has been started with a pre-set DD_VERSION, and `ini_set("datadog.version", "4")` is only executed afterwards, that span will still have the pre-set value.

Sorry for commenting on this closed issue, but I just had a question about this:

We started dynamically setting the DD_VERSION tag via ini_set("datadog.version", "") as early in a request's code as possible but one thing I've noticed is if I have one distinct service "A" that makes calls to another known service "B" (eg. a curl call), service B's version starts to show up under Service A. Is this the expected behavior?
