### ISSUE TITLE
[Feature] allow toggling enable/disable tracing at runtime

### ISSUE THREAD

**Issue by philippefuentes** [DataDog/dd-trace-php#1146]
**Is your feature request related to a problem? Please describe.**
We run a docker php app on AWS ECS with around 80 tasks distributed on around 10 instances.
We don't want to trace all our traffic but instead being able to turn it on/off according to specific criterias.  

**Describe the solution you'd like**
Our customers are identified through their subdomain, we'd like to enable tracing at runtime for specific customers, with something like this:
```php
ddtrace_enable_trace(true);
```

**Comment by SammyK** [comment]
Hello @philippefuentes. Thank you for the feature request. Although we do not have an option to enable the tracer from a disabled state, you can disable the tracer at runtime using:

```php
dd_trace_disable_in_request();
```

Would that work for your use case?

**Comment by philippefuentes** [comment]
Thank you @SammyK for your quick answer.
I tried it and it seems to be exactly what I was looking for :).
Can you just confirm please that the overhead of this function call is minimal as it we'll be using it on each request for a specific customer ?
Besides, is there any official documentation on this ?

Thank you

**Comment by SammyK** [comment]
I'm glad to hear that solution works for your use case. :)

In terms of overhead, the tracer will still go through the bootstrapping process for every request. Your idea of enabling the tracer at runtime from a disabled state would avoid the bootstrapping overhead issue for requests that do not need to be traced. I will leave this feature request open as that is a valid use case to enable the tracer at runtime. Thank you again for the request!

**Comment by krakjoe** [comment]
Beyond the request for help, which seems solved ... The idea floating around in this thread is that it should be possible to implement a zero overhead, runtime (that is to say request time) installation of the instrumentation that dd needs to trace.

The problem with that is that some instruments have to be setup early in the processes lifecycle, a constraint born of the processing models PHP supports.

The most we can do is to disable for individual requests, minimising impact.

So, I'm going to close this: While it's a "valid use case", technical constraints prohibit an implementation that looks much different from the API already available.

**Comment by joshlevinson** [comment]
@SammyK Is `dd_trace_disable_in_request` considered to be part of the php tracer public API? I see it's implemented in C, and not documented anywhere, so just wanting to confirm.

**Comment by SammyK** [comment]
Yes, `dd_trace_disable_in_request()` is considered part of the public API.

**Comment by bwoebi** [comment]
I'd like to note that it is has become possible to write

```
ini_set("datadog.trace.enabled", 1);
```
at runtime (if disabled via `datadog.trace.enabled = 0` in an ini file).
The `ddtrace.disable` ini setting (which activates zero-overhead mode) cannot be toggled at runtime, as @krakjoe mentioned.

`dd_trace_disable_in_request()` is just a thin wrapper around an internal `ini_set("datadog.trace.enabled", 0);`.

**Comment by ogidimitrov** [comment]
@bwoebi i try to use `datadog.trace.enabled=0` in `/usr/local/etc/php/conf.d/99-ddtrace-custom.ini` then runtime 
```
bash-5.0# php /home/jiminny/artisan ti
Psy Shell v0.10.3 (PHP 7.4.9 — cli) by Justin Hileman
>>> ini_set('datadog.trace.enabled', '1')
=> false
>>> ini_set('datadog.trace.enabled', 1)
=> false
>>>
>>> ini_get('datadog.trace.enabled')
=> "0"
>>>
```
which fails. Advice please ?
