### ISSUE TITLE
[BUG] Support Symfony on PHP 8

### ISSUE THREAD

**Issue by kalimatas** [DataDog/dd-trace-php#1148]
### Bug description
PHP compatibility documentation says that Symfony framework and PHP 8 are supported https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/php/. But after upgrading my app to PHP 8, I no longer see proper Symfony integration. For example, before, `symfony.request` was a primary operation and traces contained corresponding information. Now, `web.request` is a primary operation and it has only one span.

Also, `\DDTrace\Integrations\IntegrationsLoader` says the following:

```
        // Add integrations as they support PHP 8
        if (\PHP_MAJOR_VERSION >= 8) {
            $this->integrations[CodeIgniterIntegration::NAME] =
                '\DDTrace\Integrations\CodeIgniter\V2\CodeIgniterIntegration';
            $this->integrations[CurlIntegration::NAME] =
                '\DDTrace\Integrations\Curl\CurlIntegration';
            $this->integrations[EloquentIntegration::NAME] =
                '\DDTrace\Integrations\Eloquent\EloquentIntegration';
            $this->integrations[GuzzleIntegration::NAME] =
                '\DDTrace\Integrations\Guzzle\GuzzleIntegration';
            $this->integrations[LaravelIntegration::NAME] =
                '\DDTrace\Integrations\Laravel\LaravelIntegration';
            $this->integrations[MysqliIntegration::NAME] =
                '\DDTrace\Integrations\Mysqli\MysqliIntegration';
            return;
        }
```

And SymfonyIntegration is not part of the list.

### PHP version
PHP 8.0.2 (cli) (built: Feb  5 2021 04:43:21) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies
    with ddtrace v0.55.0, Copyright Datadog, by Datadog

### Installed extensions
```
php -m
[PHP Modules]
apcu
bcmath
Core
ctype
curl
date
dom
ds
fileinfo
filter
ftp
hash
iconv
igbinary
intl
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Xdebug
Zend OPcache
```
### OS info
```
cat /etc/os-release | grep -E "(NAME)|(VERSION)"
NAME="Alpine Linux"
VERSION_ID=3.13.1
PRETTY_NAME="Alpine Linux v3.13"
```

### Upgrading info
Previous PHP version 7.4.8.

ddtrace 0.50.0

**Comment by labbati** [comment]
Hi @kalimatas, which version of Symfony you are on? We want to enable tests for that very specific version before enabling the deep instrumentation. Note, though, that you will see ALL the other spans (dbs, cache, http clients, etc...)

**Comment by kalimatas** [comment]
Hi @labbati, we are on Symfony 5.2.3 now.

**Comment by labbati** [comment]
Hello. Support has been added and it will be included with the next release.

**Comment by floranpagliai** [comment]
Hello @labbati, it's been a while now since we are waiting for this fix to be deployed. Any news about a release soon ?

**Comment by labbati** [comment]
We target early next week. Our goal is to deploy to our pre-release environment today or Monday, and after ~48 hours under heavy load with no issues we will release 0.57.0.
