### ISSUE TITLE
Laravel authorize middleware not working

### ISSUE THREAD

**Issue by Sh4d1** [DataDog/dd-trace-php#115]
Hey,

I use the authorization via middleware of laravel (https://laravel.com/docs/5.7/authorization#authorizing-actions-using-policies).

In the Laravel provider ([line 61](https://github.com/DataDog/dd-trace-php/blob/4f9c95cef0afe38b112f67493ae51ef642f6e72a/src/DDTrace/Integrations/LaravelProvider.php#L61)) instead of a class I get `'Illuminate\\Auth\\Middleware\\Authorize:users'` which leads to this error: `unexpected parameter combination, expected (class, function, closure) or (function, closure)`.

**Comment by labbati** [comment]
@Sh4d1 confirmed in #117  that the fix worked for hime. Resolving this issue. @Sh4d1 thanks for the help and the patience.
