### ISSUE TITLE
[Feature] Instrumenting PHP Extension methods

### ISSUE THREAD

**Issue by radykal-com** [DataDog/dd-trace-php#1161]
### Bug description
When trying to instrument a long running process that consumes from RabbitMQ using AMQP extension (https://github.com/php-amqp/php-amqp) I tried to use trace_method on the callable we pass to `AMQPQueue::consume` but it was never triggering I suspect due to the way AMQP extension calls that callable (maybe related to https://github.com/DataDog/dd-trace-php/issues/443). Then I tried to trace directly some AMQP extension methods like (https://github.com/php-amqp/php-amqp/blob/df1241852b359cf12c346beaa68de202257efdf1/amqp_queue.c#L500) but neither using `\DDTrace\trace_method('AMQPQueue', 'consume'...` or `\DDTrace\trace_method('\AMQPQueue', 'consume'...` were working.

### PHP version
```
PHP 7.4.14 (cli) (built: Jan 12 2021 02:26:27) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies
    with ddtrace v0.55.0, Copyright Datadog, by Datadog
```
### Installed extensions
```
[PHP Modules]
amqp
bcmath
Core
ctype
curl
date
ddtrace
dom
fileinfo
filter
ftp
gd
grpc
hash
iconv
igbinary
intl
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
protobuf
rdkafka
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

### OS info
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by SammyK** [comment]
Hello @radykal-com. An optimization exists that [ignores all internal functions and methods](https://docs.datadoghq.com/tracing/setup_overview/custom_instrumentation/php/?tab=tracingfunctioncalls#tracing-internal-functions-and-methods) by default. To trace an internal method, add the fully qualified name to the `DD_TRACE_TRACED_INTERNAL_FUNCTIONS` environment variable. (e.g. `DD_TRACE_TRACED_INTERNAL_FUNCTIONS=AMQPQueue::consume`). After restarting the PHP process, the `AMQPQueue::consume` method should be able to be traced.

Let us know if you still have trouble with it after setting that environment variable.

**Comment by radykal-com** [comment]
Yeah, its working fine. Thanks you!
