### ISSUE TITLE
[BUG] Compatiblity with opentracing/opentracing:1.0.1

### ISSUE THREAD

**Issue by Agares** [DataDog/dd-trace-php#1182]
### Bug description
I'm trying to use this extension with opentracing/opentracing:1.0.1. It works fine with 1.0.0-beta6, but it fails on 1.0.1 due to missing typehints.
Version >=1.0.0 is required for PHP8 compatibility.

```
<br />
<b>Fatal error</b>: Declaration of DDTrace\OpenTracer\Tracer::getScopeManager() must be compatible with
OpenTracing\Tracer::getScopeManager(): OpenTracing\ScopeManager in
<b>/opt/datadog-php/dd-trace-sources/src/DDTrace/OpenTracer/Tracer.php</b> on line <b>134</b><br />
```

### PHP version
```
PHP 8.0.2 (cli) (built: Feb  2 2021 19:28:42) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
    with ddtrace v0.54.0, Copyright Datadog, by Datadog
```

### Installed extensions
```
[PHP Modules]
apcu
bz2
calendar
Core
ctype
curl
date
ddtrace
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
igbinary
intl
json
json_post
libxml
mbstring
msgpack
openssl
pcntl
pcre
PDO
pdo_sqlite
pdo_sqlsrv
Phar
readline
redis
Reflection
session
SimpleXML
sockets
SPL
sqlite3
sqlsrv
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
ddtrace
```

### OS info
```
NAME="CentOS Linux"
VERSION="7 (Core)"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
CPE_NAME="cpe:/o:centos:centos:7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
#### Output of phpinfo() (ddtrace >= 0.47.0)

![image](https://user-images.githubusercontent.com/303398/111464640-5387a080-8721-11eb-9555-93ffdd2eb932.png)

**Comment by bbaga** [comment]
Hello @labbati 
this issue is making it hard to upgrade our applications to PHP 8, I've submitted a PR (#1188) with a possible fix, a review/feedback would be much appreciated

**Comment by labbati** [comment]
[0.57.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.57.0) is out, which includes the fix for this issue. Please feel free to try it and to ping me in case anything is not working as expected. I am closing this issue for now. Thank you again @bbaga for the PR.
