### ISSUE TITLE
[Question] Laravel Integration modification (best practice, example, etc)

### ISSUE THREAD

**Issue by matthewnessworthy** [DataDog/dd-trace-php#1187]
**Is your feature request related to a problem? Please describe.**
I would like to add additional tags to the laravel integration

**Describe the solution you'd like**
The recommended place and method to enhance integration tags

**Describe alternatives you've considered**
Currently I have a Laravel Global Middleware that adds the required tags

e.g.: (some details clipped because reasons)
```
    public function handle($request, Closure $next)
    {
        if (
            ($rootScope = GlobalTracer::get()->getRootScope())
            && ($rootSpan = $rootScope->getSpan())
        ) {
            $rootSpan->setTag('http.referer', $request->header('HTTP_REFERER'));
            ...
        }

        return $next($request);
    }
```

**Additional context**
Specifically I would like to add http referer to the laravel route resolution `findRoute` binding

**Comment by labbati** [comment]
Hi @matthewnessworthy, for this very specific issue - adding a request header - did you try `DD_TRACE_HEADER_TAGS`? See our docs: https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=containers#environment-variable-configuration

In general they way you are doing is ok. Soon we will be expanding our api for manual tracing and will add even simpler ways to do this, e.g. not requiring you to inject code related to observability in your own code. More soon on this.

**Comment by labbati** [comment]
Also, note that the `DD_TRACE_HEADER_TAGS ` configuration option is available starting from [0.56.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.56.0).

**Comment by matthewnessworthy** [comment]
Hi @labbati, 
That sounds like a really useful feature, where can find additional usage examples or documentation for `DD_TRACE_HEADER_TAGS`?
The middleware I added is working as expected, but if i could replicate that functionality within the infra code that would be very cool.

**Comment by labbati** [comment]
I assume the header you want to access is [Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer).

Set an env `DD_TRACE_HEADER_TAGS =referer` and you are good to go. Note that is you are using PHP-FPM you have to configure this env in the pool config
```
[www]

...

env[DD_TRACE_HEADER_TAGS] = referer

```

**Comment by matthewnessworthy** [comment]
Is there some way of transforming or normalising the keys?

In this specific case I'm interested in storing the referer, user agent, and the request id

Currently I'm solving this like so:
```
$rootSpan->setTag('http.referer', $request->header('HTTP_REFERER'));
$rootSpan->setTag('http.request_id', $request->server('HTTP_X_REQUEST_ID'));
$rootSpan->setTag('http.useragent', $request->userAgent());
```

**Comment by labbati** [comment]
As of today, no unfortunately. We were considering the possibility to rename, but in that case the key would have been under the `http.(request|response).headers.*` namespace in any case. May I ask why you cannot use our namespace? Because of monitors/alerts you have already in place?

**Comment by matthewnessworthy** [comment]
i'm attempting to normalise the heads and data we have into the datadog namespace

it could be that i'm missing something though

e.g.: 
$_SERVER['HTTP_X_REQUEST_ID'] -> http.request_id
$_REQUEST['HTTP_REFERER'] -> http.referer
$_SERVER['HTTP_USER_AGENT'] -> http.useragent

**Comment by labbati** [comment]
Hi @matthewnessworthy, let me make an example using your own header names.

Say you have a PHP-FPM `www.conf` and there you add:

```
env[DD_TRACE_HEADER_TAGS] = x-request-id,referer,user-agent
```
Then when the request has those headers (so they are in `$_SERVER`, not in `$_REQUEST`) you would have them automatically added to the root span.

```
curl -v -H 'x-request-id: 123' -H 'referer: http://example.com' localhost:80
```
generates
![image](https://user-images.githubusercontent.com/2952352/113214267-87160f00-9279-11eb-9114-439526babea7.png)

You cannot change the tag name, for example, from `http.request.headers.x-request-id` to `http.request_id`.
