### ISSUE TITLE
Missed RedisCluster support

### ISSUE THREAD

**Issue by TheLevti** [DataDog/dd-trace-php#1200]
RedisCluster support has been added in 0.55.0, but a few places were missed out like the connection tracing. Because of this we can not use  `DD_TRACE_REDIS_CLIENT_SPLIT_BY_HOST` together with a cluster connection.

https://github.com/DataDog/dd-trace-php/blob/b2339cf714abe53e8768dfceb2e7dcb9f697ae5e/src/DDTrace/Integrations/PHPRedis/PHPRedisIntegration.php#L54

**Comment by radykal-com** [comment]
Is there any chance to get this one done? All our redis are redis cluster and we are missing the split by host feature that would be so nice to have

**Comment by radykal-com** [comment]
@labbati I've opened a PR with the implementation. Can someone give it a try? Thank you
