### ISSUE TITLE
[BUG] DDTrace\Format no longer autoloadable / part of API

### ISSUE THREAD

**Issue by ben-challis** [DataDog/dd-trace-php#1230]
### Bug description
We were previously using `TracerInterface::extract()`, `TracerInterface::inject()` with `$format` as `Format::TEXT_MAP` for custom AMQP based distributed tracing. After upgrading to the latest version (we were rather behind so I'm not certain where this change occurred), we now cannot autoload the `Format` enum. This appears related to splitting the autoloadable files into an `api` sub-directory, and not including `Format`. Is this intended behaviour? The `TracerInterface` PHPDoc also references `Format`.

We've changed over to just using the equivalent raw string values from the enumeration for now though this is of course inferior to referencing your constants.

**Comment by labbati** [comment]
Hi @ben-challis, the fix to this issue has been released with 0.62.0
