### ISSUE TITLE
[Feature] Ability to not report an exception as an error with trace_* C APIs

### ISSUE THREAD

**Issue by ben-challis** [DataDog/dd-trace-php#1231]
**Is your feature request related to a problem? Please describe.**
With the PHP API we have `Span::setError()` that can take a `\Throwable`. While this adds extra boilerplate and explicit steps to trace code with, it gives full control. When using `trace_method|function` APIs, `error.msg`, `error.type`, `error.stack` are auto-populated, and do not appear to be removable.

For our use case we are tracing phplibamqp's internals, where an `AMQPTimeoutException` is used to flag a timeout, but a throw will be expected behaviour in many situations, and being vendor code, this is not something we can rewrite away from the exception modelling. This has the effect of a worker listening for messages to come in constantly reporting errors as it has a short timeout after which it immediately waits again.

![image](https://user-images.githubusercontent.com/8275163/118132941-25a89a80-b3f8-11eb-9872-e62cacac3b34.png)

We're using the below to trace this code:

```php
    \DDTrace\trace_method(
        AbstractChannel::class,
        'wait',
        function (\DDTrace\SpanData $span, array $args, $returnValue, $exception): void {
            $span->name = 'amqp.wait';
            $span->type = Type::MESSAGE_CONSUMER;
            $span->service = 'amqp';
            $span->meta['timeout'] = $args[2] ?? '0';

            if ($exception instanceof AMQPTimeoutException) {
                // This does not work, despite being a "post hook" - when does it get populated?
                unset($span->meta['error.type'], $span->meta['error.msg'], $span->meta['error.stack']);
            }
        }
    );
```

Previously our tracing logic was:

```php
    \dd_trace(
        AbstractChannel::class,
        'wait',
        function (...$args) {
            $scope = GlobalTracer::get()->startActiveSpan('amqp.wait');
            $span = $scope->getSpan();

            $span->setTag(Tag::SPAN_TYPE, Type::MESSAGE_CONSUMER);
            $span->setTag(Tag::SERVICE_NAME, 'amqp');
            $span->setTag('timeout', $args[2] ?? '0');

            try {
                return \dd_trace_forward_call();
            } catch (\Throwable $throwable) {
                if (!$throwable instanceof AMQPTimeoutException) {
                    $span->setError($throwable);
                }

                throw $throwable;
            } finally {
                $scope->close();
            }
        }
    );
```

**Describe the solution you'd like**
Ability in the C tracing API to conditionally clear the error from the provided `SpanData` instance.

**Describe alternatives you've considered**
We're limited as this is vendor code we need to trace, the exception modelling for a timeout here is debatable, but not something we can change. 

I've tried clearing all `error` related properties from `meta`, but they appear unset at this stage anyway.

**Comment by mannion007** [comment]
Is there any update on this please? We have filtered it out but of course that isn't ideal for anyone not using a saved view in logs or  looking for a point of failure in a trace.

**Comment by mannion007** [comment]
We've now been working with the above log stream since upgrading to the latest client (the C API) for a month. Can we please get an acknowledgement of this issue and any indication of the priority for adding this feature to the C API?

Should we be considering downgrading back to the older version/PHP API? As detailed by @ben-challis above, we rely on this feature which has seemingly not been ported.

Please do let me know if there is an alternative channel to raise and discuss issues on, this issue has significant impact for us.

**Comment by mannion007** [comment]
We continue to wait for this to be triaged or even acknowledged a full two months after reporting this issue and raising with our account manager. This really does have significant impact on the feasibility of DataDog for our requirements. Would really appreciate any response to allow us to plan accordingly.

**Comment by labbati** [comment]
Hello @ben-challis and @mannion007!

I take full responsibility for the huge delay in the acknowledgment and the response. The specific subject of this issue makes things even worse: security issues, application crashes, missed errors, and false positives in error reporting have the highest priority while we schedule our next work.

Acknowledgement and responsibility, though, does not help much. One resource is taking this as their next task; this means tomorrow/Monday. If it will not make into `0.62.0` on Tuesday/Wednesday, It will make into `0.63.0`.

The api that we are considering is:
- `unset($span->exception);`; and
- `$span->exception = null`.

You still have time to provide feedback on this, if you prefer other ways.

**Comment by mannion007** [comment]
Hi @labbati thank you for the response and effort to resolve this, it is very much appreciated.

Any API that reinstates the feature Ben demonstrated in the example of how we previously used the PHP API to clear the exception would meet our needs to be honest.

For me, `unset($span->exception);` seems sensible.

**Comment by bwoebi** [comment]
Hey @ben-challis and @mannion007, we've just merged your feature request, but we have a backlog of changes on PHP 8, which are requirements for this specific feature to be easily backported to PHP 7 and ultimately PHP 5.
This feature will land in 0.62.0, but only on PHP 8.

We will work on this within the next week and aspire to land this feature for PHP 7 on master within a week. It will then be part of the 0.63.0 release as @labbati mentioned.

**Comment by mannion007** [comment]
Thanks for your help @bwoebi and @labbati. I have been keeping an eye for the release of v63, do you have any idea when you are looking to release it please?

**Comment by labbati** [comment]
no yet, unfortunately. We are currently actively working on this, though, not shifting the focus to anything else.

**Comment by labbati** [comment]
Heads up about this issue.

We are releasing 0.63.0 without this fix on PHP 7. The [work for PHP 7](https://github.com/DataDog/dd-trace-php/pull/1293) to solve this issue is in progress and we are fixing/improving our test suite after the changes.
Some preparatory work that blocks this specific fix is going to be released with [0.63.0](https://github.com/DataDog/dd-trace-php/pull/1260), but not the complete fix. This work took longer than expected, hence the additional release.

0.64.0 will be released immediately once we have this feature landing. It could be as soon as end of the week if we do not find any unexpected problems.

Thanks for you patience!

**Comment by labbati** [comment]
[0.64.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.64.0) is out that fixes this issue on PHP 7. Thank you for the patience

**Comment by mannion007** [comment]
Hi, I have upgraded to v0.64.1 and deployed to a test environment. I still see the AMQPTimeoutException errors on the traces for amqp.wait.

```
\DDTrace\trace_method(
    AbstractChannel::class,
    'wait',
    function (\DDTrace\SpanData $span, array $args, $returnValue, $exception): void {
        $span->name = 'amqp.wait';
        $span->type = Type::MESSAGE_CONSUMER;
        $span->service = 'amqp';
        $span->meta['timeout'] = $args[2] ?? '0';

        if ($exception instanceof AMQPTimeoutException) {
            // Remove non-error exception.
            unset($span->exception);
        }
    }
);
```
