### ISSUE TITLE
[Feature] Ability to conditionally trace in the trace_* C API

### ISSUE THREAD

**Issue by ben-challis** [DataDog/dd-trace-php#1233]
**Is your feature request related to a problem? Please describe.**
With the previous `dd_trace` based API, we could conditionally just early return passing through the call, essentially acting as hook only. For example, here we only want to trace the code if it a span is in progress. This code may fire outside of our primary use case (worker message processing) when it is simply looking for events (polling approach). We do not want thousands of traces containing just this span to be reported to DataDog as they are not useful to us. 

```php
    if (\in_array(EventStore::class, $interfaces, true)) {
        \dd_trace(
            $class,
            'readAllFromSequenceNumber',
            function (...$args) {
                if (!GlobalTracer::get()->getActiveSpan()) {
                    return \dd_trace_forward_call();
                }
```

Another example would be AMQP interaction, where by the queue is being polled/waited on until a message comes in, with a timeout. When this timeout is hit, it polls/awaits again repetitively until a message arrives in the queue. We _are_ interested in this low level queue interaction, but not in all contexts; and certainly not when it would create a root span / entire trace!

**Describe the solution you'd like**
Functionality (or documentation if this is already supported) for how to achieve abandoning or not starting a span with the `DDTrace\trace_*` C APIs.

**Describe alternatives you've considered**
The alternative here is decoration, and the PHP API, but this is far more cumbersome than the AoP style interception. As it is vendor code we're at the mercy of the vendor. For example, we've previously hit restrictive `instanceof` checks that make decoration with OpenTracing/DataDog wrappers problematic as it refuses to accept the decorator as a supported instance type. 

From digging at the C source, it appears a `prehook` and `posthook` with the `hook_*` API, and then calling the regular userland PHP APIs could possibly achieve this but declaring both hooks at the same time isn't yet supported.

```c
    if (prehook && posthook) {
        // both callbacks given; not yet supported
        ddtrace_log_debug(
            "DDTrace\\hook_function was given both prehook and posthook. This is not yet supported; ignoring call.");
        RETURN_FALSE;
    }
```

**Comment by ben-challis** [comment]
An update on this one would be appreciated, this is functionality we lost when tracing shifted into C and there's still no solution (that we're aware of) for, thanks!

**Comment by bwoebi** [comment]
Hey @ben-challis, we're going to track this via #1358, we plan to make starting and closing spans in hook methods possible at all (and solve the simultaneous prehook and posthook-ability at the same time).

I'm closing this issue thus.

**Comment by bwoebi** [comment]
Hey @ben-challis,

It's been a long time, but with 0.76.0 simultaneous pre- and posthooks are now allowed :-)
