### ISSUE TITLE
musl issue isn't extension specific, but PHP specific

### ISSUE THREAD

**Issue by derickr** [DataDog/dd-trace-php#1242]
https://github.com/DataDog/dd-trace-php/blob/70891f17d671de3230e1ef2ae6ccde2f17b72bcd/dockerfiles/ci/alpine/php-8.0/Dockerfile#L86

https://github.com/php/php-src/pull/7018

**Comment by SammyK** [comment]
TIL. Thanks for the heads up, @derickr (and the upstream patch).
