### ISSUE TITLE
Better documentation on how to create custom instrumentation for long-running processes

### ISSUE THREAD

**Issue by gnumoksha** [DataDog/dd-trace-php#1264]
Although [there is an example](https://github.com/DataDog/dd-trace-php/blob/master/examples/long-running/long-running-script.php) of how to create instrumentation for a long-running script, it is too simple because it assumes the PHP process will process only one routine and then die. A more common scenario is a daemon that processes events coming from a queue, in which case one wants to create custom instrumentation for each event and/or each event listener.

I'm trying to do that and faced some issues:
1. [The example](https://github.com/DataDog/dd-trace-php/blob/master/examples/long-running/long-running-script.php) is not on the documentation
2. The [documentation](https://docs.datadoghq.com/tracing/setup_overview/custom_instrumentation/php/?tab=tracingfunctioncalls#trace-a-custom-function-or-method) does not explain how to do instrumentation for daemons (scenario I've described above)
3. There is a lack of documentation for datadog functions, like [hook_method](https://github.com/DataDog/dd-trace-php/blob/15ac90b97ec2cf24b6063e2c13258f8551da614d/ext/php7/ddtrace.c#L665). This is partially related to https://github.com/DataDog/dd-trace-php/issues/664 because that is more focused on PhpStorm.
4. [Here](https://github.com/DataDog/dd-trace-php/issues/1065#issuecomment-716743812) you said "In any case we are moving away from userland spans altogether to rely only on internal spans" what that means?

**Comment by labbati** [comment]
Hello. For tracing long running scripts please look at our docs: https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=containers#tracing-cli-scripts

We will add method stubs as soon as possible.

Thank you!
