### ISSUE TITLE
[BUG] Error running post-install on Docker alpine:3.11

### ISSUE THREAD

**Issue by leonildojunior** [DataDog/dd-trace-php#1268]
### Bug description
I'm trying to install the extension with the code below:

```
RUN apk add bash
ENV DDTRACE_VERSION=0.60.0
RUN wget --no-check-certificate https://github.com/DataDog/dd-trace-php/releases/download/0.60.0/datadog-php-tracer-${DDTRACE_VERSION}.x86_64.tar.gz
RUN tar -xf datadog-php-tracer-${DDTRACE_VERSION}.x86_64.tar.gz -C / && sh /opt/datadog-php/bin/post-install.sh
```

But I'm getting the error `/opt/datadog-php/bin/post-install.sh: line 93: syntax error: unexpected "(" (expecting "}")`

### PHP version
PHP 7.3.22

### Installed extensions
[PHP Modules]
apcu
Core
ctype
curl
date
dom
fileinfo
filter
gd
hash
iconv
igbinary
imagick
intl
json
libxml
mbstring
memcached
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
redis
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

### OS info
NAME="Alpine Linux"
VERSION_ID=3.11.11
PRETTY_NAME="Alpine Linux v3.11"

**Comment by morrisonlevi** [comment]
:wave: Hello! I see a few immediate issues:

1. You install bash as the post-install.sh script requires it, but then you execute it with `sh` anyway.
2. You would still need to do something like `apk add php7 libexecinfo libcurl` for the post-install.sh script to work.

I think you would avoid these issues by installing the apk instead e.g.: https://github.com/DataDog/dd-trace-php/releases/download/0.60.0/datadog-php-tracer_0.60.0_noarch.apk. Is there a reason the APK doesn't work for you?

**Comment by leonildojunior** [comment]
I haven't posted my full code, above I add php7-fpm.

It really went much more smoothly with the .apk, thank you so much for your help.
