### ISSUE TITLE
[Feature] Completely remove _generated.php file

### ISSUE THREAD

**Issue by toVersus** [DataDog/dd-trace-php#1285]
**Is your feature request related to a problem? Please describe.**

We have built dd-trace-php from source code according to the official instruction [1].

[1] https://docs.datadoghq.com/tracing/faq/php-tracer-manual-installation/#install-from-source

Here is our minimum working Dockerfile:

```Dockerfile
FROM php:8.0.7-fpm-alpine3.14 AS deps

RUN set -eux \
  && apk add --virtual .build-deps \
  curl-dev \
  g++ \
  make \
  autoconf

RUN set -eux \
  # install datadog trace from source
  && DATADOG=0.61.0 \
  && curl -sqLo - https://github.com/DataDog/dd-trace-php/archive/${DATADOG}.tar.gz | tar zx -C / \
  && cd /dd-trace-php-${DATADOG} \
  && phpize \
  && ./configure --enable-ddtrace \
  && make -j $(nproc) && make install && make clean \
  && mkdir -p /usr/local/share/dd-trace-php \
  && cp -a /dd-trace-php-${DATADOG}/composer.json /usr/local/share/dd-trace-php/ \
  && cp -a /dd-trace-php-${DATADOG}/bridge /usr/local/share/dd-trace-php/ \
  && cp -a /dd-trace-php-${DATADOG}/src /usr/local/share/dd-trace-php/ \
  && cd - \
  && echo $'extension=ddtrace.so\nddtrace.request_init_hook=/usr/local/share/dd-trace-php/bridge/dd_wrap_autoloader.php' >> /usr/local/etc/php/conf.d/docker-php-ext-ddtrace.ini \
  && apk del .build-deps
```

When we run our PHP application as Kubernetes Pod and tried to trace the application metrics, we got the following error:

```
bash-5.1$ cat /var/log/php.log | tail -5
[19-Jul-2021 17:20:35 Asia/Tokyo] Unable to auto flush the tracer
[19-Jul-2021 17:21:04 Asia/Tokyo] Exception thrown in request init hook: require_once(/usr/local/share/dd-trace-php/bridge/_generated.php): Failed to open stream: No such file or directory
[19-Jul-2021 17:21:04 Asia/Tokyo] Unable to auto flush the tracer
[19-Jul-2021 17:28:52 Asia/Tokyo] Exception thrown in request init hook: require_once(/usr/local/share/dd-trace-php/bridge/_generated.php): Failed to open stream: No such file or directory
[19-Jul-2021 17:28:52 Asia/Tokyo] Unable to auto flush the tracer
```

It seems that the `_generated.php` file is missing in the bundle.

**Describe the solution you'd like**

Do you have any plans to remove _generated.php file as mentioned in the https://github.com/DataDog/dd-trace-php/issues/1128#issuecomment-756757714?

**Describe alternatives you've considered**

Currently, we add the step to emit `_generated.php` file via pecl installation as describe in the https://github.com/DataDog/dd-trace-php/issues/1128#issuecomment-756214118, and we confirm that the application metrics are properly sent to the Datadog trace agent.

Here is the updated version of our minimum working Dockerfile:

```Dockerfile
FROM php:8.0.7-fpm-alpine3.14 AS deps

RUN set -eux \
  && apk add --virtual .build-deps \
  curl-dev \
  g++ \
  make \
  autoconf

RUN set -eux \
  # install datadog trace from source
  && DATADOG=0.61.0 \
  && curl -sqLo - https://github.com/DataDog/dd-trace-php/archive/${DATADOG}.tar.gz | tar zx -C / \
  && cd /dd-trace-php-${DATADOG} \
  && phpize \
  && ./configure --enable-ddtrace \
  && make -j $(nproc) && make install && make clean \
  && mkdir -p /usr/local/share/dd-trace-php \
  && cp -a /dd-trace-php-${DATADOG}/composer.json /usr/local/share/dd-trace-php/ \
  && cp -a /dd-trace-php-${DATADOG}/bridge /usr/local/share/dd-trace-php/ \
  && cp -a /dd-trace-php-${DATADOG}/src /usr/local/share/dd-trace-php/ \
  && cd - \
  # emit _generated.php via pecl 
  && pecl install --onlyreqdeps --nobuild datadog_trace-${DATADOG} \
  && mv /usr/local/lib/php/datadog_trace/bridge/_generated.php /usr/local/share/dd-trace-php/bridge/ \
  # end
  && echo $'extension=ddtrace.so\nddtrace.request_init_hook=/usr/local/share/dd-trace-php/bridge/dd_wrap_autoloader.php' >> /usr/local/etc/php/conf.d/docker-php-ext-ddtrace.ini \
  && apk del .build-deps
```

**Additional context**

None

**Comment by morrisonlevi** [comment]
Thanks for the report! Do you need to build from source for some specific reason?

Until the team gets back to you with answers to your questions, I did verify that I was able to do a from-source build through pecl:

```dockerfile
FROM php:8.0.7-fpm-alpine3.14 AS deps

RUN set -eux \
  && apk add --virtual .build-deps \
  curl-dev \
  g++ \
  make \
  autoconf

RUN set -eux \
  # install datadog trace from source
  && DATADOG=0.61.0 \
  && pecl install datadog_trace-${DATADOG} \
  && printf "extension=ddtrace.so\n" >> /usr/local/etc/php/conf.d/docker-php-ext-ddtrace.ini \
  && apk del .build-deps
```

To do a basic health check, I ran this in the container where `DD_AGENT_HOST` is set to the hostname of the agent: `DD_AGENT_HOST=datadog_agent php --ri=ddtrace`. Look for this line in the output for a basic health check:

> Diagnostic checks => passed

**Comment by toVersus** [comment]
Thanks for your quick response!
This comment https://github.com/DataDog/dd-trace-php/issues/1115#issuecomment-767463109 and subsequent discussion describe the reason we need to build it from source code. We have been heavily used custom span traces which need DDTrace* namespace but it seems that there is no `src/api` when installing it via pecl.

**Comment by labbati** [comment]
Hello @toVersus. We confirm we eventually will remove the `_generated.php` file, but the work is still ongoing and will proceed through Q3. We need a different short term fix.

In case #1115 comes from your same organization and my understanding is correct, here are the root problems:
1. you want to enforce "composer package version" == "installed extension version" to avoid breaking changes; and
2. you cannot run `make generate` since it does not work on PHP 8, while it used to work before https://github.com/DataDog/dd-trace-php/issues/1115#issuecomment-767463109

We separated our code between `src/api` (aka the public api) and `src/DDTrace` (aka the internal classes) for this very specific reason - you are now not required to pin the two versions:
- `src/api` (autoloaded in composer) is not changing and we have no plans to change it;
- `src/DDTrace` (not autoloaded in composer) can change any time, **but you should NOT use it**, so if you use classes from this foleder we have to work together to understand the underlying reasons and fix them, rather than working around this behavior. **You cannot trust classes within `src/DDTrace`**, as eventually they will be removed one by one.

The correct way for you to move forward is to only use classes from our public api, aka the ones defined in `src/api`, installing our composer package. Such api is stable. You do not need the extension installed in the development machines, since classes will be available through composer and autocomplete will work out of the box.

Composer package and the extension are not required to stay on the very same version. Once you do this move, then you can install through our regular released installers, which contains the `_generated.php`.

We acknowledge this is a confusing setup, hence our urge to move away from this hybrid approach. But until we get rid of `_generated.php` and all the files in `src/DDTrace`, we are limited in our options.

**Comment by toVersus** [comment]
Thanks for your suggestion!
Yes, your understanding is correct, so we will try to migrate to regular released installers and give you a response in next week.

**Comment by toVersus** [comment]
@labbati 
We were able to confirm that our custom spans were successfully traced using the ddtrace extension installed from the pre-compiled package and also verify that we only relied on the public api under `src/api`.

My only concern is that the old or other distribution's ddtrace extensions (total 60 MB) are bundled in the pre-compiled package, so we need to delete them manually to reduce the image size.

```bash
/var/www/html # ls -lha /opt/datadog-php/extensions/
total 62M
drwxr-xr-x    2 root     root        4.0K Jul 29 07:33 .
drwxr-xr-x    8 root     root        4.0K Jul 29 07:33 ..
-rwxr-xr-x    1 root     root        1.6M Jul 28 13:32 ddtrace-20100412-alpine.so
-rwxr-xr-x    1 root     root        1.4M Jul 28 13:33 ddtrace-20100412-debug.so
-rwxr-xr-x    1 root     root        1.6M Jul 28 13:33 ddtrace-20100412-zts.so
-rwxr-xr-x    1 root     root        1.7M Jul 28 13:33 ddtrace-20100412.so
(...)
-rwxr-xr-x    1 root     root        2.0M Jul 28 13:32 ddtrace-20200930-alpine.so
-rwxr-xr-x    1 root     root        1.7M Jul 28 13:33 ddtrace-20200930-debug.so
-rwxr-xr-x    1 root     root        1.9M Jul 28 13:33 ddtrace-20200930-zts.so
-rwxr-xr-x    1 root     root        2.1M Jul 28 13:33 ddtrace-20200930.so
```

Here is our minimum working Dockerfile:

```Dockerfile
FROM php:8.0.7-fpm-alpine3.14 AS deps

RUN set -eux \
  && apk add curl \
  && _github_latest() { \
  curl -sqLo - https://api.github.com/repos/$1/releases/latest | grep '"tag_name":' | cut -d'"' -f4; \
  } \
  # install dd-trace-php from pre-compiled package
  && DATADOG=$(_github_latest DataDog/dd-trace-php) \
  && echo DATADOG: ${DATADOG} \
  && curl -sL https://github.com/DataDog/dd-trace-php/releases/download/${DATADOG}/datadog-php-tracer_${DATADOG}_noarch.apk -o /tmp/datadog-php-tracer.apk \
  && apk add /tmp/datadog-php-tracer.apk --allow-untrusted \
  # delete old or other distribution's pre-compiled dd-trace-php extensions
  && extension_abs_path=$(awk -F "=" '/extension/ {print $2}' /opt/datadog-php/etc/ddtrace.ini) \
  && extension_file_name=$(basename $extension_abs_path) \
  && extension_file_dir=$(dirname $extension_abs_path) \
  && find ${extension_file_dir} ! -name ${extension_file_name} -type f -exec rm {} +
```

But, we don't care so much about that. Thanks to your kind instruction, we can get out of the hard way to compile ddtrace extension by hand and simplify the build step. Thanks again for your help!

**Comment by labbati** [comment]
Thank you for confirming. About the side package, I acknowledge that is bigger than it should be and most of the bytes are useless. At the moment we have no plans to do a per version and php variant release (so your approach to remove the files is the best option), but if we collect here enough interested it can be something we can do for sure.
