### ISSUE TITLE
[BUG] dd-doctor: Cannot redeclare ddtrace_config_read_env_or_ini()

### ISSUE THREAD

**Issue by gnumoksha** [DataDog/dd-trace-php#1315]
```
[09-Sep-2021 19:14:35 UTC] PHP Fatal error:  Cannot redeclare ddtrace_config_read_env_or_ini() (previously declared in /usr/share/pear/datadog_trace/bridge/_generated_internal.php:85) in /var/app/current/public/a/dd-doctor.php on line 24
```

https://github.com/DataDog/dd-trace-php/blob/master/src/dd-doctor.php

**Comment by morrisonlevi** [comment]
This incompatibility was introduced in #1260 when `ddtrace_config_read_env_or_ini` was added to `bridge/configuration.php`.

**Comment by labbati** [comment]
@gnumoksha please instead of using `dd-doctor.php` try enable `DD_TRACE_DEBUG=1` and hit a `phpinfo();` page.`dd-doctor.php` will be removed soon.

**Comment by labbati** [comment]
I close this issue for now, based on my comment above. Feel free to comment and we will reopen, if appropriate.
BTW, thank you for the report :)
