### ISSUE TITLE
[BUG] Installing ddtrace on a Alpine docker image does not have any effect

### ISSUE THREAD

**Issue by drupsys** [DataDog/dd-trace-php#1348]
### Bug description
Installing ddtrace on an alpine docker image does not have any effect.

docker snippet that I run to install dd-trace-php
```
FROM alpine:3.8
...

## Install latest version of datadog tracer
RUN curl -s https://api.github.com/repos/DataDog/dd-trace-php/releases/latest | grep "browser_download_url.*apk" | cut -d / -f 8,8 > DATADOG_VERSION \
    && wget https://github.com/DataDog/dd-trace-php/releases/download/$(cat DATADOG_VERSION)/datadog-php-tracer_$(cat DATADOG_VERSION)_noarch.apk \
    && apk add --no-cache --allow-untrusted datadog-php-tracer_$(cat DATADOG_VERSION)_noarch.apk \
    && rm datadog-php-tracer_$(cat DATADOG_VERSION)_noarch.apk

...
```

### PHP version
```
PHP 5.6.40 (cli) (built: Jan 16 2019 23:59:17) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

### Installed extensions
```
[PHP Modules]
Core
ctype
curl
date
dom
ereg
fileinfo
filter
hash
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
standard
tokenizer
xmlwriter
zlib

[Zend Modules]
```
### OS info
```
NAME="Alpine Linux"
VERSION_ID=3.8.5
PRETTY_NAME="Alpine Linux v3.8"
```

#### Output of phpinfo() (ddtrace >= 0.47.0)
There is no `ddtrace` section on phpinfo page

**Comment by labbati** [comment]
How do you install PHP?

In the meantime, you can follow the .tar.gz install procedure: https://docs.datadoghq.com/tracing/faq/php-tracer-manual-installation/#install-from-the-targz-archive

Note that on Alpine you need to install `apk add bash curl libexecinfo` first.

**Comment by drupsys** [comment]
I was not able to figure out why it didn't work I've simple used a different base alpine image (php:5.6-fpm-alpine) and then installation worked without any additional configuration. I think this can be closed.

**Comment by drupsys** [comment]
So I had to do this again for a different project where I could not just switch base image, meanning I had to figure out what was happening here, I though I'll post the solution here incase someone else has the same problem.

Basically when ddtrace php extension is being install it detects apache installation and creates `conf.d` files (98-ddtrace.ini and 98-ddtrace.ini) in the apache folder

```sh
### ddtrace.ini created
###
### Created empty /opt/datadog-php/etc/ddtrace-custom.ini
###
### Linking ddtrace.ini for supported SAPI's
### 

### Found SAPI config directory: /etc/apache2/conf.d
### Linking ddtrace.ini to /etc/apache2/conf.d/98-ddtrace.ini
### Linking ddtrace-custom.ini to /etc/apache2/conf.d/99-ddtrace-custom.ini
###
### Failed enabling ddtrace extension
###
### The extension has been installed but couldn't be enabled
### Try adding the extension manually to your PHP - php.ini - configuration file
### e.g. by adding following line: 
###
###     extension=/opt/datadog-php/extensions/ddtrace-20180731-alpine.so
###
### Note that your PHP API version must match the extension's API version
### PHP API version can be found using following command
###
###     /usr/bin/php -i | grep 'PHP API'
###
```

I really should have just read the install message the first time arround, would have saved me a lot of time...

So any way the conf files were created in `/etc/apache2/conf.d/...` but my php instalation expects all conf files to be in `/etc/php7/conf.d/`

solution was to add the following two lines to Dockerfile

```
RUN ln -s /opt/datadog-php/etc/ddtrace.ini /etc/php7/conf.d/98-ddtrace.ini && \
    ln -s /opt/datadog-php/etc/ddtrace-custom.ini /etc/php7/conf.d/99-ddtrace-custom.ini
```

This creates sim links in the expect php conf directory.

**Comment by drupsys** [comment]
Alternatively you can also just install things in a particular order

1. install php
2. install ddtrace php extension
3. install apache2

this way ddtrace extension will pickup php config path instead of apache2
