### ISSUE TITLE
[BUG] There is no user-span on the top of the stack. Cannot close. when using userland-span

### ISSUE THREAD

**Issue by Bibob7** [DataDog/dd-trace-php#1358]
### Bug description

i see the following error messages, when applying the tracing implementation above:

`There is no user-span on the top of the stack. Cannot close.`

I already found another issue with the same error #1302, but the related bug should already be fixed in the version I am using.

My implementation:

```
\DDTrace\hook_method(
            'Grpc\BaseStub',
            '_simpleRequest',
            function ($baseStub, $class, $args) use ($serviceName) {
                if (!\class_exists('DDTrace\\GlobalTracer', false)) {
                    return;
                }

                $tracer = GlobalTracer::get();
                $scope = $tracer->startActiveSpan(GrpcIntegration::NAME . '.request', [
                    'tags' => [
                        Tag::SERVICE_NAME => $serviceName,
                        Tag::SPAN_TYPE => GrpcIntegration::NAME,
                    ]
                ]);

                \DDTrace\hook_method(
                    'Grpc\UnaryCall',
                    'wait',
                    null,
                    function ($unaryCall, $class, $args) use ($scope) {
                        if ($scope != null) {
                            $scope->close();
                        }
                    }
                );
            }
        );
```

### PHP version
PHP 8.0.12 (cli) (built: Oct 21 2021 16:17:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
    with ddtrace v0.66.0, Copyright Datadog, by Datadog
    with blackfire v1.59.2~linux-musl-x64-non_zts80, https://blackfire.io, by Blackfire

### Installed extensions
[PHP Modules]
blackfire
Core
ctype
curl
date
ddtrace
dom
fileinfo
filter
ftp
grpc
hash
iconv
json
libxml
mbstring
mongodb
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
protobuf
rdkafka
readline
Reflection
session
SimpleXML
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]
blackfire
ddtrace

### OS info
NAME="Alpine Linux"
VERSION_ID=3.14.2
PRETTY_NAME="Alpine Linux v3.14"

**Comment by labbati** [comment]
Hi, you are mixed two different APIs and using `hook_` (will not automatically generate a span) instead of `trace_` (will automatically generate a span). If my understanding of your problem is correct, here is what you should do. If it does not work, please explain a bit the usage you are doing of Grpc, as I am not familiar with this library.

```
\DDTrace\trace_method(
            'Grpc\BaseStub',
            '_simpleRequest',
            function ($span, $args) use ($serviceName) {
                $span->name = GrpcIntegration::NAME . '.request';
                $span->service = $serviceName;
                $span->type = 'custom';

                \DDTrace\hook_method(
                    'Grpc\UnaryCall',
                    'wait',
                    null,
                    function ($unaryCall, $class, $args) use ($scope) {
                        if ($scope != null) {
                            $scope->close();
                        }
                    }
                );
            }
        );

\DDTrace\hook_method(
        'Grpc\UnaryCall',
        'wait',
        null,
        function ($unaryCall, $class, $args) {
            \DDTrace\close_span();
        }
    );
```

My snippet assume that after `wait` is called the span has to end, for example is `wait()` blocks until the call has completed. Otherwise you might have to find another hook.

**Comment by Bibob7** [comment]
I want to have a span that spans two sequential method calls:

$sampleServiceClient->_simpleRequest($getSampleRequest)->wait();

The first method sends the request and wait waits for the response.
So the span for `_simpleRequest` should end when wait is finished.
However, I will try out your suggestion. Thank you!

**Comment by Bibob7** [comment]
Unfortunately, I see the same mistake. :/

**Comment by labbati** [comment]
Apparently we do not support this use case. The problem is that a new span cannot at the moment be generated from within a hook method. We will make sure we support it asap as we are rethinking our manual instrumentation capabilities.

For example this snippet (which is the right way to do what you need to do) will not generate the span you intend to generate.

```<?php

class BaseStub
{
    public function __simpleRequest()
    {
        sleep(1);
        return new UnaryCall();
    }
}

class UnaryCall
{
    public function wait()
    {
        sleep(1);
    }
}


\DDTrace\hook_method(
    'BaseStub',
    '__simpleRequest',
    function () {
        $span = \DDTrace\start_span();
        $span->name = 'grpc.request';
        $span->resource = 'some_action_or_method_name';
        $span->service = 'my_service_name';
        $span->type = 'custom';
    }
);

\DDTrace\hook_method(
    'UnaryCall',
    'wait',
    null,
    function () {
        \DDTrace\close_span();
    }
);

$baseStub = new BaseStub();
$unaryCall = $baseStub->__simpleRequest();
$unaryCall->wait();```

**Comment by bwoebi** [comment]
This use case now is properly supported with the release of 0.76.0.
Span creation and hooks are now independent, allowing this code to just work.
