### ISSUE TITLE
[BUG] Can't install in Alpine 3.13

### ISSUE THREAD

**Issue by wtbloom** [DataDog/dd-trace-php#1376]
### Bug description
I am unable to get the dd-trace-php installed under Alpine using the instructions provided.

We are using php:7.4.20-fpm-alpine3.13 via Docker.

### PHP version

PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/datadog-php/extensions/ddtrace-20190902-alpine.so' (tried: /opt/datadog-php/extensions/ddtrace-20190902-alpine.so (Error relocating /opt/datadog-php/extensions/ddtrace-20190902-alpine.so: unsupported relocation type 8), /usr/local/lib/php/extensions/no-debug-non-zts-20190902//opt/datadog-php/extensions/ddtrace-20190902-alpine.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20190902//opt/datadog-php/extensions/ddtrace-20190902-alpine.so.so: No such file or directory)) in Unknown on line 0
PHP 7.4.20 (cli) (built: Jun 28 2021 21:43:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.20, Copyright (c), by Zend Technologies

### Installed extensions

PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/datadog-php/extensions/ddtrace-20190902-alpine.so' (tried: /opt/datadog-php/extensions/ddtrace-20190902-alpine.so (Error relocating /opt/datadog-php/extensions/ddtrace-20190902-alpine.so: unsupported relocation type 8), /usr/local/lib/php/extensions/no-debug-non-zts-20190902//opt/datadog-php/extensions/ddtrace-20190902-alpine.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20190902//opt/datadog-php/extensions/ddtrace-20190902-alpine.so.so: No such file or directory)) in Unknown on line 0

### OS info
NAME="Alpine Linux"
VERSION_ID=3.13.5
PRETTY_NAME="Alpine Linux v3.13"

**Comment by bwoebi** [comment]
Hey Taylor,

Under which architecture are you running ddtrace? (`uname -a` should provide the information)

At least this on i386 or x86_64 architectures relocation type 8 is the default relocation type for shared libraries (R_X86_64_RELATIVE).

This error could appear, if you are running the extension under a non-supported architecture.

**Comment by labbati** [comment]
Closing this issue since it seems to have not activity. In case there is more work needed on our side please ping me here.
