### ISSUE TITLE
[Feature] Allow PDO connection name to be altered easily

### ISSUE THREAD

**Issue by marcus-crane** [DataDog/dd-trace-php#1377]
**Is your feature request related to a problem? Please describe.**
We're currently onboarding our PHP monolith + various microservices onto Datadog APM. For our microservices, we have them reporting each DB shard connection as an individual service so eg; shard-01, shard-02 etc.

Whether this is Datadog's expected use case, I couldn't say, but it's useful for visualising traffic in the service map since different shards have different req/s etc and I mean, it looks cooler 😏 

Anyway, for the PHP agent, it uses the PDO integration which hardcodes the service name to "pdo" as seen in the various `trace_method` instrumentations: https://github.com/DataDog/dd-trace-php/blob/b17550dfb6c8f9ed9a85e26fb475a4f34d616a00/src/DDTrace/Integrations/PDO/PDOIntegration.php#L40

**Describe the solution you'd like**
It would be nice if there was a way to override the service name used by pdo.

Perhaps an easy way to make use of [existing logic](https://github.com/DataDog/dd-trace-php/blob/b17550dfb6c8f9ed9a85e26fb475a4f34d616a00/src/DDTrace/Integrations/PDO/PDOIntegration.php#L20) could be to add an identifier to the connection DSN such as `service_name=shard-01` and if that exists, use that for the integration name instead?

Perhaps `dd_service=shard-01` to keep in line with the naming convention used for the tracer configuration environment variables.

**Describe alternatives you've considered**
We could manually reimplement the pdo trace_methods manually, overriding the service name but it's bulk of code for a small change. It's also a pretty small feature that would provide value to other customers too 🙂 

**Additional context**
Happy to (attempt) to write and test a PR for this feature myself if the idea checks out with the team

**Comment by labbati** [comment]
I completely skipped this issue, sorry for such a late response.

Today you can use service mapping. For example you can do `DD_SERVICE_MAPPING=pdo:shard-01` to rename all `pdo` services.

Moreover, starting from [0.71.0](https://github.com/DataDog/dd-trace-php/pull/1498) that will soon be released, you will have another option, split by instance. If you set `DD_TRACE_DB_CLIENT_SPLIT_BY_INSTANCE=true` the service name for `pdo` spans will be `pdo-<instance-name>`.

I am closing this issue for now but feel free to ping me in case anything is not working for you.
