### ISSUE TITLE
NoopSpan doesn't have additional methods

### ISSUE THREAD

**Issue by funkjedi** [DataDog/dd-trace-php#140]
Integration works fine for web requests but my Laravel workers fail when running `artisan queue:work`

```
Symfony\Component\Debug\Exception\FatalThrowableError Call to undefined method OpenTracing\NoopSpan::setResource() 
    vendor/datadog/dd-trace/src/DDTrace/Integrations/PDO/PDOIntegration.php:42 PDO::DDTrace\Integrations\PDO\{closure}
    vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:68 Illuminate\Database\Connectors\Connector::createPdoConnection
    vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:44 Illuminate\Database\Connectors\Connector::createConnection
    vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php:24 Illuminate\Database\Connectors\MySqlConnector::connect
```
The problem appears to be the tracer is trying to use [NoopSpan](https://github.com/opentracing/opentracing-php/blob/1.0.0-beta5/src/OpenTracing/NoopSpan.php) which doesn't have the extra methods implemented in `DDTrace\Span`.
https://github.com/DataDog/dd-trace-php/blob/690bd17583dcd14ca776fbc8f3c768f3c3704d51/src/DDTrace/Tracer.php#L97-L99
There probably needs to be a `OpenTracing\NoopSpan` subclass in DDTrace that implements all the additional methods that have been added.

Temporarily worked around by registering the DDTrace service provider from my AppServiceProvider only when not on CLI.
```php
/**
 * Register any application services.
 *
 * @return void
 */
public function register()
{
    if (extension_loaded('ddtrace') && php_sapi_name() !== 'cli') {
        $this->app->register(\DDTrace\Integrations\LaravelProvider::class);
    }
```

**Comment by labbati** [comment]
Hi @funkjedi, thanks for the issue. Working on it very soon!

**Comment by labbati** [comment]
Fixed by #141 in CR.

**Comment by labbati** [comment]
Hi @funkjedi, 0.4.2 has been released: https://github.com/DataDog/dd-trace-php/releases/tag/0.4.2
Can you please confirm that this release fixes your issue?
Thanks for the patience!

**Comment by labbati** [comment]
Hi @alkin , we are aware of the issue and we will be providing a fix in two steps:
 - initially we are just returning a DDTrace version of NoopSpan which provides the required methods
 - then we will refactor our integration with open tracing entirely relying on our classes (which will be compatible with open tracing though)
Working on it today, for the first step, which will be enough to work around the issue, though.

**Comment by labbati** [comment]
Just to let you know, we just release 0.5.0 which fixes the issue reported here (we implemented our own `NoopSpan` as @funkjedi was suggesting). We will also go further soon and slightly refactor the way we integrate with `OpenTracing`.

If you have a moment and can confirm that this actually works for you it would be great.

Thanks for the patience.

**Comment by funkjedi** [comment]
So far so good.

**Comment by labbati** [comment]
Closing this issue as it seems to be resolved!
