### ISSUE TITLE
[BUG] web requests reporting longer at 0.64.0 and up

### ISSUE THREAD

**Issue by rabidsloth** [DataDog/dd-trace-php#1419]
### Bug description
When upgrading to anything past 0.64.0 all of our php web requests report an additional 80-100ms on average increase at the end of the request, seemingly after the request has already been filled as end users see no detectable increase in load time. I tested all versions up to 0.67.0

Before 0.64.0:
![datadog-0-62](https://user-images.githubusercontent.com/1073033/146301672-10310b3e-e76d-4519-9d7f-909135b9f3fe.png)

Post 0.64.0:
![datadog-0-64](https://user-images.githubusercontent.com/1073033/146301686-d01501d3-c4b0-4d9c-83df-b30db1e00b10.png)

### PHP version
PHP 7.4.26 (cli) (built: Dec  2 2021 14:29:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies
    with ddtrace v0.64.1, Copyright Datadog, by Datadog

### Installed extensions
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
ddtrace
dom
exif
fileinfo
filter
ftp
gd
hash
iconv
igbinary
imap
intl
json
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
ddtrace

### OS info
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

#### Output of phpinfo() (ddtrace >= 0.47.0)
DATADOG TRACER CONFIGURATION => {"date":"2021-12-16T03:11:21Z","os_name":"Linux ccx72 4.14.252-195.483.amzn2.x86_64 #1 SMP Mon Nov 1 20:58:46 UTC 2021 x86_64","os_version":"4.14.252-195.483.amzn2.x86_64","version":"0.64.1","lang":"php","lang_version":"7.4.21","env":"env","enabled":true,"service":null,"enabled_cli":false,"agent_url":"{}","debug":false,"analytics_enabled":false,"sample_rate":1.000000,"sampling_rules":null,"tags":{},"service_mapping":{},"distributed_tracing_enabled":true,"priority_sampling_enabled":true,"dd_version":null,"architecture":"x86_64","sapi":"cli","datadog.trace.request_init_hook":"/opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php","open_basedir_configured":false,"uri_fragment_regex":null,"uri_mapping_incoming":null,"uri_mapping_outgoing":null,"auto_flush_enabled":false,"generate_root_span":true,"http_client_split_by_domain":false,"measure_compile_time":true,"report_hostname_on_root_span":false,"traced_internal_functions":null,"auto_prepend_file_configured":false,"integrations_disabled":"default","enabled_from_env":true,"opcache.file_cache":null,"DDTRACE_REQUEST_INIT_HOOK":"'DDTRACE_REQUEST_INIT_HOOK=/opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php' is deprecated, use DD_TRACE_REQUEST_INIT_HOOK instead."}

**Comment by labbati** [comment]
Hello @rabidsloth. I tried to recreate with all possible combinations of:
- PHP 7.4
- Tracers 0.63.0, 0.64.1, 0.67.0
- Laravel 5.8 and a synthetic php script

I was not able to observe this additional time.

Might I ask if you use a specific web framework I can test out AND if you are doing or not manual instrumentation?

**Comment by rabidsloth** [comment]
@labbati thanks for taking a look into this. 

We're actually not using a standard web framework and we're doing manual instrumentation, so it's gonna make troubleshooting this kinda difficult. I didn't write the manual instrumentation, so I'm riding blind here, I was hoping it was just a bug with the agent, but it looks like I'm going to have to really dive into our code to see what we're utilizing that changed to cause this behavior.

**Comment by labbati** [comment]
hello @rabidsloth, did you have a chance to investigate your manual instrumentation if it was responsible for the extra 100ms?

**Comment by labbati** [comment]
I am closing this issue for now, but feel free to reach out in case this is a confirmed problem and I need to reopen it.
