### ISSUE TITLE
[Question] how to correctly orchestrate distributed queued processes (RabbitMQ, SQS, etc.)?

### ISSUE THREAD

**Issue by rmikalkenas** [DataDog/dd-trace-php#1494]
The title speaks for itself. I couldn't find any example nor in this repository code, neither at datadog's documentation, so tried various options while I found a way to do it. I'm not sure if I did it correctly, so asking maybe some of you could guide me and help with the implementation.
Adding the examples of how my producer's and consumer's implementations look like

**Message producer:**
```
$tracer = GlobalTracer::get();
$scope = $tracer->startActiveSpan('Bus: message send');
$tracer->inject($scope->getSpan()->getContext(), Format::TEXT_MAP, $context);
// a peace of code that dispatches message to queue broker with added $context to message
$scope->close();
```

**Message consumer:**
```
$context = // is populated with data from queued message, the same passed in producer process
$tracer = GlobalTracer::get();
$externalSpanContext = $tracer->extract(Format::TEXT_MAP, $context);
$scope = $tracer->startActiveSpan(
    'Bus: message received',
    ['references' => Reference::create(Reference::FOLLOWS_FROM, $externalSpanContext)]
);
// a peace of code that processes received queued message
$scope->close();
$tracer->flush();
```

with such approach datadog shows full trace tree (starting at consumer and ending with handled queued messages). But as the trace is scattered in graph, how to find out which span's were "childs" of main process and which ones are descendants of these child processes? Basically, how to draw full tree of processes, because each of them depends from one another. Or maybe I have implemented tracing in a wrong way and it should be done differently?
 
![child_of](https://user-images.githubusercontent.com/14221532/152402159-493f4b2f-54b8-4b3f-9eb3-bafe2031aa6c.png)

**Comment by pj-datadog** [comment]
Hi @rmikalkenas, I am a Product Manager at Datadog. Thank you for reaching out to us, and sharing your implementation examples of producers and consumers. It seems like your examples are generally-accepted cases of implementation, and also align with our recommendation. I will suggest you to reach out to [Datadog Support](https://www.datadoghq.com/support/) where you can help us take a thorough look at your use-case and explore other alternatives we might have for you.
I am happy to answer any other questions you might have. Thank you!

**Comment by rmikalkenas** [comment]
> Hi @rmikalkenas, I am a Product Manager at Datadog. Thank you for reaching out to us, and sharing your implementation examples of producers and consumers. It seems like your examples are generally-accepted cases of implementation, and also align with our recommendation. I will suggest you to reach out to [Datadog Support](https://www.datadoghq.com/support/) where you can help us take a thorough look at your use-case and explore other alternatives we might have for you. I am happy to answer any other questions you might have. Thank you!

Thanks @pj-datadog for a quick answer! Will definitely contact DD support
