### ISSUE TITLE
[BUG] Upgrading to anything past 0.61.0 stops generating traces

### ISSUE THREAD

**Issue by ilazaridis** [DataDog/dd-trace-php#1514]
### Bug description
Upgrading to any version past 0.61.0 stops generating traces for us.
What we have tried so far indicates that `trace_method` seems to work fine but not our manual instrumentation which looks similar to the following:

```
$tracer = new Tracer();
GlobalTracer::set($tracer);

$rootSpan = $tracer->startRootSpan(
    'test',
    StartSpanOptions::create(['start_time' => Time::now()])
)
    ->getSpan();

$rootSpan->setTag(Tag::SPAN_TYPE, Type::CLI);
$rootSpan->setTag(Tag::SERVICE_NAME, 'my-service');
$rootSpan->setTag(Tag::RESOURCE_NAME, 'my-resource-name', true);
$rootSpan->setTag('command_origin', 'my-command-origin');

// do some stuff

GlobalTracer::get()?->flush();
```

just a note here, this code is part of a long running process, we make use of react event loop, so it's been executed quite often.

### PHP version
```
PHP 8.0.15 (cli) (built: Jan 20 2022 21:14:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.15, Copyright (c), by Zend Technologies
    with Xdebug v3.1.3, Copyright (c) 2002-2022, by Derick Rethans
    with ddtrace v0.62.0, Copyright Datadog, by Datadog
```

### Tracer version
`0.62.0`

### Installed extensions
```
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
ddtrace
dom
fileinfo
filter
ftp
hash
iconv
intl
json
libxml
mbstring
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
rdkafka
readline
redis
Reflection
session
SimpleXML
soap
sodium
SPL
sqlite3
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
ddtrace
```

### OS info
```
NAME="Alpine Linux"
VERSION_ID=3.15.0
PRETTY_NAME="Alpine Linux v3.15"
```

#### Output of phpinfo() (ddtrace >= 0.47.0)
```                               
Diagnostic checks => passed

Directive => Local Value => Master Value
ddtrace.disable => Off => Off
ddtrace.request_init_hook => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php
ddtrace.cgroup_file => /proc/self/cgroup => /proc/self/cgroup
```
### Upgrading info
Last working version is 0.61.0

**Comment by bwoebi** [comment]
Just to make sure: Which environment variables have you set? The full output of the phpinfo() would be useful, on ddtrace 0.70.0.
0.62.0 is the first version to use internal spans, in subsequent versions some bugs have been fixed.

Also a quick question: Are you close()ing your started $rootSpan at some point, before flushing?

**Comment by ilazaridis** [comment]
> Also a quick question: Are you close()ing your started $rootSpan at some point, before flushing?

I just give it a quick try, it seems to work! We didn't close it it seems. How did this work before though ? :thinking: 
I will test it with latest version one more time just to be 100% sure.
Thanks for the quick response.

**Comment by ilazaridis** [comment]
I am closing this ticket, as our issue seems to have been solved.
Thank you again @bwoebi
