### ISSUE TITLE
[BUG] Memcached Tracing Not Working with PHP 8.0.16 and 0.70.0 and 0.70.1

### ISSUE THREAD

**Issue by gman-wa** [DataDog/dd-trace-php#1535]
### Bug description
Using the memcached module with PHP 8.0.16 with dd-trace-php and memcache tracing does not appear in DD APM.

As soon as 8.0.16 comes online, tracing stops.

Reverting to 7.4.28 and memcached tracing comes back.

mod_Memcache built from:

https://github.com/php-memcached-dev/php-memcached 

### PHP version
PHP 7.4.28 and PHP 8.0.16

### Tracer version
0.70.0 and 0.70.1

### Installed extensions
core mod_so mod_watchdog http_core mod_log_config mod_logio mod_version mod_unixd mod_access_compat mod_alias mod_auth_basic mod_authn_core mod_authn_file mod_authz_core mod_authz_host mod_authz_user mod_autoindex mod_deflate mod_dir mod_env mod_filter mod_headers mod_mime prefork mod_negotiation mod_php7 mod_remoteip mod_reqtimeout mod_rewrite mod_setenvif mod_speling mod_status

### OS info
(PHP 7.4) Linux ab8a10850926 4.14.262-200.489.amzn2.x86_64 #1 SMP Fri Feb 4 20:34:30 UTC 2022 x86_64 

#### Output of phpinfo() (ddtrace >= 0.47.0)

PHP 7.4 DD PHP Trace Config

{"date":"2022-03-02T05:53:21Z","os_name":"Linux 7da1241b144d 4.14.262-200.489.amzn2.x86_64 [#1](https://help.datadoghq.com/hc/requests/1) SMP Fri Feb 4 20:34:30 UTC 2022 x86_64","os_version":"4.14.262-200.489.amzn2.x86_64","version":"0.70.0","lang":"php","lang_version":"7.4.21","env":"qa-r2d2","enabled":true,"service":"php","enabled_cli":false,"agent_url":"http:\/\/172.17.0.1:8126","debug":false,"analytics_enabled":false,"sample_rate":1,"sampling_rules":[],"tags":[],"service_mapping":[],"distributed_tracing_enabled":true,"priority_sampling_enabled":true,"dd_version":null,"architecture":"x86_64","sapi":"apache2handler","datadog.trace.request_init_hook":"\/opt\/datadog-php\/dd-trace-sources\/bridge\/dd_wrap_autoloader.php","open_basedir_configured":false,"uri_fragment_regex":null,"uri_mapping_incoming":null,"uri_mapping_outgoing":null,"auto_flush_enabled":false,"generate_root_span":true,"http_client_split_by_domain":true,"measure_compile_time":true,"report_hostname_on_root_span":false,"traced_internal_functions":null,"auto_prepend_file_configured":false,"integrations_disabled":"default","enabled_from_env":true,"opcache.file_cache":null}

PHP 8.0 DD PHP Trace Config

{"date":"2022-03-01T23:13:46Z","os_name":"Linux bbf65d0242c2 4.14.262-200.489.amzn2.x86_64 [#1](https://help.datadoghq.com/hc/requests/1) SMP Fri Feb 4 20:34:30 UTC 2022 x86_64","os_version":"4.14.262-200.489.amzn2.x86_64","version":"0.70.0","lang":"php","lang_version":"8.0.8","env":"qa-r2d2","enabled":true,"service":"php","enabled_cli":false,"agent_url":"http:\/\/172.17.0.1:8126","debug":false,"analytics_enabled":false,"sample_rate":1,"sampling_rules":[],"tags":[],"service_mapping":[],"distributed_tracing_enabled":true,"priority_sampling_enabled":true,"dd_version":null,"architecture":"x86_64","sapi":"apache2handler","datadog.trace.request_init_hook":"\/opt\/datadog-php\/dd-trace-sources\/bridge\/dd_wrap_autoloader.php","open_basedir_configured":false,"uri_fragment_regex":null,"uri_mapping_incoming":null,"uri_mapping_outgoing":null,"auto_flush_enabled":false,"generate_root_span":true,"http_client_split_by_domain":true,"measure_compile_time":true,"report_hostname_on_root_span":false,"traced_internal_functions":null,"auto_prepend_file_configured":false,"integrations_disabled":"default","enabled_from_env":true,"opcache.file_cache":null}

### Upgrading info
PHP 7.4.28 and dd-trace-php works for tracing memcache, PHP 8.0.16 and dd-trace-php does not work for tracing memcache

**Comment by gman-wa** [comment]
We also have this crossposted at https://help.datadoghq.com/hc/en-us/requests/701426

**Comment by bwoebi** [comment]
memcache is currently not supported for PHP 8 in dd-trace-php.

We'll look at adding support for it in the near future.
One thing having us hold back from supporting it, is that there (still) is no proper release of memcached supporting the PHP 8 and PHP 8.1 versions.

**Comment by bwoebi** [comment]
Yep :-) We'll look at integrating it within the next couple weeks.

**Comment by gman-wa** [comment]
https://github.com/php-memcached-dev/php-memcached/releases/tag/v3.2.0  !!!!

**Comment by gman-wa** [comment]
@bwoebi - is there a targeted release for this integration?

**Comment by bwoebi** [comment]
I'm working on it right now. There's no officially committed target yet, but we're looking at having it ready for the next minor version.

**Comment by gman-wa** [comment]
Thanks @bwoebi !
