### ISSUE TITLE
[BUG] Breaking change in 0.70 when auto-starting root scope

### ISSUE THREAD

**Issue by cvele** [DataDog/dd-trace-php#1539]
### Bug description
When `DD_TRACE_GENERATE_ROOT_SPAN=1`:

```
$rootScope = GlobalTracer::get()->getRootScope();
$rootSpan = $rootScope->getSpan();
```

In 0.69 `$rootSpan` will be populated instance of `DDTrace\Scope` however in 0.70+ same snippet will return `DDTrace\NoopScope`.
This new behaviour prevents us from assigning tags to root scope.

### PHP version
7.3

### Tracer version
0.70+

### OS info
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by cvele** [comment]
Thank you, will try it  out.

**Comment by labbati** [comment]
@cvele I am closing this issue for now, but feel free to post the info we discussed below and if appropriate we can reopen it. Thank you for taking the time.
