### ISSUE TITLE
[Feature] Add Laravel Queue Job support

### ISSUE THREAD

**Issue by NickStallman** [DataDog/dd-trace-php#1572]
**Is your feature request related to a problem? Please describe.**
The Laravel integration for DD Trace is good, however it completely omits Queue support. Any jobs that run are not traced at all.

**Describe the solution you'd like**
Queue tracing can be accomplished with something along these lines:
```php
\DDTrace\trace_method(
    'Illuminate\Queue\Worker',
    'process',
    function (\DDTrace\SpanData $span, array $args) {
        list($connectionName, $job, $options) = $args;

        if (!($job instanceof \Illuminate\Contracts\Queue\Job)) {
                return;
        }

        $payload = $job->payload();
        $span->resource = JobName::resolve($job->getName(), $payload);
        $span->name = 'laravel.queue.worker';
        $span->type = Type::MESSAGE_CONSUMER;
        $span->meta = [
                'waitTime' => !empty($payload['pushedAt']) ? (microtime(true) - $payload['pushedAt']) : false,
                'pushedAt' => !empty($payload['pushedAt']) ? date('c', $payload['pushedAt']) : false,
        ];
});
```

**Additional context**
The aboove code has had some very basic tests and seems to work fine. Additional meta info might be handy but that's easy to add to.

I ran the queue worker like this:
```
DD_TRACE_CLI_ENABLED=true DD_TRACE_AUTO_FLUSH_ENABLED=true DD_TRACE_GENERATE_ROOT_SPAN=false ./artisan queue:work
```

**Comment by kalemdzievski** [comment]
Hey, @NickStallman I was researching about the very same thing, but no luck so far. 
I wanted to ask u, where did u place this code?

**Comment by NickStallman** [comment]
@kalemdzievski you can pop it anywhere really. a Laravel Service Provider is ideal for defining this in a boot() function.

**Comment by kalemdzievski** [comment]
Thank you!

**Comment by erictt** [comment]
How do you mark the failed jobs? It seems like there is no way to mark the span as error if the job failed.

**Comment by NickStallman** [comment]
@erictt Laravel Jobs are typically failed via Exceptions.

$job->hasFailed() can determine if it has failed or not. To get further information an extra hook on Job::fail($e) may be needed.

**Comment by nikalemdzievski** [comment]
Hey @NickStallman! Hope you are doing well. The code snipped you provided was really helpful, tho I noticed that timed-out jobs are not being traced. Any experience with this?

**Comment by NickStallman** [comment]
The timeout would probably be caught as an exception like above, however I haven't revisited my code since so I don't have an updated snippet sorry.

**Comment by dreanmer** [comment]
@NickStallman first, thanks for the snippet, work like a charm!

now I'm trying to ignore events that fails by some specific exceptions, do you have some tips to help? thanks!

**Comment by NickStallman** [comment]
I don't have an immediate solution off the top of my head for filtering the jobs that get reported.
This hook just catches when the job is run, but to look at the result of the Job you'd need to hook the exception handler or something like that. I don't know how you'd prevent this job hook from firing if an exception occurred however.

**Comment by dreanmer** [comment]
I just found this documentation: https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/php/?tab=currentspan#writing-the-custom-instrumentation

the solution was easy, there is for someone wo needs:

```php
           \DDTrace\trace_method('Illuminate\Queue\Worker', 'process', function (\DDTrace\SpanData $span, array $args, $retval, $exception)
            {

                [...]

                if ($exception !== null && $exception instanceof XxxxException) {
                    return;
                }
```

there is this last parameter, that carries the exception if it occurs!

**Comment by NickStallman** [comment]
Oh well now that does indeed make it quite easy. :)

**Comment by dreanmer** [comment]
As the last code won't worked as expected, i tried to change to trace the `Jobs::fire` method, so we can intercept the exceptions... but https://github.com/DataDog/dd-trace-php/issues/1921 and this is the case of this method... So I'm working on another option while this isn't fixed

**Comment by morrisonlevi** [comment]
:wave: I left this comment in [another thread](https://github.com/DataDog/dd-trace-php/issues/386#issuecomment-1545947480) and I'll copy it here in case it's valuable to you as well.

-----

Just chiming in to add that [v0.87.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.87.0) is out now!

There is also a new config mode in the `datadog-setup.php` script, which allows you to set service, env, version, etc, through the CLI. I think Laravel users might git a bit more out of this feature than some other users, so I'm sharing it with you:

```bash
# Install the tracer (no appsec, no profiling)
php datadog-setup.php --php-bin=php

# Get service and env from the .env file
ddservice=$(awk -F= '$1 ~ /^APP_NAME$/ {print $2}' < .env)
ddenv=$(awk -F= '$1 ~ /^APP_ENV$/ {print $2}' < .env)

# Grab version from git (or however you do it)
ddversion=$(git rev-parse HEAD)

# Sets service, env, and version through the installer, uses INI syntax.
php datadog-setup.php config set --php-bin=php \
    -ddatadog.service="${ddservice?}" \
    -ddatadog.env="${ddenv?}" \
    -ddatadog.version="${ddversion?}"
```

Our online docs should be updated within the next week or so to reflect this.

Thanks for the patience on the Laravel queue worker support. We're excited to hear your feedback!

**Comment by NickStallman** [comment]
Excellent news! This looks much better than my interim hack so I'll be switching over. :)

**Comment by lifekent** [comment]
@NickStallman Does this https://github.com/DataDog/dd-trace-php/issues/1572#issue-1210322276 custom tracing still work with the latest version (0.89.0)? It was working fine for us with some previous version but it doesn't anymore.

**Comment by jhjm32087** [comment]
I'm not seeing any Laravel Horizon on Datadog with 0.91.2. Are there any environmental settings to enable after the upgrade?

**Comment by PROFeNoM** [comment]
Hey @jhjm32087 

This is definitely not normal :eyes: Could you please open an issue to follow this bug? I would first be particularly interested in knowing the following:

- The version of Laravel you are using
- Any exception debug output generated when using `DD_TRACE_DEBUG=true`
- Whether you still receive other traces from this service
- The output of `phpinfo`

**Comment by jhjm32087** [comment]
@PROFeNoM, I submitted a bug here https://github.com/DataDog/dd-trace-php/issues/2268

**Comment by PROFeNoM** [comment]
Hey everyone :wave:

Span Links are now broadly available as a Beta Feature in the UI and connect pushing and processing traces 😃 

![image](https://github.com/DataDog/dd-trace-php/assets/42672104/1973d25a-793e-4c68-b7db-bd7a802afd70)

Please feel free to provide us with your feedback on this feature!
