### ISSUE TITLE
[Feature] Laravel integration should use `$request->fullUrl()` instead of `$request->url()` for tag `Tag::HTTP_URL`

### ISSUE THREAD

**Issue by matthewnessworthy** [DataDog/dd-trace-php#1577]
**Is your feature request related to a problem? Please describe.**
APM monitoring for Laravel integrations shows the url excluding the query string
For bugs that are triggered by query string contents this makes debugging difficult

**Describe the solution you'd like**
Replace the use of `$request->url()` with `$request->fullUrl()` in `Illuminate\Routing\Router::findRoute` `hook_method`
```
\DDTrace\hook_method(
    'Illuminate\Routing\Router',
    'findRoute',
    null,
    function ($This, $scope, $args, $route) use ($rootSpan, $integration) {
		...
        $rootSpan->meta[Tag::HTTP_URL] = \DDTrace\Util\Normalizer::urlSanitize($request->fullUrl());
		...
    }
);
```

**Describe alternatives you've considered**
Manually applying this change in local code with a custom `\DDTrace\hook_method()` call

**Additional context**
None

**Comment by bwoebi** [comment]
There is #1566. It however only touches `urlSanitize()`.

So thanks for the good heads up to also go through our integrations and ensure that actual full URLs are passed to `urlSanitize()` here.
