### ISSUE TITLE
[BUG] Unable to load PHPRedis integration on PHP 8.0

### ISSUE THREAD

**Issue by elliotfehr** [DataDog/dd-trace-php#1592]
### Bug description

Setting `DD_TRACE_PHPREDIS_ENABLED` does not seem to enable the `phpredis` extension on PHP 8.

The debug logs show:
```
PHP message: [2022-05-04T19:21:35+00:00] [ddtrace] [debug] - Attempting integrations load
PHP message: [2022-05-04T19:21:35+00:00] [ddtrace] [debug] - Loaded integration web
PHP message: [2022-05-04T19:21:35+00:00] [ddtrace] [debug] - Loaded integration codeigniter
PHP message: [2022-05-04T19:21:35+00:00] [ddtrace] [debug] - Loaded integration curl
PHP message: [2022-05-04T19:21:35+00:00] [ddtrace] [debug] - Loaded integration eloquent
PHP message: [2022-05-04T19:21:35+00:00] [ddtrace] [debug] - Loaded integration guzzle
PHP message: [2022-05-04T19:21:35+00:00] [ddtrace] [debug] - Loaded integration laravel
PHP message: [2022-05-04T19:21:35+00:00] [ddtrace] [debug] - Loaded integration mysqli
PHP message: [2022-05-04T19:21:35+00:00] [ddtrace] [debug] - Loaded integration symfony
PHP message: Successfully triggered flush with trace of size 3
```

This appears to line up with: https://github.com/DataDog/dd-trace-php/blob/23fd62a4727fe2cfa996891696d8ebf8a8fa3523/src/Integrations/Integrations/IntegrationsLoader.php#L63-L80

### PHP version

```
php -v
PHP 8.0.18 (cli) (built: Apr 13 2022 02:45:05) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.18, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.18, Copyright (c), by Zend Technologies
    with ddtrace v0.72.0, Copyright Datadog, by Datadog
```

### Tracer version

`0.72.0`

### Installed extensions

```
php -m | grep redis
redis
```

### OS info

`CentOS Linux release 7.9.2009 (Core)`

**Comment by bwoebi** [comment]
Hey Elliot,

The list of integrations you found in the IntegrationsLoader are always loaded integrations (unless disabled).

There exists a different list of integrations, which are only loaded when specific function or method is called:
https://github.com/DataDog/dd-trace-php/blob/5995fe165935b63cecde0ecd1f28df24922c102c/ext/php8/integrations/integrations.c#L86-L126

Which includes PHPRedis. These deferred integrations apparently do not seem to emit a log line when loaded though.

This is an oversight in our logging I think, but the integration should actually be loaded.
