### ISSUE TITLE
Passing objects within span tags

### ISSUE THREAD

**Issue by ryannutley** [DataDog/dd-trace-php#16]
Is this possible to do currently? Looking to pass an array/object into a span tag and view it within the trace attributes

**Comment by jcchavezs** [comment]
Thanks for opening an issue! There is complexity around accepting other
things than scalar. In one hand there is a concern about how to serialise
it, in the other hand it is about cardinality, tags are suppose to be low
cardinality if possible. If you explain your use case we could understand
better the need for this.

> --

*José Carlos*

**Comment by kevinlebrun** [comment]
I don't know if it will help you but if you flatten your data structures and join keys with a dot it will appear nicely in the UI. Here is an example with `setTag('bindings.0', 'xxx')`:
![screenshot 2018-06-08 18 39 19](https://user-images.githubusercontent.com/798082/41170147-688668f8-6b4b-11e8-8e1d-6081fee79da7.png)

**Comment by jcchavezs** [comment]
This is interesting. OpenTracing spec [defines tag values as scalar](
https://github.com/opentracing/specification/blob/master/specification.md#set-a-span-tag)
so I would say the serialisation should be done by the instrumentation
(a.k.a developer)--

*José Carlos*

**Comment by chuck** [comment]
@ryannutley Has your question been answered? I agree with @jcchavezs and @kevinlebrun that the spec is clear on tags being scalar. At the integration level, we might serialize down info ourselves in the way that Kevin suggested.

**Comment by chuck** [comment]
I'm going to close this, but happy to continue conversation or re-open if needed.
