### ISSUE TITLE
[BUG] Installer doesn't find PHP versions on Plesk

### ISSUE THREAD

**Issue by KDederichs** [DataDog/dd-trace-php#1625]
### Bug description
The installer doesn't see all the installed PHP versions on Plesk, only the default system one.

Plesk does store them in `/opt/plesk/php/<VERSION>/bin/php` so scanning for those would also be neat

**Comment by labbati** [comment]
I was able to recreate, we will release a fix soon. Thanks for opening the issue

**Comment by labbati** [comment]
0.76.0 is out and includes a fix to this issue. Please let me know if the new release resolves the problem for you

**Comment by KDederichs** [comment]
Sorry for the late response, yes that fixed it. Thanks :)
