### ISSUE TITLE
[BUG] package.xml still says that the minimum PHP version is 5.4

### ISSUE THREAD

**Issue by mlocati** [DataDog/dd-trace-php#1653]
### Bug description
The `package.xml` file still declares that the package supports PHP 5.4+, whereas (I think) the minimum PHP version is now 7.0.
See https://github.com/DataDog/dd-trace-php/blob/0.76.0/package.xml#L128

### PHP version
n/a

### Tracer version
n/a

### Installed extensions
n/a

### OS info
n/a

#### Output of phpinfo() (ddtrace >= 0.47.0)
n/a

**Comment by bwoebi** [comment]
I've just merged #1652 which should solve it for the next version.
