### ISSUE TITLE
[BUG] Enabling ddtrace.so disables PHP8 JIT

### ISSUE THREAD

**Issue by silvervest** [DataDog/dd-trace-php#1654]
### Bug description
Installing the latest ddtrace via the datadog-setup.php script disables PHP's JIT, with the warning from FPM:
```
NOTICE: PHP message: PHP Warning:  JIT is incompatible with third party extensions that setup user opcode handlers. JIT disabled. in Unknown on line 0
```

Disabling ddtrace.so with no other changes allows JIT to become enabled again.

[This blog post](https://www.datadoghq.com/blog/engineering/php-8-observability-baked-right-in/) notes that the PHP tracer has been using the observer API since 0.52.0 so I'd expect this to not interfere?

### PHP version
```
root@9057ee5627c8:/app# php -v
PHP 8.1.7 (cli) (built: Jun 23 2022 07:57:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7, Copyright (c), by Zend Technologies
```

### Tracer version
```
root@848c29c9c327:/app# php -r "echo phpversion('ddtrace').PHP_EOL;"
0.76.0
```

### Installed extensions
```
root@848c29c9c327:/app# php -m
[PHP Modules]
apcu
bcmath
Core
ctype
curl
date
ddappsec
ddtrace
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
ddappsec
ddtrace
```

### OS info
Contained based off `php:8.1-fpm`
```
root@848c29c9c327:/app# cat /etc/os-release | grep -E "(NAME)|(VERSION)"
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
```

#### Output of phpinfo() (ddtrace >= 0.47.0)
<img width="949" alt="image" src="https://user-images.githubusercontent.com/132018/178632114-6784e7fa-13e2-475a-be38-68a2eed3397a.png">

**Comment by bwoebi** [comment]
Tracer version 0.76.1 has been published and contains a fix for the JIT.

**Comment by silvervest** [comment]
Thanks for the stupid fast turn around @bwoebi - can confirm that 0.76.1 indeed allows JIT to run while letting APM traces through. Much appreciated!
