### ISSUE TITLE
[BUG] Can not parse 'Via' header when running behind a GCP load balancer

### ISSUE THREAD

**Issue by khewady-mollie** [DataDog/dd-trace-php#1692]
### Bug description
GCP load balancers add the HTTP `Via` header in the following format: `{http-protocol-version} google`. For example `Via: 1.1 google`. This is compliant with [RFC7230](https://httpwg.org/specs/rfc7230.html#header.via).  
The datadog php tracer only allows for ip address (and optionally ports). It treats other tokens as errors despite that they are RFC-complaint and used in the wild.  

Here is the related implementation code 
https://github.com/DataDog/dd-trace-php/blob/ea44e8b9f0068cef2fb874621ebd62f7d5795ecf/ext/php8/ip_extraction.c#L367-L384

Accordingly, we get an error log line from the tracer for every http request. For example
```
[Tue Aug 09 08:46:42.731199 2022] [php:notice] [pid 159962] [client {redacted-ip}:0] Not recognized as IP address: "google"
```

### PHP version
PHP 8.1.8 (cli) (built: Aug  2 2022 07:31:17) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.8, Copyright (c), by Zend Technologies
    with ddtrace v0.77.0, Copyright Datadog, by Datadog

### Tracer version
0.77.0

#### Output of phpinfo() (ddtrace >= 0.47.0)
Bug seems unrelated to specific setup we run. Can add it if necessary.

**Comment by estringana** [comment]
Hello @khewady-mollie. Thanks for reporting this. I'm looking into the problem right now. I will let you know when it gets fixed

**Comment by estringana** [comment]
The fix just got merge @khewady-mollie. It will be part of the next release

**Comment by khewady-mollie** [comment]
Thanks a lot for your prompt action. Have a nice day!
