### ISSUE TITLE
[Feature] Symlinking open_basedir

### ISSUE THREAD

**Issue by KDederichs** [DataDog/dd-trace-php#1719]
**Is your feature request related to a problem? Please describe.**
If I'm seeing this correctly the open_basedir configuration now changes with each version of dd-trace-php (/opt/datadog/dd-library/0.78.0/dd-trace-sources) which is EXTREMELY inconvenient since you now have to change your open_basedir configuration each time you update the lib. Symlinking it on each update/install would be more convenient.

**Describe the solution you'd like**
Symlinking it to /opt/datadog/dd-trace-sources would be nice, so people who want can alternatively use that symlink that'll just update itself

**Describe alternatives you've considered**
Alternative would be changing it manually each time, which seems a bit cumbersome....

**Additional context**
I'm comming from a Plesk environment and EVERY website there has different PHP settings with their own open_basedir, which leads to the problem as described.

**Comment by bwoebi** [comment]
Hey @KDederichs,

I wonder, would it not suffice for you to just set open_basedir to `/opt/datadog/dd-library`, which includes all current and former versions of the PHP source?

Is there a particular reason, why it needs to be that specific?

**Comment by KDederichs** [comment]
hmm could also work, I have to admit I updated from a rather old one which still lived in `/opt/datadog-php/dd-trace-sources` so I wasn't sure how it'd handle the version numbers in there.

But if that also works that's fine.

**Comment by bwoebi** [comment]
Let me know if that works for you, then I'll close this issue :-)

**Comment by KDederichs** [comment]
Yup, seems to work. Maybe do add that to the setup docs though. There doesn't seem to be a section about open_basedir stuff.
