### ISSUE TITLE
Very long trace autoload

### ISSUE THREAD

**Issue by juslintek** [DataDog/dd-trace-php#1728]
Is it suppose to be this long?
![image](https://user-images.githubusercontent.com/5687423/188529019-a02b173e-03e3-40b2-80e9-2f240b439655.png)
ubuntu 22.04, php 8.0, fpm, nginx 1.18, ec2 m6g.xlarge instance.

**Comment by morrisonlevi** [comment]
I would not expect that, no! What organization should I look at to investigate this more? If you aren't comfortable sharing that publicly here, then open a support ticket on the Datadog website. As part of the ticket, tell them I told you to escalate it to me. Once I have the organization, I can use the service name which is visible in the screenshot to look at the profiles further. Thanks!

**Comment by morrisonlevi** [comment]
BTW, I can see from the Execution Time Breakdown on the left that there was very little CPU time used. My guess is that file I/O is very slow for some reason. If this ends up being the case, we should see it pretty easily in the profiles. Do you happen to have a network mounted file system?

**Comment by juslintek** [comment]
I will open a ticket. :-) Screenshot does not expose any private info. :-) But for further investigation, I guess we should take it there.

**Comment by juslintek** [comment]
Okay I cannot escalate this on Datadog, because I currently use free account for testing, but I have a person that I can contact. Will contact him. But I see that CPU usage dropped after disabling:
```
;extension = ddappsec.so
```

**Comment by bwoebi** [comment]
@juslintek Was appsec actually enabled on your installation (i.e. `datadog.appsec.enabled` set to `On`) or only the `extension=ddappsec.so` entry active?

**Comment by juslintek** [comment]
Only the entry. I've commented it out and it started to use less cpu. I guess it can also be related with sample rate. At the moment it is set to 1.

**Comment by maxime-aknin** [comment]
Hi,

I'm encountering the same issue with the extension on a classic prestashop website, some admin `POST` requests were very long to complete and I found it is caused by the `ddtrace_init` function (disabling the datadog extension resolves the issue). I tried also to disable appsec and profiling but the delay persisted. I don't have any network mounted filesystem just a classic linux box (and I'm also currently on dd free tier). Will investigate more to see if I can figure it out.

<img width="1426" alt="Screenshot 2022-09-16 at 3 27 31 PM" src="https://user-images.githubusercontent.com/8659993/190651394-57fecd1b-9b25-4591-8385-10183492f1f1.png">

**Comment by Anilm3** [comment]
Hi @maxime-aknin we have identified an issue in appsec which causes a 7.5s delay on requests with a large number of parameters (>256), this seems to match what you're seeing so my suggestion for now would be to disable appsec until we're able to release a patch, although we have a fix so this should be available in the next release of the tracer. 

You can disable appsec by setting `datadog.appsec.enabled = Off` in the relevant `98-ddtrace.ini` file. Also if you had enabled appsec through environment variables, please make sure to set those as well to the appropriate value.

**Comment by maxime-aknin** [comment]
Hi @Anilm3,
Thanks for your response, yes indeed enabling the tracer but not the appsec module seems to fix the issue, sorry I don't know why I missed that in my first test and concluded it was the tracer 🧐. Good to know a fix is on the way, I'll wait for the next release to re-enable the module 👍
