### ISSUE TITLE
[BUG] datadog-setup.php using incorrect version format for the library zip file

### ISSUE THREAD

**Issue by AndrewCustomSumIT** [DataDog/dd-trace-php#1736]
### Bug description
Using the `datadog-setup.php` to install the latest DD library for PHP fails as it appears to be trying to download the library ZIP file using a wrong version format in the library's URL.

Using the following code in my Dockerfile:
```
RUN wget https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php -O datadog-setup.php \
  && php datadog-setup.php --php-bin all --enable-appsec \
  && apt-get autoremove --yes --purge wget \
  && rm -f datadog-setup.php
```

Results in the following output:
```
...
0 1.094 2022-09-09 13:13:43 (706 KB/s) - 'datadog-setup.php' saved [55117/55117]
#0 1.094
#0 1.132 Searching for available php binaries, this operation might take a while.
#0 1.302 Downloading installable archive from https://github.com/DataDog/dd-trace-php/releases/download/0.79.0/dd-library-php-0.79.0-x86_64-linux-gnu.tar.gz.
#0 1.302 This operation might take a while.
#0 1.623
#0 1.623 Download completed
#0 1.623
#0 1.633 tar: This does not look like a tar archive
#0 1.636
#0 1.636 gzip: stdin: not in gzip format
#0 1.636 tar: Child returned status 1
#0 1.636 tar: Error is not recoverable: exiting now
#0 1.637 ERROR: Cannot extract the archive
#0 1.637 Failed command (return code 2): tar -xf '/tmp/dd-install/dd-library-php-x86_64-linux-gnu.tar.gz' -C '/tmp/dd-install'
#0 1.637 ---- Output ----
#0 1.637
#0 1.637 ---- End of output ----
```

Note the `.gz` URL is https://github.com/DataDog/dd-trace-php/releases/download/0.79.0/dd-library-php-0.79.0-x86_64-linux-gnu.tar.gz which is not valid.

I believe it should have the version format `v0.79.0`: https://github.com/DataDog/dd-trace-php/releases/download/v0.79.0/dd-library-php-0.79.0-x86_64-linux-gnu.tar.gz

**Comment by pierotibou** [comment]
Hello,
sorry about that, I made a mistake tagging the release. We've retagged the release so it should be working fine now.
Again, sorry about the inconvenience.

**Comment by AndrewCustomSumIT** [comment]
@pierotibou just spun up my Docker container again and it is all working correctly.

Thanks very much! 👍
