### ISSUE TITLE
[Feature] HTTP POST Data and headers

### ISSUE THREAD

**Issue by kissifrot** [DataDog/dd-trace-php#1740]
**Is your feature request related to a problem? Please describe.**
Currently we don't have POST data when span concerns POST requests, which makes debugging sometimes quite troublesome, and that's something we miss in Datadog compared to tools like Sentry.

**Describe the solution you'd like**
Have a breakdown of POSTed variables as well as request headers in the Info tab.

**Describe alternatives you've considered**
Write a listener to add tags in symfony (as it's the main target), bit it's time consuming and not that optimized (and also out of scope)

**Additional context**
(n/a)

**Comment by bwoebi** [comment]
Hey @kissifrot,

Are you looking at full POST data (also values, which may or may not contain sensitive information), or only the information whether some fields have been set (i.e. keys only)?

Headers can already be sent via `DD_TRACE_HEADER_TAGS` as a comma-separated whitelist of header fields you'd like to see.

**Comment by kissifrot** [comment]
Well goal for eventually debugging is having the POST values along with their keys.
But you're right, it causes the risk of getting PII in them.
Maybe there could be a blacklist or a preprocess option to replace some values by `[REDACTTED]` when keys contains expression or regexes such as '*password*' or something equivalent.
