### ISSUE TITLE
Rust errors when running unrelated code (v0.78.0)

### ISSUE THREAD

**Issue by aykutersoyrmn** [DataDog/dd-trace-php#1741]
After upgrading to v0.78.0 we started to seeing Rust errors in one of our pipeline jobs.

Snippet of all the errors:

```
root@82bd0148c877:/var/www/html# vendor/bin/phpcs --parallel=16
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:1311:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

Above command runs in Docker `php:8.1.8-fpm-bullseye`
This is how we install `dd-trace-php` in Dockerfile

```
RUN curl --fail -L -O -J https://github.com/DataDog/dd-trace-php/releases/download/0.78.0/datadog-setup.php \
    && php datadog-setup.php --php-bin /usr/local/sbin/php-fpm --enable-profiling
```

I'm also attaching full backtrace dump hopefully that will be helpful.

[rust-errors.log](https://github.com/DataDog/dd-trace-php/files/9555822/rust-errors.log)

**Comment by morrisonlevi** [comment]
The profiler doesn't yet support forking at the PHP level (it does support the Apache forking model for requests), which is how `phpcs` achieves parallelism. can you confirm that if you don't run `phpcs` in parallel that you don't have any issues?

**Comment by aykutersoyrmn** [comment]
Hey @morrisonlevi, thanks for your reply. It works just fine without parallelism.

I have to mention that v0.77.0 doesn't throw any errors when running with parallel flag.
