### ISSUE TITLE
AGENT_REQUEST_BODY_LIMIT is hard coded and no longer valid

### ISSUE THREAD

**Issue by pgibson1-godaddy** [DataDog/dd-trace-php#1750]
If my understanding is correct, the reference mentioned here is no longer valid (hard cap at 10MB), but it's still enforced in the PHP library. This means that when increasing the agent limit, we're still hard capped at 10MB in this library and the payload is rejected.

https://github.com/DataDog/dd-trace-php/blob/873e48296ccdd4bd1324d417b3db82794367d66f/src/DDTrace/Transport/Http.php#L21-L23

**Comment by bwoebi** [comment]
Hey @pgibson1-godaddy,

your understanding is correct, however the current source of truth is https://github.com/DataDog/dd-trace-php/blob/873e48296ccdd4bd1324d417b3db82794367d66f/ext/comms_php.h#L10

We will look at adding support for configuration here.
