### ISSUE TITLE
[Feature or Bug] Guzzle not loaded when DD_TRACE_GENERATE_ROOT_SPAN = false 

### ISSUE THREAD

**Issue by erictt** [DataDog/dd-trace-php#1762]
I found that guzzle won't be loaded when `DD_TRACE_GENERATE_ROOT_SPAN` set to false, aka, no root span. But i'm running a long run job worker which require Guzzle to pass along the trace downstream to the external services. Without loading Guzzle, there will be no trace headers. Can anyone help me to figure out how to fix this?

The related code is here: https://github.com/DataDog/dd-trace-php/blob/51b4da799c63dd67a985a076178d1cb5073e33cf/src/Integrations/Integrations/Guzzle/GuzzleIntegration.php#L27-L30

Why do you need a root span for loading guzzle?

**Comment by erictt** [comment]
Thanks for fix!

**Comment by bwoebi** [comment]
The fix has been released as part of 0.81.0, thanks for the report :-)
