### ISSUE TITLE
[Feature] Allow INI Configuration for DD_PROFILING_ENABLED

### ISSUE THREAD

**Issue by JanThiel** [DataDog/dd-trace-php#1764]
**Is your feature request related to a problem? Please describe.**
We want to profile code which is executed by a 3rd party CLI script. It's a scheduler system calling php "cron-like" tasks. We have no way to inject ENV variables into the call stack which calls the actual php executable we want to profile.
Tracing works fine as we can enable this within the `98-ddtrace.ini` file. But we need the Profiling...

**Describe the solution you'd like**
Allow to enable profiling using the `ini` way. That will allow us to simply enable the profiling for all executions using a particular php executable and config set.

**Describe alternatives you've considered**
Executing the final php calls manually. Which doesn't make sense at all as we are talking about several hundreds per hour where we don't really know which execution will contain the desired spans we are looking for.

**Additional context**

https://docs.datadoghq.com/tracing/trace_collection/library_config/php/#environment-variable-configuration
=> DD_PROFILING_ENABLED
![image](https://user-images.githubusercontent.com/3857275/196219634-563b2807-4b4d-4efc-91e5-c09f129bc212.png)

**Comment by morrisonlevi** [comment]
Thanks for the report! This quarter we are planning to support INI configuration for all settings for the profiler, which of course would include this setting. The expectation is for it to be `datadog.profiling.enabled`.

**Comment by JanThiel** [comment]
Thanks @morrisonlevi Good to hear that :-)
And by the way, thank you very much for the amazing installer. When we last tried DD PHP Tracing the installation was ... no fun ... to put it mildly ;-). 
Today it's amazingly easy. Very well done!

**Comment by pierotibou** [comment]
Hello @JanThiel, this is now possible since [our last release](https://github.com/DataDog/dd-trace-php/releases/tag/0.82.0).

**Comment by morrisonlevi** [comment]
Note that `datadog.profiling.enabled` defaults to being on in this release when you pass `--enable-profiling` to the installer. You should be able to upgrade, and then remove the env var if you like (but env vars are still supported). I recommend moving from env vars `DD_SERVICE`, `DD_ENV`, and `DD_VERSION` to ini settings `datadog.service`, `datadog.env`, and `datadog.version` going forward!
