### ISSUE TITLE
[BUG] deprecation of ${} in 8.2 raises errors

### ISSUE THREAD

**Issue by SaTechnicalManager** [DataDog/dd-trace-php#1776]
### Bug description
PHP 8.2 will be deprecating ${} string interpolation https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation

In the analysis of the top public packagist repos affected by this, yours came back as seen in the analysis done in the RFC for this deprecation: https://gist.github.com/iluuu1994/05427dd74100af8e41ebff3d4201742c lines 90-129

The RFC also includes the recommended steps to convert to the supported syntax going forward.

### PHP version
8.2 - Deprecation
9.0 - Removal

**Comment by SaTechnicalManager** [comment]
Closing as after closer inspection bug #1738 contains these errors. They are related to RFC's that passed for 8.2 for deprecation.

**Comment by morrisonlevi** [comment]
That issue didn't fix all of the issues in the entire repo, actually, so I'm re-opening this ticket. In particular I can see that `datadog-setup.php` needs adjustment.

**Comment by bwoebi** [comment]
Closing this as it has been fixed completely with 0.82.0.
