### ISSUE TITLE
Override Symfony route name for APM?

### ISSUE THREAD

**Issue by AntoineLemaire** [DataDog/dd-trace-php#1777]
### Bug description
I'm using APM to trace which of my routes take too much resources. The issue is that my GraphQL endpoint is a uniq route name, whatever the query or the mutation
![image](https://user-images.githubusercontent.com/2025537/198050320-3dfccde4-c97a-45a9-8ecf-9a773a4a5fe6.png)

My goal would be to have different rows for each kind of query/mutation that I can do in GraphQL. For that I tried to dynamicly change the route name with let's say my GraphQL operation name

```
$span = \DDTrace\root_span();
if (null !== $span) {
    $span->meta['symfony.route.name'] = 'youshido_graphql_'.$operationName;
}
```
I tried with both `http.route.name` or `symfony.route.name`, but `symfony.route.name` is not changed and I still have only one row in APM services tab for all my GraphQL endpoint

![image](https://user-images.githubusercontent.com/2025537/198051016-27f519b5-e20d-4294-8078-e5d2ba237977.png)

### Possible fix:
Add a check in `src/Integrations/Integrations/Symfony/SymfonyIntegration.php` : 

```diff
-if (null !== $route && null !== $request) {
+if (null !== $route && null !== $request && empty($integration->symfonyRequestSpan->meta['symfony.route.name'])) {
    $integration->symfonyRequestSpan->resource = $route;
    $integration->symfonyRequestSpan->meta['symfony.route.name'] = $route;
}
```

### PHP & Tracer version
PHP 7.1.33 (cli) (built: Oct 26 2019 06:32:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33, Copyright (c) 1999-2018, by Zend Technologies
    with ddtrace v0.80.0, Copyright Datadog, by Datadog
    with ddappsec v0.4.3, Copyright Datadog, by Datadog

### OS info
Alpine Linux 3.9.6

**Comment by bwoebi** [comment]
Hey @AntoineLemaire a possible fix for you use case should be just using a register_shutdown_function(), i.e.:
```
register_shutdown_function(function() {
    $span = \DDTrace\root_span();
    if (null !== $span) {
        $span->meta['symfony.route.name'] = 'youshido_graphql_'.$operationName;
    }
});
```

Does that help you?

**Comment by AntoineLemaire** [comment]
Hi @bwoebi, thanks for your help
I tried, and it well change symfony route name, but the APM row still appear with default route :thinking: 
Do you know where this value comes from?
![image](https://user-images.githubusercontent.com/2025537/200260454-a1ccdbeb-f5d3-465d-baca-23c285af9588.png)

**Comment by bwoebi** [comment]
The information there is the span name itself, i.e. `$span->name`. If you want to update that one too, assign the same value to it in that Closure.

**Comment by AntoineLemaire** [comment]
Thank you @bwoebi for your help, I think we can close this issue as I now have a workaround to do what I needed.

For complete answer, I finally updated `$span->resource`, so I can have 1 row per graphql query, based on the queryname sent.

```        
register_shutdown_function(function() use ($overridedResourceName) {
    $span = \DDTrace\root_span();
    if (null !== $span) {
        $span->resource = $overridedResourceName;
    }
});

```

![image](https://user-images.githubusercontent.com/2025537/200558348-6ffd6fa8-9cac-43bc-b647-b3dfbe9dc540.png)
