### ISSUE TITLE
[Feature] W3C Trace Context support?

### ISSUE THREAD

**Issue by ymtdzzz** [DataDog/dd-trace-php#1781]
**Is your feature request related to a problem? Please describe.**
Referring to the code below, W3C Trace Context is not supported currently.
https://github.com/DataDog/dd-trace-php/blob/674dc1998b22fd25db12d83d56ed050cfa1804b7/ext/configuration.h#L102

**Describe the solution you'd like**
With supporting context extraction from W3C Trace Context styled header would enable this tracer to work well together with OpenTelemetry easier 😃

**Comment by bwoebi** [comment]
Hey @ymtdzzz,

We are currently in progress of determining the exact representation of the tracestate header, which will ferry information from x-datadog-tags, x-datadog-origin and x-datadog-sampling-priority (which is more specific than the binary 0/1 which w3c expose).
Once we have that set in stone (I expect end of next week - but no guarantees), we will move onto implementing it.

It's definitely on our to-do list, and will probably have been implemented by early december, but we are not quite there yet.

So, while we definitely appreciate the offer for help, we need to make all our datadog tracers cooperate for the ferrying of vendor-specific (i.e. our) information.

Thanks!

**Comment by ymtdzzz** [comment]
Hi @bwoebi, thanks for your quick reply!

> It's definitely on our to-do list

That's great, I look forward to the release of the feature!

Thank you.

**Comment by bwoebi** [comment]
I'll leave the issue open though, for now, until we have implemented it, also for visibility that we're indeed going to work on it.

**Comment by bwoebi** [comment]
Will be implemented by #1856.

**Comment by bwoebi** [comment]
Has been merged by now, so closing this.
