### ISSUE TITLE
[BUG] Elasticsearch integration is outdated

### ISSUE THREAD

**Issue by Fake51** [DataDog/dd-trace-php#1787]
### Bug description
The newest version of the Elastic package for PHP (https://packagist.org/packages/elasticsearch/elasticsearch) is using a new namespace. The DD tracer doesn't handle this.

Specifically, from https://github.com/DataDog/dd-trace-php/blob/master/src/Integrations/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php

         // Dynamically generate namespace traces to ensure forward compatibility with future ES versions
        $integration = $this;
        \DDTrace\trace_method('Elasticsearch\Client', '__construct', [

But the Elasticsearch  package from 8.0 and onwards uses

    Elastic\Elasticsearch\*

Check https://packagist.org/packages/elasticsearch/elasticsearch

### PHP version
Any

### Tracer version
0.81.1

### OS info
Any

#### Output of phpinfo() (ddtrace >= 0.47.0)
Not relevant

#### Output of dd-doctor (ddtrace < 0.47.0)
Not relevant

### Upgrading info
Not relevant

**Comment by pierotibou** [comment]
Hello @Fake51, support for Elasticsearch 8 has been added in [our last release](https://github.com/DataDog/dd-trace-php/releases/tag/0.82.0).
