### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nikhipandeysendinblue** [DataDog/dd-trace-php#1811]
ARG PHP_VERSION=8.1.11
ARG NGINX_VERSION=1.18

# "php" stage
FROM php:${PHP_VERSION}-fpm-buster AS api_platform_php
ENV PHP_MONGODB_VERSION=1.14.2
ENV PHP_DD_TRACE_VERSION=0.56.0
ENV PHP_XDEBUG_VERSION=3.1.3

RUN set -ex &&\
    apt-get update &&\
    cd /tmp &&\
    curl -L --output dd-php-tracer.deb https://github.com/DataDog/dd-trace- 
        php/releases/download/${PHP_DD_TRACE_VERSION}/datadog-php-tracer_${PHP_DD_TRACE_VERSION}_amd64.deb &&\
    dpkg -i dd-php-tracer.deb &&\
    apt-get autoremove --purge -y libicu-dev && apt-get autoclean &&\
    rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

error getting 
 #0 34.29  dpkg: error processing archive dd-php-tracer.deb (--install):
#0 34.29  package architecture (amd64) does not match system (arm64)
#0 34.30 Errors were encountered while processing:

**Comment by bwoebi** [comment]
It seems like you're trying to install an amd64 binary on arm64. Could you retry with the *_arm64.deb asset instead?
