### ISSUE TITLE
Ini file created by datadog-setup.phpdoes not align with rpm package

### ISSUE THREAD

**Issue by JanThiel** [DataDog/dd-trace-php#1833]
Hey guys,

we encountered several "PHP Warning: Module 'ddtrace' already loaded in Unknown on line 0" warnings after we used your installer over the last couple of weeks. We had DD as well as the profiler installed before we used your installer for the first time.

The reason was a bit tough to find but logical at the end :-)

https://github.com/DataDog/dd-trace-php/blob/7cdb199db6513d10eaaceb1ca3c5ae33465dae8c/datadog-setup.php#L227

We install all DD packages using the remi repo rpm packages on Centos ( let's take a jump back to the past: https://github.com/DataDog/dd-trace-php/issues/214 ).
Remi adds the ini files with the prefix `40-ddtrace.ini`. Thus all updates to the rpm packages leads to a duplicate ini file being present.
Your installer creates `98-ddtrace.ini`.

We now simply moved your ini file to `40-ddtrace.ini`. But still running the installer again or setting up a fresh system will always lead to this ini clash.

Maybe you could add a check to your installer to see if a `xx-ddtrace.ini` file is already present in `/php.d/` and offer to overwrite these instead of creating a new file?

Best regards,

Jan

**Comment by bwoebi** [comment]
Ping @remicollet - is there a particular reason why you use a diverging prefix `40-` instead of `98-` in your packaging?

**Comment by remicollet** [comment]
> Ping @remicollet - is there a particular reason why you use a diverging prefix `40-` instead of `98-` in your packaging?

Just following packaging practices (and Guidelines)
Don't know where is idea of "98" comes from, and btw, relying on some ini name seems terribly strange (and obviously not robust, and subject for breakage, like this one,  QED)

**Comment by bwoebi** [comment]
Hm, in that case I think we could do a grep for `^extension\s*=.*ddtrace` to check whether some ini already exists, then warn during installation.
