### ISSUE TITLE
Memcache GET's stopped working somewhere between .72 and 0.80

### ISSUE THREAD

**Issue by gman-wa** [DataDog/dd-trace-php#1868]
### Bug description
Traces of Memcache GETs disappear from DD UI sometime between 0.72 and 0.80 - 0.72 works.  Still not working in 0.83.

GET's are reported for about 20 min after a deploy and then stop.  SET's continue to be reported.

### PHP version
8.0.x (latest)

### Tracer version
0.72 works - 0.76 does not - possibly more in between 0.72 and 0.76 don't work

### Installed extensions
memcached 3.2.0

### OS info
4.14.301-224.520.amzn2.x86_64

#### Output of phpinfo() (ddtrace >= 0.47.0)
{ "date": "2023-01-17T23:01:49Z", "os_name": "Linux 269731679e46 4.14.301-224.520.amzn2.x86_64 #1 SMP Fri Dec 9 09:57:03 UTC 2022 x86_64", "os_version": "4.14.301-224.520.amzn2.x86_64", "version": "0.83.0", "lang": "php", "lang_version": "8.0.21", "env": "qa-r2d2", "enabled": true, "service": "php", "enabled_cli": false, "agent_url": "http:\/\/172.17.0.1:8126", "debug": false, "analytics_enabled": false, "sample_rate": 1, "sampling_rules": [], "tags": [], "service_mapping": [], "distributed_tracing_enabled": true, "priority_sampling_enabled": true, "dd_version": "23.2.1.10", "architecture": "x86_64", "sapi": "apache2handler", "datadog.trace.request_init_hook": "\/opt\/datadog\/dd-library\/0.83.0\/dd-trace-sources\/bridge\/dd_wrap_autoloader.php", "open_basedir_configured": false, "uri_fragment_regex": null, "uri_mapping_incoming": null, "uri_mapping_outgoing": null, "auto_flush_enabled": false, "generate_root_span": true, "http_client_split_by_domain": true, "measure_compile_time": true, "report_hostname_on_root_span": false, "traced_internal_functions": null, "auto_prepend_file_configured": false, "integrations_disabled": "default", "enabled_from_env": true, "opcache.file_cache": null }-name>.php` when you are done -->

### Upgrading info
Noticed in 0.79 - did not have time to try every version after 0.72

**Comment by bwoebi** [comment]
Hey @gman-wa,

there's nothing in the memcached intregation which has been changed since long time.
I wonder, maybe you are running into specific limits like `DD_TRACE_SPANS_LIMIT`?

I'd suggest you write a ticket to the DataDog support, so that we can also see the received data for ourselves / have some of our support engineers verify the issue.

Thanks!

**Comment by gman-wa** [comment]
Sorry for the delay - just getting back to this.  Here is the DD ticket# - 1095183.

For additional information, we ran 0.72 for a couple weeks and memcache reporting in DD stayed constant.  We deployed 0.83 and GETs disappeared from DD UI pretty quick.

**Comment by bwoebi** [comment]
This bug has been fixed as of 0.85.0. This was due to the JIT not calling zend_execute_internal, our internal hook to trace internal functions.
