### ISSUE TITLE
[Feature] support blocklist for http requests.

### ISSUE THREAD

**Issue by erictt** [DataDog/dd-trace-php#1889]
**Is your feature request related to a problem? Please describe.**

We want to block certain http endpoint to be traced, i.e. `/status`. This function has been supported in the javascript lib: https://datadoghq.dev/dd-trace-js/interfaces/plugins.http.html

Is it possible to bring the feature here?

**Comment by bwoebi** [comment]
Hey @erictt,

We do not have a direct blocklist here (currently), but for now, you can disable it directly in the PHP script by adding `ini_set("datadog.trace.enabled", "0");` for your /status endpoint.
If using apache, you can disable it within e.g. a `<File>` directive and add `php_value datadog.trace.enabled "0"`.

Does that help your use case?

**Comment by erictt** [comment]
Hi @bwoebi,

Thanks for the quick reply. 

You mean add `ini_set("datadog.trace.enabled", "0");` in the Controller for `/status`? If i do that, it will change the value globally, right? isn't gonna affect the other endpoints as well? Anyway, let me make some tests.

I'm using Nginx for the webproxy, but i think i can find a way to do the same tricks, but i wonder if this gonna have the same issue like configuring it in PHP.

**Comment by bwoebi** [comment]
Hey @erictt,

yes, exactly, only in the controller you don't want to be traced.
With php-fpm/nginx I'm not aware of any solutions on that layer except directly changing the code.

**Comment by erictt** [comment]
@bwoebi I realize if i use this inside a function, it will reset after the function returns. Nice trick. Thanks!
