### ISSUE TITLE
Problem with composer installing symfony/polyfill

### ISSUE THREAD

**Issue by M1ke** [DataDog/dd-trace-php#19]
For projects which already use a library dependent on some component of the `symfony/polyfill` library the `composer require` process for this library will likely fail, e.g.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install symfony/polyfill v1.7.0|remove symfony/polyfill-php56 v1.4.0
    - don't install symfony/polyfill-php56 v1.4.0|don't install symfony/polyfill v1.7.0
    - don't install symfony/polyfill v1.7.0|don't install symfony/polyfill-php56 v1.4.0
    - datadog/dd-trace 0.1.0 requires symfony/polyfill ~1.7.0 -> satisfiable by symfony/polyfill[v1.7.0].
    - Installation request for datadog/dd-trace ^0.1.0 -> satisfiable by datadog/dd-trace[0.1.0].
    - Installation request for symfony/polyfill-php56 (locked at v1.4.0) -> satisfiable by symfony/polyfill-php56[v1.4.0].
```

This is likely why the `symfony/polyfill` project recommend:

> It is strongly recommended to upgrade your PHP version and/or install the missing extensions whenever possible. This polyfill should be used only when there is no better choice or when portability is a requirement.

I've installed the library on a system with PHP 7.0.30 and the tests pass fine. So I think it's only a few specific polyfills that might be required and it would be worth listing them.

I can submit a PR to remove the polyfill library but obviously my case isn't the only one. Is there a list of extensions required that we can polyfill specifically for?

**Comment by jcchavezs** [comment]
AFAIR we only required so we could include `Throwable` in the hinting: https://github.com/DataDog/dd-trace-php/blob/8826319509531a53d6d4de00edd4472375795da8/src/DDTrace/Span.php#L240

**Comment by chuck** [comment]
Looks like just specifying symfony/polyfill-php70 instead of symfony/polyfill should also work, and is what the library wants us to do.

**Comment by chuck** [comment]
Should be set, please let me know if you have any additional problems here!

**Comment by Hoten** [comment]
With an empty composer file and no lock file, I get this error:
```
> composer require datadog/dd-trace

Using version ^0.1.0 for datadog/dd-trace
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Removal request for opentracing/opentracing == 1.0.0.0-beta5
    - datadog/dd-trace 0.1.0 requires opentracing/opentracing 1.0.0-beta5 -> satisfiable by opentracing/opentracing[1.0.0-beta5].
    - Installation request for datadog/dd-trace ^0.1.0 -> satisfiable by datadog/dd-trace[0.1.0].
```

**Comment by chuck** [comment]
I've pushed 0.1.2 with all of the recent fixes, including one for this.
Thanks for the report!
