### ISSUE TITLE
[BUG] FPM shows warnings about rust errors when activating profiler

### ISSUE THREAD

**Issue by Spea** [DataDog/dd-trace-php#1919]
### Bug description

We activated the datadog profiler in our php applications, but FPM reports a warning about an error in rust 👇 

```
WARNING: child 77 said into stderr: "thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:1311:40"
WARNING: child 77 said into stderr: "stack backtrace:"
WARNING: child 77 said into stderr: "   0:     0x7f4043390f74 - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5"
WARNING: child 77 said into stderr: "   1:     0x7f4043390f74 - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5"
WARNING: child 77 said into stderr: "   2:     0x7f4043390f74 - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5"
WARNING: child 77 said into stderr: "   3:     0x7f4043390f74 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22"
WARNING: child 77 said into stderr: "   4:     0x7f40431a556c - core::fmt::write::he803f0f418caf762"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17"
WARNING: child 77 said into stderr: "   5:     0x7f404338ba1a - std::io::Write::write_fmt::h70bc45872f37e7bb"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15"
WARNING: child 77 said into stderr: "   6:     0x7f4043393a06 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5"
WARNING: child 77 said into stderr: "   7:     0x7f4043393a06 - std::sys_common::backtrace::print::h359300b4a7fccf65"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9"
WARNING: child 77 said into stderr: "   8:     0x7f4043393a06 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22"
WARNING: child 77 said into stderr: "   9:     0x7f4043393726 - std::panicking::default_hook::h03ca0f22e1d2d25e"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9"
WARNING: child 77 said into stderr: "  10:     0x7f40433941f6 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17"
WARNING: child 77 said into stderr: "  11:     0x7f4043393e9c - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:586:13"
WARNING: child 77 said into stderr: "  12:     0x7f40433914b4 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18"
WARNING: child 77 said into stderr: "  13:     0x7f4043393c2d - rust_begin_unwind"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5"
WARNING: child 77 said into stderr: "  14:     0x7f4043178643 - core::panicking::panic_fmt::he1bbc7336d49a357"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14"
WARNING: child 77 said into stderr: "  15:     0x7f404317850d - core::panicking::panic::h4241c5ccea17faca"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5"
WARNING: child 77 said into stderr: "  16:     0x7f40431c19d9 - core::option::Option<T>::unwrap::h0af1abade8f69c20"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:752:21"
WARNING: child 77 said into stderr: "  17:     0x7f40431c19d9 - std::thread::JoinInner<T>::join::h51bbd40ab6e6b0a8"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:1311:9"
WARNING: child 77 said into stderr: "  18:     0x7f40431c19d9 - std::thread::JoinHandle<T>::join::hd7eb153ed30bac93"
WARNING: child 77 said into stderr: "                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:1443:9"
WARNING: child 77 said into stderr: "  19:     0x7f40431c9851 - datadog_php_profiling::profiling::Profiler::stop::hd9d5d1320e2d4d07"
WARNING: child 77 said into stderr: "                               at /home/circleci/datadog/profiling/src/profiling.rs:724:27"
WARNING: child 77 said into stderr: "  20:     0x7f40431c12ed - datadog_php_profiling::mshutdown::h53825f379a205901"
WARNING: child 77 said into stderr: "                               at /home/circleci/datadog/profiling/src/lib.rs:881:9"
WARNING: child 77 said into stderr: "  21:     0x55d813befdff - <unknown>"
WARNING: child 77 said into stderr: "  22:     0x55d813be8570 - <unknown>"
WARNING: child 77 said into stderr: "  23:     0x55d813bfbef9 - zend_hash_graceful_reverse_destroy"
WARNING: child 77 said into stderr: "  24:     0x55d813be9907 - <unknown>"
WARNING: child 77 said into stderr: "  25:     0x55d813b84c42 - php_module_shutdown"
WARNING: child 77 said into stderr: "  26:     0x55d813a3d683 - <unknown>"
WARNING: child 77 said into stderr: "  27:     0x7f40499f0eb0 - __libc_start_call_main"
WARNING: child 77 said into stderr: "  28:     0x7f40499f0f60 - __libc_start_main_alias_2"
WARNING: child 77 said into stderr: "  29:     0x55d813a3f0c5 - _start"
WARNING: child 77 said into stderr: "  30:                0x0 - <unknown>"
WARNING: child 77 said into stderr: "fatal runtime error: failed to initiate panic, error 5"
WARNING: child 77 exited on signal 9 (SIGKILL) after 191.615477 seconds from start
```

This error leads to FPM becoming unresponsive after a while and I'm not sure how to resolve this. 

Datadog is installed inside docker via the following command

```
RUN curl -A "Docker" -o /tmp/datadog-setup.php -D - -L -s https://github.com/DataDog/dd-trace-php/releases/download/0.84.0/datadog-setup.php \
    && php /tmp/datadog-setup.php --php-bin=all --enable-profiling
```

### PHP version

```
PHP 8.1.15 (cli) (built: Jan 31 2023 15:13:17) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.15, Copyright (c), by Zend Technologies
    with ddtrace v0.84.0, Copyright Datadog, by Datadog
    with datadog-profiling v0.13.0, Copyright Datadog, by Datadog
    with ddappsec v0.6.0, Copyright Datadog, by Datadog
```

### Tracer version

```
0.84.0
```

### Installed extensions

```
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
datadog-profiling
date
ddappsec
ddtrace
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
grpc
hash
iconv
igbinary
intl
json
libxml
mbstring
memcached
msgpack
newrelic
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
readline
redis
Reflection
session
SimpleXML
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
datadog-profiling
ddappsec
ddtrace
```

### OS info

```
NAME="AlmaLinux"
VERSION="9.1 (Lime Lynx)"
VERSION_ID="9.1"
PRETTY_NAME="AlmaLinux 9.1 (Lime Lynx)"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

#### Output of phpinfo() (ddtrace >= 0.47.0)

DATADOG TRACER CONFIGURATION

```json
{
    "date": "2023-02-10T11:23:37Z",
    "os_name": "Linux web-7d6f5865bb-czsjj 5.15.58-flatcar #1 SMP Wed Aug 3 19:35:04 -00 2022 x86_64",
    "os_version": "5.15.58-flatcar",
    "version": "0.84.0",
    "lang": "php",
    "lang_version": "8.1.14",
    "env": "production",
    "enabled": true,
    "service": "web-blue",
    "enabled_cli": false,
    "agent_url": "unix:\/\/\/var\/run\/datadog\/apm.socket",
    "debug": false,
    "analytics_enabled": false,
    "sample_rate": 1,
    "sampling_rules": [],
    "tags": [],
    "service_mapping": [],
    "distributed_tracing_enabled": true,
    "priority_sampling_enabled": true,
    "dd_version": "datadog-profiler",
    "architecture": "x86_64",
    "sapi": "fpm-fcgi",
    "datadog.trace.request_init_hook": "\/opt\/datadog\/dd-library\/0.84.0\/dd-trace-sources\/bridge\/dd_wrap_autoloader.php",
    "open_basedir_configured": false,
    "uri_fragment_regex": null,
    "uri_mapping_incoming": null,
    "uri_mapping_outgoing": null,
    "auto_flush_enabled": false,
    "generate_root_span": true,
    "http_client_split_by_domain": false,
    "measure_compile_time": true,
    "report_hostname_on_root_span": false,
    "traced_internal_functions": null,
    "auto_prepend_file_configured": false,
    "integrations_disabled": "default",
    "enabled_from_env": true,
    "opcache.file_cache": null
}
```
![image](https://user-images.githubusercontent.com/495017/218081381-1f458c8d-fa4a-45a7-a12d-60d453979b2a.png)

**Comment by realFlowControl** [comment]
Hey @Spea,

thanks for reaching out and sorry for this bug.

- Do you by chance use `fork()` in one of your scripts?
   As this problem looks related to https://github.com/DataDog/dd-trace-php/issues/1741
- Were you upgrading from an older version of the profiler/tracer and if so, from which version?

Regards
Florian

**Comment by Spea** [comment]
Hey @realFlowControl, thanks for your reply

* No, we are not using `pcntl_fork()` anywhere in the project
* We just started using datadog recently, so we used `0.83.1` in the beginning, but when I started enabling the profiler I switched to `0.84.0`.

**Comment by Spea** [comment]
> Sorry that you are having issues. 

Nothing to be sorry about, thank you for helping me out here!

> At your convenience, can you upload the `datadog-profiling` section of `phpinfo()`?

Sure, here you go

![image](https://user-images.githubusercontent.com/495017/218134640-0b7c9637-35b7-45ba-988e-c07b9dc678a3.png)

**Comment by morrisonlevi** [comment]
Thank you for the datadog-profiling section! How often is this occurring, btw? Is this highly reproducible? If so, the fastest approach might be to jump in a Zoom call together.

**Comment by Spea** [comment]
We are currently testing the profiler in a separate deployment in our kubernetes cluster. It is not "highly" reproducible, but FPM **always** becomes unresponsive after a while. Most of the time this happens shortly after our integration tests went through (sometimes it even becomes unresponsive before the tests are finished), but I can not point it to a specific endpoint/request that breaks it. 

My assumption is, that something is blocking the fpm child processes and thus no new requests can be handled (= runs into a gateway timeout)

I'm fine with doing a zoom call, though I'm not sure I can give you any more insights.

**Comment by morrisonlevi** [comment]
By chance, do any of those tests intentionally hit the PHP request timeout, or otherwise use signals? Thank you for your information so far!

**Comment by realFlowControl** [comment]
> We use the [auto generated preload file](https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading) from symfony and activate it via the following ini configuration:

Which Symfony version are you using?

**Comment by morrisonlevi** [comment]
@Spea Thus far we haven't been able to reproduce it. I'll continue to try to reproduce it next week. In the meantime, I have a PR open to help mitigate the issue which should ship in 0.85.0. At the very least, the PR will provide more log messages about what's going on.

**Comment by Spea** [comment]
@morrisonlevi Thank you for the update. I'll try the new version once it is released and let you know if anything changes.

**Comment by realFlowControl** [comment]
Hey @Spea,
I would really be interested in seeing this. If you offer to have a Zoom call still persists, you may signup to our public slack at https://chat.datadoghq.com/ and ping me there (Florian Engelhardt) or write me an email to `$firstname.$lastname@datadoghq.com`. Looking forward to meeting you!

**Comment by Spea** [comment]
I could make a little progress here. With the newest nightly build the rust errors mentioned in the initial post are gone, but the core issue (fpm processes being blocked) is not yet resolved. 

To see if any of the preloaded classes might be the issue, I gradually removed classes from the preloading file until only an empty file was left 👇 

```php
use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

$classes = [];
```

Even with this empty file, the fpm processes became blocked after a while. So it seems by solely enabling preloading we run into blocked fpm processes.

While taking a closer look at the logs I realized that the fpm processes are getting blocked after the `Stopping profiler` log message https://github.com/DataDog/dd-trace-php/blob/e64b2a554ab6f749afcd621d26c6349a0a8c188e/profiling/src/profiling/mod.rs#L464 

As the `warn` and `debug` messages from the following lines are not printed, my assumption is, that the channel is full and thus the `send` method blocks the (fpm) thread https://github.com/DataDog/dd-trace-php/blob/6a3f9fad509aba897f94bd8cf24a33749aac542f/profiling/src/profiling/mod.rs#L465-L468

As there are also no log messages from the [handle_resource_message](https://github.com/DataDog/dd-trace-php/blob/6a3f9fad509aba897f94bd8cf24a33749aac542f/profiling/src/profiling/mod.rs#L250-L253) method in the `TimeCollector` class it does indeed looks like the channel is full. Though I'm not sure why the messages are not consumed/handled by the receiver I hope this gives you some more hints on what might be wrong here.

In the following gist you can also find the complete log output: https://gist.github.com/Spea/d93ea64e20c7d5261562f6f9dbc7a3fb

**Comment by morrisonlevi** [comment]
I have attempted to reproduce this using the symfony/demo app on GitHub that uses Symfony 6.2.7 on PHP 8.1.15. These version numbers are very close to yours but aren't exact. I wasn't able to get it to crash using the CLI webserver nor php-fpm. Hopefully Florian will be able to get to the root of it in the next Zoom call.

**Comment by Spea** [comment]
I was finally able to reproduce this in an isolated environment. The issue happens only when the fpm process is started as a non-root user **and** preloading is enabled. I was able to reproduce this behaviour on my mac and on another ones linux machine. 

To reproduce it, follow these steps:

1. Check out the `replicate-process-blocking` branch from [my fork](https://github.com/rebuy-de/dd-trace-php/tree/replicate-process-blocking) ([viewable diff](https://github.com/DataDog/dd-trace-php/compare/master...rebuy-de:dd-trace-php:replicate-process-blocking))
2. Execute the following commands inside the `examples/nginx-php-fpm` directory
   * `docker-compose build`
   * `docker composer up -d`
3. After that you have to make a little bit over 100 request to nginx/fpm so the [crossbeam channel](https://github.com/DataDog/dd-trace-php/blob/f49d1af5cbe8bc5fc49fd704bbaf3c8ad2784cfd/profiling/src/profiling/mod.rs#L399) is full and blocks the process. The easiest way to do that, is by using the `ab` command
   * `ab -n 150 -c 8 http://127.0.0.1:8888/`
4. When you now go to [http://127.0.0.1:8888/](http://127.0.0.1:8888/), you should see a gateway timeout.

This issue will not happen if either of the two things will be changed

1. Disable preloading by removing [this line](https://github.com/rebuy-de/dd-trace-php/blob/replicate-process-blocking/examples/nginx-php-fpm/Dockerfile_php_fpm#L14) from the docker file
2. Run fpm as root by removing the [USER instruction](https://github.com/rebuy-de/dd-trace-php/blob/replicate-process-blocking/examples/nginx-php-fpm/Dockerfile_php_fpm#L21) from the docker file

Side note: I saw that you are using the `send_timeout` method now when stopping the profiler (via https://github.com/DataDog/dd-trace-php/commit/d36fe7d16d82b3613f9fcfcf58dd7ce2eeedfa4d). I will test this change later today, but I assume with this change my the issue i describe is quite likely gone. Nevertheless I wanted to provide a reproducible case, so you might be able find the root cause.

**Comment by realFlowControl** [comment]
Thanks @Spea, this is amazing!
I can reproduce your behaviour thanks to your example on my local machine. I'll analyse this and ping you once we understand whats going on.

**Comment by Spea** [comment]
> Side note: I saw that you are using the `send_timeout` method now when stopping the profiler (via [d36fe7d](https://github.com/DataDog/dd-trace-php/commit/d36fe7d16d82b3613f9fcfcf58dd7ce2eeedfa4d)). I will test this change later today, but I assume with this change my the issue i describe is quite likely gone. Nevertheless I wanted to provide a reproducible case, so you might be able find the root cause.

Just wanted to confirm: After using the latest build artifacts (via https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/10320/workflows/46a9deed-874f-47f5-ae69-19cf0be766c4/jobs/1957745/artifacts), fpm processes no longer get blocked

**Comment by morrisonlevi** [comment]
@Spea Thank you for assisting us with this! FYI, that commit went out in the 0.85.0 release. I am preparing a PR now for the core issue with preloading.

**Comment by realFlowControl** [comment]
Hey @Spea,
[`0.86.0`](https://github.com/DataDog/dd-trace-php/releases/tag/0.86.0) has been released containing the fix 🎉

**Comment by Spea** [comment]
With the new version we now see data coming in, thank you so much everyone for helping on this issue, really appreciated 🥳
