### ISSUE TITLE
User extractor - Error when the id is a protected property

### ISSUE THREAD

**Issue by Lavoaster** [DataDog/dd-trace-php#192]
We use Doctrine within our Laravel Project, and not eloquent. So we don't expose our object properties, however, the code for extracting users appears to rely on accessing the id property directly, as apposed to going through the `\Illuminate\Contracts\Auth\Authenticatable` interface, which is required anyway.

You could modify the code in place to the following, and get rid of the try/catch.

```php
$user = auth()->user();
// You probably would want to import the class below
if ($user && $user instanceof \Illuminate\Contracts\Auth\Authenticatable) {
    $span->setTag('laravel.user', strlen($user->getAuthIdentifierName()) > 0 ? $user->getAuthIdentifierName() : '-');
}
```

**Comment by tatianajiselle** [comment]
hey -- please see this PR for this ticket; https://github.com/DataDog/dd-trace-php/pull/376

**Comment by SammyK** [comment]
Hey @Lavoaster! Thanks again for reporting this issue. This patch was applied in version `0.16.0` via #363.
