### ISSUE TITLE
[BUG] Tracer swallowing uncaught exception in Symfony 3.4

### ISSUE THREAD

**Issue by tommym9** [DataDog/dd-trace-php#1955]
### Bug description
In a Symfony site we have an `onKernelException` subcriber. This takes any uncaught exceptions and does some processing before creating a response and calling `$event->setResponse($response);`.

This gets interupted by the Data Dog tracer. It *looks* like the uncaught exception is getting handled before it gets to the `kernel.exception` stage, so then we see an `The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?` error.

In an ideal world we would handle this exception before it gets to this stage (i.e in the controller), but this is the way the application has been architected and so I'm stuck with it for the forseeable.

Lastly this happens with the 'Full installation', 'APM + ASM' and 'APM only'.

Any help is much appreciated.

### PHP version
7.4.33

### Tracer version
0.84.0

### Installed extensions
["Core","date","libxml","openssl","pcre","sqlite3","zlib","ctype","curl","dom","fileinfo","filter","ftp","hash","iconv","json","mbstring","SPL","PDO","pdo_sqlite","session","posix","readline","Reflection","standard","SimpleXML","Phar","tokenizer","xml","xmlreader","xmlwriter","mysqlnd","cgi-fcgi","ddtrace","ddappsec","memcached","exif","gd","imagick","mysqli","pcntl","pdo_mysql","soap","sodium","sysvsem","zip","Zend OPcache"]

### OS info
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

#### Output of phpinfo() (ddtrace >= 0.47.0)
```
{ "date": "2023-03-06T16:21:12Z", "os_name": "Linux ip-172-20-43-40.eu-west-2.compute.internal 5.10.162-141.675.amzn2.x86_64 #1 SMP Mon Jan 9 22:45:11 UTC 2023 x86_64", "os_version": "5.10.162-141.675.amzn2.x86_64", "version": "0.84.0", "lang": "php", "lang_version": "7.4.30", "env": null, "enabled": true, "service": null, "enabled_cli": false, "agent_url": "http:\/\/localhost:8126", "debug": false, "analytics_enabled": false, "sample_rate": 1, "sampling_rules": [], "tags": [], "service_mapping": [], "distributed_tracing_enabled": true, "priority_sampling_enabled": true, "dd_version": null, "architecture": "x86_64", "sapi": "fpm-fcgi", "datadog.trace.request_init_hook": "\/opt\/datadog\/dd-library\/0.84.0\/dd-trace-sources\/bridge\/dd_wrap_autoloader.php", "open_basedir_configured": false, "uri_fragment_regex": null, "uri_mapping_incoming": null, "uri_mapping_outgoing": null, "auto_flush_enabled": false, "generate_root_span": true, "http_client_split_by_domain": false, "measure_compile_time": true, "report_hostname_on_root_span": false, "traced_internal_functions": null, "auto_prepend_file_configured": false, "integrations_disabled": "default", "enabled_from_env": true, "opcache.file_cache": null } 
```

**Comment by bwoebi** [comment]
Looking at the code, this error is emitted in `HttpKernel::handleRaw()`. The kernel.exception code happens sometime afterwards.

The tracer is not supposed to touch any exceptions by itself. I assume that the issue does not happen with the tracer disabled? At least the tracer should not be even able to suppress exceptions at all.

I am wondering whether some issue in the tracer may cause that. If you set `DD_TRACE_DEBUG=1`, do you get any extra errors in your php error log?

**Comment by tommym9** [comment]
Hi @bwoebi 

You assume correct, I can't get my head around it as like you said the tracer *shouldn't* affect the running of the application.

I set `DD_TRACE_DEBUG=1` and it did give me a little bit of extra info:

<img width="1204" alt="Screenshot 2023-03-07 at 11 25 23" src="https://user-images.githubusercontent.com/3606130/223409195-08737621-d450-43b4-acae-a58ef36cae86.png">

Before I only had the log entry about the `LogicException` and now I have a bit more with the notices about undefined variables.

I can also see a few entries like `PHP message: Flushing trace of size 331 to send-queue for http://localhost:8126` which looks like the tracer is happily sending data to Data Dog.

Finally I am aware that the above logs should be going into Data Dog. The Lambda forwarder we have setup to go from Cloudwatch => Data Dog doesn't want to do it for the environment I've setup to test this stuff out so I'm stuck in the dark ages!

Cheers

Tom

**Comment by bwoebi** [comment]
Hm yeah @tommym9 It definitely looks like some exception being swallowed. Now, in a recent not yet released commit https://github.com/DataDog/dd-trace-php/commit/e26d63268e656a5b32a3a2cf7981991aa61ce4ba I did discover that we might be swallowing exceptions in case a hook callback could not be called.

It would be interesting for me to know whether this commit fixes your issue or whether we have another issue.
A recent build is: https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/10148/workflows/33ac6f87-1804-4f52-99b0-805a6dc54525/jobs/1884512/artifacts - download the `dd-library-php-*.tar.gz` file which matches your system, and run the datadog installer with the appropriate artifact, e.g. `php datadog-setup.php --file dd-library-php-*.tar.gz`.

**Comment by tommym9** [comment]
Hi @bwoebi 

Using the nightly looks like its fixed it. I've got a load more testing to do my end later this week so I won't be able to confirm until Friday.

Will update here once I've managed to get the rest of the testing done.

Cheers

Tom

**Comment by tommym9** [comment]
Hi @bwoebi 

I've completed the testing my end and its all looking good. Do you know when this one will make it into a release?

Cheers

Tom

**Comment by bwoebi** [comment]
Hey @tommym9,

Now :-)

We just released 0.85.0 containing that fix.

**Comment by tommym9** [comment]
Hi @bwoebi 

I've got an update on this one. When I tested with the nightly build from March 7th, this was working all fine.

I then used the latest release `https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php` in my code and deployed to my production environment.

This looked all good, but then we started seeing this issue crop up again on the 20th of March. I took this off production on the 21st and its taken me this long to get back round to giving this another go.

I've re-instaned the latest release on a PR envinronment and I can see this erorr is present.

Any help is much appreciated. Like I said I have a separate envronment to test on, so I can enable debugging and any other bits to help diagnose this one.

Cheers

Tom

**Comment by bwoebi** [comment]
Hey @tommym9,

I have no immediate ideas what could've gone wrong, with `DD_TRACE_DEBUG=1` this time nothing stands out in particular?

**Comment by tommym9** [comment]
Hi @bwoebi,

Nothing is jumping out at me, for reference here is the DD tracer config in case anything jumps out from that?

```
NOTICE: PHP message: DATADOG TRACER CONFIGURATION - {
    "date": "2023-05-03T10:26:31Z",
    "os_name": "Linux ip-172-20-41-137.eu-west-2.compute.internal 5.10.177-158.645.amzn2.x86_64 #1 SMP Thu Apr 6 16:53:11 UTC 2023 x86_64",
    "os_version": "5.10.177-158.645.amzn2.x86_64",
    "version": "0.86.3",
    "lang": "php",
    "lang_version": "7.4.33",
    "env": null,
    "enabled": true,
    "service": null,
    "enabled_cli": false,
    "agent_url": "http://localhost:8126",
    "debug": true,
    "analytics_enabled": false,
    "sample_rate": 1,
    "sampling_rules": [],
    "tags": [],
    "service_mapping": [],
    "distributed_tracing_enabled": true,
    "priority_sampling_enabled": true,
    "dd_version": null,
    "architecture": "x86_64",
    "sapi": "fpm-fcgi",
    "datadog.trace.request_init_hook": "/opt/datadog/dd-library/0.86.3/dd-trace-sources/bridge/dd_wrap_autoloader.php",
    "open_basedir_configured": false,
    "uri_fragment_regex": null,
    "uri_mapping_incoming": null,
    "uri_mapping_outgoing": null,
    "auto_flush_enabled": false,
    "generate_root_span": true,
    "http_client_split_by_domain": false,
    "measure_compile_time": true,
    "report_hostname_on_root_span": false,
    "traced_internal_functions": null,
    "auto_prepend_file_configured": false,
    "integrations_disabled": "default",
    "enabled_from_env": true,
    "opcache.file_cache": null
}
```

**Comment by tommym9** [comment]
Hi @PROFeNoM 

Gotcha, so I'll explain the workflow for the controller method that is showing this issue as that might help. Disclaimer I didn't write this code, I've inherited this code base!

- This method accepts a POST of data for a `user`
- This then calls a service that takes the POST data and creates a `user` object from it
- This service then calls the validator against the `user` object
- This list of validation violations are then thrown in a custom exception as an array of violations keyed by property
- This then bubbles up to the controller method, where there isn't the handling and so is caught by the `onKernelException` subscriber and returned as a response
- - Its this part that looks like its causing the issue as locally this works, but when the tracer is on, it doesn't

Looking at the tests for it, pushing invalid data to it in PHPUnit **will** get the validation exception thrown in the service, that is then caught by the `onKernelException` subscriber and returned as a response.

The other bit that has aroused my suspicion is for **some** reason the call to the service is wrapped in a `try` block with no `catch` only a `finally`. This looks something like this

```
try {
  // Validation exception is thrown in this method if the data is invalid.
  $user = $this->userService->create([POST_DATA]);
  // Logic to save the $user to the database.
} finally {
   // Logic to release a lock we aquired earlier in the function.
}

 return $response;
```

The code smell here is this `try` with no `catch` which could be confusing the tracer? I can't quite get my head around how this is working at the moment without the PHP interpreter kicking off.

Cheers

Tom

**Comment by PROFeNoM** [comment]
Thanks for this precious information, Tom! Just one thing that we are wondering is whether the custom exception is being set in the trace? Maybe you do have a screenshot of the flame graph, which would really be top notch 👌

**Comment by tommym9** [comment]
Here's the flame chart. I've blanked some bits out being careful.

<img width="1063" alt="Screenshot 2023-05-05 at 14 41 03" src="https://user-images.githubusercontent.com/3606130/236486689-f2130069-72b6-453c-80da-18d0ce868f92.png">

Looking at the trace I can see that the custom exception **is** being thrown in this service.

Hope this helps and thanks for your help so far. I really appeciate it.

Cheers

Tom
