### ISSUE TITLE
[Feature] Per-request configuration without environment variables

### ISSUE THREAD

**Issue by brainlock** [DataDog/dd-trace-php#1958]
Hi,

in the DataDog docs I read that the recommended way to configure ddtrace-php is via environment variables.

In our setup though, we use each pool of php-fpm processes to serve requests for multiple customers, for multiple versions of our backend, and even for different environments (prod/stage/test). Environment variables configured on the fpm pool won't cut it in this situation.

In order to tag each trace with the correct values, I've been using the php api at the beginning of the request to annotate the root span:

```
$span = \DDTrace\root_span();
if ($span) {
    $span->service = '…';
    $span->type = 'web';
    $span->meta['branch'] = …;
    $span->meta['version'] = …;
    $span->meta['commit'] = …;
    $span->meta['site_name'] = …;
    $span->meta['env'] = …;
}
```

and then later, when the routing has found the endpoint which will handle the request, to annotate the active span:

```
$span = \DDTrace\active_span();
if ($span) {
    $span->resource = $endpoint_name;
}
```

This seems to work well for the traces, I can add the custom fields as columns, filter, facets.

The profiles though aren't annotated with this information: each profile appears to be under the default service name of "web.request", and I don't see any of the other fields (env, version…). It does seem to pick up the endpoint name though, the one I'm setting on the active span->resource.

It would be great if we could also filter the profiles by the fields above.

Is this something you plan to support at some point? Or am I missing something and there is another obvious way of doing this?

(Another way I could pass some of the parameters is via fastcgi parameters, because many of the routing decisions have been made by that point, but not all. Ideally the per-request configuration via the php API would also be picked up in the profiles.)

Thanks for your feedback!

Alberto

**Comment by bwoebi** [comment]
Hey @brainlock,

As described in our docs https://docs.datadoghq.com/tracing/trace_collection/library_config/php/#environment-variable-configuration, each env var has its corresponding ini.

So, in your case with php-fpm, you can add an [.user.ini](https://www.php.net/manual/en/configuration.file.per-user.php) for each target. (Assuming your routing is to different files)

Obviously, if it's fully dynamic, you might have to still do some configuration in code.

**Comment by bwoebi** [comment]
Also, I am noticing that we always fetch version and env from the ini for each span. Do you think it would make sense to fetch it from the parent span if one is available? That should be probably better for your use case too.

**Comment by bwoebi** [comment]
I did miss that you were talking about the profiler and read "profile" as "the profile of a trace".

I've forwarded the issue to our profiler team, so that they can also have a look.

**Comment by morrisonlevi** [comment]
In general, the profiler is intentionally unaware of the tracer and only integrates at specific points to provide enhanced functionality such as Code Hotspots and Endpoint Profiling. It works without the tracer installed, and this is a feature.

Also, the profiler is active the moment a request starts. It is entirely possible that it will gather samples before your configuration code has run, and those samples wouldn't have the "correct" values for service, env, version, etc. The root span's resource is special cased to be fetched only when the trace completes, but there are edges here where it may not apply. For instance:

1. Trace begins.
2. Samples are collected.
3. An upload occurs
4. Then the trace finishes.

In this case, the samples will not have endpoint information. The samples are still there and associated to the configured service, env, and version, they just don't get associated to the endpoint. The user experience would not be as nice if we extended it to service, env, and version, as you'd have the "initial" config some times, and the "runtime" config in others. I think the compromise for endpoint profiling was fine, but I'm not so sure about service, env, and version. We'll have to think about that.

Hopefully this explains why the profiler configuration acts the way it does: it's not laziness, but impact from other design choices. I'd like to improve runtime configuration, but I can't promise a short turn-around on this one.

**Comment by morrisonlevi** [comment]
It may be helpful to sometime to have a Zoom meeting to understand what you are doing in more detail. The concept of a "service" as in "service uptime" and such would generally not be so dynamic as per request. Maybe there's some mismatch of semantics on both sides we could straighten out a bit.

**Comment by brainlock** [comment]
Thanks for the explanation @morrisonlevi. I see where you're coming from, and of course I understand it isn't laziness :-) I'm coming at this with my one use-case, you have to support all the others as well.

You're right there is a mismatch:

- you're thinking of a model where service = pool of processes (fpm)

- we're using fpm more as an application server: the pool of processes is there, fixed, and it can serve multiple applications. We do the routing upstream, in the form of nginx configs, and the config values identifying which application to serve (fs root), which "site" is it, which environment, are passed via fastcgi_params

From this perspective, I need to profile "a request" more than "the process", because the fpm process might serve application A and then application B (and indeed this is what I see when I look under "Profiles" in DataDog).

However: I'm just starting to use DD, and have just now noticed that I don't need to start from the "Profiles" tab and filter the profiles until I find the one I'm interested in. I can start from the details of a single trace (i.e. the Traces tab), and under "Code Hotspots" there is a nice "View in full page" button that links to the exact profile for that trace.

Since the trace is configured dynamically with the site/env/version tags, this gives me all the tools I need.

Please just keep in mind that someone _is_ making use of the capability to configure these root spans at runtime :) As @bwoebi pointed out above, some of our config we could achieve with `.user.ini` files, but some of it couldn't, so it's way more convenient to have it all in once place.

Thanks, both of you, for your comments!
