### ISSUE TITLE
[BUG] Not able to set tag value different than string type

### ISSUE THREAD

**Issue by eugeniocaroccicastoredc** [DataDog/dd-trace-php#2033]
### Bug description
I'm doing something really simple such as

```php
$value = 10;
$scope = GlobalTracer::get()->getRootScope();
$scope->getSpan()->setTag('test_value', (int) $value);
```

But in APM I get this tag set as a string and I haven't found any way to have this one as a number. I need for this to be a number so that I can apply filters on it.

### PHP version

```shell
PHP 8.2.5 (cli) (built: Apr 14 2023 17:42:09) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologies
```

### Tracer version
```
0.82.0
```

**Comment by bwoebi** [comment]
Hey @eugeniocaroccicastoredc,

tags are always strings.
To store a number, set a metric, i.e. `setMetric()` instead of `setTag()`.

**Comment by eugeniocaroccicastoredc** [comment]
@bwoebi Sorry for the `bug` label then! Gonna try right now :)

**Comment by eugeniocaroccicastoredc** [comment]
It works correctly! Thanks @bwoebi :)
