### ISSUE TITLE
4xx started showing as errors after 0.87.0 update

### ISSUE THREAD

**Issue by nklmilojevic** [DataDog/dd-trace-php#2051]
Hi, 

After the upgrade to 0.87.0 4xx status codes have started showing as errors and have been messing with our alerts that are based on error rate. Is there some regression in the last release that could have caused that? We are running Laravel 9/10.

We also think that it was added in these exact lines of codes:

https://github.com/DataDog/dd-trace-php/pull/2026/files#diff-bb8a209447709db0e9e6cea7b06ee6c0bf538050f17c82b6a58a4ab2ede2d516R240

All exceptions do land into that ‘report’ method and only later they are filtered out. But since they hook to ‘report’, datadog gets all the exceptions.

Thanks!

**Comment by bwoebi** [comment]
Hey @nklmilojevic,

we've just released 0.87.1 containing a fix for this - thanks for reporting!

**Comment by nklmilojevic** [comment]
Thanks for the quick patch!
