### ISSUE TITLE
[Feature] profiling `ZTS` builds

### ISSUE THREAD

**Issue by sumerc** [DataDog/dd-trace-php#2070]
Hi,

Is supporting `zts` builds something planned for the future, is there any issue for this? Sorry, if this is already discussed, but I can not seem to find an issue for that.

**Comment by sumerc** [comment]
It was for profiling. Thanks for the info!

What is the main reason behind the complexity?. Maybe we might think to work on it if we understand the underlying problem?

**Comment by morrisonlevi** [comment]
May I ask what you are using ZTS builds for? What libraries and such are you using?

Some of the complexity is that the PHP ABIs change for ZTS. The C macros that C extensions use don't always help since the profiler is primarily written in Rust. It's possible to support, I think, and is more of a matter of priority. Understanding what you are using ZTS builds for can help us understand the priority.

**Comment by sumerc** [comment]
We are thinking of integrating continuous profiling for https://docs.platform.sh/languages/php.html.

And it currently uses ZTS.  I am wondering how hard this task may be?

**Comment by piotrekkr** [comment]
I wanted to use [frankenphp](https://github.com/dunglas/frankenphp) as replacement for `php-fpm+nginx`. It is a ZTS build. Installer does not allow profiling. I liked how profiling worked with php-fpm and would be nice if it was available with ZTS.

```
$ docker build . -f Dockerfile-frankenphp                                            
...
------                                                                                                                                                                                                                                                                                                                      
 > [stage-0 4/4] RUN php /datadog-setup.php --php-bin=all --enable-profiling:                                                                                                                                                                                                                                               
0.536 Searching for available php binaries, this operation might take a while.                                                                                                                                                                                                                                              
0.666 Downloading installable archive from https://github.com/DataDog/dd-trace-php/releases/download/0.96.0/dd-library-php-0.96.0-x86_64-linux-gnu.tar.gz.                                                                                                                                                                  
0.666 This operation might take a while.                                                                                                                                                                                                                                                                                    
1.620 ...................                                                                                                                                                                                                                                                                                                   
8.662 Download completed
8.662 
12.51 Installed required source files to '/opt/datadog/dd-library/0.96.0'
12.57 Installing to binary: php (/usr/local/bin/php)
12.66 Copied '/tmp/dd-install/dd-library-php/trace/ext/20230831/ddtrace-zts.so' to '/usr/local/lib/php/extensions/no-debug-zts-20230831/ddtrace.so'
12.66 Copied '/tmp/dd-install/dd-library-php/appsec/ext/20230831/ddappsec-zts.so' to '/usr/local/lib/php/extensions/no-debug-zts-20230831/ddappsec.so'
12.66 Created INI file '/usr/local/etc/php/conf.d/98-ddtrace.ini'
12.66 ERROR: Option --enable-profiling was provided, but it is not supported on this PHP build or version.
12.66 
------
Dockerfile-frankenphp:6
--------------------
   4 |     ADD https://github.com/DataDog/dd-trace-php/releases/download/0.96.0/datadog-setup.php /datadog-setup.php
   5 |     
   6 | >>> RUN php /datadog-setup.php --php-bin=all --enable-profiling
   7 |     
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c php /datadog-setup.php --php-bin=all --enable-profiling" did not complete successfully: exit code: 1
```

**Comment by realFlowControl** [comment]
Hey @sumerc / @piotrekkr,

I just wanted to let you know that I'll working on bringing ZTS support to the profiler. A first [PR to make it compile](https://github.com/DataDog/dd-trace-php/pull/2463) is already there, more to follow. I'll keep you posted.

Kind regards
Florian

**Comment by sumerc** [comment]
Thanks for the update!

**Comment by piotrekkr** [comment]
Cool. can't wait :+1:

**Comment by realFlowControl** [comment]
Hey @sumerc / @piotrekkr,

we just release [`0.98.0`](https://github.com/DataDog/dd-trace-php/releases/tag/0.98.0) which brings ZTS (more or less as private beta) support for CPU and Wall time profiling and the support for [timeline](https://docs-staging.datadoghq.com/datadog/florian/enable-php-profiler/profiler/profile_visualizations/#timeline-view). I have also tested this with FrankenPHP!
I have not yet tested Exception Profiling, but it seems to work, I'll make this sure for a later release and I am currently working on making allocation profiling thread safe in https://github.com/DataDog/dd-trace-php/pull/2506. There will also be some work done by me to better support FrankenPHP's worker mode in https://github.com/DataDog/dd-trace-php/pull/2523.

Let me know how this works for you!

Kind regards
Florian

**Comment by realFlowControl** [comment]
Hey there 👋 

[`0.99`](https://github.com/DataDog/dd-trace-php/releases/tag/0.99.0) just got released and brings ZTS support for exception, as well as allocation profiling and FrankenPHP support (including worker mode) 🎉 

The tracer also [added support for FrankenPHP](https://github.com/DataDog/dd-trace-php/pull/2602) into this release.

Thanks everyone for your patience 🙏 and in case you find anything, please [open a Github Issue](https://github.com/DataDog/dd-trace-php/issues/new/choose) or reach out to [support](https://www.datadoghq.com/support/).
