### ISSUE TITLE
[BUG] Cannot build OFFLINE

### ISSUE THREAD

**Issue by remicollet** [DataDog/dd-trace-php#2103]
Since version **0.88.0** which uses rust :(

Possible workaround used for some other ext (ex skywalking_agent)
is to vendor the dependencies (using `cargo vendor ...`)

Sadly it doesn't work for this project
```
    Updating git repository `https://github.com/pawelchcki/tarpc.git`
warning: spurious network error (3 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
error: failed to get `tarpc` as a dependency of package `datadog-ipc v0.1.0 (/builddir/build/BUILD/php-pecl-datadog-trace-0.88.0/NTS/libdatadog/ipc)`
```

Other common issues with rust
- big sources (40M instead of 500K)
- big extension (20M instead of 400K)
- slow build (-j flag of make not inherited for cargo build)

For now, this is a blocker for me packaging RPM
Will stay with 0.87.2 until some hack is found.

**Comment by bwoebi** [comment]
Looks like github.com couldn't be resolved for you? I never had that issue...

The extension shouldn't be that big, we're stripping the rust debug information within config.m4, so it should be a reasonable ~6MB (before was ~2MB).

The cargo build indeed does not inherit the `-j` flag, that's something we can fix.

vendoring the dependencies would be possible for the pecl build, if that would help you?

**Comment by remicollet** [comment]
> Looks like github.com couldn't be resolved for you? I never had that issue...

Yes, this issue is about OFFLINE build (so without internet access)

**Comment by bwoebi** [comment]
Sorry, misread the title, we'll investigate whether we can vendor in pecl source.

**Comment by bwoebi** [comment]
Hey @remicollet,

we've just released 0.88.1, which includes tarpc directly vendored in the libdatadog folder. With you setup using crates.io, it now should properly compile.

Please let me know if there are still issues.
Thanks for all the work you are doing packaging our tracer :-)

**Comment by remicollet** [comment]
I confirm version 0.88.1 build fine offline using the vendored solution.

BTW
- build is slow...
- build take lot of disk space (some failure related to "out of disk")
- extension is huge
- packages are huge

**Comment by bilhackmac** [comment]
Yes ext is now really, really huge and not suitable for my docker images.

On the same based docker image :
`debian 12 - ddtrace 0.87.2`
```bash
ls -sh $(php-config --extension-dir)/ddtrace.so
412K /usr/local/lib/php/extensions/no-debug-non-zts-20220829/ddtrace.so
```

`debian 12 - ddtrace 0.88.1`
```bash
ls -sh $(php-config --extension-dir)/ddtrace.so
140M /usr/local/lib/php/extensions/no-debug-non-zts-20220829/ddtrace.so
```

That's 440 times more space !

**Comment by bwoebi** [comment]
Something went wrong and we accidentally enabled rust debug builds by default when installing manually.
Pass to `./configure`: `--disable-ddtrace-rust-debug` to build in release mode, and `--disable-ddtrace-rust-symbols` to strip debug symbols from rust (only). 

It should always use rust release builds from the next version on.

**Comment by bilhackmac** [comment]
It's a lot better, it drop to 6.5M.

Thx
