### ISSUE TITLE
[BUG] ERROR: Required library 'libgcc_s' not found (PHP 8.1.20, Alpine 3.17)

### ISSUE THREAD

**Issue by jaspernbrouwer** [DataDog/dd-trace-php#2109]
### Bug description

Installing dd-trace-php (by following the instructions here: https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/php/?tab=containers#install-the-extension) on Alpine 3.17 fails:

```
$ curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php
ERROR: Required library 'libgcc_s' not found.
```

### PHP version

```
$ php -v
PHP 8.1.20 (cli) (built: Jun 15 2023 04:09:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.20, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.20, Copyright (c), by Zend Technologies
```

### Tracer version

Not available, fails to install.

### Installed extensions

Not relevant at this point.

### OS info

```
$ cat /etc/os-release | grep -E "(NAME)|(VERSION)"
NAME="Alpine Linux"
VERSION_ID=3.17.4
PRETTY_NAME="Alpine Linux v3.17"
```

#### Output of phpinfo() (ddtrace >= 0.47.0)

Not available, fails to install.

#### Output of dd-doctor (ddtrace < 0.47.0)

Not available, fails to install.

### Upgrading info

When installing dd-trace-php 0.87.2, everything is fine :)

**Comment by realFlowControl** [comment]
Hey there 👋 

sorry for the inconvenience. You can run `apk add libgcc` prior to running `datadog-setup.php` to solve this. I'll update the docs in the mean time.

Kind regards
Florian

**Comment by jaspernbrouwer** [comment]
Hey!

Sure. I'm wondering though, what is libcc used for exactly?
And, can I remove it after installing dd-trace-php?

**Comment by bwoebi** [comment]
Hey,

libgcc_s is a dependency of most rust code, providing core functionalities rust needs (related to unwinding, for example).
So no, you can't drop it.
