### ISSUE TITLE
Lot of entries are missing in the .gitattributes files

### ISSUE THREAD

**Issue by VincentLanglet** [DataDog/dd-trace-php#2181]
Hi @bwoebi, @morrisonlevi, @PROFeNoM, @labbati

The following file avoid to download non-necessary files/folder when installing the library with composer
https://github.com/DataDog/dd-trace-php/blob/master/.gitattributes

Currently, I get
<img width="219" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/9052536/2ca83d9d-4925-4d9c-9f49-81df41caa60c">

I assume a lot of them could be added to the gitattributes file too:
- .github/.gitlab folders and github-action-helpers
- docs folder
- example folder
- all `.*` files
- all `.md` files
- docker-composer.yml, phpstan.neon, Makefile, etc
- certainly some folder which I don't know what they are useful for (I currently only use the src one)

Would it be possible to add more entries to the gitattributes file ?
I'm ok doing the PR if needed, but I don't know which folder/files can be also added (other than the one I listed)

**Comment by pierotibou** [comment]
Hello, thanks for reporting this.
The issue auto closed when I merged #2401 as I've taken a first stab at this.
