### ISSUE TITLE
[Feature] Make service name handling consistent with other tracers

### ISSUE THREAD

**Issue by REBELinBLUE** [DataDog/dd-trace-php#2190]
### Describe the feature you'd like

In other tracers, the DD_SERVICE is used as a prefix for services which are automatically created, such as curl, amqp, redis etc.

So with a node JS app with DD_SERVICE=myapi you end up with myapi, myapi-curl, myapi-redis etc in the traces

With PHP you end up with myapi, curl, redis etc which then makes it harder to see which service the traces are from if you have multiple applications using curl, redis etc

### Is your feature request related to a problem?

It means the behaviour of the PHP tracer library is completely different to others

### Describe alternatives you've considered

Use `DD_SERVICE_MAPPING` to refine everything, but this seems suboptimal as all tracers should behave the same way out of the box

**Comment by REBELinBLUE** [comment]
I see now that such a request was closed 2 years ago https://github.com/DataDog/dd-trace-php/issues/1114 because `we are going to change the way we approach service maps and service naming in the near future for all the tracers` but 2 years later they are still like this and it makes the trace UI very messy

**Comment by morrisonlevi** [comment]
I'll send someone who knows more about it this way to comment on the ticket, but I can confirm that there are real and recent efforts to improve this.

**Comment by labbati** [comment]
Hi @REBELinBLUE. The new service experience is going private beta today as it was presented at our [Dash conference](https://www.dashcon.io/).

You can open a ticket for assistance asking for the feature "New Service page and Inferred Services" enabled. Here is a description of how that works https://docs.datadoghq.com/tracing/guide/inferred-service-opt-in/?tab=php and how to enable it.

We are not going to implement prefixes as we are moving away from "service names" to build the service map.

Thanks for your patience.

**Comment by REBELinBLUE** [comment]
Looks great! thanks
