### ISSUE TITLE
[Bug]: PHP Stubs are not working for `ddtrace.stub.php` file

### ISSUE THREAD

**Issue by Ferror** [DataDog/dd-trace-php#2200]
### Bug report

<img width="547" alt="Screenshot 2023-08-09 at 00 30 23" src="https://github.com/DataDog/dd-trace-php/assets/17534504/d330ea69-6ae6-4ba7-9f23-242f0e7e3955">

I'm trying to configure PHP Storm and Stubs for dd-trace and it seems like `uhook.stub.php` & `uhook_attributes.stub.php` files are loaded and interpreted correctly, but the one inside `ddtrace.stub.php` is not.

<img width="741" alt="Screenshot 2023-08-09 at 00 33 16" src="https://github.com/DataDog/dd-trace-php/assets/17534504/7895e528-03fc-4215-9a2b-d5eb6362ac08">

### PHP version

8.2.X

### Tracer or profiler version

master

**Comment by PROFeNoM** [comment]
Hi :wave: Do you still have the issue if you add the stub path (`/Users/ferror/Projects/ferror/dd-trace-php/ext`) to the list located in the 'Include  Path' tab instead of adding it to the Default stubs path?

**Comment by Ferror** [comment]
> Hi 👋 Do you still have the issue if you add the stub path (`/Users/ferror/Projects/ferror/dd-trace-php/ext`) to the list located in the 'Include Path' tab instead of adding it to the Default stubs path?

Hi! It seems like adding it to the `Include Path` solves it, but shouldn't that be the same?

**Comment by PROFeNoM** [comment]
Glad it solved your issue 🙌 However, I'll honestly say that I don't have enough expertise on PhpStorm to know the underlying reason. Looking at the documentation, it seems like the [Default stubs path](https://www.jetbrains.com/help/phpstorm/php.html#advanced-settings-area) is for _Composer package stubs_ and the [Include Path Tab](https://www.jetbrains.com/help/phpstorm/php.html#include-path-tab) for _libraries_ (e.g., dd-trace-php 😃). This would be my explanation 😅
