### ISSUE TITLE
[Bug]: Unable to install on Alpine Linux 3.17 and Debian 12 (Bookworm)

### ISSUE THREAD

**Issue by mlocati** [DataDog/dd-trace-php#2232]
### Bug report

Here's how I'm try to install the ddtrace extension:

- Alpine Linux 3.17
   ```sh
   # In a docker container launched with
   # docker run --rm -it php:8.2-cli-alpine3.17 sh
   apk add $PHPIZE_DEPS curl-dev cargo
   pecl install datadog_trace
   ```
- Debian 12 (Bookworm)
   ```sh
   # In a docker container launched with
   # docker run --rm -it php:8.2-cli-bookworm bash
   apt update
   apt install -qy libcurl4-openssl-dev cargo
   pecl install datadog_trace
   ```

In both cases I have the following error:

```
error: package `nix v0.27.1` cannot be built because it requires rustc 1.65 or newer, while the currently active rustc version is 1.63.0
Either upgrade to rustc 1.65 or newer, or use
cargo update -p nix@0.27.1 --precise ver
where `ver` is the latest version of `nix` supporting rustc 1.63.0
```

[Here's the full build log](https://github.com/DataDog/dd-trace-php/files/12461846/build.log).

### PHP version

PHP 8.2.9 (cli) (built: Aug 17 2023 23:36:34) (NTS)

### Tracer or profiler version

n/a

### Installed extensions

[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
ftp
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
random
readline
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]

### Output of `phpinfo()`

n/a

**Comment by PROFeNoM** [comment]
Hey :wave:

A note was left in the README.md not so long ago (0.88.0) about the fact that cargo **1.64.0+** needs to be installed on the system for installations via pecl and from source. On the error message you provided, I believe that your current version is 1.63.0.

https://github.com/DataDog/dd-trace-php#installation-from-pecl-datadog_trace-or-from-source

Please ensure that cargo's version is at least **1.64.0**, then installation should work as usual 😃

**Comment by mlocati** [comment]
> On the error message you provided, I believe that your current version is 1.63.0.

Nope: Alpine 3.17 comes with cargo 1.64.0 and Debian 12 comes with cargo 1.65.0.

**Comment by bwoebi** [comment]
I see what happened: the pecl .tar.gz does not have its rust dependencies pinned, i.e. the Cargo.lock is missing in the pecl archive.

We'll fix this, thanks for reporting!

**Comment by bwoebi** [comment]
@mlocati For now, for 0.90.0 you'll have to upgrade you cargo version, we'll release 0.91 soon, which will anyway require version 1.71.0.

**Comment by mlocati** [comment]
I'm trying to install the latest `master` version with pecl, to no avail.

Here's what I have:

```
2 source files, building
running: phpize
Configuring for:
PHP Api Version:         20220829
Zend Module Api No:      20220829
Zend Extension Api No:   420220829
m4:config.m4:27: cannot open `./m4/polyfill.m4': No such file or directory
m4:config.m4:28: cannot open `./m4/ax_execinfo.m4': No such file or directory
m4:config.m4:29: cannot open `./m4/threads.m4': No such file or directory
autom4te: error: /usr/bin/m4 failed with exit status: 1
ERROR: `phpize' failed
```

Would you mind if I submit a pull request that highlights this error?

**Comment by bwoebi** [comment]
How exactly did you invoke / download this? Sounds like the `m4` folder is missing for you?

**Comment by morrisonlevi** [comment]
We build our binary releases with the latest Alpine version, as at least currently this is backwards compatible for the relevant Alpine releases. If you want to build from source, you generally need to use the latest Alpine version.

But I do not recommend building from source, for a few reasons:

1. This restricts you to tracing. You cannot enable profiling and security monitoring. This may _eventually_ change, but for now it's required to use `datadog-setup.php`.
2. The `datadog-setup.php` script also has a config mode, which allows you to set ini settings for our products from the CLI.
3. If we add build-time optimizations like link-time optimization, this almost certainly will not work with the toolchains customers install by default, as it has to get compatible LLVM toolchains for C and Rust.

**Comment by mlocati** [comment]
I simply would like to add a test so that the package published on pecl.php.net works.

In order to do so, in the above GitHub Action:

1. I create the `datadog_trace-*.tgz` package using `tooling/bin/pecl-build`
2. store that tgz file
3. restore it in different docker containers
4. install it with `pecl install`

(that's the most way to emulate `pecl install datadog_trace` afaik)

Am I missing something? How do you build the package for https://pecl.php.net/package/datadog_trace ?

**Comment by bwoebi** [comment]
Yes, you are missing the fact that `tooling/bin/pecl-build` expects all the files it uses as arguments:
```
codefiles=""
for file in "$@"; do
  codefiles="${codefiles}"$'\n            <file name="'"${file}"'" role="'"$([[ $file == tests/* ]] && echo test || echo src)"'" '"$([[ $file == */configuration.h ]] && echo ">$configuration_placeholder" || echo "/>")"
done
```

The Makefile contains a `build_pecl_package` target which collects all the files and feeds it to that script, if you want to use that yourself, i.e. `make build_pecl_package`.

By the way, we _do_ have such a test, but it just wasn't failing because at the time of the release, the dependency set was successfully resolved, even without the Cargo.lock:
https://github.com/DataDog/dd-trace-php/blob/8ccf313c6f8a053749f43c05232546ec1865ce9e/.circleci/continue_config.yml#L1697-L1738
