### ISSUE TITLE
[Bug]: laravel.request traces/operations no longer being reported

### ISSUE THREAD

**Issue by Magic-Mayo** [DataDog/dd-trace-php#2252]
### Bug report

After updating to the latest release, 0.91.0, we longer see any laravel.request operations in APM.  At the same time we now see a few different eloquent (eloquent.get, eloquent.update, etc.) operations coming thru where we had never seen them before.  We have a few different apps that are all exhibiting the same behavior and for now we are just pinning to the previous release as we seem to still get laravel.request traces on 0.90.0.

### PHP version

8.1.17,8.0.30

### Tracer or profiler version

0.91.0

### Upgrading from

0.90.0

**Comment by luizeduardocostaml** [comment]
It's happening here too in my applications. It's only recognizing database operations.

**Comment by PROFeNoM** [comment]
Hi 👋

What version of laravel are you using?

**Comment by Magic-Mayo** [comment]
I will go check all the versions we're using across the apps that were affected and report back.  We haven't changed anything with our process on how the datadog trace library is installed and run ( very basically - download the `datadog-setup.php` script from this repo and run it ).  I can also add the env var to a test run and see if any errors come up.

**Comment by Magic-Mayo** [comment]
Versions `9.52.12`, `10.7.1`, `9.37.0` are the versions of the apps I can confirm were affected.  The one that was running `9.37.0` is still not showing traces so I am going to start troubleshooting with that app first.

**Comment by aolol** [comment]
Hi  👋
In our case when setting `DD_TRACE_DEBUG=1` no new errors can be seen, but I notice that the new version created a new service under APM, but with a different icon and the name instead of `group.service` it's just `service`. The original `group.service` name contains the resources and traces before the update and the one with the new service name `service` contains the resources and traces after the update. (0.86.0 => 0.91.0)

**Comment by PROFeNoM** [comment]
Hi everyone :wave:

Thanks for these additional details 💎  There was indeed a mistake introduced in the last release. Could any of you please try out this [artifact](https://output.circle-artifacts.com/output/job/50e8fe33-bfe4-4f4c-bd55-8c76cf88bc8c/artifacts/0/datadog-setup.php) ([CI Job](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/12696/workflows/0a4af5e6-a6c9-496b-8417-38407282a0be/jobs/2864217/artifacts) - [Related PR](https://github.com/DataDog/dd-trace-php/pull/2256))? 

With this, the service name should now be appropriately retrieved if available 😃  Please let me know if it addresses the issue :+1:

FYI, to install the artifact, if you followed the extension installation [doc](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/php/?tab=containers#install-the-extension), simply change the URL of the official installer by the URL of the artifact and you're good to go 👍

**Comment by Magic-Mayo** [comment]
Looks like it works with that artifact!

**Comment by PROFeNoM** [comment]
Hey there :wave: The latest release - [0.91.2](https://github.com/DataDog/dd-trace-php/releases/tag/0.91.2) - includes the fix :+1:
