### ISSUE TITLE
Laravel Eloquent Integration failing to call traced methods on the Model class

### ISSUE THREAD

**Issue by grantcarver** [DataDog/dd-trace-php#226]
I encountered this issue when trying to persist changes to Eloquent models to the DB. It seems the protected method \Illuminate\Database\Eloquent\Model::performUpdate() isn't being found when being called from the traced override in \DDTrace\Integrations\Eloquent\EloquentIntegration.

Likely to be related to the PHP 5.4 support changes in PR #194, I haven't had time to investigate this though.

### Stack Trace
```
BadMethodCallException: Call to undefined method Humble\Models\BillingSubscription::performUpdate()
#105 vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(50): throwBadMethodCallException
#104 vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): forwardCallTo
#103 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1608): __call
#102 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(0): call_user_func_array
#101 vendor/datadog/dd-trace/src/DDTrace/Util/TryCatchFinally.php(31): executePublicMethod
#100 vendor/datadog/dd-trace/src/DDTrace/Integrations/Eloquent/EloquentIntegration.php(59): DDTrace\Integrations\Eloquent\{closure}
#99 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(644): save
```

### Environment
 - PHP 7.2.11
 - Laravel 5.7.19
 - dd-trace-php 0.9.0

**Comment by labbati** [comment]
Hi @grantcarver thanks for reporting this and I am sorry you experienced this issue.
We just released version [0.9.1](https://github.com/DataDog/dd-trace-php/releases/tag/0.9.1) which brings a fix for this bug.
If you have a chance to test it and confirm it works for you then it would be great.

**Comment by grantcarver** [comment]
Thanks @labbati I can confirm that using a closure has enabled the calling of the protected methods again.

**Comment by labbati** [comment]
Hi @grantcarver happy to hear that. I am closing this issue then as fixed. Thank you again for taking the time to provide as with the detailed info.
