### ISSUE TITLE
Support for default tags w/ Laravel Provider?

### ISSUE THREAD

**Issue by nampas** [DataDog/dd-trace-php#228]
Is there support for default tags? With the node tracer, for example, you can pass in a `tags` property into the initialization function. Here there is no initialization function, just the environment variables. We have an `env` tag that needs to get added to all metrics.
I do see documentation on initializing a tracer with custom tags but the Laravel 5 integration provider creates its own tracer. So I don't have a handle on that. I also considered writing another ServiceProvider to pull the GlobalTracer created by the DD ServiceProvider and update its config, but theres no way of fetching the configs from the tracer object.

**Comment by SammyK** [comment]
Hey @nampas! Although the tracer does support default tags that propagate to all the spans from the constructor...

```php
$tags = ['env' => 'foo'];
$tracer = new Tracer(null, null, ['global_tags' => $tags]);
```

...there isn't a way to inject those into the Laravel provider. But I'll add this as a feature request. Thanks for submitting the issue! :)

**Comment by labbati** [comment]
Hey @nampas, an update after the 0.12.0 release. We added support for global tags through configuration env variable: `DD_TRACE_GLOBAL_TAGS=key1:value1,key2:value2`.
This approach is the recommended approach as the direct configuration of the tracer will soon to be deprecated.
A bonus point of configuration through `DD_TRACE_GLOBAL_TAGS` is also that you do not need to depend on our library in composer.

Closing the issue now, feel free to re-open if you need further info and thanks for you question.

**Comment by nampas** [comment]
Thanks for the update!
