### ISSUE TITLE
[Bug]: Failed connecting to the sidecar: Connection refused (os error 111)

### ISSUE THREAD

**Issue by remicollet** [DataDog/dd-trace-php#2285]
### Bug report

Trying to build RPM of new version 0.92.0 I encounter tons of test failures with this message, ex

```
========DIFF========
001+ Failed connecting to the sidecar: Connection refused (os error 111)
002+ Failed connecting to the sidecar: Connection refused (os error 111)
     Traced header.
========DONE========
FAIL Ensure that if a user adds an internal function we already trace to traced internal functions list that it doesn't misbehave [tests/ext/traced_internal_functions_override_01.phpt] 

```

This may be related to multiple build running simultaneously.

How to debug this ?
Is this a network port ?
Is it possible to set this port (to use a different one for each build) ?

### PHP version

N/A

### Tracer or profiler version

0.92.0

**Comment by bwoebi** [comment]
It's an unix socket in /dev/shm this is connecting to, at a well-known location. It's not possible to set that port.
To isolate it by testsuite, you could create a new mount namespace per build, then mount a new tmpfs to /dev/shm.

I.e. start your process prefixed by `unshare -m`, then within: `mount -n -t tmpfs tmpfs /dev/shm`.

The only time that should happen, is if the sidecar/datadog-ipc-helper process crashes.

As to how to debug: Checking for core dumps, checking lsof of the sidecar process if it still runs. Setting `DD_SPAWN_WORKER_USE_EXEC=1` in env, then running in gdb with `set follow-fork-mode child`.

I'm surprised at the failures, also the #2286 one. Given that we run our testsuite on CentOS 7 as well.

**Comment by remicollet** [comment]
Does it make sense to use the same socket, and the same helper for all PHP stacked installed?

`#define DD_TRACE_CIRCUIT_BREAKER_SHMEM_KEY ("/dd_trace_shmem_" PHP_DDTRACE_VERSION)`

It's quite usual to run various PHP stacks simultaneously 
Using some build related suffix may help

**Comment by bwoebi** [comment]
Yes, because the socket and helper are independent of the PHP version, they're just tied to their own exposed ABI, which is consumed by the ddtrace extensions, which is why they are just tied to the extension versioning.

If you encounter issues here, it means that probably something is broken.

**Comment by remicollet** [comment]
> If you encounter issues here, it means that probably something is broken.

Yes, and this is the reason why I open this report ;)

I will make it unique per build using something like `/dev/shm/dd_trace_shmem_0.92.0_fc37_php_8.2.11`

**Comment by bwoebi** [comment]
@remicollet This is the limiter functionality (which is just a share memory file), https://github.com/DataDog/libdatadog/blob/f55b72072fbaadec7692d7b85ec8a26acbc0e841/sidecar/src/setup/unix.rs#L89 here's the sidecar socket path.

**Comment by remicollet** [comment]
Simple way, "disable test suite" on my side  and rely only on your CI
