### ISSUE TITLE
[Bug]: PHPRedis infinite flushing loop

### ISSUE THREAD

**Issue by B-Galati** [DataDog/dd-trace-php#2311]
### Bug report

Hello,

When PHPRedis integration is enabled it keeps flushing while my worker is totally idled.

For example:

```
$ php bin/console -n messenger:consume -q events --time-limit=240 --memory-limit=128M
[2023-10-11T09:53:24+00:00] [ddtrace] [debug] - Attempting integrations load; note: some integrations are only loaded on first usage
[2023-10-11T09:53:24+00:00] [ddtrace] [debug] - Loaded integration web
[2023-10-11T09:53:25+00:00] [ddtrace] [debug] - Loaded integration DDTrace\Integrations\Logs\LogsIntegration
[2023-10-11T09:53:25+00:00] [ddtrace] [debug] - Loaded integration DDTrace\Integrations\PHPRedis\PHPRedisIntegration
Notifying profiler of finished local root span.
Flushing trace of size 1 to send-queue for http://datadog-agent.infra:8126
Notifying profiler of finished local root span.
Flushing trace of size 1 to send-queue for http://datadog-agent.infra:8126
Notifying profiler of finished local root span.
Flushing trace of size 1 to send-queue for http://datadog-agent.infra:8126
Notifying profiler of finished local root span.
Flushing trace of size 1 to send-queue for http://datadog-agent.infra:8126
```

The message `Flushing trace...` keeps appearing every 1 second I would say.

Is it by design or something is wrong?

### PHP version

8.2

### Tracer or profiler version

0.92.2

**Comment by B-Galati** [comment]
@PROFeNoM thank you but I don't understand. I am using Symfony, not Laravel and there are no integrations that relate to these Frameworks.

**Comment by PROFeNoM** [comment]
All my apologies, I read too quickly and overlooked the fact that you weren't using Laravel Horizon, but symfony messenger.

I'm not familiar with Symfony Messenger, but looking at their source code, it indeed seems like the consumer [waits](https://github.com/symfony/messenger/blob/641bde9896f8f4399426a65a0925c09d05519bfa/Command/ConsumeMessagesCommand.php#L82) 1s before checking for new messages, as you observed.

Assuming you are using a redis receiver, I would then indeed believe that the current behavior is expected.

**Comment by B-Galati** [comment]
We are using RabbitMQ but that's not impossible it's calling Redis for some reasons.

It may be because the container is restarted between each messages but I need to dig further.

Not a bug with Datadog in any case!

Thanks!
