### ISSUE TITLE
[Bug]: 4xx reporting as errors in v 0.92.2

### ISSUE THREAD

**Issue by s1rc** [DataDog/dd-trace-php#2336]
### Bug report

Possibly a regression of https://github.com/DataDog/dd-trace-php/issues/2051 4xx status codes are being shown as errors. 

I have tried `0.87.1` and 4xx are reported correctly. If I have time I will try to determine which release could be the cause. From my testing so far I believe it's < `0.92.0`.

### PHP version

8.2.11

### Tracer or profiler version

0.92.2

**Comment by s1rc** [comment]
4xx started reporting as errors in `0.88.0` it seems.

**Comment by PROFeNoM** [comment]
Do you have any more information/a screenshot of such traces? Testing with Laravel, I tried with 404s and 405s, but I couldn't reproduce the issue.

Does it happen with all 4xx requests?

**Comment by s1rc** [comment]
I think we have narrowed the issue to another cause. There is an authentication exception thrown that is supposed to be ignored from a dependency. 

We will have to dig into why dd-trace is not ignoring it, but I believe this issue was a false alarm. Apologies.

**Comment by PROFeNoM** [comment]
That's alright :smiley: Thank you for keeping us updated!
