### ISSUE TITLE
[Bug]: Growing asset size

### ISSUE THREAD

**Issue by greg0ire** [DataDog/dd-trace-php#2396]
### Bug report

It looks like the assets in the release are getting bigger and bigger.
In https://github.com/DataDog/dd-trace-php/releases/tag/0.85.0, they're 30Mb to 60Mb. In https://github.com/DataDog/dd-trace-php/releases/tag/0.94.0, there are 100 extra Mb

Looking at what's on disk after installing a package, I can see this:

```
/opt/datadog-php/extensions:
total 86M
-rwxr-xr-x 1 root root 2.5M Apr  5  2023 ddtrace-20151012-alpine.so
-rwxr-xr-x 1 root root 2.1M Apr  5  2023 ddtrace-20151012-debug.so
-rwxr-xr-x 1 root root 2.8M Apr  5  2023 ddtrace-20151012-zts.so
-rwxr-xr-x 1 root root 3.0M Apr  5  2023 ddtrace-20151012.so
-rwxr-xr-x 1 root root 2.5M Apr  5  2023 ddtrace-20160303-alpine.so
-rwxr-xr-x 1 root root 2.2M Apr  5  2023 ddtrace-20160303-debug.so
-rwxr-xr-x 1 root root 2.8M Apr  5  2023 ddtrace-20160303-zts.so
-rwxr-xr-x 1 root root 3.0M Apr  5  2023 ddtrace-20160303.so
-rwxr-xr-x 1 root root 2.5M Apr  5  2023 ddtrace-20170718-alpine.so
-rwxr-xr-x 1 root root 2.2M Apr  5  2023 ddtrace-20170718-debug.so
-rwxr-xr-x 1 root root 2.8M Apr  5  2023 ddtrace-20170718-zts.so
-rwxr-xr-x 1 root root 3.0M Apr  5  2023 ddtrace-20170718.so
-rwxr-xr-x 1 root root 2.5M Apr  5  2023 ddtrace-20180731-alpine.so
-rwxr-xr-x 1 root root 2.2M Apr  5  2023 ddtrace-20180731-debug.so
-rwxr-xr-x 1 root root 2.9M Apr  5  2023 ddtrace-20180731-zts.so
-rwxr-xr-x 1 root root 3.1M Apr  5  2023 ddtrace-20180731.so
-rwxr-xr-x 1 root root 2.6M Apr  5  2023 ddtrace-20190902-alpine.so
-rwxr-xr-x 1 root root 2.3M Apr  5  2023 ddtrace-20190902-debug.so
-rwxr-xr-x 1 root root 2.9M Apr  5  2023 ddtrace-20190902-zts.so
-rwxr-xr-x 1 root root 3.1M Apr  5  2023 ddtrace-20190902.so
-rwxr-xr-x 1 root root 2.6M Apr  5  2023 ddtrace-20200930-alpine.so
-rwxr-xr-x 1 root root 2.3M Apr  5  2023 ddtrace-20200930-debug.so
-rwxr-xr-x 1 root root 3.0M Apr  5  2023 ddtrace-20200930-zts.so
-rwxr-xr-x 1 root root 3.2M Apr  5  2023 ddtrace-20200930.so
-rwxr-xr-x 1 root root 2.7M Apr  5  2023 ddtrace-20210902-alpine.so
-rwxr-xr-x 1 root root 2.4M Apr  5  2023 ddtrace-20210902-debug.so
-rwxr-xr-x 1 root root 3.1M Apr  5  2023 ddtrace-20210902-zts.so
-rwxr-xr-x 1 root root 3.3M Apr  5  2023 ddtrace-20210902.so
-rwxr-xr-x 1 root root 2.7M Apr  5  2023 ddtrace-20220829-alpine.so
-rwxr-xr-x 1 root root 2.4M Apr  5  2023 ddtrace-20220829-debug.so
-rwxr-xr-x 1 root root 3.2M Apr  5  2023 ddtrace-20220829-zts.so
-rwxr-xr-x 1 root root 3.4M Apr  5  2023 ddtrace-20220829.so
```

What are all these files and do they actually all need to end up in the assets?

### PHP version

8.2.12

### Tracer or profiler version

0.94.0

**Comment by bwoebi** [comment]
Hey @greg0ire,

these files are the individual compiled artifacts for nts, debug, zts and alpine+nts on PHP 7.0 to 8.3.
So, many versions plus many targets equals many megabytes :-/

We also recently added rust to our codebase, which led to the files getting bigger.

You generally just need exactly one of all these files, but we're providing them all for all the different configurations of PHP existing.

**Comment by greg0ire** [comment]
Ok , we've found a workaround so feel free to close this, unless you think it might be worth working on producing several distinct packages, for instance one per PHP version

**Comment by morrisonlevi** [comment]
Can you speak a bit more directly to what your concern was? The `datadog-setup.php` script will download a tar package based on the platform it's on, and install the relevant pieces, and not keep the downloaded files around. So the final size on disk contains only what it needs. Now, in the interim, it does download and extract an archive that is growing over time, so there's definitely room for improvement. But any improvements should be made with more focused goals, so that's why I'm wondering what your concern was more specifically.

**Comment by greg0ire** [comment]
TIL about `datadog-setup.php`. We've written our install script long before that installer was documented in https://github.com/DataDog/documentation/commit/d3a4d08207b8c1be5d905e9c28abc5104ce90695, so I guess that is the root cause. We should work on switching to it. Closing, then.
