### ISSUE TITLE
[Question] Add tag to parent request root span

### ISSUE THREAD

**Issue by Julian-Louis** [DataDog/dd-trace-php#2410]
Hello,
I have a question about tracing with `dd-trace-php`, I have a PHP service (Service 1) calling another PHP service (Service 2), both are traced with Datadog. Here is an example trace:
<img width="1047" alt="Screenshot 2023-12-06 at 10 20 59" src="https://github.com/DataDog/dd-trace-php/assets/86676740/53113b3c-ce24-45de-bb88-1cb326ca25b8">

When service 1 send a request to service 2, service 2 is adding a tag to his root span (`symfony.request`):
<img width="408" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/86676740/7d28dc51-7dee-4134-b9f0-65f219600e3c">

My goal is to add the tag to the parent trace (`symfony.request` of Service 1) from service 2. Do you think this is possible? If so, could you guide me on how to achieve it?

**Comment by PROFeNoM** [comment]
Hey @Julian-Louis!

One possible solution that comes to my mind is to return the `user_id` as a response to the `curl_exec` call made from service1 to service2. Although this approach may seem a bit crude, it could effectively enable you to retrieve the `user_id` within the context of service1 and set it on service1's `symfony.request` root span.

(For my curiosity + context) Why do you need to set these tags on the trace root span specifically? What use case are you trying to achieve? 😃 Maybe this would foster another idea in my mind

**Comment by Julian-Louis** [comment]
Thank you for your answer @PROFeNoM,
> One possible solution that comes to my mind is to return the user_id as a response to the curl_exec call made from service1 to service2. Although this approach may seem a bit crude, it could effectively enable you to retrieve the user_id within the context of service1 and set it on service1's symfony.request root span.

I was also thinking about that, but it seems easier to add the tag from the service 2 directly (instead of doing it on all project that depends on service 2).



Service 2 is an authentication service, and for debugging purposes, I would like to be able to filter the parent request traces by `user_id`.

And I was thinking about two solutions:
- Add the tag in each service that depends on service 2
- Add a tag directly from service 2 to the parent trace

**Comment by Julian-Louis** [comment]
Hello, thank you for your answer !
Now I understand why that's not possible.

I will try contacting the support team, thank you !
