### ISSUE TITLE
[Bug]: seeing host-unparsable-host and "CURL request failure" in apm in curl_multi_exec context

### ISSUE THREAD

**Issue by skranz-codi** [DataDog/dd-trace-php#2444]
### Bug report

I was waiting for the fix for https://github.com/DataDog/dd-trace-php/issues/1156 since some time and was happy to try out 0.95 and later 0.96. while the problem described in https://github.com/DataDog/dd-trace-php/issues/1156 looks fixed now, i see the following in dd-apm now even if the curl calls work fine like before as far as i can tell:
<img width="955" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/d7587f8d-485e-448c-b1a6-b5ccc8369e1b">
going back to pre 0.91.2 (the version i used before) brings back the old behavior (no curl_exec spans but also no errors in dd).
the guzzle transfer span right before the curl multi spans looks good, btw (no problem with the hostname):
<img width="369" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/7957c41d-ac5f-4db0-aca2-4ff117de78f6">
<img width="258" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/5f10f9be-727d-492f-b0d1-eff3ee93db55">
the actual curl request url looks something like that: https://foo.bar.eu:8443/foo/bar/baz .
this code runs locally inside a docker container via docker-compose with configured extra-hosts like that: 
foo.bar.eu: 172.xxx.xxx.xxx

sadly i was not able to find where the ddtrace code brakes while debugging this issue. i did not find any other issue regarding this topic so i created this issue. do you need more info from my side?

thx in advance!

### PHP version

8.1.21

### Tracer or profiler version

0.95.0 and 0.96.0

### Installed extensions

[PHP Modules]
apcu
bcmath
Core
ctype
curl
date
ddappsec
ddtrace
dom
fileinfo
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
pdo_sqlsrv
Phar
posix
readline
redis
Reflection
session
SimpleXML
sodium
SPL
sqlite3
sqlsrv
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
ddappsec
ddtrace

### Output of `phpinfo()`

<img width="885" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/7d9cc87f-2e60-4822-acad-b95a651a7406">
<img width="853" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/e492e45b-7e73-4e8f-ac9a-45b79413527f">
<img width="878" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/b8816842-ac90-45c5-a354-03c060e93d10">
<img width="855" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/0ac3f4c6-6711-4760-9945-8f398d4a6dfb">
<img width="854" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/93f50564-a9a4-4e73-bb30-2f5d04c4d429">
<img width="856" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/13435877-b1e3-42b8-9ea5-909d0bcb9f14">
<img width="863" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/29d30a56-dc3a-414f-9eda-5a7f0aaa328d">

### Upgrading from

0.91.2

**Comment by PROFeNoM** [comment]
Hi @skranz-codi !

After doing some testing on my side, _using _guzzle, I've been able to reproduce your issue in two ways:
- Curl commands that would fail (SSL or hostname-related, for instance)
- Redirections

In these previous cases, I'd have what I call "dummy `curl_exec` spans", most notably with `host-unparsable-host`. I tried [some changes](https://github.com/DataDog/dd-trace-php/commit/e63474a1e1f06acfc71c0037ef91b01ec351dfbc) in a branch of mine that aims to address these cases.

Could please try out this [artifact](https://output.circle-artifacts.com/output/job/c24b7df9-7ac3-41ca-9bac-67378e3c43ee/artifacts/0/datadog-setup.php) ([CI job](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/13975/workflows/fe442fd0-8a61-4689-ae55-ebaa52ad8287/jobs/3413457/artifacts))? To use the artifact, you can simply replace the datadog-setup.php link you are using when [installing the tracer](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/php/) with the one from the artifact.

**Comment by skranz-codi** [comment]
hi @PROFeNoM and thx for the response!
I tried your version, but the issue sadly is still there:
<img width="410" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/5a3ac7dc-92de-4e64-8f5c-7e5c697c8e6f">
i checked the build pipe and i am quite sure i am now using your version when installing the extension:
<img width="1092" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/adb3898d-d107-427e-bef6-d998cd9c1c29">

One thing I never fully understood: I have to install the extension AND add the dependency via composer ("datadog/dd-trace": "0.96.0"), right? While testing your version i still have the 0.96.0 composer lib installed. Is this ok?

Thx again for your effort!

**Comment by PROFeNoM** [comment]
Hi @skranz-codi !

Alright, I'll try to reproduce it further. Can I please know _how_ are you making these requests (the essence of the code that is running)? What I was trying was to do some `getAsync` and wait for them (as you may see in this [draft](https://github.com/DataDog/dd-trace-php/compare/alex/issue/gh2444#diff-fcb15d8e0722e8ae43cbf1f57c75ce4d6fa30698ddfb449de650d0486cef67c3) test file).

If you have this information, I'd be interested to know what status code you expect from these requests (so that I can try to reproduce it with the same type of request).

Thanks

>  I have to install the extension AND add the dependency via composer ("datadog/dd-trace": "0.96.0"), right? While testing your version i still have the 0.96.0 composer lib installed. 

You don't _have to_. Only the extension is required.

>  Is this ok?

It shouldn't be a problem; it isn't required for common use cases.

**Comment by skranz-codi** [comment]
Hi @PROFeNoM ,
i try to list all the pieces from the "outside" to the "inside":

```php
$results = Utils::unwrap([ 
'foo' => $fooService->getFoo($id),
'bar' => $barService->getBar($id),
'baz' => $bazService->getBaz($id),
]);
```

inside those service calls:
```php
return $this->client->getAsync('/foo/bar/baz' , $options + ['http_errors' => false,]);
```

this is how the client is build:
```php
$guzzleClient = new HttpClient([
'base_uri' => $config->get('foo.client.base_uri'),
'auth' => [ 
$config->get('foo.client.auth.username'), 
$config->get('foo.client.auth.password')
],
'verify' => $config->get('foo.client.verify'),
'timeout' => $config->get('foo.client.timeout'),
'allow_redirects' => false,
'handler' => $handlerStack,
'headers' => [ 
'Accept' => 'application/json', 
'Accept-Encoding' => 'gzip, deflate', 
'sap-statistics' => $this->getFooHeaderValue($config),
],
]);
```

and here the handlerstack:
```php
$this->app->singleton(HttpFooHandlerStack::class, static function (Application $app) {
    $handlerStack = HttpFooHandlerStack::create($app->make(CurlMultiHandler::class));
    $handlerStack->push($app->make(FooErrorHandlingMiddleware::class)->__invoke());
    $handlerStack->before('http_errors', $app->make(HttpLoggingMiddleware::class)->__invoke());
    return $handlerStack;
});
```

the middlewares look kind of like this:

```php
public function __invoke(): callable{
    return function (callable $handler) {
        return function (RequestInterface $request, array $options) use ($handler) {
            return $handler($request, $options)->then($this->handleResponse($request));
        };
    }
;}

 private function handleResponse(RequestInterface $request): callable
{
        return function (ResponseInterface $response) use ($request) {
            ...
        }
}
```

and

```php
public function __invoke(){
    return function (callable $handler) {
        return function (RequestInterface $request, array $options) use ($handler) {
            $id = Uuid::uuid4()->toString();
            $request = $this->handleRequest($request, $id);
            $start = microtime(true);
            return $this
                ->getPromise($request, $options, $handler)
                ->then(
                    $this->handleResponse($request, $start, $id),
                    $this->handleRejection($id)
                );
        };
    };
}

private function getPromise(RequestInterface $request, array $options, callable $next): PromiseInterface
{
        return $next($request, $options);
}

private function handleRequest(RequestInterface $request, string $guzzleRequestId): RequestInterface
{
...
}

private function handleResponse(RequestInterface $request, float $start, string $guzzleRequestId)
{
        return function (ResponseInterface $response) use ($request, $start, $guzzleRequestId) {
            return $response;
        };
}
```

While checking this out i made some more tests and found out, that leaving out the second and third call from the unwrap, the error is gone and the first request will be displayed correctly in the dd ui:
```php
$results = Utils::unwrap([ 
'foo' => $fooService->getFoo($id),
]);
```
<img width="349" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/7949a2ae-a791-46cd-a19e-497d69d07c1f">


Hope this helps. Let me know if i can give you more infos.

**Comment by PROFeNoM** [comment]
Hi @skranz-codi!

Thanks for your fantastic description.

This time I've made another [artifact](https://output.circle-artifacts.com/output/job/4dbcb911-dc65-4c9b-be4c-bef2c4cb0eca/artifacts/0/datadog-setup.php) ([CI Job](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/14033/workflows/1226bb05-6fa5-416c-b5b1-cc7c857f9425/jobs/3438848/artifacts) - [Branch](https://github.com/DataDog/dd-trace-php/compare/master...alex/tmp/debug2444)) that should cover some additional cases, especially when considering non-erroneous requests (which is your case) 🤞

**Comment by skranz-codi** [comment]
i only had 5 minutes but this looks really promising:
<img width="433" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/129496616/98614607-9457-4214-a2eb-4727823c7efa">
thx so far.

**Comment by PROFeNoM** [comment]
Hey @skranz-codi :wave:

FYI, the [0.97.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.97.0) release was made yesterday, which includes the PR #2460 :)

**Comment by skranz-codi** [comment]
hi, i am already testing it and it still looks very good 👍 thx again for the fix!
