### ISSUE TITLE
[Bug]: default value for sample_rate is wrong

### ISSUE THREAD

**Issue by B-Galati** [DataDog/dd-trace-php#2476]
### Bug report

Hi there,

I was wondering why we were not ingesting all the traces and I noticed that our default values are the following:

```
$ php-fpm -i | grep -i sampl
    "sample_rate": -1,
    "sampling_rules": [],
    "priority_sampling_enabled": true,
```

While the [doc](https://docs.datadoghq.com/tracing/trace_collection/library_config/php/) mentioned that `sample_rate` default value is `1`.

Here is our customized config just in case:

```
DD_DBM_PROPAGATION_MODE=full
DD_PHP_TRACER_VERSION=0.96.0
DD_LOGS_INJECTION=false
DD_ENV=prod
DD_VERSION=2024.01.17.0
DD_TRACE_ENABLED=true
DD_TRACE_AGENT_PORT=****
DD_SERVICE_MAPPING=curl:aa/curl,guzzle:aa/guzzle,pdo:aa/pdo,phpredis:aa/phpredis
DD_AGENT_HOST=*****
DD_TAGS=product:aa,other:bb
DD_SERVICE=service_name
DD_INSTRUMENTATION_TELEMETRY_ENABLED=false
```

Is it a problem with the doc?

### PHP version

8.2.14

### Tracer or profiler version

0.96.0

**Comment by bwoebi** [comment]
Hey @B-Galati,

Yes, good call, we need to indeed update our docs here - `-1` means that a rate is calculated by the agent, e.g. if a MAX_TRACES_PER_SECOND is configured on the agent.

This changed 3 versions ago.

**Comment by B-Galati** [comment]
Thanks! Do you have a doc that explains all the different values?

Also curious to know how it interacts with the priority sampling?

Do you want to keep the issue opened until the doc is updated?

**Comment by bwoebi** [comment]
There aren't multiple values, just -1 and 0-1. I've done a PR to our docs now. Thanks for reporting :-)

**Comment by B-Galati** [comment]
Thanks 👍
