### ISSUE TITLE
[Bug]: Nested exceptions are not recorded in `Integration::setError()`

### ISSUE THREAD

**Issue by alex-patterson-webdev** [DataDog/dd-trace-php#2498]
### Bug report

Our application often catches and re-throws exceptions; recasting them with generic messages. The `$previous` argument is passed so that we maintain a chain of thrown exceptions. 

For example:

    try {
       $nestedException = new NestedException('A very detailed exception message');

        throw new CustomException('An error message', 456, $nestedException);
    } catch (\Throwable $e) {
        throw new \Exception('This is a generic exception message', 123, $e);
    }

The method `DDTrace\Integrations\Integration::setError()` currently records exception information in the following way.

    public function setError(SpanData $span, $exception)
    {
        $span->meta[Tag::ERROR_MSG] = $exception->getMessage();
        $span->meta[Tag::ERROR_TYPE] = get_class($exception);
        $span->meta[Tag::ERROR_STACK] = $exception->getTraceAsString();
    }

This logic prevents the nested exceptions from being recorded as there is no check of `$exception->getPrevious()`. The result of this is that only the 'parent' exception information is recorded in DataDog, meaning very generic and unhelpful error messages or traces. The real exception information of `$nestedException` is lost/not available.

To ensure there is specific recording of the `$nestedException`, we would need to modify `setError()` to recursively check `$e->getPrevious()` and build a chain of the thrown exceptions. If you could advise on how this data could be structured on `$span` and I can create a PR.

We are using the `SymfonyIntegration` (Symfony v5) if that is relevant.

### PHP version

8.1.0

### Tracer or profiler version

0.97.0

**Comment by PROFeNoM** [comment]
Hey @alex-patterson-webdev :wave:

Thanks for this very clear description! There is an `exception` span property on which we can assign instances of `Throwable`, and the [serialization process](https://github.com/DataDog/dd-trace-php/blob/fecdcfc44bd8c2c86b63e03e1c4775f5146e83e3/ext/serializer.c#L302-L340) should be able to handle nested exceptions (credits to @bwoebi) recursively.

> If you could advise on how this data could be structured on $span and I can create a PR.

I've made a [branch](https://github.com/DataDog/dd-trace-php/compare/master...alex/issue/gh2498), but I'll have to modify the tests to accommodate this change. I will save you from these cumbersome tasks, but it's up to you ;-)

**Comment by alex-patterson-webdev** [comment]
@PROFeNoM That's great it's already supported as part of the exception span! I think you would be best suited to address the unit tests; thanks so much for looking at this so quickly 👍🏻
