### ISSUE TITLE
Please clarify PHP dependency

### ISSUE THREAD

**Issue by remicollet** [DataDog/dd-trace-php#250]
PECL changelog states:

> - Initial C extension PHP 5.4 support #205 

And build against 7.3 seems ok.

But, in package.xml, still have
```
  <php>
    <min>5.6</min>
    <max>7.2.99</max>
   </php>

```

**Comment by SammyK** [comment]
Thanks for bringing this up @remicollet! Since we don't support PHP 5.5 yet, we're keeping the min PHP version PHP 5.6. And we don't have any automated tests in place for PHP 7.3 yet, but it's on the TODO list. As soon as we have that set up we'll increase the max PHP version to 7.3. :)
