### ISSUE TITLE
[Feature] CURL multi exec integration is lacking data in the APM view

### ISSUE THREAD

**Issue by B-Galati** [DataDog/dd-trace-php#2504]
### Describe the feature you'd like

Hi!

The new `curl_multi_exec` is great but it lacks some data to be 100% correct like `curl_exec`.

In short, if we go to the APM view, with `operations:curl_multi_exec` we can only see something like this:

![image](https://github.com/DataDog/dd-trace-php/assets/895123/18864ad0-24ec-405e-a038-20517c3e6b49)

And if we go to the APM with `operations:curl_exec` we cannot see any calls where the parent span is `operations:curl_multi_exec`.

**Comment by bwoebi** [comment]
I think I understand the issue:
- the service page you are looking at is showing entry spans for a specific service.
- curl_exec and curl_multi_exec have the same service (curl)
- curl_multi_exec spawns child spans within curl_exec, which are not root spans and thus not shown in the resources page

I'm not sure how to solve that and will inquire internally. Thanks for reporting!

**Comment by bwoebi** [comment]
@B-Galati We've fixed it and will be part of the next release.

In the meantime, you could experiment with https://docs.datadoghq.com/tracing/guide/inferred-service-opt-in/?tab=php, in particular the following **agent** setting: `DD_APM_COMPUTE_STATS_BY_SPAN_KIND=true`. I haven't tried myself, but that should fix it.

**Comment by B-Galati** [comment]
Thanks I will let you know 👍

**Comment by B-Galati** [comment]
Just to be clear: do I need these settings with the new release?

**Comment by bwoebi** [comment]
No, you don't.

Alternatively you could just use the artifact from current master: https://output.circle-artifacts.com/output/job/d2ceb793-505f-4302-a30c-8c255c1d7fd5/artifacts/0/datadog-setup.php
