### ISSUE TITLE
Add feature to validate releases for PECL

### ISSUE THREAD

**Issue by SammyK** [DataDog/dd-trace-php#251]
In order to avoid issues like  #249 and #248 in the future, we should add a script to check these things in the CI builds. I'm open to ideas as to how we accomplish this. :)

**Comment by remicollet** [comment]
Perhaps you can give a look to 
https://github.com/krakjoe/sandbox/blob/release/checkpackage.sh

**Comment by morrisonlevi** [comment]
We have improved our lint checks starting in release 0.48.0, and run tests using the pecl package too. I think we're good now. Good work, Sammy.
