### ISSUE TITLE
[Bug]: PDO/PHPRedis client split by instance inconsistency

### ISSUE THREAD

**Issue by TheLevti** [DataDog/dd-trace-php#2519]
# PDO/PHPRedis client split by instance inconsistency

The change https://github.com/DataDog/dd-trace-php/blob/346de4d66c7597ef7dc57cff7ceff8dc931c53b0/src/Integrations/Integrations/PDO/PDOIntegration.php#L319, which has been introduced in https://github.com/DataDog/dd-trace-php/pull/1498 is not behaving like expected by the [documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/php/) in conjunction with the env variable `DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED` being set to `true`.

Other split by instance integrations like for example phpredis, ignore this flattening rule.

## Environment

php: 8.2.15
dd-trace-php: 0.97.0

## Current behaviour

Call to a database host datadoghq.com from the service `my-test` has the service name `pdo-datadoghq.com` instead of the default service name of `pdo` or flattened service name `my-test-datadoghq.com` (when `DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED` is set to true).

## Expected behaviour

Independently of `DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED`, the service name is `pdo-datadoghq.com`.

## Discussion points

- What is the expected impact of `DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED` on the split by instance feature on multiple integrations?
  1. Should `DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED` **have no effect** on the split by instance feature? Then the change introduced in https://github.com/DataDog/dd-trace-php/pull/1498 is not correct. Instead of a concatenation, it should overwrite the service name with the original integration name, same as done for the phpredis split by instance.
  2. Should `DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED` **have an effect** on the splitting of instances, then the phpredis integration at line https://github.com/DataDog/dd-trace-php/blob/master/src/Integrations/Integrations/PHPRedis/PHPRedisIntegration.php#L351, which has been introduced with https://github.com/DataDog/dd-trace-php/pull/2163, is not correct and needs to be fixed instead, by doing a concatenation instead of overwriting.
- Documentation for `DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED` is missing on the datadog docs. Only Ruby has mentioned this feature even though almost all SDKs have implemented it.

## Impact

Currently this causes misalignment across deployed services as for phpredis we are getting a global phpredis service, split by instances, but not for PDO even though we configured it to split by instance. As a result each deployed service has its own split by instance for pdo, which is kind of useless at the moment. On the other hand I see a use case for splitting by instance PER deployed service where we have multiple databases/redis instances, which is in favor of fixing the phpredis integration instead.

**Comment by TheLevti** [comment]
Currently this causes misalignment across deployed services as for phpredis we are able to monitor it's behaviour across deployed services per instance, but not for PDO even though we configured it to split by instance. As a result each deployed service has its own split.

**Comment by bwoebi** [comment]
Thanks for the report, this inconsistent behaviour indeed makes no sense.
We will release this tomorrow in 0.98.0.
