### ISSUE TITLE
[Bug]: ddtrace overrides php error log permissions

### ISSUE THREAD

**Issue by klj613** [DataDog/dd-trace-php#2563]
### Bug report

I currently set `php_admin_value[error_log] = /path/to/error.log` in my FPM configuration and have the permissions on the file as `0600`.

I've noticed when ddtrace logs to the php error log file it changes the permissions to 0666 unexpectedly. Upon a quick look I have found https://github.com/DataDog/dd-trace-php/pull/2528/files and unsure why permissions 0666 is required.

### PHP version

8.0.30

### Tracer or profiler version

0.98.1

**Comment by bwoebi** [comment]
Hey @klj613,

It's true - the tracer wants to create the error log with 666 if it doesn't exist yet. We need to handle the case where the file already exists.

Thanks for the report, we'll fix that.
