### ISSUE TITLE
[Bug]: Standalone null Return Type for update_span_duration Causes Phan Parsing to Fail for PHP <8.2

### ISSUE THREAD

**Issue by scott-shields-github** [DataDog/dd-trace-php#2585]
### Bug report

The standalone null return type for [update_span_duration](https://github.com/DataDog/dd-trace-php/blob/0.98.1/ext/ddtrace.stub.php#L417) causes Phan parsing to fail with a segfault. This function looks like it can return `false|null` like `close_span`; can this be updated to match `close_span`'s return type? This looks like it affects lib versions 0.94.0 - latest.

I'd contribute, but I don't think I can at the moment without signoff.

### PHP version

8.1.25

### Tracer or profiler version

0.98.1

**Comment by morrisonlevi** [comment]
Indeed, it looks like it should be `false|null`, returning false on invalid parameters:

https://github.com/DataDog/dd-trace-php/blob/5d2c3cb0aa570ac5ce3035aa0155fd8e2bb60f5c/ext/ddtrace.c#L2324-L2329

@bwoebi Should we update `false` here or take an alternative action?
