### ISSUE TITLE
[Bug]: Service name is always "laravelqueue" and can't be changed

### ISSUE THREAD

**Issue by viccatoff** [DataDog/dd-trace-php#2637]
### Bug report

All executed jobs are assigned to "laravelqueue" service, so it's doesn't consider project settings. 

I found that it set [here](https://github.com/DataDog/dd-trace-php/blob/6d15aec26c33b8f9d966fe06ed3630539c1905c8/src/DDTrace/Integrations/LaravelQueue/LaravelQueueIntegration.php#L171) . 

Maybe it's better to use `$integration->getAppName();` instead `$integration->getName();` ?
 

### PHP version

8.3

### Tracer or profiler version

0.99

**Comment by pablomartinezbernardo** [comment]
Thanks for flagging, [fixed it here](https://github.com/DataDog/dd-trace-php/pull/2643), it will be included in the next release.

**Comment by bwoebi** [comment]
1.0 has now been released, including the bug fix for this - thanks for reporting it :-)
