### ISSUE TITLE
[Help]: Configurations in Docker and kubernetes 

### ISSUE THREAD

**Issue by amardeep2006** [DataDog/dd-trace-php#2663]
### Help in configuration

I am adding dd-trace-php to an existing Docker Image that has drupal and Apache2 server baked in.
I have looked at the documentation but it has lead to more confusion hence asking here.

Here is my Dockerfile

```
FROM myrepo/ubuntu_drupal_apache2:latest
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php \
	&& php datadog-setup.php --php-bin=all
```

Installation logs : 

```
Installed required source files to '/opt/datadog/dd-library/0.99.1'
Installing to binary: php (/usr/bin/php8.1)
Copied '/tmp/dd-install/dd-library-php/trace/ext/20210902/ddtrace.so' to '/usr/lib/php/20210902/ddtrace.so'
Copied '/tmp/dd-install/dd-library-php/profiling/ext/20210902/datadog-profiling.so' to '/usr/lib/php/20210902/datadog-profiling.so'
Copied '/tmp/dd-install/dd-library-php/appsec/ext/20210902/ddappsec.so' to '/usr/lib/php/20210902/ddappsec.so'
Created INI file '/etc/php/8.1/cli/conf.d/98-ddtrace.ini'
Installation to 'php (/usr/bin/php8.1)' was successful
Created INI file '/etc/php/8.1/apache2/conf.d/98-ddtrace.ini'
Installation to 'php (/usr/bin/php8.1)' was successful
Installing to binary: php8.1 (/usr/bin/php8.1)
Copied '/tmp/dd-install/dd-library-php/trace/ext/20210902/ddtrace.so' to '/usr/lib/php/20210902/ddtrace.so'
Copied '/tmp/dd-install/dd-library-php/profiling/ext/20210902/datadog-profiling.so' to '/usr/lib/php/20210902/datadog-profiling.so'
Copied '/tmp/dd-install/dd-library-php/appsec/ext/20210902/ddappsec.so' to '/usr/lib/php/20210902/ddappsec.so'
Updating existing INI file '/etc/php/8.1/cli/conf.d/98-ddtrace.ini'
Installation to 'php8.1 (/usr/bin/php8.1)' was successful
Updating existing INI file '/etc/php/8.1/apache2/conf.d/98-ddtrace.ini'
Installation to 'php8.1 (/usr/bin/php8.1)' was successful
Installing to binary: php-fpm8.1 (/usr/sbin/php-fpm8.1)
Copied '/tmp/dd-install/dd-library-php/trace/ext/20210902/ddtrace.so' to '/usr/lib/php/20210902/ddtrace.so'
Copied '/tmp/dd-install/dd-library-php/profiling/ext/20210902/datadog-profiling.so' to '/usr/lib/php/20210902/datadog-profiling.so'
Copied '/tmp/dd-install/dd-library-php/appsec/ext/20210902/ddappsec.so' to '/usr/lib/php/20210902/ddappsec.so'
Created INI file '/etc/php/8.1/fpm/conf.d/98-ddtrace.ini'
Installation to 'php-fpm8.1 (/usr/sbin/php-fpm8.1)' was successful
```

Question : How do I set the configurations dynamically via OS environment variables when this image will run? I could see multiple options that are confusing me. 

Q1. Can I set following env variables while starting the Image ? DD_SERVICE,DD_VERSION,DD_AGENT_HOST ? Will php-tracer automatically read then on run time . I have used Java and Node tracer in past and they can do that. Need confirmation for php.
My docker image is reused across projects hence I donot want to bake hardcoded details via Dockerfile.

Q2. If this information cannot be read dynamically automatically in php then where should I write this ? I see many options that is confusing ?  

```
/etc/php/8.1/fpm/php.ini
/etc/php/8.1/apache2/conf.d/98-ddtrace.ini
/etc/php/8.1/fpm/conf.d/98-ddtrace.ini
/etc/php/8.1/fpm/pool.d/www.conf
```
Few recommendations are for .htaccess / server config files as well. Any help greatly appreciated. 

### PHP version

8.1.28

### Tracer or profiler version

0.99.1

### Installed extensions

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
ddappsec
ddtrace
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
PDO
pdo_pgsql
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib
[Zend Modules]
Zend OPcache
ddappsec
ddtrace

**Comment by morrisonlevi** [comment]
Environment variables for PHP are more difficult, because every SAPI tends to handle them differently. INI settings are generally much more consistent across SAPIs, so I recommend setting them that way. The `datadog-setup.php` script has a config mode that can be used to set them as part of your script, e.g.:

```
FROM myrepo/ubuntu_drupal_apache2:latest
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php \
	&& php datadog-setup.php --php-bin=all \
	&& php datadog-setup.php config set \
		-d datadog.service=app-name \
		-d datadog.env=prod \
		-d datadog.version=1.3.2 \
		-d datadog.agent_host=localhost
```

**Comment by amardeep2006** [comment]
Thanks @morrisonlevi for quick response .
If I pass the configs with -d at build time then which file/location can I see these after configuration ? 
I still see 2 issues :
1. Since my docker image is reusable it will be confusing if all apps report traces with same service , env and version.
2. The agent in my case is running on kubernetes host node as daemonset. I can inject the IP of kubernetes node via helm while deploying but I need to set agent_host that can point to OS environment variable having IP address of kubernetes node.

**Comment by amardeep2006** [comment]
I tried following configs :

Config 1 : 
```
FROM myrepo/ubuntu_drupal_apache2:latest
RUN apt-get update -yq \
	&& apt-get upgrade -yq
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php \
	&& php datadog-setup.php --php-bin=all
RUN echo "env[DD_ENV] = \$DD_ENV" >>/etc/php/8.1/fpm/pool.d/www.conf \
	&& echo "env[DD_SERVICE] = \$DD_SERVICE" >>/etc/php/8.1/fpm/pool.d/www.conf \
	&& echo "env[DD_VERSION] = \$DD_VERSION" >>/etc/php/8.1/fpm/pool.d/www.conf \
	&& echo "env[DD_AGENT_HOST] = \$KUBERNETES_HOST_IP" >>/etc/php/8.1/fpm/pool.d/www.conf 
```

Config 2  with clear_env = no: 
```
FROM myrepo/ubuntu_drupal_apache2:latest
RUN apt-get update -yq \
	&& apt-get upgrade -yq
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php \
	&& php datadog-setup.php --php-bin=all
RUN echo "env[DD_ENV] = \$DD_ENV" >>/etc/php/8.1/fpm/pool.d/www.conf \
	&& echo "env[DD_SERVICE] = \$DD_SERVICE" >>/etc/php/8.1/fpm/pool.d/www.conf \
	&& echo "env[DD_VERSION] = \$DD_VERSION" >>/etc/php/8.1/fpm/pool.d/www.conf \
	&& echo "env[DD_AGENT_HOST] = \$KUBERNETES_HOST_IP" >>/etc/php/8.1/fpm/pool.d/www.conf \	
	&& echo "clear_env = no" >>/etc/php/8.1/fpm/pool.d/www.conf 
```
I am passing KUBERNETES_HOST_IP via helm chart. 

```
  - name: KUBERNETES_HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

```
ISSUE I faced:  It does not set `datadog.agent_host`  and it still points to localhost. Interestingly datadog.env , datadog.service and datadog.version are set. 

I then Injected DD_AGENT_HOST via helm chart like this and now datadog.agent_host has the correct IP even without making entry in www.conf file.
```
  - name: DD_AGENT_HOST 
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

```
Seems like configurations I have set in `/etc/php/8.1/fpm/pool.d/www.conf` are not effective and It's picking up OS environment variables directly.

And at last I cannot still see the APM traces in datadog.

**Comment by amardeep2006** [comment]
I tried one more config but still phpinfo() does not use the values I passed. Kind of hitting end of read now.
```
FROM myrepo/ubuntu_drupal_apache2:latest
RUN apt-get update -yq \
	&& apt-get upgrade -yq
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php \
	&& php datadog-setup.php --php-bin=all
RUN echo "env[DD_ENV] = \$DD_ENV" >>/etc/php/8.1/fpm/pool.d/www.conf \
	&& echo "env[DD_SERVICE] = \$DD_SERVICE" >>/etc/php/8.1/fpm/pool.d/www.conf \
	&& echo "env[DD_VERSION] = \$DD_VERSION" >>/etc/php/8.1/fpm/pool.d/www.conf \
	&& echo "env[DD_AGENT_HOST] = \$DD_AGENT_HOST" >>/etc/php/8.1/fpm/pool.d/www.conf
RUN echo "PassEnv \$DD_ENV" >>/etc/apache2/apache2.conf \
	&& echo "PassEnv \$DD_SERVICE" >>/etc/apache2/apache2.conf \
	&& echo "PassEnv \$DD_VERSION" >>/etc/apache2/apache2.conf \
	&& echo "PassEnv \$DD_AGENT_HOST" >>/etc/apache2/apache2.conf
```

**Comment by amardeep2006** [comment]
@morrisonlevi 
Finally I was able to solve it.  Here is what worked for me for future reference if anyone faces the same 

```
FROM FROM myrepo/ubuntu_drupal_apache2:latest
ARG PHP_VERSION=8.1
ARG DDTRACE_LIB_VERSION=0.99.1
RUN apt-get update -yq \
	&& apt-get upgrade -yq
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/download/${DDTRACE_LIB_VERSION}/datadog-setup.php \
	&& php datadog-setup.php --php-bin=all \
	&& php datadog-setup.php config set --php-bin=php --php-bin=php-fpm${PHP_VERSION} \
		-d datadog.service=\${DD_SERVICE} \
		-d datadog.env=\${DD_ENV} \
		-d datadog.version=\${DD_VERSION} \
		-d datadog.agent_host=\${DD_AGENT_HOST} 	
RUN echo "PassEnv DD_ENV" >>/etc/apache2/apache2.conf \
	&& echo "PassEnv DD_SERVICE" >>/etc/apache2/apache2.conf \
	&& echo "PassEnv DD_VERSION" >>/etc/apache2/apache2.conf \
	&& echo "PassEnv DD_AGENT_HOST" >>/etc/apache2/apache2.conf
```

Here are how I am passing env variable via helm chart. Somehow only DD_AGENT_HOST is respected by dd-trace only.
```

  - name: DD_AGENT_HOST 
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: DD_ENV
     value: dev
  - name: DD_SERVICE
     value: drupal-app-name
  - name: DD_VERSION
    value: 1.0.16
```

I also found one issue with DD official documentation . For Apache + mod_php in VirtualHost or server configuration file the example shows Dollar sign like this which is wrong

```
PassEnv $DD_ENV
PassEnv $DD_SERVICE
PassEnv $DD_VERSION
```

The correct configs for apache2.conf


```
PassEnv DD_ENV
PassEnv DD_SERVICE
PassEnv DD_VERSION
PassEnv DD_AGENT_HOST 
```

![image](https://github.com/DataDog/dd-trace-php/assets/50517840/ad9c3ee7-0d0f-4765-b2d3-088dd51e4d93)

![image](https://github.com/DataDog/dd-trace-php/assets/50517840/edff1cf2-a45f-474f-93db-9578b6e06b58)

**Comment by amardeep2006** [comment]
Here is the most simple config that also worked.

```
FROM myrepo/ubuntu_drupal_apache2:latest
RUN apt-get update -yq \
	&& apt-get upgrade -yq
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php \
	&& php datadog-setup.php --php-bin=all	
RUN echo "PassEnv DD_ENV" >>/etc/apache2/apache2.conf \
	&& echo "PassEnv DD_SERVICE" >>/etc/apache2/apache2.conf \
	&& echo "PassEnv DD_VERSION" >>/etc/apache2/apache2.conf \
	&& echo "PassEnv DD_AGENT_HOST" >>/etc/apache2/apache2.conf
```

**Comment by morrisonlevi** [comment]
If you want to use env vars, that's fine. I'm glad you figured out how to pipe them through! I'll pass along the documentation issue you mentioned.

**Comment by amardeep2006** [comment]
Thanks . I fotgot to updte here but the docs ahe been corrected in datadog app as well.
![image](https://github.com/DataDog/dd-trace-php/assets/50517840/e7019086-a632-4470-9056-6b36769105b6)
