### ISSUE TITLE
Standalone install from IPv6-only server

### ISSUE THREAD

**Issue by gman-wa** [DataDog/dd-trace-php#2688]
### Describe the feature you'd like

Since AWS is charging for public IPv4 and Cloudflare can serve web applications on IPv4 and IPv6 and just connect to origin over IPv6 only, running AWS origin services IPv6 is doable.

Running the datadog-setup script is not since it wants to download packages from GitHub which is IPv4 only.

It would be great to be able to copy datadog-setup and the GZ package manually onto the server and have a option for data dog-setup to use a GZ archive already downloaded. 

### Is your feature request related to a problem?

I want to run an IPv6-only origin server.

**Comment by realFlowControl** [comment]
Hey @gman-wa 👋 

there is an undocumented [`--file` argument](https://github.com/DataDog/dd-trace-php/blob/7557b8aad57681d2d704cecedea5249f4786d915/datadog-setup.php#L489-L491) to the `datadog-setup.php` that you can use like this:
```bash
$ php datadog-setup.php --your-args --file /path/to/file.tar.gz
```
Hope this helps in the meantime while we are looking for solutions.

**Comment by gman-wa** [comment]
oh that's cool - is file.tar.gz the name of the tarball from GH releases or the renamed version that the script puts in /tmp/ ?  or should it not matter?

**Comment by bwoebi** [comment]
@gman-wa It does not matter, only the contents matter

**Comment by gman-wa** [comment]
ok - thank you!
