### ISSUE TITLE
PEAR DB support

### ISSUE THREAD

**Issue by dlpetrie** [DataDog/dd-trace-php#275]
Any chance that PEAR DB support can be added? We have a massive legacy application that uses PEAR DB (DB_common_original class).

If not, is there a way we can hook this into our tracing?

**Comment by labbati** [comment]
Hi @dlpetrie, thanks for bringing up PEAR DB to our attention. Unfortunately, we do not have a real plan to support it at the moment. That said you are totally welcomed to both open a PR to include it in the official repo or to provide it as part of your own code.
As a source of inspiration you can take a look at our [PDO integration](https://github.com/DataDog/dd-trace-php/blob/110c14ffb543236342ecd9315f1d5005d7a680a4/src/DDTrace/Integrations/PDO/PDOIntegration.php). Let us know if you get stuck and we will try to help!

Welcome to the dd-trace-php community!

**Comment by labbati** [comment]
Closing this issue, @dlpetrie feel free to reopen it if you feel as you need further info. Thanks again for your interest.
