### ISSUE TITLE
[Bug]: Can't get Single Step Instrumentation to work

### ISSUE THREAD

**Issue by rafilkmp3** [DataDog/dd-trace-php#2807]
### Bug report

Hey, i am implementing datadog on my company's services and while i was able to do a Single Step Instrumentation for JS apps, i can't do it on our main app that is PHP. I checked the latest `dd-trace-php` release and the main feature is adding beta support for PHP Single Step Instrumentation, linking to the official doc but in that doc there isn't any mention whatsoever about how to do the instrumentation on a PHP app. 
I tried the obvious thing that would be adding 

     apm:
      enabled: true
      instrumentation:
        enabled: true
        libVersions: 
          js: "5"
          php: "8"
          
but no success on it. Is there any guide or a more specific doc to make this possible? Thank you

### PHP version

PHP 8.1.29

### Tracer or profiler version

n/a

### Installed extensions

apcu
bcmath
bz2
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gmp
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
redis
Reflection
session
SimpleXML
soap
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

**Comment by iamluc** [comment]
Hi @rafilkmp3,

Yes support has been merged, but hasn't reached General Availability.
If you're interested in joining the beta, you can send an email to [onboarding-beta@datadoghq.com](mailto:onboarding-beta@datadoghq.com).

Thanks for your interest.

**Comment by rafilkmp3** [comment]
> Hi @rafilkmp3,
> 
> Yes support has been merged, but hasn't reached General Availability. If you're interested in joining the beta, you can send an email to [onboarding-beta@datadoghq.com](mailto:onboarding-beta@datadoghq.com).
> 
> Thanks for your interest.

Hey, thank you for the response. I've just emailed them asking for beta access.
