### ISSUE TITLE
[Bug]: Integration DDTrace\Integrations\Swoole\SwooleIntegration not available. New attempts WILL NOT be performed.

### ISSUE THREAD

**Issue by jaesonarsoftware** [DataDog/dd-trace-php#2809]
### Bug report

We are using Swoole and Laravel.  On startup, DDtrace shows this.  I cannot find how to have it load the Swoole Integration or what the issue is.

```
DD_ENV=local
DD_TRACE_AUTO_FLUSH_ENABLED=1
DD_TRACE_LARAVEL_ENABLED=1
DD_TRACE_LARAVELQUEUE_ENABLED=1
DD_TRACE_DEBUG=1
DD_TRACE_CLI_ENABLED=1
DD_TRACE_SWOOLE_ENABLED=1
DD_TRACE_RESOURCE_URI_QUERY_PARAM_ALLOWED=*

```

```
[ddtrace] [debug] Loaded integration DDTrace\Integrations\Laravel\LaravelIntegration
[ddtrace] [debug] Loaded integration DDTrace\Integrations\ElasticSearch\V1\ElasticSearchIntegration
[ddtrace] [debug] Loaded integration DDTrace\Integrations\Guzzle\GuzzleIntegration
[ddtrace] [debug] Loaded integration DDTrace\Integrations\Eloquent\EloquentIntegration
[ddtrace] [debug] Loaded integration DDTrace\Integrations\LaravelQueue\LaravelQueueIntegration
[ddtrace] [debug] Loaded integration DDTrace\Integrations\Exec\ExecIntegration
[ddtrace] [debug] Integration DDTrace\Integrations\Swoole\SwooleIntegration not available. New attempts WILL NOT be performed.

```

### PHP version

8.1

### Tracer or profiler version

1.2.0

### Installed extensions

[PHP Modules]
bcmath
blackfire
calendar
Core
ctype
curl
date
ddtrace
dom
ds
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
intl
json
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pgsql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
swoole
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
blackfire
ddtrace

**Comment by bwoebi** [comment]
Hey @jaesonarsoftware,

What's your swoole version? At least 5.0.2 is required for the integration to work.

**Comment by jaesonarsoftware** [comment]
My version 4.8. Ok, I guess that solves it.  Thanks
