### ISSUE TITLE
[Bug]: 1.4.0 still throws deprecated exception on MongoDBIntegration

### ISSUE THREAD

**Issue by cyberdelia1987** [DataDog/dd-trace-php#2883]
### Bug report

MongoDBIntegration still throws deprecation exception when trying to use deprecated `CommandStartedEvent::getServer()`

Probably this is because of `method_exists($event, 'getPort')` condition, which will return `true` in case of MongoDB 1.20, and `self::$useDeprecatedMethods` will be set to `true`, which leads to usage of old and deprecated `CommandStartedEvent::getServer()` method

```
yii\base\ErrorException: Method MongoDB\Driver\Monitoring\CommandStartedEvent::getServer() is deprecated in /opt/datadog/dd-library/1.4.0/dd-trace-sources/src/DDTrace/Integrations/MongoDB/MongoDBIntegration.php:33
```

### PHP version

8.3

### Tracer or profiler version

1.4.0

**Comment by bwoebi** [comment]
You're absolutely right, a `!` was missing: #2884 fixes it.

Sorry for that. A 1.4.1 will be upcoming within a few days.

**Comment by alexandr-sibov** [comment]
Thanks, @bwoebi !

**Comment by bwoebi** [comment]
Closing as 1.4.1 has been released last week.
