### ISSUE TITLE
[Bug]: 1.4.0 - 40mb core dumps since version was updated

### ISSUE THREAD

**Issue by j-fulbright** [DataDog/dd-trace-php#2905]
### Bug report

Checking on some unrelated issues on our servers and found that there were 400+ `core.####` files (at 40mb a piece) in the root of our application. 

Further investigation, aka just seeing what was in the file, appears to be a crash from datadog of some sort. 

This is a new issue from what I can only assume was the move up to 1.4.0, so we're locking our version 1.3.2 for the time being. 

This is a Docker container running on Fargate

### PHP version

8.2.23

### Tracer or profiler version

1.4.0

**Comment by bwoebi** [comment]
Hey @j-fulbright,

We have two sources of crashes identified within 1.4.1 (and also some with 1.4.0) and we've just released 1.4.2.
Could you please confirm whether these crashes are still present?

Thanks!

**Comment by j-fulbright** [comment]
@bwoebi Did some checking and it appears that 1.4.2 has likely fixed the core dumps we were seeing.

**Comment by bwoebi** [comment]
@j-fulbright Awesome, then I suppose I may close this issue?
