### ISSUE TITLE
[Bug]: Missing php classes stubs

### ISSUE THREAD

**Issue by zbigniew-malcherczyk-tg** [DataDog/dd-trace-php#2931]
### Bug report

There are a few missing stubs for version 1.4.2

* https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Span.php
* https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/SpanContext.php

Please. It's so hard to work with dd-trace library and extension. It's really sad how hard it is to install the extension, to maintain anything that depends on this lib. No to mention that release is 1GB...

### PHP version

8.2.25

### Tracer or profiler version

1.4.2

**Comment by bwoebi** [comment]
Hey @zbigniew-malcherczyk-tg,

I'm a bit confused here what you would like to see here. The *.stub.php files are for functions exposed by the extension, not the PHP source files shipped alongside it.

I'd like to understand the usecase / workflow for this? For integration in the IDE, I just pull it via composer and it sees the stub files as well as all files in src/.

**Comment by bwoebi** [comment]
I'd like though, to understand, why installing the extension is hard? I thought just downloading and executing `php datadog-setup.php` would be really easy.
But maybe that's not the case?

About the size of the full artifact (containing all php versions), we've been annoyed too. I suppose the easiest way is to split this up into more individual files...

**Comment by bwoebi** [comment]
Overall, we're also willing to hear what makes it hard to work with dd-trace-php. In fact, we mostly hear from our users when something is actually broken, but merely "hard to work with" is nothing I get to hear often. Feedback is important and most welcome too.

**Comment by zbigniew-malcherczyk-tg** [comment]
Hi! @bwoebi Let's start from the files and stubs. The OpenTelemetry is relatively new feature for PHP and datadog, so I cannot tell if that would solve anything for us. Our usecase is that you just cannot enable tracing for everything to get more detailed info we have to provide spans and tags semi-manual. For that we use and more
```
use DDTrace\Contracts\Span;
use DDTrace\GlobalTracer;
use DDTrace\Http\Urls;
use DDTrace\Tag;
use DDTrace\Contracts\Span;
```

So we could call it internal tooling-ish. Now the stubs are mostly important with two cases IDE and phpstan. It is a great PITA that the stubs don't consists of other elements. Those listed above are part of extension, but are not marked as internal, therefore they should usable.

**Comment by bwoebi** [comment]
Thanks @zbigniew-malcherczyk-tg,

We quickly tried generating stubs in #2933. The resulting src/ddtrace_php_api.stubs.php contains all stubs for the PHP code, minus the extension stubs. I wonder, at that point, whether it would be preferable to have a single stub file instead of 4? (merging that one, ext/ddtrace.stub.php and ext/hook/uhook.stub.php and ext/hook/uhook_attributes.stub.php?) Also, do you wish to see that as a release artifact or rather just in the repository?

**Comment by bwoebi** [comment]
Sounds good, we'll add some logic to compile a big stub file together and add it as artifact.
A composer package is probably quite a bit more annoying as you cannot have more than one per github repository... (AFAIK?)

**Comment by zbigniew-malcherczyk-tg** [comment]
Yea. packageist mostly supports single package single repository scenarios 😢

**Comment by bwoebi** [comment]
Release artifacts now have a `datadog-tracer.stubs.php` file. For release 1.5.0 that is at https://github.com/DataDog/dd-trace-php/releases/download/1.5.0/datadog-tracer.stubs.php.

**Comment by morrisonlevi** [comment]
> These datadog-setup.php file is not tested by me, but I would start with a simple question. How do I get this file in the first place for my Dockerfile? From the github repo? I would need to download it. Copy and paste it? I would need to maintain it. Yet it does download the same release as the first solution.

To address these related things about `datadog-setup.php`:
 1. Yes, you download `datadog-setup.php` from the repository for the given release e.g. `https://github.com/DataDog/dd-trace-php/releases/download/1.5.0/datadog-setup.php`. This is a small download.
2. The `datadog-setup.php` script does _not_ do the same stuff as the apk/deb/etc files. It is intended to work on far more deployments (which is partly why it was created, each one of those package types has restrictions that make it not work for some customers).
3. The `datadog-setup.php` script then downloads artifacts based on PHP version and platform. In the past, this additional download was quite large, but as of 1.5 it's small again. For a single PHP version (the most common case), the download is roughly 40 MiB.

The `datadog-setup.php` script usage will often look like this:

```sh
# APM only
php datadog-setup.php --php-bin=all

# APM + Profiling
php datadog-setup.php --php-bin=all --enable-profiling

# APM + ASM
php datadog-setup.php --php-bin=all --enable-appsec

# Full installation: APM + ASM + Profiling
php datadog-setup.php --php-bin=all --enable-appsec --enable-profiling
```

You can also use it to set INI settings, which is my preferred way to configure things:

```sh
php datadog-setup.php config set --php-bin=all \
  -d datadog.service="app-name" \
  -d datadog.env="prod" \
  -d datadog.version="1.3.2"
```

If you want to env vars at runtime (like in docker or such) you can also do things like this, it's a little known feature of PHP ini settings:

```sh
php datadog-setup.php config set --php-bin=all \
  -d datadog.service=\$DD_SERVICE \
  -d datadog.env=\$DD_ENV \
  -d datadog.version=\$DD_VERSION \
```
