### ISSUE TITLE
[Feature] Resource based trace sampling rules

### ISSUE THREAD

**Issue by orlandothoeny** [DataDog/dd-trace-php#2962]
### Describe the feature you'd like

It would be helpful if it was possible to configure tracing sampling rules using the `DD_TRACE_SAMPLING_RULES` env variabled based on resources. For example as it is possible for Java ([Docs](https://docs.datadoghq.com/tracing/trace_pipeline/ingestion_mechanisms/?tab=java#in-tracing-libraries-user-defined-rules))

Example config:
```shell script
export DD_TRACE_SAMPLING_RULES='[{"service": "my-service", "resource":"foo_endpoint", "sample_rate": 1},{"service": "my-service", "sample_rate": 0.2}]'
```

### Is your feature request related to a problem?

It is only possible to set sample rates based on the service. Alternatively, it is possible to completely remove resources using the `DD_APM_IGNORE_RESOURCES` env variable on the DataDog Agent. However, there is currently no possibility to define sample rates based on resources for PHP applications.

### Additional context

We have high traffic API endpoints for which we don't need as many traces as for other endpoints.

**Comment by bwoebi** [comment]
Hey @orlandothoeny,

Does this not work with dd-trace-php for you? This is supposed to work, so I'm confused why you're marking it feature and not bug?

Thanks

**Comment by bwoebi** [comment]
Looking at the documentation, it seems like the PHP tab never got updated to reflect this.

**Comment by orlandothoeny** [comment]
@bwoebi Ah okay. I didn't try it out and only looked at the documentation. I'll give it a try then, then it's probably fine

**Comment by orlandothoeny** [comment]
Tried it out. Using `resource` works

**Comment by lifeofguenter** [comment]
@orlandothoeny were you able to make it work? for us it is still not working.

**Comment by orlandothoeny** [comment]
@lifeofguenter Yes it works for us

**Comment by iNviNho** [comment]
Seems it doesn't work for us
```Dockerfile
ENV DD_TRACE_SAMPLING_RULES='[{"service": "broker.offer-service", "resource": "kafka.consume", "sample_rate": 0.0}, {"service": "broker.offer-service", "resource": "kafka.produce", "sample_rate": 0.0}]'
```

But I still see 

<img width="832" height="501" alt="Image" src="https://github.com/user-attachments/assets/c5db74f7-d2c8-4523-bd3c-c393ad1a2e28" />

We are using 1.6.2 php tracer version
