### ISSUE TITLE
[Bug]: Span not created for mysqli_real_query

### ISSUE THREAD

**Issue by junjihashimoto** [DataDog/dd-trace-php#2963]
### Bug report

No spans created for mysqli_real_query in mysqli integration.
There is no real_query in the following file:
https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Integrations/Mysqli/MysqliIntegration.php

### PHP version

7.4

### Tracer or profiler version

1.4.2

**Comment by PROFeNoM** [comment]
Thanks for your contribution!
