### ISSUE TITLE
Alpine (musl libc): "backtrace_symbols: symbol not found" since 0.13.2

### ISSUE THREAD

**Issue by mruoss** [DataDog/dd-trace-php#312]
I'm testing ddtrace on our alpine php-fpm docker image. `php --ri=ddtrace` returns the following error:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'ddtrace.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/ddtrace.so (Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20170718/ddtrace.so: backtrace_symbols: symbol not found), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/ddtrace.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20170718/ddtrace.so.so: No such file or directory)) in Unknown on line 0
Extension 'ddtrace' not present.
```

I have read that on musl-libc, while the package libexecinfo-dev provides the headers, implementation is missing. This makes the extension unusable on alpine images.

**Comment by mclueppers** [comment]
I'm having similar problem when I try to build a package for my Alpine repository so I don't have to --allow-untrusted

**Comment by mclueppers** [comment]
Right, after some searching around I found the solution for the problem. `backtrace_symbols` is not part of musl, as you've said. After adding `-lexecinfo` to LDFLAGS I managed to build an extension that successfully loaded and passed all tests.

```
build() {
  local jobs=$(($(nproc)+1))

  cd "$builddir"/

  phpize

  EXTENSION_DIR=/usr/lib/php/$_phpver/modules \
  CFLAGS="-fstack-protector-strong -fpic -fpie -O2" \
  CPPFLAGS="$CFLAGS" \
  LDFLAGS="-Wl,-O1 -Wl,--hash-style=both -pie -lexecinfo" \
  ./configure \
    --prefix=/usr \
    --with-php-config=/usr/bin/php-config \
    --enable-ddtrace

  make -j $jobs
}
```

**Comment by mruoss** [comment]
Oh I see! Thanks for the hint - that solves the issue indeed!
