### ISSUE TITLE
Installing 0.13.4 from source in alpine docker image fails

### ISSUE THREAD

**Issue by tot-ra** [DataDog/dd-trace-php#321]
Getting `opt/datadog-php/bin/post-install.sh: line 69: syntax error: unexpected "(" (expecting "}")`

while building docker container using image `FROM php:7.0-fpm-alpine3.7`
```
ENV DD_VERSION=0.13.4

RUN curl -L -s https://github.com/DataDog/dd-trace-php/releases/download/$DD_VERSION/datadog-php-tracer-$DD_VERSION-beta.x86_64.tar.gz  | tar xvzf - -C /tmp  \
 && cd /tmp \
 && sh opt/datadog-php/bin/post-install.sh \
 && rm -rf cd /tmp/opt
```

**Comment by labbati** [comment]
Hi @tot-ra 👋, thanks for opening this issue.

For alpine we also provide a package, just in case you want to avoid the manual installation.

If you still want to do manual installation, a couple of things form the top of my head:

1. with the command above you extract the files in `/tmp` and within there you will find `opt`, but you have to move `/tmp/opt/*` to `/opt`.
1. the script is bash compatible, not dash compatible (but it should be and we can work to make it happen). In the meantime `bash` is not part of the alpine 3.7 distribution, so if you want to do it please `apk add bash` before running the post install.

Then you should be good to go

**Comment by tot-ra** [comment]
Thanks for quick reply! Added bash & seems to work now. Closing issue
