### ISSUE TITLE
Tags env:none

### ISSUE THREAD

**Issue by raffaellopaletta** [DataDog/dd-trace-php#337]
Seems that there is no way to pass the env tag. In APM view I see the **env** tag set to none. According to docs I tried to set the environment variable DD_TRACE_GLOBAL_TAGS = env:st but it does not effect. Im using last version of library, SF4 and Automatic Instrumentation. Is there some other way to set env tag ?

**Comment by labbati** [comment]
Hi  @raffaellopaletta!

This can be set in your agent's `datadog.yaml` file [here the template](https://github.com/DataDog/datadog-agent/blob/047913008543e953cff7a049ed8cd31790325f0b/pkg/config/config_template.yaml#L785).

```
apm_config:
  env: my_env
```

**Comment by raffaellopaletta** [comment]
Hi @labbati !

Thanks. I'm using docker agent. I have 

`DD_DOCKER_LABELS_AS_TAGS='{"com.trace.xconik.environment":"env"}'` 

inside the docker agent container and the label 
`labels {
          ...
          com.trace.xconik.environment = "st"
        }`

inside the application container, but It does not work as expected. I'll continue to investigate.

**Comment by labbati** [comment]
Hi! Now I see. I would suggest to open an issue on the agent's repo https://github.com/DataDog/datadog-agent/issues if you feel that tagging is not working as expected.

I am closing this issue for now, but feel free to re-open if you have further questions.

**Comment by raffaellopaletta** [comment]
Ok, Thanks!!

**Comment by raffaellopaletta** [comment]
I solved by passing the env

`DD_APM_ENV =" st "`

into container
