### ISSUE TITLE
Support for Zend framework 2.x

### ISSUE THREAD

**Issue by mclueppers** [DataDog/dd-trace-php#342]
I'm having a legacy application that's using Zend framework 2.x and it's not picked up automatically by the automatic application instrumentation. Reading the docs ZF 1.12 is the only supported (so far) version of the framework. Are there any plans to extend the range of the supported versions?

**Comment by labbati** [comment]
Hi @mclueppers, this is in our radar but unfortunately I can provide with an ETA yet. Two options for you:

1. We are always happy to welcome new contributors to the repo 😄 
2. Did you try to simply install the extension and run you app? We offer generic web requests tracing that already shows you request metadata and all spans from libraries and datastores integrations. This may be a good starting point while we can work on ZF2

**Comment by jakobdoc** [comment]
Hi @labbati, we are in the same situation, currently evaluating dd and one application is at zend framework 2.4.13. I have tried option 2 and it seems to be ok...only problem I have is that service name mapping does not work for the generic web request service. Its always named web.request ... DD_SERVICE_MAPPING works for all services despite the generic one.

**Comment by pierotibou** [comment]
ZF2 is now supported
