### ISSUE TITLE
WoD with Laravel 5.8

### ISSUE THREAD

**Issue by stayallive** [DataDog/dd-trace-php#346]
I have been trying to get some useful debug info but as far as I can tell the Laravel integration breaks with Laravel 5.8 and dumps the following (truncated error) to the screen.

```
2019/03/08 20:51:15 [error] 24207#24207: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class events does not exist in /home/forge/cert.chief.app/releases/20190308204600/vendor/laravel/framework/src/Illuminate/Container/Container.php:794
Stack trace:
#0 /home/forge/cert.chief.app/releases/20190308204600/vendor/laravel/framework/src/Illuminate/Container/Container.php(794): ReflectionClass->__construct('events')
#1 /home/forge/cert.chief.app/releases/20190308204600/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\Container\Container->build('events')
#2 /home/forge/cert.chief.app/releases/20190308204600/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\Container\Container->resolve('events', Array)
#3 /home/forge/cert.chief.app/releases/20190308204600/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Container\Container->make('events', Array)
#4 /home/forge/cert.chief.app/releases/20190308204600/vendor/laravel/framework/src/Illuminate/Conta" while reading response header from upstream, client: 83.84.103.115, server: cert.chief.app, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "cert.chief.app"
```

I have been trying to get some more useful debug in info but got nil to show.

Disabled the Laravel integration with the following in nginx until the cause is found.

```
fastcgi_param DD_INTEGRATIONS_DISABLED laravel;
```

Might be nice to also figure out how to not dump stack traces to the screen in production.

**Comment by ArondeParon** [comment]
We experienced this same issue as well today. Took us quite some time to figure out why this was going wrong, but it's definitely the APM that is causing our application to break.

![image](https://user-images.githubusercontent.com/7697/54120993-94919f80-43f9-11e9-9adb-db351affbd6f.png)

**Comment by stayallive** [comment]
The way of "safely" getting the user ID is a probable source of errors.

See: https://3v4l.org/fgakS, it cannot be catched :)

Something like below would IMHO be the preferred way.

```php
try {
    $userId = '-';

	if (auth()->check()) {
        $user = auth()->user()->getAuthIdentifier();
    }

    $span->setTag('laravel.user', $user)
} catch ...
```

**Comment by labbati** [comment]
Hi, thanks for reporting this issue. Looking into this right now!

**Comment by labbati** [comment]
Hi @stayallive , we just released [0.15.1](https://github.com/DataDog/dd-trace-php/releases/tag/0.15.1) which brings the fix we to laravel 5.8.

Thanks again for your help on this.

**Comment by ArondeParon** [comment]
@labbati thanks for the quick update! 

I just tested this in our production environment and it is working again.

One thing though: we are stills seeing errors reported due to this line:

`$user = auth()->user()->id;`

Perhaps this variable could be null-coalesced? IE:

`$user = auth()->user()->id ?? null;`

**Comment by labbati** [comment]
@stayallive and @ArondeParon fix to the user id issue has been merged and will be available with the next release https://github.com/DataDog/dd-trace-php/pull/363

Thanks @SammyK

**Comment by stayallive** [comment]
Perfect! Closing this issue since the original is resolved and with the next release also the user id, thanks for the quick actions!
