### ISSUE TITLE
Add "restart PHP" to the docs

### ISSUE THREAD

**Issue by karllhughes** [DataDog/dd-trace-php#358]
Maybe this is obvious to most people, but after banging my head on the keyboard for a couple hours I realized all I needed to do to get traces working was restart PHP 🤦‍♂️ 

Just wanted to lobby for putting a note about that in the PHP APM docs. Thanks!

**Comment by SammyK** [comment]
Very good point - thanks so much for the suggestion! And I'm glad you got it working. I'll put this suggestion into the backlog. :)

**Comment by SammyK** [comment]
This change should show up in the docs sometime today. Thanks again for the suggestion @karllhughes! :)
