### ISSUE TITLE
Not able to find ddtrace-20121113.so

### ISSUE THREAD

**Issue by gitkeat** [DataDog/dd-trace-php#362]
Hi,

I downloaded datadog-php-tracer-0.15.1-1.x86_64.rpm version and run 
`rpm -ivh datadog-php-tracer-0.15.1-1.x86_64.rpm`

When I checked with php -v, it show

`PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/datadog-php/extensions/ddtrace-20121113.so' - /opt/datadog-php/extensions/ddtrace-20121113.so: cannot open shared object file:
 No such file or directory in Unknown on line 0`

From the path, i do not have 20121113 version but other version. I tried to change the path to below existing library but still hit error. Anyone know what the issue.? How I can find the 2012113 version?

PHP Warning:  PHP Startup: ddtrace: Unable to initialize module
Module compiled with module API=20100525
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Existing library 
ddtrace-20100412-debug.so
ddtrace-20100412.so
ddtrace-20131106-debug.so
ddtrace-20131106.so
ddtrace-20131106-zts-debug.so
ddtrace-20131106-zts.so
ddtrace-20151012-debug.so
ddtrace-20151012.so
ddtrace-20151012-zts-debug.so
ddtrace-20151012-zts.so
ddtrace-20160303-debug.so
ddtrace-20160303.so
ddtrace-20160303-zts-debug.so
ddtrace-20160303-zts.so
ddtrace-20170718-debug.so
ddtrace-20170718.so
ddtrace-20170718-zts-debug.so
ddtrace-20170718-zts.so
ddtrace-20180731-debug.so
ddtrace-20180731.so
ddtrace-20180731-zts-debug.so

**Comment by labbati** [comment]
Hi @gitkeat 👋 , which php version you are using? (PHP 5.5?) Please find here supported versions at the moment.

**Comment by gitkeat** [comment]
yes. PHP 5.5.33.
Checked the supported version. Only for 5.4.x and 5.6.x.

Thank for your advice.

**Comment by labbati** [comment]
This is in our radar though, I cannot commit to a date but I think it is coming quite soon.

**Comment by gitkeat** [comment]
Great to hear that. Looking forward for it

**Comment by Shyru** [comment]
Is there any progress on this? Because the Datadog documentation states that Ubuntu 14.04+ is supported and since we use Ubuntu 14.04 with php 5.5.9 it would be great to be able to use it.

**Comment by labbati** [comment]
Hy @Shyru, Ubuntu 14.04+ is supported by our agent and this is not related to the PHP APM tracer. PHP APM tracer do not support 5.5 at the moment and I cannot provide an ETA right now.
