### ISSUE TITLE
Error data not being sent when laravel is in production mode

### ISSUE THREAD

**Issue by atrauzzi** [DataDog/dd-trace-php#400]
In production mode, Laravel by default hides all exception traces to the user by offering up some simplified "an error has ocurred" representation.  Either by HTML, plain text or JSON, it usually knows what to do.  Usually something along the lines of:

> Internal Server Error

Unfortunately, this reduced error info is also all that's being captured in the DataDog portal:

![image](https://user-images.githubusercontent.com/115199/55977081-84b4e780-5c53-11e9-847f-b4b1b3719929.png)

I think it would be more helpful if datadog obtained the true exception stack trace and provided it as the error instead of obtaining what the application is configured to show based on its environment.

These are differentiated as [reportable vs. renderable](https://laravel.com/docs/5.8/errors#renderable-exceptions) errors.

**Comment by labbati** [comment]
Hi @atrauzzi thanks for reporting this issue. This is definitely and unexpected behavior that we want to investigate and fix. This is probably something we can work soon in the upcoming weeks.

**Comment by labbati** [comment]
This issue has long been resolved and I missed completely commenting on this. My apologies for that.
I am closing this for now as the latest released package no longer experience this. Feel free to comment and I will reopen.
