### ISSUE TITLE
PHP 5.6/Zend not working on versions > 0.15.1

### ISSUE THREAD

**Issue by eday69** [DataDog/dd-trace-php#426]
We are currently working with version 0.12.2, but want to upgrade to most current version. 
After multiple tries, we were only able to upgrade up to version 0.15.1; all bigger version caused our system to break.
Currently using PHP 5.6 and Zend 1.1 (yes, old news, but its a huge legacy system).
This is the error we get (its on our side, but if I downgrade to 0.15.1, this error disappears)
`2019-05-01T22:50:51+00:00 ERR (3):
exception 'Icarus\Api\Exception' with message 'An API call failed to complete.' in /vagrant/icarus/source/library/Icar
us/Api/Curl.php:211
Stack trace:
#0 /vagrant/icarus/source/library/Icarus/Api/Curl.php(110): Icarus\Api\Curl->curlCall()`

Any ideas? Would love to upgrade to latest version...
Thanks in advance.

**Comment by labbati** [comment]
Hi @eday69 sorry for the issue. The latest direct change we made to the curl integration is with `0.19.1`. If you have a minute, could you confirm that 0.19.0 works for you and 0.19.1 does not?

Moreover, can you provide a snippet to show us what's going on around `Api/Curl.php:211`? This would help us to figure it out what we are missing.

Thanks in advance

**Comment by eday69** [comment]
Hi @labbati  ! Thanks for the quick reply.
I do not think the issue is with the curl integration itself.
Everything works with 0.15.1, but once I switch to version 0.16.1, things break exactly the same through to version 0.20.0. version 0.21.0  is worse (get very different errors, see below)

I've included the curl call anyways. Line 211 is `throw new \Icarus\Api\Exception...`

`    /**
     * Making the curl call
     *
     * @return \Zend_Http_Response
     *
     * @throws \Exception The response >= 400
     */
    protected function curlCall() {
        $response = $this->client->request();

        // If the response >= 400, log an error and throw an exception.
        if ($response->getStatus() >= \Icarus_Http_Code::BAD_REQUEST) {
            \Zend_Registry::get('log')->err(
                'API error: ' . $this->url . PHP_EOL . $response->getBody()
            );
            throw new \Icarus\Api\Exception('An API call failed to complete.');
        }

        return $response;
    }
`

version 0.21.0 errors:
`Fatal error: Call to undefined function DDTrace\Integrations\PDO\dd_trace_forward_call() in /vagrant/icarus/vendor/datadog/dd-trace/src/DDTrace/Integrations/PDO/PDOIntegration.php on line 81

Fatal error: Call to undefined function DDTrace\dd_trace_disable_in_request() in /vagrant/icarus/vendor/datadog/dd-trace/src/DDTrace/Bootstrap.php on line 37`

**Comment by eday69** [comment]
A bit more info. Testing 0.16.1 - 0.20.0, got this messages:

`<b>Fatal error</b>:  Call to undefined function DDTrace\dd_trace_disable_in_request() in <b>/vagrant/icarus/vendor/datadog/dd-trace/src/DDTrace/Bootstrap.php</b> on line <b>35</b><br ` 
and, if I comment out previous error line, then I get this error:
`<b>Fatal error</b>:  Call to undefined function DDTrace\Encoders\dd_trace_serialize_msgpack() in <b>/vagrant/icarus/vendor/datadog/dd-trace/src/DDTrace/Encoders/MessagePack.php</b> on line <b>18</b>
`

So, for some reason, it is not finding function stated above from releases 0.16.0 forward...hope this helps to figure out my problem.

**Comment by SammyK** [comment]
Hey @eday69! Are you updating the PHP tracer with Composer? If so, have you also [installed the extension from one of the packages again](https://docs.datadoghq.com/tracing/setup/php/#install-the-extension)? If you don't install the extension from one of the packages, none of the new functions that have been added will be available. This is what appears to be the issue with the `Call to undefined function` errors.

Also - if you don't have any custom integrations, you can just install the extension from a package and remove the Composer dependency to ensure the PHP tracer has one "source of truth" for the tracer.

Let us know how it goes! :)

**Comment by eday69** [comment]
@SammyK, many thanks ! You hit the issue right on the nose. I will close this since it is not an issue.

**Comment by SammyK** [comment]
@eday69 Yay! Happy to hear it all worked out! :)

**Comment by gmansilla** [comment]
@SammyK so we shouldn't use composer and just download the precompiled packaged?

thanks.

**Comment by SammyK** [comment]
@gmansilla Yes, my recommendation would be to install the precompiled package. The Composer package was necessary for early development of the tracer and will eventually be phased out. :)

**Comment by gmansilla** [comment]
@SammyK but if I remove the composer package then how am I supposed to set manual tags in my traces? i.e.

    $span = GlobalTracer::get()->getActiveSpan();
    $span->setTag(Tag::SERVICE_NAME, $dataDogServiceName);
    $span->setTag(Tag::RESOURCE_NAME, $dataDogResourceName);
    $span->setTag(Tag::HTTP_METHOD, $httpMethod);

**Comment by SammyK** [comment]
@gmansilla The PHP code ships with the precompiled package so you should still be able to run that code snippet. Let us know if you have any trouble with that! :)
