### ISSUE TITLE
Resources on Datadog Dashboard fail to distinguish individual endpoints

### ISSUE THREAD

**Issue by tatianajiselle** [DataDog/dd-trace-php#427]
Available in other languages supported by DataDog, the resources section in the APM dashboard display the individual endpoints hit via the corresponding service. However, in the PHP APM dashboard, the resource section only displays `web.requests`

current view:
<img width="159" alt="Screen Shot 2019-05-02 at 4 01 03 PM" src="https://user-images.githubusercontent.com/13118794/57112191-cafde380-6cf3-11e9-962b-973d079a114c.png">

expected (example):
<img width="269" alt="Screen Shot 2019-05-02 at 4 03 48 PM" src="https://user-images.githubusercontent.com/13118794/57112210-e4069480-6cf3-11e9-9621-1caf713d03fd.png">

This causes difficultly for filtering endpoints seen in the dashboard, or removing them from APM completely. (For example, removing health check calls).

**Comment by labbati** [comment]
Hi @tatianajiselle, sorry for the confusion here. Actually PHP supports resource differentiation based on route. What you observe is due to the fact that we do not support at the moment your web framework. What web framework do you use?

**Comment by tatianajiselle** [comment]
Ah i understand -- is this feature out on the roadmap for future releases?

we have two services which arent displaying routes. One uses Slim and the other one doesnt really use a framework, just uses php-fpm + php.

**Comment by gmansilla** [comment]
@tatianajiselle one way to accomplish this is by manually setting tags.

I'm not too familiar with Slim but I'd guess it has a class/service that processes routes (or even callbacks?). So, you would do something like this



    $dataDogServiceName = 'MyService'; //you would get this value dynamically 
    $dataDogResourceName = 'MyResource'; //same as above, I usually just grab the current uri
    $span = GlobalTracer::get()->getActiveSpan();
    $span->setTag(DDTrace\Tag\Tag::SERVICE_NAME, $dataDogServiceName);
    $span->setTag(DDTrace\Tag\Tag::RESOURCE_NAME, $dataDogResourceName);

**Comment by labbati** [comment]
Hi everybody. In addition to what @gmansilla correctly point that support for Slim framework is due in the next one week or two.

In addition to that, we would also like to let you know that we are currently working to a generic request uri -> resource mapping that will automatically:

- Url: `http://example.com/users/123/permissions` --> Resource: `GET /users/?/permissions`
- Url `http://example.com/users/<UUID>/permissions` --> Resource: `GET /users/?/permissions`
- Also we will provide a way to map path fragments that are not able to recognize,. e.g. to automatically map URI `/some/new_york/place` to resource name `GET /some/?/place`.

This is due in the upcoming week or two.

**Comment by SammyK** [comment]
Just a heads up that #442 is under review and adds the functionality that @labbati described. I'll update this thread once it has been rolled into a release. :)

**Comment by labbati** [comment]
This functionality has been shipped, closing now, please @tatianajiselle feel free to open it back if you fell like it does not address entirely your requirements.
