### ISSUE TITLE
Lumen Integration not registering Services/Resources based on routes

### ISSUE THREAD

**Issue by gmansilla** [DataDog/dd-trace-php#438]
I'm not sure if this is a bug or something that I'm doing wrong.

I tried this in my current lumen 5.2 app and on a brand new Lumen 5.8.4 app.

In both cases requests are being recorded on APM under "Lumen" Service and either "web.request" or "unnamed_route" Resources.

**Comment by labbati** [comment]
Hey @gmansilla thanks for reporting this. Do you do any special configuration for resource names? I am asking because we have integration tests that correctly report resource names, so I think this is a use case we do not properly cover, but it may be a little bit hard to find. If you could provide us with any additional detail it would be great.

**Comment by SammyK** [comment]
Hey @gmansilla! Also - what version of the PHP tracer are you using? Lumen support was just added in the latest release of `0.23.0`. :)

**Comment by gmansilla** [comment]
@SammyK yes Sammy, that's the version I'm using. I'm going to document my findings and post it here soon.

**Comment by gmansilla** [comment]
Ok, here's what I found:

1. "unnamed_route" is not a bug, it's a [feature](https://github.com/DataDog/dd-trace-php/blob/0.23.0/src/DDTrace/Integrations/Lumen/V5/LumenIntegrationLoader.php#L37) :). 

Basically, with this route
    
    $router->get('/foo', function () {
         return 'Hello World';
    });

the resource will be registered as "unnamed_route" whereas with this route

    $router->get('foo', ['as' => 'foo', function () {
        return 'hello';
     }]);
 
the resource will be registered as "GET foo". 

Whether "/foo" should be registered as "unnamed" or not I'll leave up to you guys. I feel like we could just parse the uri an use it as the resource name? idk. 

2. Here's is where I don't know if we have a bug.

Before 0.23.0 added Lumen support I was doing manual instrumentation as described [here](https://github.com/DataDog/dd-trace-php/issues/427#issuecomment-492257683). My instrumentation is taking place in a custom RouteService we built (right after a route has been found and just before a controller is instantiated).

The problem I'm facing now (and I'm more than open to refactor my code if necessary) is the way `LumenIntegrationLoader` traces `Laravel\Lumen\Application::dispatch`; Basically it is [calling](https://github.com/DataDog/dd-trace-php/blob/0.23.0/src/DDTrace/Integrations/Lumen/V5/LumenIntegrationLoader.php#L36) Lumen's dispatcher (which at some point executes my manual instrumentation) and then [overwrites](https://github.com/DataDog/dd-trace-php/blob/0.23.0/src/DDTrace/Integrations/Lumen/V5/LumenIntegrationLoader.php#L46) my resource name tag.

That being said, I think [dd_trace_forward_call](https://github.com/DataDog/dd-trace-php/blob/0.23.0/src/DDTrace/Integrations/Lumen/V5/LumenIntegrationLoader.php#L36) should be called at the very [end](https://github.com/DataDog/dd-trace-php/blob/0.23.0/src/DDTrace/Integrations/Lumen/V5/LumenIntegrationLoader.php#L47) just like it is done in the [Laravel Integration](https://github.com/DataDog/dd-trace-php/blob/0.23.0/src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php#L48).

Finally, it caught my attention that the resource name tag is being set during `Laravel\Lumen\Application::dispatch` and not right after a route has been found (just like you guys do with the [Laravel Implementation](https://github.com/DataDog/dd-trace-php/blob/0.23.0/src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php#L33). In my opinion (and I might be wrong) the instrumentation should happen when a route has been found, either [here](https://github.com/laravel/lumen-framework/blob/5.8/src/Concerns/RoutesRequests.php#L243) or [here](https://github.com/laravel/lumen-framework/blob/5.8/src/Concerns/RoutesRequests.php#L273)

**Comment by SammyK** [comment]
Wow - thanks so much for digging into this and providing the detailed report @gmansilla! :)

> Whether "/foo" should be registered as "unnamed" or not I'll leave up to you guys. I feel like we could just parse the uri an use it as the resource name? idk.

Very good point. With #442 under review, certainly falling back to a sane default vs `unnamed_route` would be better in these cases. I'll update that PR based on your findings - thanks so much for that suggestion! :)

> That being said, I think dd_trace_forward_call should be called at the very end just like it is done in the Laravel Integration.

The reasoning behind forwarding the call early was to access `$this->currentRoute`. But as you pointed out:

>  In my opinion (and I might be wrong) the instrumentation should happen when a route has been found, either here or here

I agree! That would be a better place to add the route/resource tags and wouldn't overwrite your custom implementation. I'll submit a separate PR and tag you in it so you can follow along if you like. :)

Thanks again for taking the time to dive so deeply into the tracer @gmansilla! :)

**Comment by bwoebi** [comment]
Given that PR 442 has been merged long ago, and we are not overloading the Lumen Application dispatch() anymore, but handleFoundRoute, I think the problem (2.) exposed here has been fixed long ago and I'll close the issue thus.

If you think this has been closed in error, feel free to comment.
