### ISSUE TITLE
Programatically control tracing?

### ISSUE THREAD

**Issue by joker806** [DataDog/dd-trace-php#454]
Hi,

is it possible to programatically control tracing? Currently we have two possible use cases for that:

1. Enable tracing only for certain URLs - we have single entry script that is launched for every request, including health checks, which I would like to completely exclude from tracing.

2. We have RabbitMQ consumer script processing multiple messages in single run. I would like to each message to be separate trace. Similar use case is I think also for ReactPHP where multiple web requests are handled by single script run.

Or maybe is there a better way how to handle these?

**Comment by SammyK** [comment]
Hey @joker806!

1. You can exclude specific URI's from the Agent level [by setting `DD_APM_IGNORE_RESOURCES`](https://docs.datadoghq.com/agent/docker/apm/?tab=java#docker-apm-agent-environment-variables) (i.e. `DD_APM_IGNORE_RESOURCES="GET health-check"`)

2. Support for multiple traces within a single request is not supported. The use case you've provided is a good one and I've added your suggestion to our backlog. Thanks for that! :)
