### ISSUE TITLE
URL normalization mangles path version

### ISSUE THREAD

**Issue by vnwhlr** [DataDog/dd-trace-php#455]
First, thanks for introducing #442 - this solves a major headache for us.

However, our service's versioning scheme uses the path, so we end up with URIs like `/v1.0/users/1414`, and when the default substitution patterns are applied, we end up with resources that look something like `/v1.?/users/?`. 

Is there a clever pattern for excluding the version, but still performing the substitution on identifiers? If not, could versions be excluded from the default substitution patterns? Otherwise, we'd have to provide custom substitution patterns for all routes (and we have upwards of 100 of them).

**Comment by SammyK** [comment]
Hey @vnwhlr! I'm glad to hear #442 was useful for you! :)

You can customize the URL mapping using the `DD_TRACE_RESOURCE_URI_MAPPING` environment var. There are two wildcards `*` (match & substitute) & `$*` (just match). So in your case you could set `DD_TRACE_RESOURCE_URI_MAPPING=/v$*/users/*` which will generate a resource name of `GET /v1.0/users/?`.

Let us know if you run into any issues with it! :)

**Comment by labbati** [comment]
We should probably handle this in a more smart way. @SammyK I am reopening this issue to proceed a conversation around this.

Assuming common scenarios like `/v1.0/users`, `/v1.0/something`, we would end up having to register tens if not hundreds of special cases. Let's instead only replacing pure integers so cases like these are handled. What do you think?

**Comment by labbati** [comment]
Initially I misundestood the problem, my concern not becomes: let's make sure that if we have `DD_TRACE_RESOURCE_URI_MAPPING=/v$*/` then
- `/v1.0/users/1414` goes to `GET /v1.0/users/1414`
- `/v1.1/somethingelse/123` goes to `GET /v1.1/somethingelse/?`

If this is true then I think that this case is convered. WDYT?

**Comment by SammyK** [comment]
Thanks for reopening this @labbati! My apologies for misunderstanding the original issue @vnwhlr.

We should have a patch for this issue very soon. I'll update this thread when we have released it. :)

**Comment by SammyK** [comment]
Hey @vnwhlr! We just released [version `0.26.0` of the PHP tracer](https://github.com/DataDog/dd-trace-php/releases/tag/0.26.0) which contains a patch for this issue. Whenever you get a chance to update and confirm this issue has been resolved for you, we'll close this issue out.

Thanks for reporting this and my apologies again for misunderstanding the issue at first! :)

**Comment by vnwhlr** [comment]
@SammyK Works perfectly! Thanks for the quick response, keep crushing it 👍

**Comment by SammyK** [comment]
@vnwhlr Wonderful! Thanks for the cheers! :) Let us know if you run into any more issues.
