### ISSUE TITLE
Nette framework integration

### ISSUE THREAD

**Issue by kozaktomas** [DataDog/dd-trace-php#489]
Hi,

we are using Nette framework for our projects and it would be nice to have integration. I can prepare PR here. But the question is, are you going to support frameworks like Nette in this repository?

Thanks!

Nette framework: https://github.com/nette/nette

**Comment by labbati** [comment]
Hi @kozaktomas and thanks for you  patience on this issue.
Of course feel free to provide an  integration  and you can use either Laravel or Symfony one as a template.

Even before that, I would recommend you see if generic web framework support can work for you. It is on by default.

Also a couple of experimental features that will likely make into official  support are:

`DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED=true` that will use the URI as resource names.
