### ISSUE TITLE
New MongoDB driver integration

### ISSUE THREAD

**Issue by prasantkrsuman** [DataDog/dd-trace-php#501]
Hi,

We have migrated our symfony apps to use new mongodb drivers https://pecl.php.net/package/mongodb with https://github.com/mongodb/mongo-php-library and we found that we were not having mongo traces. When i checked then i found that integration for them are missing.

We are really missing those mongodb traces for our apps as it help us a lot. 

We are open to contribute to integration.

Thanks!

**Comment by SammyK** [comment]
Hey @prasantkrsuman! The tracer currently only instruments [ext/mongo](https://pecl.php.net/package/mongo) but we are working to provide more integrations soon. Thanks for the offer to contribute the integration. We'd love to take you up on that offer! :)

**Comment by brunopadz** [comment]
Any news on that @SammyK? We're depending on that to use DD as our main APM solution.

**Comment by labbati** [comment]
Hi @brunopadz unfortunately we are wrapping up other tasks and refactoring and I cannot guarantee we can start working on this in the very short term. Your best option here is to each out to our [support team](https://docs.datadoghq.com/help/) and notify them about the missing integration, so we can prioritize.

**Comment by sureshgf** [comment]
Any news on this to support the mongodb extension

**Comment by KTamas** [comment]
This was a dealbreaker for us as well as we are using the new mongodb extension as well. Makes me sad because otherwise I really liked Datadog.

**Comment by morrisonlevi** [comment]
I'm looking at [mongodb/mongo-php-library](https://github.com/mongodb/mongo-php-library) and it appears the extension is still required. To clarify: when both the library and extension are installed you don't see _any_ mongo spans at all? Or just missing the higher-level spans from the library?

**Comment by brunopadz** [comment]
> This was a dealbreaker for a client of mine as well as they are using the new mongodb extension as well. Makes me sad because otherwise I really liked Datadog.

Yeah, we had the same issue last year when we begun looking for New Relic alternatives.

The solution we founde is to instrument the application with OpenTracing. We're working on it right now, but we're asking for a big fat discount because of that.

**Comment by labbati** [comment]
@brunopadz happy to know you are interested in this driver. Would you be interested in contributing an integration into the our code base so it can be beneficial to the entire community? If you are interested I can improve our docs for how to contribute a new integration.

**Comment by brunopadz** [comment]
> @brunopadz happy to know you are interested in this driver. Would you be interested in contributing an integration into the our code base so it can be beneficial to the entire community? If you are interested I can improve our docs for how to contribute a new integration.

I could contribute, but I'm not a PHP developer lol.

We're using OpenTracing to get mongo traces as well redis using phpredis which is also not supported, so we don't have to wait for these integrations and could use an open source solution like Jaeger in the future.

**Comment by maxperrimond** [comment]
Hi,
I saw a recent integration for `mongodb` has been added (https://github.com/DataDog/dd-trace-php/pull/1345) but doesn't seem to work with a default configuration or neither with env vars, is there a way to enable it or is it not ready yet ?

**Comment by labbati** [comment]
@maxperrimond the new integration has been released and you should already see spans on >0.67.0. Which version of mongodb/php are you on?

**Comment by labbati** [comment]
In the meantime I am going to close this issue as the original request has been fulfilled on PHP 7 and PHP 8 and we have no plans at the moment to backport the integrations to PHP 5.

**Comment by maxperrimond** [comment]
@labbati Our current images are using mongodb extension `1.8` with php `7.4.22`. Is there a minimum version support for it ?

**Comment by labbati** [comment]
Thanks for letting me know, yeah that definitely makes sense. Enjoy Datadog APM
