### ISSUE TITLE
Not able to generate .so file show error

### ISSUE THREAD

**Issue by ask664** [DataDog/dd-trace-php#508]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/ddtrace.so' - /usr/lib/php/20160303/ddtrace.so: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by SammyK** [comment]
Hey @ask664! What is the OS name and version and what is the PHP version? Also, how did you install the ddtrace extension? The recommended way is via [the precompiled packages](https://docs.datadoghq.com/tracing/setup/php/#install-the-extension).

**Comment by ask664** [comment]
OS - ubuntu 16.04
PHP  - 7.1
I already follow this link but when I run this command then showing me error =>  php --ri=ddtrace

**Comment by viktor-lisevich** [comment]
have the same problem 
OS - ubuntu 16.04
PHP - 7.2
On version 7.3 tracer work properly. 
If switch to 7.2 and install datadog-php-tracer once again with recompiled packege, tracer dont work, can anybody help with the issue ?

**Comment by labbati** [comment]
Closing this issue as it is stale. @ask664 if you still experience any issues please comment here and I will reopen it for you.
