### ISSUE TITLE
PDO: Prepared statements not released/deallocated

### ISSUE THREAD

**Issue by The-Sorce** [DataDog/dd-trace-php#510]
Prepared SQL statements are automatically released by PDO on the database connection (i.e. on MySQL using `DEALLOCATE PREPARE`) when the last reference to the `PDOStatement` is unset. Under certain circumstances, dd-trace-php prevents this from happening.

For persistent/long-lived PHP processes, this will cause unexpected behavior in terms of leftover prepared statements on the database server. This can be observed directly on the database with commands such as `SHOW GLOBAL STATUS LIKE 'prepared_stmt_count';`. In specific test cases I saw this issue triggering `1461 Can't create more than max_prepared_stmt_count statements` database errors.

Environment prerequisites:
- PHP (tested with versions 5.6.40 as well as PHP 7.3.6)
- dd-trace-php (tested with version 0.29.0)
- MySQL/MariaDB database server (version N/A)
- Composer autoloader (without any specific dependencies, i.e. a freshly initialized Composer project is enough)
- PDO:s emulation of prepared statements must be disabled (i.e. the PDO option `PDO::ATTR_EMULATE_PREPARES` must be set to false)

Please see the following PHP sample code with which this issue can be recreated:
```
<?php

// A Composer autoloader (please provide your own) is for some unknown reason required to recreate the issue.
require_once __DIR__ . '/vendor/autoload.php';

// Please provide your own DB credentials. Also, modify the SQL statements below (specifically any_table, foo, bar) into
// some valid select in your specific environment.

$host = '127.0.0.1';
$port = 3306;
$dbname = 'test_db';
$username = 'mysql';
$passwd = 'secret';

$dsn = 'mysql:host='.$host.';port='.$port.';dbname='.$dbname;
$options = [PDO::ATTR_EMULATE_PREPARES => false]; // Important! PDO's preparation emulation is unaffected by this issue.
$pdo = new PDO($dsn, $username, $passwd, $options);

// Example 1: The prepared statement should be deallocated when the $prep variable is unset.
$prep = $pdo->prepare("SELECT * FROM any_table WHERE foo = :foo");
$prep->execute(['foo' => 'bar']);
unset($prep); // The last reference to the PDOStatement instance is removed

// Example 2: The prepared statement should be deallocated immediately after execution, as no reference to the
// PDOStatement instance is available anywhere.
$pdo->prepare("SELECT * FROM any_table WHERE foo = :foo")->execute(['foo' => 'bar']);

var_dump($pdo->query("SHOW SESSION STATUS LIKE 'Com_stmt_close'")->fetchColumn(1));
// Expected value (with dd-trace-php disabled): 2
// Returned value (with dd-trace-php enabled): 0
```

**Comment by SammyK** [comment]
Thank you for the detailed report @The-Sorce!

We're able to replicate this issue on our end and will update this thread as soon as we are able to provide a patch. Until that time, you can temporarily disable the PDO integration by [setting the following environment variable](https://docs.datadoghq.com/tracing/setup/php/#configuration): `DD_INTEGRATIONS_DISABLED=pdo`.

**Comment by pawelchcki** [comment]
Thanks again for the report @The-Sorce!
We've just released https://github.com/DataDog/dd-trace-php/releases/tag/0.30.1 which contains the fix that will ensure the resources are freed when expected.

Let us know if it solves your problem.

**Comment by The-Sorce** [comment]
Thank you @SammyK and @pawelchcki! I have tested with release 0.30.1 and I can confirm that this bug is now fixed and this issue can be closed. Thank you very much!
