### ISSUE TITLE
pfp-fpm hangs after a short period of time if using laravel terminate

### ISSUE THREAD

**Issue by gsaqui** [DataDog/dd-trace-php#513]
I have been able to reproduce the issue with the following project https://github.com/gsaqui/datadog-bug.  If you build the docker container and spin it up after 800+ requests php-fpm hangs.  This only happens when you have the datadog php tracer running.  If you remove the tracer from the Dockerfile the php-fpm never hangs.

The project is very simple the only thing that was added was the Dockerfile and a terminable middleware.

**Comment by SammyK** [comment]
Hey @gsaqui! Thanks for the report and for the link to the project to reproduce the issue. :)

I just wanted to confirm that this issue appears when using terminable middleware [like this middleware example](https://github.com/gsaqui/datadog-bug/blob/e5b5a60e64153270323766b502fc5f428108a024/app/Http/Middleware/ClosureMiddleware.php#L17-L20) you provided?

**Comment by gsaqui** [comment]
Yes that is correct.

**Comment by gsaqui** [comment]
@SammyK I upgraded the example app to 0.30 and it seems to have fixed the issue.  If you are happy feel free to close this issue.

**Comment by SammyK** [comment]
@gsaqui That's great to hear! Thanks for the update. :)
