### ISSUE TITLE
Can't figure out how to change resource names on a Symfony v4 app

### ISSUE THREAD

**Issue by rodrigodiez** [DataDog/dd-trace-php#514]
Hi Datadog!

I've been struggling to get a simple change in the name of the resource for the root span on a Symfony v4 app.

Some info about my setup

```
dd-trace extension v0.29.0
dd-trace php library v0.29.0
symfony 4.3
```

I want to change the name of the resource on certain requests so that they get ignored (requests coming from an acceptance test suite that triggers error I want to avoid alerts on)

I read in another issue that the best strategy is to place my code on the kernel.terminate event so I created a listener for it, with low priority. But it seems that the resource name always comes empty and despite of my changing it, it does not work (I have the feeling your extension kicks after my code, or maybe I am not grabbing the right span)

This is my services.yml, I use a factory to get the Tracer (so that the code of my listeners is testable):

```
    DDTrace\Contracts\Tracer:
        factory: ['DDTrace\GlobalTracer', 'get']

    App\EventListener\TraceRemapListener:
        arguments:
            $headerName: 'X-DD-Remap-Trace'
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate, priority: -255 }
```

This is my remapper

```
    public function onKernelTerminate(PostResponseEvent $event)
    {
        $request = $event->getRequest();
        $resource = $request->headers->get($this->headerName);

        if (null === $resource) {
            return;
        }

        $this->logger->warning(sprintf('Remapping trace to resource %s', $resource));

        $rootScope = $this->tracer->getRootScope();
        if (null !== $rootScope) {
            $rootSpan = $rootScope->getSpan();
            $this->logger->info(sprintf('Root Span resource is currently %s', $rootSpan->getTag(Tag::RESOURCE_NAME)));
            $this->logger->info(sprintf('Symfony route is currently %s', $rootSpan->getTag('symfony.route.name')));

            $rootSpan->setResource($resource);
            $rootSpan->setTag('symfony.route.name', $resource);
            $this->logger->info(sprintf('Remapped trace to resource %s', $resource));
        } else {
            $this->logger->warning('Tried to remap trace but root span could not be obtained');
            return;
        }
    }
```

Code is being triggered and runs fine, but resource name is not changed nor I can find the previous resource name:

```
api_1     | {"message":"Remapping trace to resource /dev/null [dd.trace_id=1293830805587557805 dd.span_id=1293830805587557805]","context":[],"level":300,"level_name":"WARNING","channel":"app","datetime":{"date":"2019-07-26 13:17:52.108934","timezone_type":3,"timezone":"UTC"},"extra":[],"service":"*****","env":"*****"}
api_1     | {"message":"Root Span resource is currently  [dd.trace_id=1293830805587557805 dd.span_id=1293830805587557805]","context":[],"level":200,"level_name":"INFO","channel":"app","datetime":{"date":"2019-07-26 13:17:52.109108","timezone_type":3,"timezone":"UTC"},"extra":[],"service":"*****","env":"*****"}
api_1     | {"message":"Symfony route is currently  [dd.trace_id=1293830805587557805 dd.span_id=1293830805587557805]","context":[],"level":200,"level_name":"INFO","channel":"app","datetime":{"date":"2019-07-26 13:17:52.109213","timezone_type":3,"timezone":"UTC"},"extra":[],"service":"*****","env":"*****"}
api_1     | {"message":"Remapped trace to resource /dev/null [dd.trace_id=1293830805587557805 dd.span_id=1293830805587557805]","context":[],"level":200,"level_name":"INFO","channel":"app","datetime":{"date":"2019-07-26 13:17:52.109298","timezone_type":3,"timezone":"UTC"},"extra":[],"service":"*****","env":"*****"}
```

Am I missing something?

**Comment by SammyK** [comment]
Hey @rodrigodiez! Thanks for providing all these details.

I believe what is happening is that the root span is already closed by the time the `kernel.terminate` event is fired. This means we have to explicitly set a tag after the span has already closed from the third argument to `setTag()`. So you could change this line:

```php
$rootSpan->setResource($resource);
```

To this:

```php
$rootSpan->setTag(Tag::RESOURCE_NAME, $resource, true);
```

Let us know if you still have issues with it. :)

**Comment by rodrigodiez** [comment]
Thanks! We also tried the same code on kernel.request instead of kernel.terminate with no difference.

Will try your snippet and come back to you!

**Comment by rodrigodiez** [comment]
@SammyK unfortunately that only worked partially.

Requests seem to be ignored due to the resource being remapped to an ignored one and they don't show anymore in the requests/error panel (as desired)

However traces still appear with the old resource name, and requests seem to count against the latency panel as well

What I am trying to achieve is to totally ignore some requests to APM's eyes because they come from an acceptance test suite that deliberately triggers errors and high latency to test the API behaviour


Attaching screenshots for the request/error/latency panels and the traces panel for the same time period

![Screenshot 2019-07-31 at 09 37 41](https://user-images.githubusercontent.com/823685/62196958-e8842d00-b376-11e9-8716-a11c481bbf5f.png)
![Screenshot 2019-07-31 at 09 37 35](https://user-images.githubusercontent.com/823685/62196959-e8842d00-b376-11e9-9f6a-24ae326c20d5.png)

**Comment by labbati** [comment]
Relates to #343

**Comment by labbati** [comment]
I am closing this issue as it is stale. Please feel free to comment if you are still experiencing this problem and I will reopen it for you.

To sum up:
 - in order to rename resources you can use this: https://github.com/DataDog/dd-trace-php/issues/514#issuecomment-516197089
 - then resources can be ignored in the datadog agent (not the php tracer): see env `DD_APM_IGNORE_RESOURCES ` from https://docs.datadoghq.com/agent/docker/apm/?tab=standard#docker-apm-agent-environment-variables
