### ISSUE TITLE
Redis cluster issue

### ISSUE THREAD

**Issue by dortort** [DataDog/dd-trace-php#515]
Getting the following error from PHP APM agent:

`[Tue Jul 30 06:23:44.391285 2019] [:error] [pid 8735] [client 172.31.25.132:45958] PHP Catchable fatal error:  Object of class Predis\\Connection\\Aggregate\\RedisCluster could not be converted to string in /opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/Predis/PredisIntegration.php on line 225`

https://github.com/DataDog/dd-trace-php/blob/458f38a26c394569d2fc7b309dbf1290581c8ecc/src/DDTrace/Integrations/Predis/PredisIntegration.php#L225 ?

**Comment by SammyK** [comment]
Thank you for the reporting this issue @dortort!

This is part of a known bug and we are working on a patch for it. We will update this thread as soon as we are able to provide a patch. Until that time, you can temporarily disable the Predis integration by [setting the following environment variable](https://docs.datadoghq.com/tracing/setup/php/#configuration): `DD_INTEGRATIONS_DISABLED=predis`.

**Comment by blackstar257** [comment]
+1

**Comment by blackstar257** [comment]
Any updates on this?

**Comment by SammyK** [comment]
Hey @blackstar257! We should be rolling out a release with a fix for this (from #574) early next week. :)

**Comment by SammyK** [comment]
Hey @dortort and @blackstar257! A fix for this has been rolled into the [latest release](https://github.com/DataDog/dd-trace-php/releases), `0.31.0`. Does upgrading to the latest version of the tracer resolve this issue for you?

**Comment by labbati** [comment]
Hi @dortort I am closing this issue for now as per our tests the issue has been resolved. If you have a chance to verify with your setup it would be great. Thank you for you patience.
