### ISSUE TITLE
Improve documentation adding steps to upgrade/update the extension

### ISSUE THREAD

**Issue by brandonburkett** [DataDog/dd-trace-php#533]
Hi, I see the installation notes here: https://docs.datadoghq.com/tracing/setup/php/

But I did not see any update / upgrade documentation (EX: downloading new rpm, install, stoping php-fpm, etc).

Same with removing (there was a previous GH issue that mentioned needing to remove symlinks as well as the package).

Thanks
Brandon

**Comment by SammyK** [comment]
Thanks for the excellent suggestion @brandonburkett! We've got this on the radar and we will ping you from here when the documentation has been updated. :)

**Comment by brandonburkett** [comment]
Hi, I wanted to check in on this as we recently received the email regarding `0.30.2` and `open_basedir`.  Is there official update / upgrade documentation (EX: downloading new rpm, install, stoping php-fpm, etc).

Thanks
Brandon

**Comment by SammyK** [comment]
Hey @brandonburkett! Thank you so much for following up on this. We just updated the documentation with [upgrading instructions](https://docs.datadoghq.com/tracing/setup/php/#upgrading). Let us know if you have any issues with upgrading! :)

**Comment by brandonburkett** [comment]
Thanks!  Feel free to close this one out.
