### ISSUE TITLE
Remove temp workaround for Drupal DBAL bug?

### ISSUE THREAD

**Issue by emsearcy** [DataDog/dd-trace-php#539]
The change introduced in #285 to disable PDO integration for Drupal says it can be removed once #284 is resolved ... which it is now.  Is it safe to re-enable PDO for Drupal?

(Yes, I'm using Drupal 7 and hoping to have at least have generic instrumentation, even without framework support, but missing DB spans makes it a non-starter.)

**Comment by labbati** [comment]
@emsearcy thanks for pinging us on this. In theory it should work now but to be honest we did not have the time to setup and test a drupal 7 sample web app to test it out.

If you have a *local* development environment it would be incredibly valuable for us if you could just turn it on for fun and provide us with some feedback.

**Comment by emsearcy** [comment]
I hadn't revisited this in awhile, but I just tested and deployed an upgrade to 0.45.2. PDO spans are showing up in my Drupal traces fine, even though #793 hasn't been merged yet.  I think maybe this is because the "sandboxed" PDO is now being used? In any case, this issue is resolved for me now.  Sorry I wasn't able to provide more testing of the actual code path in . At the time, attempting to compile dd-trace-php myself was a blocker.

**Comment by labbati** [comment]
Thanks for confirming @emsearcy. closing the issue as this has been long gone obsolete as now everything is enabled back.
