### ISSUE TITLE
Laravel6 support

### ISSUE THREAD

**Issue by jacksuzuki** [DataDog/dd-trace-php#567]
Everything went well when my apps used Laravel 5.8; but after we upgraded  them to Laravel 6, no logs are shown in Datadog APM dashboard.

**Comment by labbati** [comment]
Hi @jacksuzuki, thanks for reporting this. Just to make sure:

> no logs are shown in Datadog APM dashboard

1. Do you have log collection enabled and logs are not appearing anymore?
2. Or by logs you mean traces?

In the first case how is logging configured in both laravel and our agent?
In the second case I am surprised as you should see at least the default web request tracing. So in this latter case I'll need a few more info to look into this.

**Comment by morrisonlevi** [comment]
Hey, @jacksuzuki, just following up. To clarify, you aren't seeing any spans or traces at all on Laravel 6? Laravel 6 isn't supported, so it's not surprising that Laravel related spans are missing, but we would expect to see generic traces for the root span (e.g. web.request) as well as pdo or other database related spans.

**Comment by brandonburkett** [comment]
I have not updated to Laravel 6 yet, but this is one (of many) things I am waiting for official support to drop.  Laravel 6.3 was released last week.  Is there a tentative timeline on the php tracer roadmap for Laravel 6.x support?

Thanks!

**Comment by labbati** [comment]
Hi @jacksuzuki, while Laravel 6 is in our radar, at the moment we cannot provide any detailed ETA as we are focusing on other features. As @morrisonlevi correctly said, though, you should have already a pretty decent tracing support using our generic web framework (active by default).

I'd suggest to also set the env `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED=true` in order to have a nicer separation by url. (Note, we are working to enable by default this latest feature as part of the current sprint).

**Comment by HSken** [comment]
Same issue, don't see any relevant data in APM of PHP of our application, only PDO, CURL, GRUZZLE.

But not a single PHP function or anything laravel related.

**Comment by brandonburkett** [comment]
Laravel is at v6.6.x now, is there an updated ETA on where this is on the php tracer roadmap?  It is one of the reasons I am still on 5.8.x.

**Comment by snags88** [comment]
We just upgraded to Laravel 6 and we ran into the same issue as well. With Laravel 7 coming out next month, shouldn't this issue be resolved by now? Wondering what we need to do to fix this so we can continue using Datadog. Otherwise, we have to look into other services.

**Comment by labbati** [comment]
Hi @snags88, this PR https://github.com/DataDog/dd-trace-php/pull/700  has been  merged  and it supports L6+. This will  released  early next week.

**Comment by snags88** [comment]
@labbati Awesome, thanks so much!

**Comment by brandonburkett** [comment]
@labbati confirming it is live as I plan to upgrade to laravel 6 this week.

**Comment by labbati** [comment]
@brandonburkett just to make sure, you are confirming you tested it and it works fine for you?

**Comment by brandonburkett** [comment]
No, I am in the process of updating (to Laravel 6) and the updated tracer is the last on my list to update. I wanted to confirm it was released (this issue is still open).

**Comment by labbati** [comment]
Thanks for clarifying. Laravel 6 works but I leave this open as we want to
extract even more internals useful info from it.

Il mar 11 feb 2020, 18:40 Brandon Burkett <notifications@github.com> ha
scritto:

**Comment by brandonburkett** [comment]
@labbati Things are working well in our staging env (0.39.2-1).  We are able to see requests (including route names from laravel), elastic search, guzzle, etc.

**Comment by brandonburkett** [comment]
Last of my feedback, been running in production now for over a week and has been just as good as Laravel v5.8 support.  This page can probably be updated to mention Laravel 6.x support: https://docs.datadoghq.com/tracing/setup/php/

**Comment by junmajeff** [comment]
Just updated to laravel 6 and found we could not get `laravel.user`.

https://github.com/DataDog/dd-trace-php/blob/1c449b7e47ec922643082d8d9fdd1dff77b66f88/src/DDTrace/Integrations/Laravel/LaravelIntegration.php#L66-L77

**Comment by bwoebi** [comment]
We've been supporting Laravel 6 for over 3 years now. Closing this issue thus. Please create a new issue if any functionality is missing.
