### ISSUE TITLE
Traces not forwarded to DataDog agent when PDO integration is enabled

### ISSUE THREAD

**Issue by bgaillard** [DataDog/dd-trace-php#595]
Hi, we're new to DataDog and try to setup the PHP tracer extension.

In our application each time a Web request implies a call to PDO it seems that the traces are not forwarded to the DataDog agent.

Our observations are the following.

* Requests associated to "static pages" (i.e pages generated using PHP with our templating system) are correctly forwarded to the DataDog agent, we view the associated traces in the DataDog UI ; 
* Each time a request leads to a request with PDO we see trace logs in our application logs (when `DD_TRACE_DEBUG` is enabled) but we do not see any associated logs in the `/var/log/datadog/trace-agent.log` file (i.e the logs file associated to the DataDog agent)
* If we add `DD_INTEGRATIONS_DISABLED=pdo` as an environment variables the traces seems to be forwarded correctly to the DataDog agent and we view the traces in the DataDog UI ; 
* I also tried to set `DD_TRACE_SANDBOX_ENABLED=false` (as explained in https://github.com/DataDog/dd-trace-php/pull/538) but this has no effect (traces are still not forwarded to the DataDog agent).

Our environment is the following.

* DataDog Agent v6.14.1
* PHP 7.3.9
* Symfony 4.3.4

So I think the problem is clearly linked to the PDO integration, but what's strange is that we see logs which "seems to be normal" in our application logs.

Is this a known problem (for now we simply disabled the PDO integration to make it work) ?

**Comment by morrisonlevi** [comment]
Welcome to Datadog, and sorry you are having issues. A few questions:

- When the PDO integration is enabled, is your application crashing or is the integration simply malfunctioning?
- Can you run the src/dd-doctor.php script from your web server and share the results? It's important that this is run through the actual webserver and not just the PHP CLI. This will help us detect any misconfigurations.

**Comment by bgaillard** [comment]
Hi @morrisonlevi and thanks for your reactivity on this case.

> When the PDO integration is enabled, is your application crashing or is the integration simply malfunctioning?

My application is not crashing and works as expected but the traces seems to not be transmitted to the Datadog agent (the trace agent log file do not contain lines associated to pages use PDO).

I can see logs associated to traces on the PHP tracer side. I suppose their is something broken  just before the traces should be sent to the Datadog agent. 

When traces are correctly sent to the  Datadog agent (i.e from a page which do not use PDO) I see the following 3 logs.

```
NOTICE: PHP message: [2019-09-30T19:15:45+00:00] [ddtrace] [debug] - About to send trace(s) to the agent
NOTICE: PHP message: [2019-09-30T19:15:45+00:00] [ddtrace] [debug] - Traces successfully sent to the agent
NOTICE: PHP message: [2019-09-30T19:15:45+00:00] [ddtrace] [debug] - New span web.request web.request recorded.
```

But I do not see those logs on pages which load data from our database and use PDO.

> Can you run the src/dd-doctor.php script from your web server and share the results?

Here is the result on the script on the server.

```
DataDog trace extension verification

- PHP version and SAPI                       [7.3.9 - fpm-fcgi]
- ddtrace extension installed                [OK]
- ddtrace version (installed)                [0.30.2]
- ddtrace version (const)                    [0.30.2]
- ddtrace version (userland)                 [0.30.2]
- ddtrace versions in sync                   [OK]
- dd_trace() function available              [OK]
- dd_trace_env_config() function available   [OK]
- ddtrace.request_init_hook set              [OK]
- ddtrace.request_init_hook reachable        [OK]
- ddtrace.request_init_hook has run          [OK]
- IntegrationsLoader exists                  [OK]
- Integrations not loaded yet                [OK]
- Registering an autoloader...
- Integrations loaded                        [OK]
- DDTrace\Tracer class exists                [OK]
- Configured Agent host                      [datadog-agent]
- Configured Agent port                      [8126]
- Agent can receive traces                   [OK]
```

I think everything is correct with my configuration.

**Comment by morrisonlevi** [comment]
When you grep for `TRACE` in the agent's logs, does it report any spans being dropped?

We are working on release 0.31 today. We migrated the PDO integration to use the new sandbox API. There have been some other improvements too, and we think there may be a decent chance that this issue will just go away on version 0.31. If not, we can continue to debug it, of course.

**Comment by morrisonlevi** [comment]
I'm happy to say that 0.31.0 was released today. Can you upgrade and see if the issue is gone? If not, can you grep the agent's logs for `TRACE` and see if it drops any spans due to missing required info?

**Comment by bgaillard** [comment]
Hi @morrisonlevi and thanks a lot for this update.

After test I can confim the PDO integration is now working as expected :clap: 

So I think this issue can be closed now.
