### ISSUE TITLE
APM not receive data

### ISSUE THREAD

**Issue by azhari7** [DataDog/dd-trace-php#601]
i've installing dd-trace 0.30.2 my environment is centos 6.10, php 7.0, php-fpm, apache. i have running dd-doctor, all OK. but trace log says No data receive. 
![ddtrace](https://user-images.githubusercontent.com/13980646/66017378-c63c9600-e504-11e9-833d-ac658d36c63c.png)

**Comment by morrisonlevi** [comment]
azhari7, I assume this is a continuation of issue #582, is that correct? Sorry we haven't been able to resolve this yet.

**Comment by azhari7** [comment]
Yes is itu, is that a bug?

**Comment by azhari7** [comment]
Yes is it, is that a bug?

**Comment by labbati** [comment]
Hi, @azhari7 I am closing this as it refers to an obsolete version. Please feel free to reopen it if you still don't see traces with latest 0.47.0
