### ISSUE TITLE
Craft CMS Trace Resource all 'web.request'

### ISSUE THREAD

**Issue by Shikkic** [DataDog/dd-trace-php#605]
We're currently setting up a new Craft CMS application which I believe uses Yii under the hood. While I understand that Yii is not supported fully yet, I wanted to test out what automated tracing could give us in the meantime. 

We are able to get basic web requests and db calls traced, however I noticed that for the web request traces there is only one resource `web.request`.  This sort of surprises me because the traces do include the correct `url` tag.

<img width="1533" alt="Screen Shot 2019-10-04 at 2 04 20 PM" src="https://user-images.githubusercontent.com/8765687/66229999-2a03c200-e6b1-11e9-9ead-1947a5938003.png">

Is there something I can do to actually register the correct endpoint, even if it's something manual?

**Comment by SammyK** [comment]
Hey @Shikkic! You can enable URL resource names by setting `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED=1`.  You can optionally customize how the URL's are normalized using `DD_TRACE_RESOURCE_URI_MAPPING` which is documented in PR #442. Let us know if you have any trouble with it. :)

**Comment by Shikkic** [comment]
Hey @SammyK, thanks for responding so quickly!

This is great I will look into it and see how it goes. I feel silly for not seeing this earlier. Thanks again.

**Comment by SammyK** [comment]
No problem! It's easy to miss since it's not officially documented yet (docs coming soon though!) :)

**Comment by ryanwilsonperkin** [comment]
Hey @SammyK, we're looking at setting up DataDog on a CraftCMS site as well now and I came across this issue in my searching! Are there docs somewhere on how to set this up?

**Comment by SammyK** [comment]
Hey @ryanwilsonperkin! Yes, this is documented here: https://docs.datadoghq.com/tracing/setup/php/#map-resource-names-to-normalized-uri

**Comment by ryanwilsonperkin** [comment]
Wonderful, thank you very much :)
