### ISSUE TITLE
Thoughts on dropping support for < PHP 7.1

### ISSUE THREAD

**Issue by SammyK** [DataDog/dd-trace-php#62]
Just this one last thing and then I'm done blowing up your inboxes. :)

Considering the fact that PHP 5.6 and PHP 7.0 will [both be EOL in 2 months](http://php.net/supported-versions.php), what are your thoughts on dropping support for anything less than PHP 7.1 so we can remove the polyfills and take full advantage of all the amazing new features in PHP.now? :)

**Comment by chuck** [comment]
It's verrrry appealing, but we're actually looking at even lower than 5.6 support options right now so seems unlikely. :)

**Comment by skyzyx** [comment]
Please don't encourage people to continue using EOL'd versions of PHP by supporting them in a new product. Since this is a new product, I would **strongly request** that you do not begin by supporting EOL'd releases.

Please. Dear god, please.
