### ISSUE TITLE
"Error deleting memcache key" after upgrading to 0.33.0

### ISSUE THREAD

**Issue by ctrlrsf** [DataDog/dd-trace-php#622]
Hello,

Earlier today we upgraded from 0.30.2 to 0.33.0 to get Synthetics support but found we started seeing errors deleting memcache keys. All instances upgraded to this version started reporting "Error deleting memcache key" errors. Setting and getting memcache keys seems OK. I was able to delete the memcache keys manually using memcrm tool from the same instance, so problem isn't the ElastiCache nodes or network. I disabled the memcached integration by adding it to DD_INTEGRATIONS_DISABLED in Apache and errors went away on all nodes.

Please let me know if you need any additional information from me to troubleshoot.

**Comment by labbati** [comment]
Hi @ctrlrsf and sorry to hear that. While we do not officially support AWS ElastiCache (we are working on an integration right now) we absolutely should not crash the app in any case. One question: anything specific about the key (if you are able to understand which key caused the issue), something that stands out (e.g. length)?

If nothing stands out with the key then I will try to recreate a server on EC2 to connect to ElastiCache.

**Comment by ctrlrsf** [comment]
Nothing in particular with the keys. We had over 120,000 different keys affected while we were seeing the issue. Note, as far as PHP is concerned ES is just a memcache server. We're not using the PHP elasticache cluster client extension, just the standard memcached PHP extension module (php-memcached) connecting to the ES/memcache node by hostname directly.

**Comment by labbati** [comment]
@ctrlrsf thanks for the info. While we are looking into this I have a few more questions to add.

1. when the error occurs, does the app crash or is just that method not executed and the error message printed somewhere?
2. is this  a  client side  error (a log message in the php app)  or a server message (in the aws  elasticache logs)? We  cannot find a lot of info about this specific error.
3. `connecting to the ES/memcache node by hostname directly`, I am a little bit confused about ES,  did you mean EC like in ElastiCache?

**Comment by labbati** [comment]
Hi @ctrlrsf just to let you know we are investigating this as part of the current sprint. If you have a chance to answer my 3 questions above it would be very useful. Thanks for your patience.

**Comment by labbati** [comment]
Hi @ctrlrsf I was not able to reproduce it locally yet. I will try to reproduce on AWS. Can you please provide me with info about which image your EC2 is based on and which php version?

If you have a dockerfile that would be even better, I can provide you with a channel to share it confidentially

**Comment by ctrlrsf** [comment]
Hi @labbati,

Here are responses to your questions. Please let me know if you need anything else.

1. When this occurs, it seems like it's just a log message that's printed. The request continues to process successfully. Also looks like the memcache key is actually deleted.
2. It's logged on the client/PHP side that's making a memcache->delete() call.
3. Sorry, meant EC for Elasticache.

Could a recent change have affected the return of memcache->delete()? I see where we're logging this error message that the delete() call must have returned false. However, when we generate the log message we see that memcache->getResultCode() returns 0, and memcache->getResultMessage() returns "SUCCESS". The false return seems to contradict the success result code and messages. From https://www.php.net/manual/en/memcached.delete.php delete() should be returning true on success and false on failure.

Here's a piece of code that logs "Error deleting memcache key" when we have memcache integration enabled:
```
$this->memcache = new Memcached();
...
$result = $this->memcache->delete($key);
if ($result === false && $this->memcache->getResultCode() != Memcached::RES_NOTFOUND) {
	Log::write('Error deleting memcache key', Log::LEVEL_ERROR, 'cache', [
		'cacheKey' => $key,
		'code' => $this->memcache->getResultCode(),
		'message' => $this->memcache->getResultMessage(),
	]);
}
```

Looking at our logs when this occurs, code is always 0, and message is "SUCCESS".

If still needed, to reproduce we're running an Ubuntu 16.04 AMI and the PHP version is `7.2.24-1+ubuntu16.04.1+deb.sury.org+1`.

**Comment by labbati** [comment]
Hi @ctrlrsf thanks for the detailed message. We will try this script and get back to you.
I am glad to hear though the the app does not crash. Still this might be the symptom of something else that we definitely want to investigate.

**Comment by SammyK** [comment]
Hey @ctrlrsf! Thank you so much for your detailed notes on this issue. We've identified the issue and should be rolling out a fix for it sometime within the next two weeks. :)
