### ISSUE TITLE
Init script not reachable

### ISSUE THREAD

**Issue by KDederichs** [DataDog/dd-trace-php#626]
Hey according to the dd-doctor script my init file is not being found.

```
DataDog trace extension verification

- PHP version and SAPI                       [7.3.10 - fpm-fcgi]
- ddtrace extension installed                [OK]
- ddtrace version (installed)                [0.33.0]
- ddtrace version (const)                    [0.33.0]
- ddtrace version (userland)                 [FAIL]
- ddtrace versions in sync                   [FAIL]
- dd_trace() function available              [OK]
- dd_trace_env_config() function available   [OK]
- ddtrace.request_init_hook set              [OK]
- ddtrace.request_init_hook reachable        [FAIL]
- open_basedir INI directive                 [/var/www/vhosts/my_host.com/:/tmp/]
- IntegrationsLoader exists                  [FAIL]
- DDTrace\Tracer class exists                [FAIL]
- Configured Agent host                      [localhost]
- Configured Agent port                      [8126]
- Agent can receive traces                   [OK]
```

I checked though and the folder and the script are definitely at the path specified in the ini 
(/opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php)

Any idea what's causing this?

**Comment by labbati** [comment]
Hi @KDederichs, does the user under which php-fpm runs have read access to that folder?
Something like `sudo -u <php-fpm-user> ls -al /opt/datadog-php/dd-trace-sources/bridge`

**Comment by labbati** [comment]
Ah wait, here is the problem: `open_basedir INI directive [/var/www/vhosts/my_host.com/:/tmp/]`, [open_basedir](https://www.php.net/manual/en/ini.core.php#ini.open-basedir) does not allow execution of scripts in that folder. You should check with your system admins and in case they approve you should be good to go by just adding `/opt/datadog-php/dd-trace-sources` to the `open_basedir` directive.

**Comment by KDederichs** [comment]
Thanks, that did the trick!
Now I get a wall of 
`AH01071: Got error 'PHP message: PHP Warning: file_exists(): open_basedir restriction in effect. File(/proc/self/cgroup) is not within the allowed path(s): (/var/www/vhosts/my_host.com/:/tmp/:/opt/datadog-php/dd-trace-sources) in /opt/datadog-php/dd-trace-sources/src/DDTrace/Util/ContainerInfo.php on line 36'`
though I assume it's related to that?
I'd add that as well but it doesn't even seem to exist on my system (it's self hosted)

**Comment by morrisonlevi** [comment]
It's trying to determine if it's running inside of a container and failing because `/proc/self/cgroup` is not permitted in open_basedir. If you add `/proc/self` to the open_basedir then that should also work. I'll investigate if silencing the `file_exists` call will also silence the open_basedir notification, as I suspect this might be common for those using open_basedir.

**Comment by KDederichs** [comment]
That did it thanks, maybe you should consider adding the part about the open_basedir to the installation instructions on self hosted environments as well, it probably would help out some people.

**Comment by labbati** [comment]
@KDederichs we improved our `dd-doctor.php` to make sure there are more debug info about the open_basedir directive usage and debug #629. Improvements were released with 0.34.0.

I am closing this issue for now, feel free to re-open it if you believe it does not address completely your concerns.

**Comment by imsatender** [comment]
> sudo -u <php-fpm-user> ls -al /opt/datadog-php/dd-trace-sources/bridge

I think this is wrong command

**Comment by krvajal** [comment]
Which one is the right one?
