### ISSUE TITLE
shm_open: Permission denied

### ISSUE THREAD

**Issue by laurenty** [DataDog/dd-trace-php#643]
After enabling Datadog tracing in our application, our CLI scripts started outputting `shm_open: Permission denied`, it doesn't seem to prevent them from running but is creating a lot of noise.
I believe it is coming from https://github.com/DataDog/dd-trace-php/blob/master/src/ext/circuit_breaker.c#L40

Running on PHP 5.6/Centos 6
```
shmop
shmop support => enabled
```

**Comment by labbati** [comment]
Hi @laurenty and thanks for the report. We will look into this  as soon as possible. While it is  important that it  did not break your script, we want to address this soon to remove the noise that you are seeing in the error log.

**Comment by morrisonlevi** [comment]
We've merged in some code to our master branch that will only bring this info when DD_TRACE_DEBUG is enabled, and should be included in our next release.

**Comment by morrisonlevi** [comment]
Version [0.36.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.36.0) was released, and will only print these messages if debug mode is enabled. Can you upgrade and confirm this fixes the issue for you?

**Comment by morrisonlevi** [comment]
I'm closing this issue as it was fixed in v0.36.0. Of course, feel free to re-open the ticket if you need to.
