### ISSUE TITLE
Reporting of spans failed

### ISSUE THREAD

**Issue by dagnew** [DataDog/dd-trace-php#646]
dd-trace installed on a Centos7 host running nginx is showing this in the nginx error.log:
`Reporting of spans failed: 7 / Failed to connect to 127.0.0.1: Permission denied`

```
[error] 1607#0: *3 FastCGI sent in stderr: "PHP message: [2019-11-11T12:30:20+00:00] [ddtrace] [debug] - Flushing 1 traces, 1 spans
PHP message: [2019-11-11T12:30:20+00:00] [ddtrace] [debug] - circuit breaker status: closed => , total_failures => 294,consecutive_failures => 294, opened_timestamp => 4141267173420, last_failure_timestamp=> 4151668538351
```

What am I missing in the way of permissions?

**Comment by labbati** [comment]
Hi @dagnew! Would it be possible to download [`dd-doctor.php`](https://github.com/DataDog/dd-trace-php/blob/master/src/dd-doctor.php) to your web root and access it at `http://<you-host>/dd-doctor.php`?

Note that depending on your environment you might want to properly limit access to it via nginx or apache directives.

Based with the outpu we can try to help.

**Comment by dagnew** [comment]
Hey @labbati, thanks for the quick reply!

Here's the output:
```
DataDog trace extension verification

- PHP version and SAPI                               [5.6.33 - fpm-fcgi]
- ddtrace extension installed                        [OK]
- ddtrace version (installed)                        [0.34.0]
- ddtrace version (const)                            [0.34.0]
- ddtrace version (userland)                         [0.34.0]
- ddtrace versions in sync                           [OK]
- dd_trace() function available                      [OK]
- dd_trace_env_config() function available           [OK]
- ddtrace.request_init_hook set                      [OK]
- ddtrace.request_init_hook reachable                [OK]
- ddtrace.request_init_hook has run                  [OK]
- 'open_basedir' allows access to '/proc/self/'      [OK]
- IntegrationsLoader exists                          [OK]
- Integrations not loaded yet                        [OK]
- Registering an autoloader...
- Integrations loaded                                [OK]
- DDTrace\Tracer class exists                        [OK]
- Configured Agent host                              [localhost]
- Configured Agent port                              [8126]
- Agent can receive traces                           [FAIL]
Curl verbose output: 

* About to connect() to localhost port 8126 (#57)
*   Trying 127.0.0.1...
* Failed to connect to 127.0.0.1: Permission denied
* couldn't connect to host at localhost:8126
* Closing connection 57
```

**Comment by labbati** [comment]
Might it be related to `SELinux` (have you it installed and enabled at all?) In case the fix seems to be reported e.g. https://stackoverflow.com/a/27038088/2749853 but you might want to vet this solution with your system admin before. If this is the case there might be other approaches that your system admin can recommend. Unfortunately this is a little bit out of my comfort zone.

**Comment by dagnew** [comment]
Thanks @labbati, appreciate you looking. I'll close this issue as its obviously not related to dd-trace. Thanks again!

**Comment by labbati** [comment]
More then happy to help! Just to let you know, I created a task and added to our list to make sure that when we detect this same error (in the future) `dd-doctor.php` will give more information and provide links to solve this very same issue.

**Comment by dagnew** [comment]
FYI - This https://github.com/DataDog/dd-trace-php/issues/646#issuecomment-552467232 solved the issue, it was related to SELinux. I'm getting the traces now.
Thanks @labbati :+1:
