### ISSUE TITLE
Adding empty Expect Header to avoid 100-continue delay

### ISSUE THREAD

**Issue by draco2003** [DataDog/dd-trace-php#651]
Looking to see if there is auth or some other reason we'd want to do the Extra Handshake of 100-continue? or if we're just falling into the Curl default because we aren't telling it explicitly not to?
Some Background:
https://gms.tf/when-curl-sends-100-continue.html

Place we could add an empty Except header:
https://github.com/DataDog/dd-trace-php/blob/3a0d28c71e41f2ce4ee0a2e38b06d392782a476e/src/DDTrace/Transport/Http.php#L144

I was tracing around for other reasons and noticed this in the output:

sendto(71, "POST /v0.4/traces HTTP/1.1\r\nHost: localhost:8126\r\nAccept: */*\r\nContent-Type: application/msgpack\r\nContent-Length: 122120\r\nX-Datadog-Trace-Count: 1\r\nDatadog-Meta-Lang: php\r\nDatadog-Meta-Lang-Version: 7.2.9\r\nDatadog-Meta-Lang-Interpreter: fpm-fcgi\r\nDatadog-Meta-Tracer-Version: 0.33.0\r\nExpect: 100-continue\r\n\r\n", 308, MSG_NOSIGNAL, NULL, 0) = 308 <0.000033>

**Comment by labbati** [comment]
@draco2003 version [0.36.1](https://github.com/DataDog/dd-trace-php/releases/tag/0.36.1) was released. I am going ahead and close this issue that is fixed by that PR. Feel free to re-open it if appropriate.
