### ISSUE TITLE
Memcached doesn't work as expected using ddtrace-20180731.so

### ISSUE THREAD

**Issue by salexi** [DataDog/dd-trace-php#656]
Later Later Edit: i cannot say if it worked in the previous of ddtrace versions. It is possible that php failed to load the extension when i changed the version and flavour.

Later edit: ddtrace-20180731-zts.so -doesn't manifest the issue;

With ddtrace-20180731.so there is one issue with memcached, that is not present using ddtrace-20170718.so.

Tested on php 7.1.x and 7.3.x with laravel 5.8 and 6.x

The following code 
```
$memcached = new \Memcached();
$m->addServer('i_don_t_have_memcached_server', 11211);
$m->get('foo'));
$m->get('foo'));
var_dump($m->getResultCode());  // returns 47 which is correct

require __DIR__.'/../vendor/autoload.php';

$memcached = new \Memcached();
$m->addServer('i_don_t_have_memcached_server', 11211);
$m->get('foo'));
$m->get('foo'));
var_dump($m->getResultCode()); // returns 0 which is incorrect 
                               // since no memcached server is available
```

The issue since to be present only when ran in server environment (php-fpm or php development integrated server).

If we ran the file via `php -f public/index.php` it returns correctly 47 and 47

**Comment by labbati** [comment]
Hi @salexi thanks for opening this issue and for the details provided. Looking at the snippet this can be related to #622.

**Comment by salexi** [comment]
@labbati 
Do you guys have any ideea what's causing this false status codes (and messages) and if you do, is there any rough estimation till you guys sort it out ?

**Comment by labbati** [comment]
Hi, @salexi, the fix for the memcached status code is in our current sprint so hopefully we will deliver by end of next week. You can still use the tracer but unfortunately you have to turn off memcached `DD_INTEGRATIONS_DISABLED=memcached`. We'll post updates here.

**Comment by SammyK** [comment]
Hey @salexi! Thank you so much for your repro to help debug this issue. We've identified the issue (it's the same as #622) and should be rolling out a fix for it sometime within the next two weeks. :)

**Comment by salexi** [comment]
> Hey @salexi! Thank you so much for your repro to help debug this issue. We've identified the issue (it's the same as #622) and should be rolling out a fix for it sometime within the next two weeks. :)

Hehe, no problem, glad i could help, and that the issue will be fixed promptly.

**Comment by labbati** [comment]
Hi @salexi , version [0.35.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.35.0) which contains the fix for this issue. Would you please confirm that the problem actually went away for your very specific use case?
Thank you!

**Comment by salexi** [comment]
Hey @labbati 
We've tested it and it's all good with the new release. 
Thanks for the quick intervention :)
