### ISSUE TITLE
Symfony 4.4 Integration

### ISSUE THREAD

**Issue by raffaellopaletta** [DataDog/dd-trace-php#662]
`DDTrace\Integrations\Symfony\V4\SymfonyBundle` does not work since SF 4.4 due to the symfony/http-kernel component in which the method `handleException` (called by ddtrace integration class) was replaced with the method `handleThrowable`

**Comment by labbati** [comment]
Hi @raffaellopaletta thanks for opening the issue. If I see it correctly the side effect of that is that exceptions details (e.g. the stack trace) are not correctly reported but the app DOES NOT CRASH.
Is my assumption correct? Please let me know.

**Comment by raffaellopaletta** [comment]
Hi @labbati, unfortunately it crashes with an InvalidArgumentException (failed to set return for Symfony\Component\HttpKernel\HttpKernel::handleException, the method does not exist)

**Comment by labbati** [comment]
Might I ask you to provide a stack trace?  (so we check which one is the offending line). Looking at our code on [`master`](https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php#L110) it looks the we'd just not be wrapping the method and that's all. I am surely missing something and a stack trace would help.

**Comment by raffaellopaletta** [comment]
Mmm I noticed that I'm using a my fork and a branch not yet merged with master....sorry!! I will investigate...probably it was a false alarm

**Comment by labbati** [comment]
Thanks for sharing, I will try to make some time myself today in order to test it with 4.4.

**Comment by raffaellopaletta** [comment]
Hi @labbati, I've merged the current master into my forked branch (https://github.com/raffaellopaletta/dd-trace-php.git  branch merge-official-master). I had no problem with SF 4.4. and SF Integration. Thanks

**Comment by labbati** [comment]
Thank you for confirming that the app works. Still we will add a proper test suite for Symfony 4.4 now that it is out to make sure that all the relevant metadata is properly set so you can take the most out of it.

**Comment by labbati** [comment]
Closing this issue for now as Symfony 4.4 is supported.
