### ISSUE TITLE
Traces for requests ending in fatal error listed as successful (HTTP 200)

### ISSUE THREAD

**Issue by laurenty** [DataDog/dd-trace-php#668]
I am trying to solve an issue with traces for requests that end in a fatal error showing up in Datadog as HTTP 200.
I ran into this with both a manually instrumented application and one using the ZF1 integration.

It looks like when the tracer is bootstrapped it automatically register a shutdown function that closes the tracer and so far I haven't been able to register something before it.
https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Bootstrap.php#L33

**Comment by labbati** [comment]
Hi @laurenty thanks for reporting this. I am looking into this specific issue with fatals. I have a test branch where I am working on. Will post it here an ETA for release. We will try to include this in the upcoming release.

**Comment by morrisonlevi** [comment]
PR #1028 takes a step forward to show more information in the trace before flushing it. However, it does not tag the root span as an error yet, and we plan to do this in follow-up PRs.

**Comment by laurenty** [comment]
Thank you for the update @morrisonlevi. This issue came up in a conversation today and it definitely looks like good progress has been made on this. Thanks for the hard work and looking forward to the follow-up PRs

**Comment by labbati** [comment]
@laurenty this issue has been completely resolved and released for PHP 7+ now. We still have some work to do for 5.6 to cover edge cases (fatal that occurs outside of a method traced by automatic instrumentation).

I am closing this issue. If you feel your problem is still present please let me know and I will reopen it.
