### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by kazz187** [DataDog/dd-trace-php#670]
PHP 7.4 was released last weekend 🎉 

We are trying to use this new version in our projects.
But, dd-trace-php doesn't support PHP 7.4 yet.
I want to hear future plans of this project about PHP 7.4 support.

**Comment by labbati** [comment]
Hi @kazz187, thanks for opening the issue. We definitely plan to support PHP 7.4 soon, we are scheduling time to work on it, I will update this issue with an ETA as soon as possible.

**Comment by nesl247** [comment]
Why was it not completed prior to 7.4's release? This is the same complaint that we had with NewRelic. It's not like the releases are done without notice. There's nearly an entire year of releases available to work with while it's being developed.

There is literally no excuse for it to not be completed already. This is not a free product. Part of paying for that product is the expectation that you are up to date with releases such as this.

**Comment by morrisonlevi** [comment]
For what it is worth, we have had some tests with PHP 7.4 in our continuous integration pipeline for a few months now, so we hope that it will not be difficult to fully support.

**Comment by lucasvanlierop** [comment]
@labbati we're two weeks further now do you have a ETA? We'd like to upgrade to `7.4` but Data dog is preventing us from doing so.

**Comment by labbati** [comment]
Hi everyone! We have an update about this issue.
We are starting the work on this and we are planning to release it around January 15th.

**Comment by nesl247** [comment]
Out of curiosity, since we're about a week away, is everything on track?

**Comment by SammyK** [comment]
@nesl247 So far so good! :) We aren't expecting any delays, but we'll certainly update here if there is.

**Comment by SammyK** [comment]
Just a heads up, #723 adds official PHP 7.4 support and should be wrapped up by the end of the week. :)

**Comment by thedotedge** [comment]
Is there a new ETA? The end of the last week is, well, in the past :)

**Comment by labbati** [comment]
Hi  @thedotedge, you made a very good point. I am confident it will be merged by this Friday and released early next week. We have code review scheduled for tomorrow and then possibly one more day of back and forth.

**Comment by nesl247** [comment]
Now that it's merged, do you have plans to release it today?

**Comment by SammyK** [comment]
@nesl247 We'll be releasing this on Monday in the 0.38.0 release. If you like, you can [download the nightly build with PHP 7.4 support](https://106602-119990860-gh.circle-artifacts.com/0/all/packages.tar.gz) to start getting any containers or staging environments ready before the official release on Monday.

**Comment by SammyK** [comment]
Support for PHP 7.4 has been [released in v0.38.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.38.0). :)

**Comment by kazz187** [comment]
Thank you for your good work :)
