### ISSUE TITLE
Manual instrumentation fails with fatal error

### ISSUE THREAD

**Issue by pvonr** [DataDog/dd-trace-php#672]
I'm currently instrumenting a sub project that uses Zend Expressive. I followed the documented steps [here](https://docs.datadoghq.com/tracing/advanced/manual_instrumentation/?tab=php) and get this fatal error thrown:
`PHP Fatal error:  Cannot declare trait DDTrace\\Log\\LoggingTrait, because the name is already in use in /opt/datadog-php/dd-trace-sources/src/DDTrace/Log/LoggingTrait.php on line 5`

The problem seems to be stemming the CodeIgniter integration [here](https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Integrations/IntegrationsLoader.php#L86-L87). Autoloading does not work because the namespace of the sandboxed class is not PSR-4 compliant.

**Comment by pvonr** [comment]
Ok, the culprit here is that the CodeIgniter implementation is not PSR-4 compliant... I will make a small PR that fixes the problem.

**Comment by labbati** [comment]
Hi @pvonr, the fix in #650 has already been merged and it is due for release possibly today with 0.35.0

**Comment by labbati** [comment]
Hi @pvonr, version [0.35.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.35.0) which contains the fix for this issue. Would you please confirm that the problem actually went away for your very specific use case?
Thanks you!

**Comment by pvonr** [comment]
Yes the release fixes the issues with manual instrumentation. Thanks for the quick reaction!
