### ISSUE TITLE
Symfony Console command not able to load extension namespace

### ISSUE THREAD

**Issue by dcsg** [DataDog/dd-trace-php#678]
I'm using the extension (last version 0.35.0) and when I run a Symfony 4.3 command via `bin/console` it says the class `DDTrace\GlobalTracer` is not found. The extension is loaded and if I check it by running `php -a` I can get the class. Is there any trick to get this loaded via CLI? In the web app this works well.

**Comment by morrisonlevi** [comment]
For CLI scripts, the environment variable `DD_TRACE_CLI_ENABLED=1` should be set. Do you have this enabled?

**Comment by dcsg** [comment]
@morrisonlevi yes

**Comment by sdepablos** [comment]
@dcsg I found the same problem, and executing `DD_TRACE_CLI_ENABLED=true app/console <whatever command>` the problem was solved. In fact I had to add the following code for the processor to be ignore in CLI commands:
```php
        if ('cli' === PHP_SAPI) {
            return $record;
        }
```

**Comment by dcsg** [comment]
@sdepablos that's not a solution. I still want to have the trace id in the logs.

@morrisonlevi any other thing I should look at here? Also how can both, extension and lib imported via composer, work together? I tried locally and it does not work because of autoloader.

**Comment by dcsg** [comment]
FYI I opened a support case regarding this. #291040

**Comment by labbati** [comment]
Hi @dcsg. I am closing this issue as (our fault) it went stale. I think you have already worked out your issue with support. Please feel free to comment here if we can do anything else and I will reopen.
