### ISSUE TITLE
predis not working

### ISSUE THREAD

**Issue by edisoncosta** [DataDog/dd-trace-php#699]
Problems with a server that the redis service does not work and do not find anything in the logs.

![image](https://user-images.githubusercontent.com/9742485/71579530-cc2e1d00-2adb-11ea-9d73-f2b2e2f0ccc8.png)

I changed dd-doctor and it includes "predis" in "Integrations loaded" and loading is OK.

The other services work Ok

**Comment by jeremy-lq** [comment]
@edisoncosta We'll need some additional information to continue. Please open a [support ticket](https://docs.datadoghq.com/help/) with the version of predis you're using and debug logs from the tracer with debug mode enabled. Thanks.
