### ISSUE TITLE
Xdebug 2.9.1 + Datadog Tracing lib = Segmentation fault

### ISSUE THREAD

**Issue by VictorBersy** [DataDog/dd-trace-php#725]
Hello,

I'm not sure on what side the issue is, but it seemed like a good idea to open an issue here anyway, at least to let you know it happens, and let anyone else wonders why they have such error a place to discuss it.

**The issue**

I only tried with the docker image `php:7.3-apache` and `php:7.2-apache` but noticed that even a simple `php -i` was segfaulting.
So I've started investigating why it was happening on one of our app.
We recently updated from `dd-trace-php` 0.37.0 to 0.37.1 so I thought that was the issue.

It solved it, but it was not the end. I found out it was only happening when xdebug was installed. I dig further and even found out it was only when `xdebug.remote_enable=on` was set.

I took a look at any recent releases from xdebug, and Xdebug 2.9.1 was released on  16th January 2020. As we install it with a simple `pecl install xdebug`, during a docker rebuild, the last version was installed, and the issue started to appear.

By rolling back to xdebug 2.9.0, it works again.

**How to reproduce it**

I've wrote up a Dockerfile with some build arg, and wrote a bash script to quickly change values, so it was easier to see with what version it was failing. And with that, I've came up with a kinda test matrix with different version. I hope it will be helpful!

I've attached the whole "project" to reproduce the issue, but here's a simpler Dockerfile if you want to quickly test it.

_Dockerfile_
```dockerfile
FROM php:7.3-apache as base

RUN curl --silent -Lo datadog-php-tracer.deb https://github.com/DataDog/dd-trace-php/releases/download/0.37.1/datadog-php-tracer_0.37.1_amd64.deb && \
    dpkg -i datadog-php-tracer.deb && \
    rm datadog-php-tracer.deb

RUN pecl install xdebug-2.9.1

RUN touch /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "zend_extension=xdebug.so" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini
```

```
$ docker run --rm -it $(docker build -q .) bash
root@7dbcd49e2903:/var/www/html# php -i
Segmentation fault
```

Here's the "matrix" I've used and its results:
```sh
PHP_APACHE_VERSION=7.3 DATADOG_PHP_TRACER_VERSION=0.37.1 XDEBUG_VERSION=2.9.1 ./tests.sh
PHP_APACHE_VERSION=7.3 DATADOG_PHP_TRACER_VERSION=0.36.1 XDEBUG_VERSION=2.9.1 ./tests.sh

PHP_APACHE_VERSION=7.3 DATADOG_PHP_TRACER_VERSION=0.37.1 XDEBUG_VERSION=2.9.0 ./tests.sh
PHP_APACHE_VERSION=7.3 DATADOG_PHP_TRACER_VERSION=0.36.1 XDEBUG_VERSION=2.9.0 ./tests.sh


PHP_APACHE_VERSION=7.2 DATADOG_PHP_TRACER_VERSION=0.37.1 XDEBUG_VERSION=2.9.1 ./tests.sh
PHP_APACHE_VERSION=7.2 DATADOG_PHP_TRACER_VERSION=0.36.1 XDEBUG_VERSION=2.9.1 ./tests.sh

PHP_APACHE_VERSION=7.2 DATADOG_PHP_TRACER_VERSION=0.37.1 XDEBUG_VERSION=2.9.0 ./tests.sh
PHP_APACHE_VERSION=7.2 DATADOG_PHP_TRACER_VERSION=0.36.1 XDEBUG_VERSION=2.9.0 ./tests.sh
```

<details>
<summary><b>Results</b></summary>

```
$ PHP_APACHE_VERSION=7.3 DATADOG_PHP_TRACER_VERSION=0.37.1 XDEBUG_VERSION=2.9.1 ./tests.sh
PHP_APACHE_VERSION=7.3
DATADOG_PHP_TRACER_VERSION=0.37.1
XDEBUG_VERSION=2.9.1

remote_enable-on: Segmentation fault
remote_enable-off: 0


$ PHP_APACHE_VERSION=7.3 DATADOG_PHP_TRACER_VERSION=0.36.1 XDEBUG_VERSION=2.9.1 ./tests.sh
PHP_APACHE_VERSION=7.3
DATADOG_PHP_TRACER_VERSION=0.36.1
XDEBUG_VERSION=2.9.1

remote_enable-on: Segmentation fault
remote_enable-off: 0


bash-3.2$
$ PHP_APACHE_VERSION=7.3 DATADOG_PHP_TRACER_VERSION=0.37.1 XDEBUG_VERSION=2.9.0 ./tests.sh
PHP_APACHE_VERSION=7.3
DATADOG_PHP_TRACER_VERSION=0.37.1
XDEBUG_VERSION=2.9.0

remote_enable-on: 0
remote_enable-off: 0


$ PHP_APACHE_VERSION=7.3 DATADOG_PHP_TRACER_VERSION=0.36.1 XDEBUG_VERSION=2.9.0 ./tests.sh
PHP_APACHE_VERSION=7.3
DATADOG_PHP_TRACER_VERSION=0.36.1
XDEBUG_VERSION=2.9.0

remote_enable-on: 0
remote_enable-off: 0


bash-3.2$
bash-3.2$
$ PHP_APACHE_VERSION=7.2 DATADOG_PHP_TRACER_VERSION=0.37.1 XDEBUG_VERSION=2.9.1 ./tests.sh
PHP_APACHE_VERSION=7.2
DATADOG_PHP_TRACER_VERSION=0.37.1
XDEBUG_VERSION=2.9.1

remote_enable-on: Segmentation fault
remote_enable-off: 0


$ PHP_APACHE_VERSION=7.2 DATADOG_PHP_TRACER_VERSION=0.36.1 XDEBUG_VERSION=2.9.1 ./tests.sh
PHP_APACHE_VERSION=7.2
DATADOG_PHP_TRACER_VERSION=0.36.1
XDEBUG_VERSION=2.9.1

remote_enable-on: Segmentation fault
remote_enable-off: 0


bash-3.2$
$ PHP_APACHE_VERSION=7.2 DATADOG_PHP_TRACER_VERSION=0.37.1 XDEBUG_VERSION=2.9.0 ./tests.sh
PHP_APACHE_VERSION=7.2
DATADOG_PHP_TRACER_VERSION=0.37.1
XDEBUG_VERSION=2.9.0

remote_enable-on: 0
remote_enable-off: 0


$ PHP_APACHE_VERSION=7.2 DATADOG_PHP_TRACER_VERSION=0.36.1 XDEBUG_VERSION=2.9.0 ./tests.sh
PHP_APACHE_VERSION=7.2
DATADOG_PHP_TRACER_VERSION=0.36.1
XDEBUG_VERSION=2.9.0

remote_enable-on: 0
remote_enable-off: 0


```

</details>

The whole archive to get all docker files, bash scripts and .ini files: [php-7.3-datadog-xdebug-conflict.tar.gz](https://github.com/DataDog/dd-trace-php/files/4087275/php-7.3-datadog-xdebug-conflict.tar.gz)

I'm available if you need further help :)

**Comment by labbati** [comment]
Thanks you @VictorBersy for the great detail and clarity of this issue. It will definitely be very useful while investigating this.

Just to let you know, we use similar hooks as xdebug does and we are changing that to be more robust while working together with it. This plan is already in place (meaning we have developers working full time on this) but it might take more than a few days. I will reach out again with a more precise ETA once we know it.

In the meantime, unfortunately, I can only recommend to downgrade to 2.9.

@SammyK something to keep in mind while we work on the long-term plan in order to make sure that this goes away.

**Comment by SammyK** [comment]
With all the details you provided, you made it very easy to debug this issue, @VictorBersy. Thank you! :)

This appears to be an issue with the 2.9.1 release of Xdebug. We've submitted an upstream patch at xdebug/xdebug#544 that should fix the issue.

As this segmentation fault is not on the ddtrace side, I'm going to close this issue out. Feel free to follow the [updates in the Xdebug repo PR](https://github.com/xdebug/xdebug/pull/544) or [their bug tracker](https://bugs.xdebug.org/view.php?id=1736). And thanks again for the detailed issue!

**Comment by VictorBersy** [comment]
That was fast, thanks! Glad my work helped you a lot, it was fun 👍 

I will keep an eye on Xdebug PR and opened ticket, thanks for the links.
