### ISSUE TITLE
Issue with v0.37.1 and references in MessagePack

### ISSUE THREAD

**Issue by adrien-f** [DataDog/dd-trace-php#728]
Greetings 👋 

While trying the upgrade on our test bench, I've discovered an issue with the latest release. I've narrowed it down to a bug with references and https://github.com/DataDog/dd-trace-php/commit/ebedcf28bd4bc5f9901d725bac9c5ad77427fcc6

Extension debug logs:

```
[23-Jan-2020 18:39:39 Europe/Paris] [2020-01-23T18:39:39+01:00] [ddtrace] [debug] - Failed to MessagePack-encode trace
[23-Jan-2020 18:39:39 Europe/Paris] [2020-01-23T18:39:39+01:00] [ddtrace] [debug] - About to send trace(s) to the agent
[23-Jan-2020 18:39:39 Europe/Paris] [2020-01-23T18:39:39+01:00] [ddtrace] [error] - Reporting of spans failed, status code 400: EOF
```

Outputting the value of https://github.com/DataDog/dd-trace-php/blob/master/src/ext/serializer.c#L95 match `10` which is a Reference making the MessagePack logic fails.

This works again with this patch or if I force the encoder to use JSON:

```diff
diff --git a/src/DDTrace/Tracer.php b/src/DDTrace/Tracer.php
index b929beb2..1c900bc6 100644
--- a/src/DDTrace/Tracer.php
+++ b/src/DDTrace/Tracer.php
@@ -387,7 +387,7 @@ final class Tracer implements TracerInterface
         // Setting global tags on internal spans, if any
         $globalTags = $this->globalConfig->getGlobalTags();
         if ($globalTags) {
-            foreach ($internalSpans as &$internalSpan) {
+            foreach ($internalSpans as $internalSpan) {
                 foreach ($globalTags as $globalTagName => $globalTagValue) {
                     if (isset($internalSpan['meta'][$globalTagName])) {
                         continue;
```

Not sure which is the best way to go from there ?

```
PHP 7.1.33-3+0~20191218.29+debian9~1.gbp18b07c (cli) (built: Dec 18 2019 15:02:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33-3+0~20191218.29+debian9~1.gbp18b07c, Copyright (c) 1999-2018, by Zend Technologies
```

```
root@ip-10-196-79-92:/tmp/dd-trace-php# DD_TRACE_CLI_ENABLED=1 php src/dd-doctor.php
WARNING: Script is running from the CLI SAPI.
         Please run this script from your web browser.

DataDog trace extension verification

- PHP version and SAPI                               [7.1.33-3+0~20191218.29+debian9~1.gbp18b07c - cli]
- ddtrace extension installed                        [OK]
- ddtrace version (installed)                        [0.37.1]
- ddtrace version (const)                            [0.37.1]
- ddtrace version (userland)                         [0.37.1]
- ddtrace versions in sync                           [OK]
- dd_trace() function available                      [OK]
- dd_trace_env_config() function available           [OK]
- ddtrace.request_init_hook set                      [OK]
- ddtrace.request_init_hook reachable                [OK]
- ddtrace.request_init_hook has run                  [OK]
- 'open_basedir' allows access to '/proc/self/'      [OK]
- IntegrationsLoader exists                          [OK]
- Integrations not loaded yet                        [OK]
- Registering an autoloader...
- Integrations loaded                                [OK]
- DDTrace\Tracer class exists                        [OK]
- Configured Agent host                              [localhost]
- Configured Agent port                              [8126]
- Agent can receive traces                           [OK]
```

**Comment by labbati** [comment]
Hi @adrien-f thanks for the  detailed report. Looking  immediately into  it to confirm and test  and release it as part of our next release on Monday.

**Comment by adrien-f** [comment]
Thanks @labbati ! I did not suggest an MR as I was in full debug mode while looking into it and did not understand the real intention at play here. Let me know if you need me to test a nightly as well.

**Comment by labbati** [comment]
We were able to recreate and we are working  on a fix. Either as a patch today if we have time to extensively test it or as a regular release on Monday.

So far we do not need any further info from  you. The details that you added to this issue from the beginning were awesome.

**Comment by labbati** [comment]
@adrien-f we are targeting today to merge #730 and include in 0.38.0

**Comment by labbati** [comment]
Hey @adrien-f, 0.38.0 is out and it includes the fix for this issue. Would you please confirm that this resolve the bug you reported?

Thanks again  once more for the very detailed info.

**Comment by tylermarien** [comment]
It doesn't appear this fix made it into 0.38.0. It looks like it was merged after the release: https://github.com/DataDog/dd-trace-php/compare/0.38.0...master.

**Comment by labbati** [comment]
Good catch @tylermarien thanks for noticing. We just released 0.38.1 which includes that bug fix.
We have also added steps to our release process to make sure we detect such things in advance.
Let me know if the path release works for you.

**Comment by tylermarien** [comment]
It's working now. Thanks very much.

**Comment by adrien-f** [comment]
I can confirm I don't get any serialization issues now! Thanks for the prompt reaction, much appreciated 👏

**Comment by labbati** [comment]
Closing the issue then! Thanks for the report.
