### ISSUE TITLE
Use of Symlinks for `.ini` files doesn't work in setups with multiple PHP versions

### ISSUE THREAD

**Issue by grantlucas** [DataDog/dd-trace-php#729]
We recently started integrating with Datadog and got `dd-trace-php` set up on our servers. In our setup, we have _multiple_ PHP versions running at the same time due to a variety of reasons. The current use of Symlinks, and the installer dosen't really produce the correct results for this as any version used _after_ the first, will break the earlier installs.

## Steps to reproduce

1. Have two different PHP versions installed
    - For demo, I'll use PHP 7.0 and 7.1 as that's what I was dealing with
2. Use the pre-compiled installer provided in this repo _and_ use the `DD_TRACE_PHP_BIN` env var to set the php version to install to as the 7.0 version
    - **note:** this all works great. After running 7.0 was tracing properly without issue

At this point, `98-ddtrace.ini` will be a **symlink** with the PHP 7.0 version of the extension listed: `extension=/opt/datadog-php/extensions/ddtrace-20151012.so`

3. Update `DD_TRACE_PHP_BIN` to be the HPP **7.1** binary
4. Re-run the installer
5. Confirm the symlink to `.ini` files are in place for the 7.1 setup

At this point, PHP 7.1 will function properly but PHP 7.0 will **throw a warning** due to the `.so` included in the `.ini` file. Since 7.0 _and_ 7.1 are symlinked to the same place, 7.0's ini file will now be referencing `ddtrace-20160303.so` instead of `ddtrace-20151012.so`.

## How I resolved it manually on our setup

1. Clear out _all_ failed installs and remove the package entirely to start fresh
2. Install the version for PHP 7.0 setting `DD_TRACE_PHP_BIN` to the 7.0 binary
3. Convert the symlinks for 7.0 into actual files by copying them and then removing the symlinks
4. Install the version for PHP 7.1 setting `DD_TRACE_PHP_BIN` to the 7.1 binary
5. Convert the symlinks for 7.1 into actual files by copying them and then removing the symlinks

This ensures that any future installs of this extension for any _other_ PHP versions on our server don't break previously installed versions.

## Overall request

Instead of using Symlinks for the `.ini` files, please copy the files directly into place so that multiple PHP versions don't conflict with each other when installing or upgrading.

-----

Let me know if there's anything unclear or any questions! This was the only main issue I ran into when getting set up. Great work!

**Comment by labbati** [comment]
Hi @grantlucas sorry for getting back to you so late. Good point here. Let us look into it and try to fix that. We are currently involved in a couple of big changes, but we might be able to get to this in the next could of weeks.
In the meantime, it is great that you found a workaround to this.

**Comment by grantlucas** [comment]
Thanks! yeah, I definitely have a work around for now so no rush. Good to have this documented here as well for any others in a similar situation. 😄

**Comment by bwoebi** [comment]
We will not touch the old installer (we are going to phase it out), but we have fixed this in of our new installer https://github.com/DataDog/dd-trace-php/blob/0.69.0/datadog-setup.php and do not use symlinks there.

Thus I'm closing this issue.
