### ISSUE TITLE
ddtrace.request_init_hook fails to run

### ISSUE THREAD

**Issue by gornostal** [DataDog/dd-trace-php#733]
`dd-doctor.php` reports that request_init_hook fails to run:

```
DataDog trace extension verification

- PHP version and SAPI                               [5.6.40-16+0~20200123.27+debian10~1.gbp05c23e - fpm-fcgi]
- ddtrace extension installed                        [OK]
- ddtrace version (installed)                        [0.37.1]
- ddtrace version (const)                            [0.37.1]
- ddtrace version (userland)                         [0.37.1]
- ddtrace versions in sync                           [OK]
- dd_trace() function available                      [OK]
- dd_trace_env_config() function available           [OK]
- ddtrace.request_init_hook set                      [OK]
- ddtrace.request_init_hook reachable                [OK]
- ddtrace.request_init_hook has run                  [FAIL]
- 'open_basedir' allows access to '/proc/self/'      [OK]
- IntegrationsLoader exists                          [FAIL]
- DDTrace\Tracer class exists                        [FAIL]
- Configured Agent host                              [dd-agent]
- Configured Agent port                              [8126]
- Agent can receive traces                           [OK]
```

## Steps to reproduce
* Create a docker image based on Debian
* Install php5.6 and php-fpm
* Install dd tracer: https://github.com/DataDog/dd-trace-php/releases/download/0.37.1/datadog-php-tracer_0.37.1_amd64.deb
* open dd-doctor.php in a browser

## Actual result
request_init_hook is not loaded automatically

## Expected result
request_init_hook (i.e. `/opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php`) is automatically imported.

## Workaround that I found
Put this at the start of a php entry point `require_once(ini_get('ddtrace.request_init_hook'));`

**Comment by labbati** [comment]
Hi @gornostal, sorry to hear that dd-doctor was not able to give you useful info on your system. I might need more info to try to recreate as in  the basic  setup  you described it seems to be working for me.

>  Create a docker image based on Debian

Do you have a sample docker  file  to reproduce  it, it would be great if you can provide one.

If not: which debian  version?
> Install php5.6 and php-fpm
How do you install php-fpm? The default  distro repo? From sources?

> open dd-doctor.php in a browser

Which server you have in front of php fpm nginx? apache?

Please  provide the  dockerfile you are using  (feel free to strip out all  steps that might be not relevant) and we  will be able to better help.

**Comment by gornostal** [comment]
Sure. I'll provide all that soon

**Comment by gornostal** [comment]
and thanks for your prompt reply :+1:

**Comment by gornostal** [comment]
Trying to prepare a simple project with DD and php5.6 didn't result in any errors. Everything works fine there.
The problem must be somewhere in the config of my large monolithic app.

I'm closing this issue.

**Comment by gornostal** [comment]
Actually, do you have any suggestions on what I could check to find why the request_init_hook failed?

**Comment by gornostal** [comment]
Issue solved. Found that `newrelic-php5` package interferes with datadog. Everything works fine without it.
