### ISSUE TITLE
Configuration files cannot be installed properly with Alpine package 0.37.0 or later

### ISSUE THREAD

**Issue by kjdev** [DataDog/dd-trace-php#743]
No problem with php7-cli only

``` sh
$ apk --no-cache add php7-cli
$ apk add --no-cache datadog-php-tracer_0.39.0_noarch.apk  --allow-untrusted
..
### Found SAPI config directory: /etc/php7/conf.d
..
$ php -m | grep dd
ddtrace
```

Installed in apache2 directory if apache2 is installed

``` sh
$ apk --no-cache add php7-cli php7-apache2
$ apk add --no-cache datadog-php-tracer_0.39.0_noarch.apk  --allow-untrusted
..
### Found SAPI config directory: /etc/apache2/conf.d
..
$ php -m | grep dd
```

**Comment by labbati** [comment]
Thanks for reporting the issue. We will look into this as soon as possible.
In the meantime, were you able to manual install the tracer for apache2? It is enough if you copy the same `.ini` file that was installed for the cli version to the conf.d folder of the other sapi. Based on your path it should be the same, btw, so probably no action items at all in this case.

**Comment by kjdev** [comment]
tracer for apache2 is not installed.
dadadog related only install datadog-php-tracer_0.39.0_noarch.apk.

*ddtrace*.ini installed in /etc/apache2/conf.d is moved to /etc/php7/conf.d/ and used.
