### ISSUE TITLE
intercept `http_response_code` calls for capturing response code

### ISSUE THREAD

**Issue by roippi** [DataDog/dd-trace-php#750]
Currently bootstrap intercepts and parses all `header` invocations to check if the response code was changed.  It should similarly intercept `http_response_code` calls. (no parsing needed, just check if a code was provided)

https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Bootstrap.php#L156

**Comment by labbati** [comment]
Good point and good addition to the tracer. This is also a good first issue if you are interested in, otherwise we can prioritize on our side.
