### ISSUE TITLE
Not able to trace MongoDB

### ISSUE THREAD

**Issue by imsatender** [DataDog/dd-trace-php#759]
Hi,

I am trying to trace MongoDB, but not able to trace on `PHP 7.0`. I have checked the code, which is checking for pecl `mongo` extension which is supported till the `PHP 5` version. I have attached the code also for your review, please help me out on this:

`if (!extension_loaded('mongo') || Versions::phpVersionMatches('5.4')) {`
 `          // Mongodb integration is provided through an extension and not through a class loader.`
 `           return Integration::NOT_AVAILABLE;`
` }`

**Comment by labbati** [comment]
Hi @imsatender, sorry to hear that. Just as a confirmation, are you using this driver? https://docs.mongodb.com/ecosystem/drivers/php/ 

We are actually supporting an older version of the `mongo` extension, not `mongodb`.

Supporting it is in our radar, at the moment I cannot commit to an ETA though.

**Comment by ronnylt** [comment]
Hi, is the `mongodb` extension support planned?

**Comment by labbati** [comment]
Hi @ronnylt, we are tentatively planning end of Q1 or early Q2 for the mongodb latest driver support.

**Comment by ronnylt** [comment]
That would be great! Thanks.

**Comment by CammoKing** [comment]
Hey @labbati! Do you have an update on this? We also have a real need for this, we use MongoDB extensively and right now we are losing a lot of visibility with APM. We have a hybrid with SQL and NoSQL on our various apps and the Datadog PHP APM is not very illuminating when all we can see is high level endpoints and controller calls. Thanks much!

**Comment by labbati** [comment]
Support for the new mongodb driver has been added for PHP 7.x and 8.x in 0.67.0. We have no plans to add it to PHP 5. If you need the new mongodb driver on PHP 5 please open a feature request with our support team.
I am closing this issue, let me know if you experience any issue with the new integration.
