### ISSUE TITLE
Getting excessive warnings about `HTTP header "X-Datadog-Trace-Count" not found`

### ISSUE THREAD

**Issue by xyzjace** [DataDog/dd-trace-php#763]
Hi all,

Apologies if this is covered somewhere in the docs or a guide, but I've been unable to find anything relating to this in my searches thus far other than (https://github.com/spandex-project/spandex_datadog/issues/21).

We've recently installed the PHP extension for our application (a hand spun PHP app from eons ago, no framework) and added the relevant config to turn tracing on. Since then in the trace logs, we've noticed a crazy amount of WARNs in the logs pertaining to an 'X-Datadog-Trace-Count' header not being found.

e.g:
```{"agent":"trace","time":"2020-02-19 20:48:15 UTC","level":"WARN","file":"pkg/trace/api/api.go","line":"360","func":"handleTraces","msg":"Error getting trace count: \"HTTP header \\\"X-Datadog-Trace-Count\\\" not found\". Functionality may be limited."}```

Some details about the environment:
PHP version: PHP 7.0.33
Datadog extension version: datadog-php-tracer-0.39.0-1.x86_64.rpm
The apache config for tracing (although I've tried with the trace analytics and mysqli analytics off):
```
SetEnv DD_TRACE_ENABLED true
SetEnv DD_TRACE_SAMPLE_RATE 0.1
SetEnv DD_TRACE_ANALYTICS_ENABLED true
SetEnv DD_MYSQLI_ANALYTICS_ENABLED true
```

I figured I'd check here because I wanted to make sure I'm not going to go-ahead and do something dumb. I'm a little lost on this one to be honest, and was hoping for some advice please.

Is this a matter of needing to have our application emit this header on every outgoing request? 

Cheers,
Jason

**Comment by morrisonlevi** [comment]
Thanks for opening an issue, and sorry you are experiencing this. Are you getting PHP traces successfully? It's odd to see this in modern tracer versions as we've been sending this header for quite some time in the PHP tracer. Do you have any other languages sending traces to this agent?

**Comment by xyzjace** [comment]
Hi Levi,

We're getting traces, which is great! 

We don't have any languages doing tracing right now. 

Is it possible that the PHP library being included could be affecting this as well? My initial thought was it'd be just down to the extension version, but perhaps that's misguided on my part.

**Comment by morrisonlevi** [comment]
To clarify, you are installing the ddtrace extension _and_ the composer package?

**Comment by xyzjace** [comment]
Correct. We're installing the extension and the composer package.

**Comment by morrisonlevi** [comment]
I will have to research more about that situation, but I think you do not need the composer package if you are using the extension.

**Comment by xyzjace** [comment]
It's entirely possible I made assumptions when I read the documentation. 

My initial understanding was that I had to install the extension, then install the PHP library to do some extra instrumentation based on (https://docs.datadoghq.com/tracing/manual_instrumentation/?tab=php). 

From what I think you're suggesting, I may not need the library, and can instead just use the extension for the same functions?

**Comment by morrisonlevi** [comment]
I think you read the documentation correctly:

> If you really need manual instrumentation, e.g., because you want to trace specific custom methods in your application, first install the PHP tracer dependency with Composer:
> `$ composer require datadog/dd-trace`

This is not required, and I don't recommend it if you have the extension installed because you have to keep the extension and composer package in sync. I am wondering if perhaps this issue is coming from an older composer package than extension?

**Comment by xyzjace** [comment]
Let me chase that down and see what the deal is. It's entirely possible you've nailed it.

**Comment by xyzjace** [comment]
I think you were right. Even though I'd required the dd-trace agent, it looks like we have another library that's meant to provide a standardised interface for metrics and such. That library was keeping the php library at a much lower (0.26) version that the extension. Once we upgraded the library, we're not seeing the issues any longer.

Thanks very much for your help, apologies that it ended up being PEBKAC.

**Comment by xyzjace** [comment]
I'll close this issue out. Hopefully it'll serve as useful to anyone who makes this silly mistake.

Thanks again for your help and time.
