### ISSUE TITLE
[BUG] Sample rate does not seem to be working

### ISSUE THREAD

**Issue by Verhaeg** [DataDog/dd-trace-php#777]
**Describe the bug**
According to the documentation, for ddtrace version above 0.36.0 we should use the DD_TRACE_SAMPLE_RATE env variable.

- the container is set with the variable
- datadog added the apm-sample-rate:0.1 tag correctly
- using the 0.39.2 ddtrace version with PHP 7.1

Considering the numbers of requests and samples, it seems it sampled all requests completely 

Other envs for Trace:

- DD_TRACE_ANALYTICS_ENABLED=true
- DD_TRACE_CLI_ENABLED=true
- DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED=true
- DD_TRACE_DEBUG=false
- DD_TRACE_ENABLED=true

**PHP Info**
- Output of `php -v`
PHP 7.1.33 (cli) (built: Oct 25 2019 06:33:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33, Copyright (c) 1999-2018, by Zend Technologies
- Output of `php -m`
[PHP Modules]
bcmath
Core
ctype
curl
date
ddtrace
dom
ds
fileinfo
filter
ftp
gd
hash
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
Phar
posix
rdkafka
readline
Reflection
session
SimpleXML
soap
SPL
sqlite3
standard
tideways_xhprof
timezonedb
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

**OS Info**
- Output of `cat /etc/os-release | grep -E "(NAME)|(VERSION)"`
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

**Expected Output**
Sample rate according to the defined rate provided

**Comment by labbati** [comment]
Hi @Verhaeg, sorry for the issue you had to report. I am asking a few more questions, depending on the answer I might need you to open a support ticket because in case we need to go and look deeper into your account.

> datadog added the apm-sample-rate:0.1 tag correctly

Can you explain what you are referring to? UI? Looking at any specific payload?

Also

> Considering the numbers of requests and samples, it seems it sampled all requests completely

By this you mean that all requests gets through? Where are you looking at? The point here is that in stats and analytics you should see the real number, but then you should be able to access in the UI only 10 traces.

So, as an example, say you have 100 requests/sec for service `my-service` and you set `DD_TRACE_SAMPLE_RATE=0.1`. In the services list and in the analytics page you should still read 100 reqs/sec, but in the trace list only 10 reqs/sec should be listed and clickable to be inspected.

**Comment by Verhaeg** [comment]
Hi @labbati 
For the first part I was looking into the Datadog UI, when looking the host data. But you can desconsider that as I forgot that we add the trace sample as metadata for the instance. So sorry for that confusion.

Regarding the information on how it displays, we didn't find any information on that, so we only checked the total numbers of requests in the period.

The main point of the issue is that we are trying to analyze and see why enabling DD Trace makes our instance consume ~10-15% more CPU (For which we will try to talk to our CSM and perhaps open another issue to help investigate that).

I'll conduct some sampling here then, check the numbers and monitored requests. But according from what you mentioned, all times and requests are still processed but the effective trace is only visible to a part of those requests right?
Is it possible to enable the APM for only 10% of the requests entirely?

Thanks and sorry for the confusion then.

**Comment by labbati** [comment]
> The main point of the issue is that we are trying to analyze and see why enabling DD Trace makes our instance consume ~10-15% more CPU (For which we will try to talk to our CSM and perhaps open another issue to help investigate that).

Yes please if you open a support ticket for this we can also share more details about your app and behavior. Depending on the app though, ~10% might be expected.

> I'll conduct some sampling here then, check the numbers and monitored requests. But according from what you mentioned, all times and requests are still processed but the effective trace is only visible to a part of those requests right?

"processed" means that they reach the agent (still inside your host) but not datadog. We can use them to compute stats but the payload IS NOT sent to our backend and thus is not visible.

> Is it possible to enable the APM for only 10% of the requests entirely?

If by that you mean "do not trace any function call for 90% of the requests" then this is not possible, as it would produce wrong stats also, among other things. But, if you open a support ticket, we can access more info about your specific issue and do a more deep investigation / propose a plan to improve on that.

If my comment answers your question, please feel free to close this issue and we can move the conversation over there so you can share more details about your stack/app.

**Comment by Verhaeg** [comment]
Thanks a lot for all the information!
