### ISSUE TITLE
[BUG] tracing closure for execute(): Undefined variable: retval

### ISSUE THREAD

**Issue by wajdisawaf** [DataDog/dd-trace-php#788]
**Describe the bug**
Code error reported :
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - New span web.request web.request recorded.
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Attempting integrations load
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration cakephp
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration curl
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration elasticsearch
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration eloquent
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration guzzle
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration laravel
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration lumen
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Integration memcached not available. New attempts WILL NOT be performed.
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Integration mongo not available. New attempts WILL NOT be performed.
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration mysqli
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration pdo
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration predis
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration slim
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration symfony
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration web
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration zendframework
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration codeigniter
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration wordpress
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Loaded integration yii
**NOTICE: PHP message: Error raised in tracing closure for execute(): Undefined variable: retval in /opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/PDO/PDOSandboxedIntegration.php on line 131**
127.0.0.1 -  10/Mar/2020:11:19:08 +0000 "GET /index.php" 200
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Flushing 1 traces, 5 spans
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Encoding span '5398244848508102694' op: 'web.request' serv: 'web.request' res: 'GET /account/login' type 'web'
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - Tags for span 5398244848508102694 'tag:chars_count' are: system.pid:2,http.method:3,http.url:14,http.status_code:3
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - About to send trace(s) to the agent
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [debug] - circuit breaker status: closed => , total_failures => 6,consecutive_failures => 6, opened_timestamp => 3377403504257, last_failure_timestamp=> 3377993280410
NOTICE: PHP message: [2020-03-10T11:19:08+00:00] [ddtrace] [error] - Reporting of spans skipped due to open circuit breaker
127.0.0.1 -  10/Mar/2020:11:19:33 +0000 "GET /phpfpmstatus" 200

**PHP Info**
- Output of `php -v`: 
Error raised in tracing closure for execute(): Undefined variable: retval in /opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/PDO/PDOSandboxedIntegration.php on line 131
127.0.0.1 -  10/Mar/2020:11:09:18 +0000 "GET /index.php" 200

- Output of `php -m`:
[PHP Modules]
apcu
bcmath
Core
ctype
curl
date
ddtrace
dom
ev
fileinfo
filter
ftp
gd
hash
iconv
igbinary
imagick
intl
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
rdkafka
readline
redis
Reflection
SEPA
session
SimpleXML
soap
sodium
SPL
sqlite3
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
Xdebug

**OS Info**
- Output of `cat /etc/os-release | grep -E "(NAME)|(VERSION)"`:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

**Output of dd-doctor**
DataDog trace extension verification

- PHP version and SAPI                               [7.3.14 - fpm-fcgi]
- ddtrace extension installed                        [OK]
- ddtrace version (installed)                        [0.41.1]
- ddtrace version (const)                            [0.41.1]
- ddtrace version (userland)                         [0.41.1]
- ddtrace versions in sync                           [OK]
- dd_trace() function available                      [OK]
- dd_trace_env_config() function available           [OK]
- ddtrace.request_init_hook set                      [OK]
- ddtrace.request_init_hook reachable                [OK]
- ddtrace.request_init_hook has run                  [OK]
- 'open_basedir' allows access to '/proc/self/'      [OK]
- IntegrationsLoader exists                          [OK]
- Integrations not loaded yet                        [OK]
- Registering an autoloader...
- Integrations loaded                                [OK]
- DDTrace\Tracer class exists                        [OK]
- Background sender is enabled?                      [NO]
  > You can enable the background sender via
    DD_TRACE_BETA_SEND_TRACES_VIA_THREAD=true
- Configured Agent host                              [datadog-apm.datadog.svc.cluster.local:8126]
- Configured Agent port                              [8126]
- Agent can receive traces                           [FAIL]
Curl verbose output: 

* Expire in 0 ms for 6 (transfer 0x561ba2d24420)
* Expire in 5000 ms for 8 (transfer 0x561ba2d24420)
* Expire in 5000 ms for 2 (transfer 0x561ba2d24420)
* Closing connection -1

**Comment by labbati** [comment]
@wajdisawaf thanks for opening the issue. We are going to look into this ASAP. Can you please confirm that your app did not report any crash. Only the specific PDO span was missing.

**Comment by wajdisawaf** [comment]
yes, that's correct.

**Comment by SammyK** [comment]
Hey @wajdisawaf! This issue was fixed in #791 and will be rolled into the release next week. Thanks so much for the report. :)

**Comment by labbati** [comment]
Hi @wajdisawaf [0.42.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.42.0) fixes this issue, feel free to reopen the issue if this is not true for your use case.
