### ISSUE TITLE
[BUG] Segmentation fault when php://stderr is specified in error_log on Alpine

### ISSUE THREAD

**Issue by kjdev** [DataDog/dd-trace-php#797]
**Describe the bug**
When error_log of php.ini is set to php://stderr, it becomes a Segmentation fault.

**PHP Info**
- Output of `php -v`
```
PHP 7.3.15 (cli) (built: Feb 26 2020 22:04:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.15, Copyright (c) 1999-2018, by Zend Technologies
```
- Output of `php -m`
```
Segmentation fault (core dumped)
```

> When not changing error_log.
> ```
> [PHP Modules]
> Core
> date
> ddtrace
> filter
> hash
> libxml
> pcre
> readline
> Reflection
> SPL
> standard
> Zend OPcache
> zlib
>
> [Zend Modules]
> Zend OPcache
> ```

**OS Info**
- Output of `cat /etc/os-release | grep -E "(NAME)|(VERSION)"`
```
NAME="Alpine Linux"
VERSION_ID=3.11.3
PRETTY_NAME="Alpine Linux v3.11"
```

**Output of dd-doctor**

**If you are upgrading**

Updated from 0.41.0 to 0.41.1.

```
$ grep -m 1 '^error_log' /etc/php7/php.ini
error_log = "php://stderr"
```

**Comment by morrisonlevi** [comment]
Thank you for the bug report, and sorry you are experiencing issues. I was able to recreate this in a container and will prioritize this fix.

**Comment by labbati** [comment]
HI @kjdev [0.42.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.42.0) fixes this issue Feel free to reopen the issue if this is not true for your use case.
