### ISSUE TITLE
Laravel 7.x?

### ISSUE THREAD

**Issue by maxcountryman** [DataDog/dd-trace-php#808]
Hello, I'd like to know what sort of support is planned for Laravel 7.x? Should we expect that upgrading to 7 will break the Datadog integration?

**Comment by labbati** [comment]
If you are using version 0.38.0+ integration WILL NOT break for sure. Before 0.38.0 I am very confident it will not break.

On a side note, starting with 0.43.0 we wil support by default ALL the web frameworks, with some of them (more and more with time) showing up more details about their internals.

**Comment by labbati** [comment]
Hi @maxcountryman, were you able to have traces in for Laravel 7.x? Anything else we can do to help?

**Comment by brandonburkett** [comment]
Hello.  I know this one has been open a while, but with Laravel 8 released today I am planning our upgrade from Laravel 6 -> 7.  Can we assume the tracer will work for Laravel 7 just like Laravel 6?

I did not see it on the officially supported frameworks page: https://docs.datadoghq.com/tracing/compatibility_requirements/php/ (only shows up to Laravel 6)

**Comment by labbati** [comment]
Hi @brandonburkett, you can upgrade and Laravel 7 will work just fine. Worst that can happen is that you might miss a span (specifically related to Laravel internals) if a method name that we trace is changed in the Laravel code base. Still, all db calls, cache, http clients, laravel actions etc will be traced.

**Comment by brandonburkett** [comment]
Understood, thank you!

**Comment by brandonburkett** [comment]
It has been a bit, but updated to Laravel 8.x yesterday and the datadog php tracer (v0.50) is working great.

We actually see phpredis now in the stats.  Not I am not tracing console / artisan calls at all, just web spans.

**Comment by labbati** [comment]
Hi @maxcountryman and @brandonburkett. I am closing this issue as we have added support and there are no more action items here for us. Feel free to comment if you feel different and I will reopen.
