### ISSUE TITLE
[BUG]PHP5.5 Not Supported

### ISSUE THREAD

**Issue by imsatender** [DataDog/dd-trace-php#812]
**PHP5.5 Not Supported with DDTRACE_0.36.1**

I am getting the error mentioned below:

`PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/datadog-php/extensions/ddtrace-20121113.so' - /opt/datadog-php/extensions/ddtrace-20121113.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 5.5.38 (cli) (built: Oct 22 2019 14:12:40) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans`

**Comment by morrisonlevi** [comment]
We do not currently support PHP 5.5. It is planned, but I can't give an ETA; see #625 for more users who also want PHP 5.5 support.

**Comment by morrisonlevi** [comment]
PHP 5.5 support has been merged in. It still needs more tests before it's officially supported, but wanted you to know it's coming soon, probably in version 0.49.0.

**Comment by SammyK** [comment]
Thank you for opening this issue @imsatender. PHP 5.5 is now supported in [0.49.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.49.0).
