### ISSUE TITLE
[Feature] Opcache compile time included?

### ISSUE THREAD

**Issue by draco2003** [DataDog/dd-trace-php#828]
Looking to confirm/deny if Opcache compile time is included in the request time and if it can be teased apart from the request time to understand what amount of time is spent compiling the code vs. executing it.

**Comment by morrisonlevi** [comment]
The root span should have a metric `php.compilation.total_time_ms`. If it doesn't, first check to see if you are setting the environment variable `DD_TRACE_MEASURE_COMPILE_TIME` to off, but otherwise I'd consider it a bug.

**Comment by draco2003** [comment]
Perfect, thanks! Exactly what I was looking for. 
Now to figure out how to show all traces where it's greater than 1.

Have tried variations like the following:
php.compilation.total_time_ms:>1

**Comment by labbati** [comment]
Hi @draco2003, how did things go? Any further help we can provide? We can also involve our solutions team is this helps.

**Comment by bwoebi** [comment]
Closing for old age, to clean our issues up a bit. Feel free to open another issue if there's another problem.
