### ISSUE TITLE
[BUG] TraceLog report spans_malformed(invalid_start_date:474)

### ISSUE THREAD

**Issue by emanuelr93** [DataDog/dd-trace-php#843]
**Describe the bug**
With new dd-trace-php agent APM span are not sent. In the log file i see this line:
2020-04-24 11:00:11 UTC | TRACE | WARN | (pkg/trace/info/stats.go:111 in LogStats) | [lang:php lang_version:7.2.27 interpreter:fpm-fcgi tracer_version:0.43.0] -> spans_malformed(invalid_start_date:474). Enable debug logging for more details.

I have tried to enable debug logging and i see this line:
 2020-04-24 11:11:54 UTC | TRACE | DEBUG | (pkg/trace/api/normalizer.go:129 in normalize) | Fixing malformed trace. Start date is invalid (reason:invalid_start_date), setting span.start=time.now(): service:"memcached" name:"Memcached.getMulti" resource:"getMulti" traceID:1694297653726633524 spanID:3868687179575160375 parentID:1694297653726633524 meta:<key:"env" value:"DEV" > meta:<key:"memcached.command" value:"getMulti" > meta:<key:"memcached.query" value:"getMulti ?" > type:"memcached"

The dd-agent version is : 
Agent 7.17.1 - Commit: 378649d - Serialization version: 4.19.0 - Go version: go1.12.9

**PHP Info**
PHP 7.2.27 (cli) (built: Jan 26 2020 15:49:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.27, Copyright (c) 1999-2018, by Zend Technologies
    with ddtrace v0.43.0, Copyright Datadog, by Datadog

**OS Info**
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"

With version datadog-php-tracer-0.34.1-1.x86_64.rpm i haven't this issue

This is configuration:
[DD_PROCESS_AGENT_ENABLED] = true"
[DD_TRACE_ANALYTICS_ENABLED] = true
[DD_SERVICE_NAME] = php
[DD_TRACE_GLOBAL_TAGS] = env:dev
[DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED] = true
[DD_TRACE_NO_AUTOLOADER] = true
[DD_AUTOFINISH_SPANS] = true

**Comment by SammyK** [comment]
Hey @emanuelr93! Thanks for providing the information to help debug this issue. Unfortunately I was not able to replicate this issue on my end yet, so we might need to dig a little deeper.

1. Are the Agent log warnings appearing for every trace or are they occurring intermittently? 
2. Does the codebase have any custom instrumentation code or is it only using the built-in integrations?
3. Does the codebase run on a particular framework?

**Comment by emanuelr93** [comment]
> Are the Agent log warnings appearing for every trace or are they occurring intermittently?
The warning is logged for every trace and i don't see any span on DataDog Dashboard.

> Does the codebase have any custom instrumentation code or is it only using the built-in integrations?
Only built-in integration. Almost all trace is child of other trace generated via Java APM Agent (There is a java service that call PHP API)

> Does the codebase run on a particular framework?
It is a Drupal 8 instace (that is based on Laravel) and there is PHP-FPM with OpCache. Basically there are PDO Span, Memcached Span and Gruzzle Span that are automatically detected from APM Agent.

**Comment by SammyK** [comment]
Hey @emanuelr93! I have a suspension that this may be related to #855 as it appears to be clock related. Does this problem persist after upgrading to [0.44.1](https://github.com/DataDog/dd-trace-php/releases/tag/0.44.1)?

**Comment by emanuelr93** [comment]
I will try it tomorrow and i will inform you. 
Thank you

**Comment by emanuelr93** [comment]
Hey @SammyK, i can confirm that bug is resolved with 0.44.1. Now i receive the span tracing without any problem!

Thank you for support.
