### ISSUE TITLE
[Feature] Use normalized urls for curl resource names

### ISSUE THREAD

**Issue by akdh** [DataDog/dd-trace-php#864]
**Is your feature request related to a problem? Please describe.**

Outgoing curl requests are not grouped logically by type of endpoint but rather are grouped individually for requests with parameters in the URL (e.g., `/user/123`). This leads to summary statistics not being helpful in Datadog.

**Describe the solution you'd like**

The resource name for curl requests should use the normalized URL (rather than the sanitized URL). This could be possibly conditional on `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED` being set.

**Comment by SammyK** [comment]
Hey @akdh! Thank you for that request. This would be a useful feature. I can't give a timeline on when we can deliver this, but I have added it into our system and when we are able to accommodate this, we will certainly follow up with with you. Thanks again!

**Comment by akdh** [comment]
@SammyK Thanks for the quick response! I've opened a PR for this feature here https://github.com/DataDog/dd-trace-php/pull/869.

**Comment by morrisonlevi** [comment]
@akdh Just letting you know this shipped in version 0.45.0. Thanks for your contribution!
