### ISSUE TITLE
[Feature] Enable Adding of Custom Integrations

### ISSUE THREAD

**Issue by Bibob7** [DataDog/dd-trace-php#871]
**Is your feature request related to a problem? Please describe.**
We are using a custom kafka-lib developed by us and we would like to have a ddtrace integration for it. Unfortunately the IntegrationLoader class is not build to add custom integrations. It only supports officially supported ones.

**Describe the solution you'd like**
It should be easily possible to tell the IntegrationLoader to also include some custom Integrations.

**Describe alternatives you've considered**
As a workaround we can extend the officiallySupportedIntegrations array in IntegrationLoader and reload it. However, in this case we double load all officiallySupportedIntegrations.

**Comment by labbati** [comment]
Hi @Bibob7 and thanks for opening this feature request.

> Unfortunately the IntegrationLoader class is not build to add custom integrations. It only supports officially supported ones.

Correct, and as part of a performance oriented revamping we are moving away from the OOP-oriented approach for our tracer (that was strongly inspired by open tracing) into a more functional and simple one ([here](https://github.com/DataDog/dd-trace-php/compare/labbati/build/integration-loading) an example of what we are POCing and measuring). The reason why I am saying that is to suggest avoid relying on our internal code that is is strongly changing.

What can you do then? At the end of the day it's all about doing some AOP around specific functions. The more future proof approach that I can envision right now is to do the following:

1. If you are doing manual instrumentation inside methods, then use the open tracing api we expose.
2. If you you want to define your integration in a separate dedicated file, use `dd_trace_method` and `dd_trace_function` to hook into method calls, you find plenty of usage examples in our `DDTrace/Integrations/**/*Sandboxed*.php`

If you provide us with some snippets of what you intended to do then we can provide more examples based on your specific use case.

**Comment by Bibob7** [comment]
We did it with as custom class and using dd_trace_method. 

I will close this issue.
