### ISSUE TITLE
Custom UUID's pattern

### ISSUE THREAD

**Issue by rakshans1** [DataDog/dd-trace-php#873]
I have enabled `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED` 

We have many endpoints like
*  `/v1/user/:uid`
* `/v1/user/:uid/something`
* `/v1/somethingelse/:uid/something`
* ...

Uids are unique with this pattern  qFS12345678, 1FS8765435

Currently not feasible to add all combinations in `DD_TRACE_RESOURCE_URI_MAPPING` for this

It will be easier to extend the [default patterns](https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Http/Urls.php#L12)

**Comment by labbati** [comment]
Hi @rakshans1 and sorry for the late reply. Would it be ok for you to add a CSV config (for now an ENV VARIABLE, e.g. `DD_TRACE_RESOURCE_URI_PATTERNS`) with regex for fragments? E.g. in your case it could be: `DD_TRACE_RESOURCE_URI_PATTERNS=[\w\d]FS\d+`.
If you approve the format we can have a quick debrief with the team to make sure there are no blockers and propose an ETA.

**Comment by rakshans1** [comment]
@labbati Yes CSV config will be ok for me to add as an ENV variable

**Comment by labbati** [comment]
Hi @rakshans1. We now have rolled out an improve resource mapping that will cover your use case: https://docs.datadoghq.com/tracing/setup/php/#map-resource-names-to-normalized-uri

Specifically `DD_TRACE_RESOURCE_URI_FRAGMENT_REGEX` should serve you well.

Please let me know if this is solved, so we can close the issue.

**Comment by rakshans1** [comment]
@labbati I think `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED` stopped working with update. We are using lumen

![image](https://user-images.githubusercontent.com/12949352/92593118-367b9c00-f2be-11ea-9e6b-1da0d2630803.png)

From 
![image](https://user-images.githubusercontent.com/12949352/92593204-58751e80-f2be-11ea-9d2d-47438183d97b.png)

**Comment by labbati** [comment]
Hi,

`DD_TRACE_RESOURCE_URI_FRAGMENT_REGEX` is on by defualt.

Moreover you can use `DD_TRACE_RESOURCE_URI_FRAGMENT_REGEX` to define the pattern that defines your id. An example is here: https://docs.datadoghq.com/tracing/setup/php/#custom-url-to-resource-mapping

If this don't work for you, please feel free to either provide on this thread the `DD_TRACE_RESOURCE_URI_FRAGMENT_REGEX` value you have set and an example of a resource name that has not been normalized as you expected or to open a support ticket so we can look at your specific account and help solving this.

**Comment by labbati** [comment]
Hi @rakshans1 did you have a chance to test the new approach? Did it work for you?

**Comment by rakshans1** [comment]
@labbati Resource name change from URL base to controller name after update. Therefore not able to test `DD_TRACE_RESOURCE_URI_FRAGMENT_REGEX`

![image](https://user-images.githubusercontent.com/12949352/92943836-e1cc5280-f470-11ea-952e-e2b538b3ded9.png)

**Comment by labbati** [comment]
Hi @rakshans1. Is the URL --> controller change working for you? Should we convert this ticket to let you disable the URL to controller transformation or should we close this one?

**Comment by rakshans1** [comment]
@labbati Controller change is working

**Comment by labbati** [comment]
Thanks @rakshans1
