### ISSUE TITLE
[BUG] 0.46.0 broken build with 5.4

### ISSUE THREAD

**Issue by remicollet** [DataDog/dd-trace-php#913]
Using pecl archive:

`make: *** No rule to make target `/builddir/build/BUILD/php-pecl-datadog-trace-0.46.0/NTS/src/ext/php5_4/handlers_internal.c', needed by `src/ext/php5_4/handlers_internal.lo'.  Sto`

**Comment by remicollet** [comment]
package.xml in master seems outdated, so cannot open a PR to fix it (handlers_curl still presents, handlers_internal missing)

**Comment by morrisonlevi** [comment]
We opened a PR immediately after release to remove the handlers_curl.c file: https://github.com/DataDog/dd-trace-php/pull/910, but it misses the `handlers_internal.c` file; I'll update that soon.

I don't think the pecl package was ever intended to work on PHP 5.4, as the min version there says PHP 5.6, but if it did work on PHP 5.4 before that's something to know.

**Comment by morrisonlevi** [comment]
We just released 0.48.0. We now package, verify the package, and run the associated tests in CircleCI for PHP 5.6+ instead of relying on manual testing. PHP 5.4 isn't supported, so if you try there is an error like this:

> pecl/datadog_trace requires PHP (version >= 5.6, version <= 7.4.99), installed version is 5.4.45

Thanks for your persistence, Remi!
