### ISSUE TITLE
[BUG] laravel.event.handle shown as unnamed-php-service

### ISSUE THREAD

**Issue by axot** [DataDog/dd-trace-php#934]
We are currently using laravel 5.5.48, recently we updated ddtrace from 0.31.0 to 0.44.1.

A new `unnamed-php-service` appeared in APM page, it did not exists in the old version.
![image](https://user-images.githubusercontent.com/611054/85663531-29560480-b6f4-11ea-81c1-daebc5888e4f.png)

We also plan to upgrade to the latest 0.46.0 version and because the new background thread feature was introduced. we need more time to test it.

Thanks.

**Comment by labbati** [comment]
👋  How are you setting the service name? `env[DD_SERVICE_NAME]=my-app` it he www.conf?

**Comment by labbati** [comment]
I am pretty sure this is the offending release: https://github.com/DataDog/dd-trace-php/releases/tag/0.43.0 where we introduced `DD_SERVICE_NAME`

**Comment by axot** [comment]
Hi @labbati, Thank you for the information, we did not setup `DD_SERVICE_NAME` in www.conf.
Let me try this tomorrow.

Thanks!
