### ISSUE TITLE
[BUG] clear_env for php-fpm

### ISSUE THREAD

**Issue by smart--petea** [DataDog/dd-trace-php#936]
I have followed the instructions to setup datadog in docker containers for a php app. But no logs were sented to datadog site.

1.  datadog-agent container
2.  php container container containing nginx and the correspondent datadog extension

Doctor script was working fine (php cli). The requests from browser were not monitored by datadog (php-fpm). 
The problem was solved by configuring php-fpm to not remove the env variables (clear_env from /etc/php/7.1/fpm/pool.d/www.conf. see https://medium.com/@tomahock/passing-system-environment-variables-to-php-fpm-when-using-nginx-a70045370fad).

**Comment by labbati** [comment]
Hi @smart--petea, not sure I follow. If you use the `env` directive it works regardless of the value in `clear_env`. As an example, [this sample app](https://github.com/DataDog/dd-trace-php/tree/labbati/docs/nginx-fpm/examples/nginx-php-fpm) works, you can try it yourself. And as you can see in the [`www.conf`](https://github.com/DataDog/dd-trace-php/blob/labbati/docs/nginx-fpm/examples/nginx-php-fpm/www.conf) file `clear_env=no`

**Comment by labbati** [comment]
If you share your www.conf (at least the relevant part) we will be happy to help spotting the issue.

**Comment by smart--petea** [comment]
I did not not know about the sample app. In my case the www.conf is a standard one created by docker. I only changed the clear_env variable and it worked.

**Comment by labbati** [comment]
Hi @smart--petea thanks for clarifying. While `clear_env=no` works (as it will not clear the env to the newly created worker process, it might have some security implications are all the environment variables from your host machine are now available to the process (hence the envs you needed to configure the host).

If you want to work with the (typically) recommended `clear_env=yes` you can. You just have to explicitly use the `env` directive, e.g. in your `www.conf` use `env[DD_AGENT_HOST]=$DD_AGENT_HOST` which means "Provide an env named `DD_AGENT_HOST` to the worker process with value from the host environament variable DD_AGENT_HOST". More about the PHP-FPM's `env` directive here https://www.php.net/manual/en/install.fpm.configuration.php
