### ISSUE TITLE
DDTrace\GlobalTracer is undefined?

### ISSUE THREAD

**Issue by PixelDog** [DataDog/dd-trace-php#944]
**Describe the bug**
The DDTrace\\GlobalTracer is undefined for us

php > var_dump(class_exists('DDTrace\\SpanData'));
bool(true)
php > var_dump(class_exists('DDTrace\\GlobalTracer'));
bool(false)

The php module is loaded in the ini

find /var/app/current -name GlobalTracer.php shows this
/var/app/current/php/vendor/datadog/dd-trace/src/api/GlobalTracer.php.

Could this be an autoload problem? We have this command as part of our build process:
composer dump-autoload --optimize --classmap-authoritative --no-dev

**PHP Info**
PHP 7.3.13 (cli) (built: Jan 21 2020 19:15:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies
    with ddtrace v0.45.0, Copyright Datadog, by Datadog

[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
ddtrace
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
memcached
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
yaml
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
ddtrace

**OS Info**
NAME="Amazon Linux AMI"
VERSION="2018.03"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"

**Output of dd-doctor**
- Deploy `dd-doctor` to your root folder `curl https://raw.githubusercontent.com/DataDog/dd-trace-php/master/src/dd-doctor.php -o <path-to-webroot>/<some-random-name>.php`
- Access it at `http://your-host/<some-random-name>.php`
I can't seem to get this one to work, even though the path to the file is valid, it keeps telling me file can not be found?

**If you are upgrading**
not upgrading
in our composer, we have this:
"datadog/dd-trace": "^0.46.0"

**Comment by morrisonlevi** [comment]
I noticed that the version output says it has version 0.45.0 but the composer says `0.46.0`. Two things:

- Version 0.46.0 overhauled how we load PHP code and the composer package for 0.46.0 only loads a no-op API.
- Generally, this means the composer package should not be used, but if it is used it needs to match the version of the dd_trace extension that is installed.

I strongly suspect that the mismatch of 0.45 extension and 0.46 composer is the issue here.

**Comment by PixelDog** [comment]
Thank you! I will give that a go.

**Comment by PixelDog** [comment]
I don't think that was it :-(

So now in composer there is: "datadog/dd-trace": "0.45.0"
But still getting:
php > var_dump(class_exists('DDTrace\GlobalTracer'));
bool(false)

**Comment by morrisonlevi** [comment]
It's possible that 0.45's autoloader doesn't work with `composer dump-autoload`. If you can easily upgrade to 0.46 on a test server that's what I recommend as it has a revamped startup process which should avoid this issue, and it also has some performance improvements.

**Comment by PixelDog** [comment]
ok thanks! I'll try that.

**Comment by PixelDog** [comment]
It's working with 0.46, thanks! I also seems the environment might not have been loading properly in my test ugh. Anyway, I'm going to stick with 0.46, thanks!

**Comment by PixelDog** [comment]
Leaving one more comment on this. Your support is incredible. Thanks @morrisonlevi
