### ISSUE TITLE
[BUG] Missing files in 0.47.0 archives

### ISSUE THREAD

**Issue by remicollet** [DataDog/dd-trace-php#953]
Missing in package.xml

* src/ext/php5/engine_api.c
* src/ext/php5/engine_api.h
* src/ext/php5/handlers_curl.c

**Comment by SammyK** [comment]
Thanks for reporting this issue @remicollet! These files were added and our CI validator was fixed in #954. This will be shipped in 0.48.0.

**Comment by remicollet** [comment]
why a simple trivial fix not in 0.47.1 ???

**Comment by SammyK** [comment]
@remicollet This was completely my fault for missing this. The PR's were all tagged with the 0.48.0 milestone but I should have moved them into 0.47.1. I'm very sorry this wasn't part of the 0.47.1 patch release. I will certainly make sure that all the PECL fixes that have been merged will be included in the next release.

**Comment by morrisonlevi** [comment]
This fix has been shipped in 0.48.0. Thank you again for your persistence!
